### ISSUE TITLE
Javascript debugger having problem on ssh and windows.

### ISSUE THREAD

**Issue by richtera** [microsoft/vscode#107048] opened 2020-09-19 00:09 UTC
Issue Type: <b>Bug</b>

I am using visual studio on both Mac and Windows. In recent versions I can no longer use some of the javascripts debugging features. This happens in windows with an ssh connection into a hyper-v vm.
There was a really old version having these problems but they have come back. I have tried various prerelease versions and latest branches but all react the same.
When using the javascript debugging console it attempts to connect to the debugger but only seldomly success and then shows a window saying it cannot reconnect and you have to click reload, otherwise the whole UI is unresponsive.
The same thing happens sometimes with a normal launch when things take too long. I have not been able to put my fingers on specifics, but all of these features work without any problems on the mac.
And I remember this shortly being a problem and then having been resolved with an upgraded debugger.
Unfortunately there is no error condition showing anywhere or any indication how to possibly resolve the problem, so I really don't have a lot of information to post here. I hope the description is informative enough.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-117-generic
Remote OS version: Linux x64 4.15.0-117-generic
Remote OS version: Linux x64 4.15.0-117-generic
Remote OS version: Linux x64 4.15.0-117-generic
Remote OS version: Linux x64 4.15.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (30.06GB free)|
|Process Argv|--crash-reporter-id db2c49a0-c178-4fe7-b9ea-930397e91764|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: primary|
|OS|Linux x64 4.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|9.76GB (4.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: primary|
|OS|Linux x64 4.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|9.76GB (4.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: primary|
|OS|Linux x64 4.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|9.76GB (4.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: primary|
|OS|Linux x64 4.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|9.76GB (4.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: primary|
|OS|Linux x64 4.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|9.76GB (4.05GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
quokkasyntax|aid|1.2.3
language-hugo-vscode|bud|1.2.0
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
copy-syntax|ati|0.5.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
go|gol|0.17.0
python|ms-|2020.8.109390
js-debug-nightly|ms-|2020.9.1717
powershell|ms-|2020.6.0
markdown-preview-enhanced|shd|0.5.13
vsc-quokka-statusbar|ske|1.3.6
quokka-vscode|Wal|1.0.318

</details>

**Comment by connor4312** [comment] 2020-09-19 01:41
> When using the javascript debugging console it attempts to connect to the debugger but only seldomly success and then shows a window saying it cannot reconnect and you have to click reload, otherwise the whole UI is unresponsive.

Can you please share a contents/the screenshot of the window, as well as your launch config?

**Comment by richtera** [comment] 2020-09-19 13:12
There is no launch config. I am just using "Create New Javascript Debug Terminal"
Then when I run a command or node script from the command line it attempts to connect but only does 1 out of 10 or 20 times. All other times I get this
![image](https://user-images.githubusercontent.com/708186/93668011-dd4aff80-fa57-11ea-94ca-4dfa98cb4b55.png)
It shows this in the CallStack which is correct
![image](https://user-images.githubusercontent.com/708186/93668056-28fda900-fa58-11ea-9bfc-cc19c4e7827e.png)
And on the command line it shows
![image](https://user-images.githubusercontent.com/708186/93668065-3450d480-fa58-11ea-85a4-fcb912b61b99.png)
But then I get the "Cannot reconnect. Please reload the window." dialog.

**Comment by richtera** [comment] 2020-09-19 13:20
BTW launch.json works fine and I use that all the time, but I have several use cases where I need to launch the node code that's being debugged from another shell or yarn script.

**Comment by connor4312** [comment] 2020-09-19 16:23
@roblourens is there a way Andreas can find logs for ssh to see why it's booting him?

**Comment by richtera** [comment] 2020-09-19 17:10
These are the kind of logs I am seeing in the log folder
rendererNN.log
```shell
[2020-09-18 14:28:37.140] [renderer33] [error] [remote-connection][ExtensionHost][af793…][reconnect][127.0.0.1:57153] received error control message when negotiating connection. Error:
[2020-09-18 14:28:37.140] [renderer33] [error] Error: Connection error: Unknown reconnection token.
    at D (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1907:697)
    at file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1900:478
    at c.fire (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at fire (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:97)
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:457:324)
    at file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:456:317
    at c.fire (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at g.acceptChunk (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:449:445)
    at file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:448:796
    at Socket.t (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:458:885)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-09-18 14:28:37.140] [renderer33] [error] [remote-connection][ExtensionHost][af793…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2020-09-18 14:28:37.140] [renderer33] [error] Error: Connection error: Unknown reconnection token.
    at D (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1907:697)
    at file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1900:478
    at c.fire (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at fire (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:97)
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:457:324)
    at file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:456:317
    at c.fire (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at g.acceptChunk (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:449:445)
    at file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:448:796
    at Socket.t (file:///C:/Users/andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:458:885)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-09-18 14:29:07.182] [renderer33] [warning] Created tunnel does not match requirements of requested tunnel. Host or port mismatch.
[2020-09-18 14:29:08.185] [renderer33] [error] cannot open tunnel: Error: cannot open tunnel
```

**Comment by roblourens** [comment] 2020-09-22 18:55
This sort of error typically comes up when the remote extension host crashes. Is it possible that the program you are trying to debug is causing issues, maybe by using tons of cpu/memory?

**Comment by richtera** [comment] 2020-09-22 23:41
No, because setting up a launch file works properly for the same identical command. It's just very hard sometime to simulate the exact input and output and environment if a command I want to debug is part of a pipe for example. The debugger is not broken, but the automatic attach using NODE_OPTS doesn't seem to work reliably anymore. This used to be a problem a while ago and has cropped up again.

**Comment by richtera** [comment] 2020-09-23 00:18
Also work from WSL2 instance of the same folder. Seems to just have problems with ssh to hyper-v.

**Comment by roblourens** [comment] 2020-09-23 01:25
Sorry what do you mean by launch file? `launch.json`?

**Comment by richtera** [comment] 2020-09-23 01:44
Yes things work with a launch.json file, on Mac and on Windows and Unix WSL. I am only seeing this problem with ssh connecting to hyper-v. And it does work sometimes even in that configuration and it used to be broken then fixed and is now broken again over the last few versions of visual studio. It feels a little like a timeout but auto attach doesn't have a setting to control the timeout. But I really don't know exactly. I just know that I used this way to attach for the last year and it is now no longer working (again)

**Comment by roblourens** [comment] 2020-09-23 13:58
Sorry for the trouble. The error only tells me that the remote extension host has crashed. Have you set up your hyper-v VM with limited memory?

@connor4312 anything we can get from the js debug extension? Like a partial log to see whether it started at least?

**Comment by richtera** [comment] 2020-09-23 14:06
Hmmm, ok. No there is really nothing going on with the application under debug and the host itself is also working, because I have several vs code instances running and connected to the same VM and it only affects the one I am trying to attach the javascript debugger to a script running within either a yarn run ..., npm run ... or a bash script. If I create a launch.json file to point to the identical executable using either yarn, npm or a node program directly it all works. It seems to be some kind of timeout establishing and hooking up to the nodejs debugging port over ssh. Because at some random times it actually works and it initially does attach to the yarn and npm process, but not to the node process within the package.json script. So when I run "yarn build" from the debug command line I see "yarn" in processes and it says debugger connected, but then I get the error just before it attaches to the node process launched from within the script which might say something like "node build.js". Then I have to reset and reload the visual studio instance to try again. It randomly just works and I end up on a breakpoint inside of build.js just as expected, but it's no longer reliable and fails more than 80% of the time. I am not sure which other logs or so I could send, but if there is something I will. I did not find any logs specific to the debug extension preserved in the log folder. In memory logs cannot be retrieved, because the visual studio needs to be completely reloaded when the error happens.

**Comment by connor4312** [comment] 2020-09-23 18:07
Since you're using auto attach, configuration is harder. Could you try using the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the debugger (will need to install it in the remote) and then add this to your user settings?

```
"debug.javascript.terminalOptions": {
  "outFiles": []
},
```

This will prevent the debugger from trying to do anything with sourcemaps, which is by far the most memory and i/o intensive operation it does. If the failure is due to the remote being starved of some resource, this has a good chance to fix it...

**Comment by richtera** [comment] 2020-09-23 18:43
Ok will try. So far I am using the same command with WSL with the identical executables and map files and don't see any problems. So it's definitely some kind of timing, resources or memory problem. My VM has 10G of ram and 4 vCPUs and a large drive. So I don't think it's at the OS level itself.

**Comment by richtera** [comment] 2020-09-29 23:19
I was able to reproduce it once using WSL. So it does seem to be a timing issue. With WSL it seems to work 99% of the time. Also when it doesn't work, I don't know how to actually capture the error. The way it fails completely prevents me to look at any logs. But since it works most of the time and I am able to switch to WSL for most of my coding, I am not sure what else to do to help here. Maybe someone else will run into a similar issue?

**Comment by connor4312** [comment] 2021-01-22 16:39
I'm not able to repro this and we haven't received other reports of the same issue. Closing this pending reports or reproductions.

**Closed by connor4312** 2021-01-22 16:39 UTC
Labels: *not-reproducible, debug, needs more info

**Comment by richtera** [comment] 2021-01-22 18:33
Agree. Has not been a problem recently.
