### ISSUE TITLE
0.11.0-Insiders regression: C++ #define without a value breaks colorization

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#23630] opened 2017-03-30 00:28 UTC
- VSCode Version: 0.11.0-Insiders
- OS Version: Windows

Steps to Reproduce:

1. Use this code in a .c/.cpp file::
#ifndef _UCRT
#define _UCRT
#endif

Bug: The colorization is broken by the #define without a value. It's a regression from 0.10.2.

The atom/language-c people say they aren't able to repro it on 0.57.0 and they think it's a bug with VS Code itself: https://github.com/atom/language-c/issues/218. I can't tell what version VS Code is using because the OSSREADME.json has the wrong version number of 0.51.3 in it, which is the same version number as VS Code 0.10.2.

![image](https://cloud.githubusercontent.com/assets/19859882/24482265/d6fe80bc-14a4-11e7-9891-1b3e4340fb14.png)

**Comment by aeschli** [comment] 2017-04-06 12:11
duplicate of #23850

**Closed by aeschli** 2017-04-06 12:11 UTC
Labels: bug, languages basic
