### ISSUE TITLE
Unable to debug Nest.js API

### ISSUE THREAD

**Issue by kgrvr** [Microsoft/vscode#68321] opened 2019-02-09 16:21 UTC
Issue Type: <b>Bug</b>

- Update to the latest version i.e. v1.31.0

Debugging was working in the previous version, but since when I had updated to the latest version of VSCode, I'm getting issues with debugging my Nest.js API.

When I start my API, the debugger used to open my main.ts file and stops at the first line. Then I used to continue (F5) that breakpoint. Everything used to work fine that ways.
But in the latest version of VSCode, the debugger doesn't open my main.ts file automatically and in my services, it doesn't stop on any breakpoint.

I've set debugger "Auto Attach: On" since I've started working on my project. I haven't had any problems with that until in the recent version.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
clipboard-history|Anj|1.0.7
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.46
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.8
Angular-BeastCode|Mik|7.2.2
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.5.2
vscode-css-peek|pra|2.2.0
java|red|0.38.0
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1
vscode-wakatime|Wak|1.2.5
vscode-surround|yat|1.0.2
html-css-class-completion|Zig|1.18.0

(3 theme extensions excluded)

</details>

**Comment by kieferrm** [comment] 2019-02-11 00:05
Might be related to #68127.

**Comment by roblourens** [comment] 2019-02-11 20:51
Can you share their project where this happens? Or set `"trace": true` in your launch config, try it again, and share the log from the path that it prints in the debug console.

**Comment by roblourens** [comment] 2019-02-11 23:40
Ok, now I can repro this. It's not a regression on the debug adapter side, but it's more noticeable in vscode now because vscode is not highlighting the current line when it grayed out. But vscode is probably doing the right thing here. FYI @isidorn

**Comment by roblourens** [comment] 2019-02-12 01:15
The debug adapter's issue is that the runtime js file and the sourcemapped file have the same name and .ts extension, and that causes some confusion. Trying to fix that, I run into https://github.com/Microsoft/vscode/issues/68480

Trying a simpler workaround, I try to change

`frame.source.presentationHint = 'deemphasize';`

to

`frame.presentationHint = 'deemphasize';`

but it seems that this isn't respected, is there a way to do that @isidorn?

**Comment by roblourens** [comment] 2019-02-12 01:41
I am copying the comments to https://github.com/Microsoft/vscode/issues/68127 and closing this as a dupe of that because it has more comments and is older. Sorry for the notification spam @isidorn

**Closed by roblourens** 2019-02-12 01:41 UTC
Labels: bug, debug
