### ISSUE TITLE
story for pulling in remote origin topic branch that already exists into local repo

### ISSUE THREAD

**Issue by myusrn** [Microsoft/vscode#4459] opened 2016-03-19 22:33 UTC
- VSCode Version: 0.10.11
- OS Version: win10 10586.164

Steps to Reproduce:

1. open folder containing clone of remote origin master

2. click on git branch status area in bottom left corner, or enter ctrl+p or f1+>Git: Checkout, and enter name of remote origin branch you want to local copy to reference.  the git ouput window shows "git checkout -q -b someTopicBranch" and "git fetch" were executed.

3.  folder doesn't contain copy of remote origin topic branch so from command line enter "git.exe config -l --local" where you'll see that branch.someTopicBranch.remote/.merge entries are not present

4.  from command line enter "git branch -u origin/someTopicBranch" or "git branch --set-upstream-to=someTopicBranch" to update local config to contain branch.someTopicBranch.remote/.merge entries

5.  from vscode you can now use git | ... | pull == "git pull" to retrieve the contents of the remote origin someTopicBranch that already existed

My thinking is that steps 3 thru 5 should be automated for you in case where you are not looking to create new topic branch and optionally later push it into remote origin but rather create local repo topic branch into which you sync the details of remote origin copy of topic branch that already exists.

**Comment by joaomoreno** [comment] 2016-03-22 11:58
Duplicate of #3385

**Closed by joaomoreno** 2016-03-22 11:58 UTC
