### ISSUE TITLE
自动升级文件破损但VSCODE没有提供删除安装包的路径导致无法升级

### ISSUE THREAD

**Issue by VDerGoW** [Microsoft/vscode#9343] opened 2016-07-15 14:03 UTC
- VSCode Version: 1.2.1
- OS Version: windows 10 version 1151

Steps to Reproduce:

1. 检查更新
2. 立即更新

软件本身没有功能问题，是设计失误。因为网络原因，自动下载的升级包下载不完整，点击安装后提示出现错误，但是**没有告诉用户软件自动下载的升级安装文件在哪里**，所以用户没法删除这个文件，也就没法自动升级。

**Comment by weinand** [comment] 2016-07-15 15:16
@wallverb since you like this issue, I'm sure that you could help us by translating it into English. Thanks.

**Comment by wallverb** [comment] 2016-07-15 15:45
Haha, I liked this issue because for some reason it stood out from all the other issues.

Challenge accepted - although I wont lie - I used google translate:

Title: 
Automatic upgrade path file is damaged but did not provide VSCODE delete the installation package leads can not be upgraded

Steps to Reproduce:

1. Check for updates
2. Update immediately

Software does not have functional problems , design errors. Because the network reasons , automatically download the upgrade package download does not complete , then click the installation issued errors , but does not tell the user to automatically download software updates where the installation files , so users can not delete this file , it can not be automatically upgraded.

**Comment by dilijev** [comment] 2016-07-15 23:11
@wallverb I think you mean Bing translate, right? =P

**Comment by VDerGoW** [comment] 2016-07-16 06:20
Visual Studio Code reminds me that it will be upgrade after restart. When I clicked "立即更新"(it means "update now" or "upgrade now"), a pop-up box appear and informed "Error  The setup files are corrupted.Please obtain a new copy of the program.". But **vscode haven't told me where to delete the broken setup file**, so i cannot find the file to delete it and download it again, cannot upgrade program.
(English is not my native language, hope you can understand what i say)

**Comment by weinand** [comment] 2016-07-16 09:11
@VDerGoW Your English is very good and I understand your problem now.

**Comment by VDerGoW** [comment] 2016-07-16 12:57
@wallverb thank you. should I close this issue?

**Comment by Emeryao** [comment] 2016-07-18 04:33
张秋雨同学 下次提issue还是直接用英文吧 你看看把大家累的
trans: Mr Zhang( @VDerGoW ), please use English next time you opening a issue , to avoid wasting time on translation.

**Comment by VDerGoW** [comment] 2016-07-18 05:23
@Emeryao 第一次提交问题，不懂规矩，以后就知道了

**Comment by weinand** [comment] 2016-07-18 06:28
@VDerGoW why did you close the issue? It is still valid and has not been resolved, correct?

**Comment by joaomoreno** [comment] 2016-07-18 09:52
Duplicate of #780, fix came with 1.3.0.

**Closed by joaomoreno** 2016-07-18 09:52 UTC
