### ISSUE TITLE
Terminal language

### ISSUE THREAD

**Issue by KokhanevychD** [microsoft/vscode#118514] opened 2021-03-09 08:32 UTC
Issue Type: <b>Bug</b>

After every system reload I can't change language in termina to en,  this is the only language I have available in display settings. To change terminal language I have to reload vscode vs display settings set on en, even that doesnt work every time from the first try

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.4.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 3899)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.48GB (7.98GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 1959fd5c-f756-4302-b1bd-a8168c462aa6 --crash-reporter-id 1959fd5c-f756-4302-b1bd-a8168c462aa6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
django|big|1.0.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
flask-snippets|cst|0.1.1
githistory|don|0.6.15
comment-anchors|Exo|1.9.1
go|gol|0.23.0
gc-excelviewer|Gra|3.0.41
Angular2|joh|11.0.0
rainbow-csv|mec|1.8.1
mongodb-vscode|mon|0.4.2
vscode-docker|ms-|1.10.0
python|ms-|2021.2.633441544
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.2
vscode-remote-extensionpack|ms-|0.20.0
jinjahtml|sam|0.16.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
vscode-djaneiro|the|1.4.2
mako|tom|0.2.0
python-auto-venv|whi|1.1.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by meganrogge** [comment] 2021-03-10 03:19
Duplicate of #116926

**Closed** 2021-03-10 03:19 UTC
Labels: *duplicate, bug, integrated-terminal
