### ISSUE TITLE
synax check error

### ISSUE THREAD

**Issue by Oger-Me** [Microsoft/vscode#5123] opened 2016-04-10 03:07 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

my code like this :
{
	prev_text: '<',
	next_text:">",
	items_per_page: 6,
        ## // behind line will fire synax check error.
	**link_to: 'javascript:;',**
	callback: function(currentPage){
	}
}

**Comment by egamma** [comment] 2016-04-13 18:26
I cannot reproduce this

![image](https://cloud.githubusercontent.com/assets/172399/14504657/f9292046-01b5-11e6-809c-492305d20a32.png)

Can you please add a screenshot of what you are seeing.

**Comment by egamma** [comment] 2016-04-23 02:41
Cannot act on this with more information - closing, pls reopen when there is more information.

**Closed by egamma** 2016-04-23 02:41 UTC
Labels: needs more info

**Comment by Oger-Me** [comment] 2016-06-07 10:21
@egamma I'm sorry. I'm late. And the latest version is ok.
