### ISSUE TITLE
Keybinding text is not upadated on the menu

### ISSUE THREAD

**Issue by xc1427** [Microsoft/vscode#32574] opened 2017-08-15 15:32 UTC
- VSCode Version: 1.15.0
- OS Version: MacOS 10.12.6

Steps to Reproduce:
1. Install a key remapping plugin such as *IntelliJ IDEA Key Bindings for Visual Studio Code* or *VSmacs*
2. Close all the tabs and windows

<img width="350" alt="screen shot 2017-08-15 at 23 21 09" src="https://user-images.githubusercontent.com/5611770/29322555-80583fa8-8210-11e7-97fd-a8ebd7409c05.png">

3. Quit then re-open VScode
4. Keys are actually remapped but the keybinding text remains unchanged on menu. 

<img width="569" alt="screen shot 2017-08-15 at 23 25 57" src="https://user-images.githubusercontent.com/5611770/29322793-68566456-8211-11e7-85c0-12831a6966f5.png">

This bug should be reproduced with plugin installed. I suppose keybinding text is not properly loaded if nothing is opened, since it displays correctly if at least one tab is opened the last run.

**Comment by bpasero** [comment] 2017-08-16 05:04
@xc1427 I just tried and cannot reproduce, are you sure the extension is running? Does a window reload help?

Something printed to the chrome developer console (access from help menu)?

**Comment by bpasero** [comment] 2017-08-16 05:17
@xc1427 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment] 2017-08-16 05:52
I think the issue here is that when we resolve keybindings on startup (or window reload) we actually do not wait for the extensions to be ready. But since extensions can have an impact on the keybindings, we need to wait for this event to happen.

I pushed a fix for the keybindings resolver call to wait for `onExtensionsReady`. That should take care of the issue.

**Closed** 2017-08-16 05:51 UTC
Labels: bug
