### ISSUE TITLE
[FIX / Improve] #17456 when tag script included atribute src, intellisense suggest JS code, but don't end tag "</script>"

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#24323] opened 2017-04-08 17:35 UTC
- VSCode Version: 1.11.1
- OS Version: ALL

Steps to Reproduce:

![screenshot_112](https://cloud.githubusercontent.com/assets/21063534/21286909/7593ea4a-c460-11e6-8440-6304c4bdf920.png)

#17456

**Comment by chrmarti** [comment] 2017-04-08 18:22
This is documented as requiring an end tag: https://developer.mozilla.org/en/docs/Web/HTML/Element/script

This is unlike br, which is documented as not having an end tag: https://developer.mozilla.org/en/docs/Web/HTML/Element/br

**Comment by Mlocik97** [comment] 2017-04-08 18:27
I think, better is when intellisense suggest `</script>` when I write `<`, now it suggest `<$`

**Comment by aeschli** [comment] 2017-04-10 14:44
duplicate of #12787

**Closed by aeschli** 2017-04-10 14:44 UTC
