### ISSUE TITLE
VSCode doesn't watch for tsconfig.json

### ISSUE THREAD

**Issue by Kyasaki** [Microsoft/vscode#15097] opened 2016-11-07 14:21 UTC
- VSCode Version: 1.7.1
- OS Version: Mac OSX 10.12

I have a Typescript/React/TSX project. Since my team changed from grunt to webpack and  I updated VSCode, I can't get my global imports work as before, as well as the JSX recognition:

> [ts] Cannot find module 'react'.
> [ts] Cannot find module 'd3-scale'.
> [ts] Cannot use JSX unless the '--jsx' flag is provided.

We have a typings file, so I tried to fix this by making a include rule inside the tsconfig file:

```JSON
{
    "compilerOptions": {
        "target": "es6",
        "jsx": "react",
        "sourceMap": true
    },
    "include": [
        "./src/**/*",
        "./typings/index.d.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

But this file, which is at the root of the project, seems just ignored by VSCode, as doing a manual include does the job, nor the tsconfig.json file:

```TypeScript
/// <reference path="../typings/index.d.ts" />

// Global imports
import * as React from 'react';
import * as d3Scale from 'd3-scale';
// Ok!
```

I don't feel like I'm doing something wrong, but à tout hasard, this are my workspace settings:

```JSON
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```

Best regards

**Comment by devrelm** [comment] 2016-11-07 20:06
Actually, I solved this for my case: The file is not reached/included from either of the files listed in the `"files"` array. I fixed it by adding `"include"` and `"exclude"` with globs of files to be included.

We generally build using a custom script, so our tsconfig hasn't been kept up to date.

**Comment by devrelm** [comment] 2016-11-10 16:16
Update: This actually didn't fix my issue, at least not without side-effects. We're using browserify & tsify, so we select files in browserify and pass them through to tsify, which picks up the tsconfig. I can update the tsconfig to use the same files as tsify, but then we have issues with the actual build that's output being different.

I didn't have the issue with the `Cannot use JSX unless the '--jsx' flag is provided.` error in VS Code until 1.7.

**Comment by waderyan** [comment] 2016-11-10 18:57
@Kyasaki and @devrelm thank you for your comments on this issue. Can you share your code repos so we can reproduce on our end? 

@bowdenk7 could I get your eyes on this. Generally, there is an error in the tsconfig.json that causes the issue. A couple things I can see:
* I'm unfamiliar with @devrelm's use of `atom` and `filesGlob` in his tsconfig.json file. I do not see it [documented](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html). 
* The common attribute in the two files seems to be `jsx`

**Comment by Kyasaki** [comment] 2016-11-25 15:45
Hopelessly, our repos are private and I won't be able to share them.

**Comment by waderyan** [comment] 2016-11-28 20:08
@Kyasaki can you reproduce in another way that you can share with us?

**Comment by devrelm** [comment] 2016-12-22 14:55
For what it's worth, I'm not having this trouble anymore since 1.8.

**Comment by waderyan** [comment] 2017-01-03 22:24
@devrelm good to hear! 

Closing this. Please reopen if the issue reappears.

**Closed by waderyan** 2017-01-03 22:24 UTC
Labels: config, intellisense, javascript, needs more info
