### ISSUE TITLE
Theme Color Bug with typescript functions

### ISSUE THREAD

**Issue by Phaze1D** [Microsoft/vscode#45171] opened 2018-03-07 03:55 UTC
- VSCode Version: 1.20.1
- OS Version: macOS Hign Sierra Version 10.13.3

Steps to Reproduce: 

1.  When I add a newline to the params of a typescript arrow function the 'colorization' of the params fails

### Correct Colors
![screen shot 2018-03-06 at 9 49 37 pm](https://user-images.githubusercontent.com/8495952/37072730-8563f5d8-2188-11e8-938e-4decd865e14a.jpg)

### Incorrect Colors
![screen shot 2018-03-06 at 9 49 19 pm](https://user-images.githubusercontent.com/8495952/37072723-806129c0-2188-11e8-9d45-4d200604f66d.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-03-07 21:35
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/481 and similar upstream

Take a look at https://github.com/Microsoft/TypeScript-TmLanguage/pull/552

**Closed by mjbvz** 2018-03-07 21:35 UTC
Labels: grammar, javascript, upstream
