### ISSUE TITLE
Bad spacing in breadcrumbs due to icons

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#75399] opened 2019-06-13 08:10 UTC
![screenshot wHewD4](https://user-images.githubusercontent.com/22350/59415300-7ace7280-8dc3-11e9-961f-661dd499e2f9.png)

**Comment by misolori** [comment] 2019-06-13 16:17
Duplicate of #75399

**Closed by misolori** 2019-06-13 16:17 UTC
