### ISSUE TITLE
Feature request: On close activate editor on the left or right

### ISSUE THREAD

**Issue by wdscxsj** [Microsoft/vscode#47410] opened 2018-04-08 01:21 UTC
- VSCode Version: 1.22.1
- OS Version: Windows 10

It seems that when an editor is closed, VSCode will activate the most recently used editor, which may feel a little unpredictable.

There is an option `workbench.editor.openPositioning` to control where a new editor opens. Isn't it nice to have a companion option `workbench.editor.activateOnClosePositioning` that, unsurprisingly, controls which existing editor to activate when one is closed? Thanks.

**Comment by bpasero** [comment] 2018-04-08 10:04
Duplicate of https://github.com/Microsoft/vscode/issues/43459

**Closed by bpasero** 2018-04-08 10:04 UTC
Labels: workbench-tabs
