### ISSUE TITLE
Can't install code and code-insiders RPMs together from repo

### ISSUE THREAD

**Issue by rickhg12hs** [microsoft/vscode#116100] opened 2021-02-08 12:27 UTC
- VSCode Version:
   code-insiders-1.54.0-1612761896.el7.x86_64
   code-1.53.0-1612368438.el7.x86_64
- OS Version:
   Fedora 32 5.10.12-100.fc32.x86_64

Steps to Reproduce:

1.  dnf install code-insiders
2.  dnf install code
3.  Observe installation error (see below)

Does this issue occur when all extensions are disabled?: ~~Yes/No~~ Unrelated.  This is an installation bug.

### Installation Error ###
```bash
# dnf --refresh install code
...
Visual Studio Code                                                                       24 kB/s | 3.0 kB     00:00    
Dependencies resolved.
========================================================================================================================
 Package                Architecture             Version                                   Repository              Size
========================================================================================================================
Installing:
 code                   x86_64                   1.53.0-1612368438.el7                     code                    92 M

Transaction Summary
========================================================================================================================
Install  1 Package

Total download size: 92 M
Installed size: 259 M
Is this ok [y/N]: y
Downloading Packages:
code-1.53.0-1612368438.el7.x86_64.rpm                                                   4.7 MB/s |  92 MB     00:19    
------------------------------------------------------------------------------------------------------------------------
Total                                                                                   4.7 MB/s |  92 MB     00:19     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/0d/be96b94dbeaabaa50723e06b4961269ede6d21 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/17/bfe6f30fec39e3bb5069ce96a807c7bded2315 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/3d/c37ee61f555565e639c0877b5356745385c096 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/3d/c37ee61f555565e639c0877b5356745385c096.1 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/47/66940d55c56a64fc44b9068b384dd907546b35 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/62/e9518e209dbf859512fb22a4f2d09956110c45 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/66/c9609600956add52abe37ad87ad8e05b46b0cf from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/70/57f9476a6ff6d6c2c548294c1fad7611bda125 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/79/e66434515226cc13ad9ee6f153da1ce837a828 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/7b/2cf88796a14e455e392760056a8cf2bce6f9f4 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/82/ca1a9cfd961f8a51d6226ca2326d4ae7b5fe40 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/8b/7281451991f813f2e5515b86c3ac2433fb9dc5 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/a8/1e0722055b27f4d32c59538e6058b4cbbf0e61 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/b2/4de59d738335312ca8996aeacc4e7e60244ce1 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/db/f5c95305e07dc3b44c38bd92e6149943e5c869 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/dd/50ec0d1fed265f44d37c64a7e92d293a2a3f50 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/e8/7f188e8dc194aba16a64481c562f39f52ca726 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/eb/f10b7f37d02e129b35c6362b395bcdde641eb8 from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64
  file /usr/lib/.build-id/ef/53f56148cf2d1fbf2d3866e4a8387e585c41ad from install of code-1.53.0-1612368438.el7.x86_64 conflicts with file from package code-insiders-1.54.0-1612761896.el7.x86_64

```

**Comment by davidbailey00** [comment] 2021-02-08 12:46
I believe this may be an issue with [electron-installer-redhat](https://github.com/electron-userland/electron-installer-redhat), as I have encountered the same issue with some packages of my own which use the same Electron version.

Basically, the conflicting files are debugging symbols. They are the same across both packages because the same Electron binary is used.

**Comment by gjsjohnmurray** [comment] 2021-02-08 13:28
Looks like a duplicate of #115856

**Comment by rickhg12hs** [comment] 2021-02-08 13:53
@gjsjohnmurray I think you're right, this is a duplicate.  I searched issues looking for install problems, since that's what I was experiencing.

Also, **this is a relatively new problem**.  Previously I had both `code` and `code-insiders` installed from the repo and everything was fine.  Something must have changed in the past week or so.

**Comment by davidbailey00** [comment] 2021-02-08 13:56
> Also, this is a relatively new problem. Previously I had both code and code-insiders installed from the repo and everything was fine. Something must have changed in the past week or so.

I would imagine that's because, until the 1.53.0 release, the Electron binaries were different versions between `code` and `code-insiders`.

**Closed** 2021-02-08 15:07 UTC
