### ISSUE TITLE
Automatically add the repository to the RPM file for Fedora/CentOS/RHEL and OpenSuse

### ISSUE THREAD

**Issue by jorgeperezlara** [microsoft/vscode#177767] opened 2023-03-21 07:34 UTC
The [.deb package](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) for Ubuntu and Debian-based OSes automatically add the repository to APT. This way, whenever there's an update to VSCode, the users can update it in APT easily and without any hassle.

For reasons that are unknown to me, that's not the case for the RPM package, which does not automatically add the repository to your sources file. This cannot be a limitation of the RPM format, as Google Chrome, the Vivaldi web browser, Opera, 1 Password, Brave, and even Microsoft products such as Microsoft Edge (in all its channels) and Microsoft Teams do this automatically. It just seems like the sanest approach, and VSCode is just an outlier. I believe for consistency purposes, and given Fedora seems to be gaining popularity among the enthusiasts, a little bit more attention should be paid to this. More so when, even for set up RPMFusion, Fedora already provides and RPM file that just adds the repository.

**Comment by rzhao271** [comment] 2024-12-10 23:19
Duplicate of https://github.com/microsoft/vscode/issues/141788, but thanks for the examples!

**Closed by rzhao271** 2024-12-10 23:19 UTC
Labels: feature-request, rpm, packaging
