### ISSUE TITLE
When input non-english like Chinese the input box will blink

### ISSUE THREAD

**Issue by wenshin** [Microsoft/vscode#16899] opened 2016-12-08 08:49 UTC
![vscodebug1](https://cloud.githubusercontent.com/assets/4171188/21003411/292c77fe-bd66-11e6-8df2-548e53d8efa4.gif)

- VSCode Version: 1.7.2
- OS Version: MAC OS 10.11.6

Steps to Reproduce:

1. Use Chinese input source
2. Input something

**Comment by alexandrudima** [comment] 2016-12-08 13:29
Duplicate of #356

**Closed by alexandrudima** 2016-12-08 13:29 UTC
