### ISSUE TITLE
New windows start with dark theme

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29252] opened 2017-06-22 07:08 UTC
* use a light theme
* open a new window
* 🐛 the windows a dark background for the first 1 or 2 seconds

![jun-22-2017 09-07-47](https://user-images.githubusercontent.com/1794099/27421358-630df28c-572a-11e7-9193-205a8d57e871.gif)

**Comment by bpasero** [comment] 2017-06-26 04:50
I cannot reproduce this behaviour.

**Comment by jrieken** [comment] 2017-06-26 06:03
Maybe it does when using a bright theme that comes from the marketplace?

**Comment by aeschli** [comment] 2017-06-26 06:22
I also can't reproduce. What theme from the marketplace do you use? 
Before reloading did you just switch to the bright theme? There's a known issue that the initial window background color is actually from the theme configured when the window was created. Electron doesn't let us change that window color anymore, so it's just something to live with.

**Comment by jrieken** [comment] 2017-06-26 06:25
This theme: `"workbench.colorTheme": "Hop Light",`

**Comment by aeschli** [comment] 2017-06-26 06:56
I tried with 'Hop Light' and there's nothing special/wrong with that theme. Still can't reproduce.
Closing issue until we have more information.

**Comment by jrieken** [comment] 2017-06-26 06:57
Well, just come to my desk

**Comment by aeschli** [comment] 2017-06-26 09:10
Sorry that I'm currently not able to come to your desk, maybe @bpasero ?
This is what I tried
- install latest VSCode insiders (1.14.0-insider, OSX), b508e11e5a8b90c8fa19e6e3a7d8ccd57ab6e9b7
- install Hop Light
- Restart VSCode, select Hop Theme
- Open a new window

![flashing](https://user-images.githubusercontent.com/6461412/27532259-40d16684-5a92-11e7-9a53-05e0a10a6258.gif)

**Comment by bpasero** [comment] 2017-06-26 09:11
@jrieken any multiroot setup in your case maybe?

**Comment by jrieken** [comment] 2017-06-26 11:38
Currently no multi root setup but I have been using it and seeing this might correlate with having used multiroot

**Comment by aeschli** [comment] 2017-07-11 10:58
@bpasero Can you have a look at @jrieken screen?

**Comment by rebornix** [comment] 2017-07-24 18:47
Before I created a new issue, I'd like to share what I saw when I reloading the window or switching between folders

![window-reload](https://user-images.githubusercontent.com/876920/28539122-7980a45c-7065-11e7-8b1b-e1b02efa05a0.gif)

Say I was using One Dark Pro, whose background is kind of black and when I reload the window, I can see for some milliseconds the background of the editor becomes blue (which looks like Solarized Dark blue). You can see that from above gif and I was using the latest Insider.

**Comment by isidorn** [comment] 2017-08-02 14:07
Can not reproduce, assigning to august

**Comment by bpasero** [comment] 2017-08-11 07:05
@aeschli sorry, did not have time to look into this, passing back to you

**Comment by aeschli** [comment] 2017-08-15 11:02
Joh no longer sees it. Closing for now. Please reopen when this appears again.

**Closed by aeschli** 2017-08-15 11:02 UTC

**Comment by RobertBColton** [comment] 2017-08-17 19:29
https://blog.avocode.com/blog/4-must-know-tips-for-building-cross-platform-electron-apps

See: 2.1 Specify a BrowserWindow background color

You have to pass it in the constructor in Electron.
