### ISSUE TITLE
Insiders scss bug

### ISSUE THREAD

**Issue by tomliv** [microsoft/vscode#76889] opened 2019-07-08 14:54 UTC
I am getting the following error in Code-Insiders when working in a scss file. Tab key no longer moves cursor and code hinting stopped working.

"Cannot read property 'Symbol(Symbol.iterator)' of t.push"

VS Code version: Code - Insiders 1.37.0-insider (d50852db1af10ec100a71ad57cc3a04c8aead117, 2019-07-08T05:33:31.335Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (4.26GB free)|
|Process Argv|-psn_0_659617|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
Bookmarks|ale|10.4.4
project-manager|ale|10.5.2
htmltagwrap|bra|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-hasher|dee|1.0.1
beautify|Hoo|1.5.0
coldfusion|ili|1.0.1
vscode-gutter-preview|kis|0.19.4
vscode-apache|mrm|1.2.0
gremlins|nho|0.14.3
es6-css-minify|olb|2.7.0
sort-lines|Tyr|1.8.0
vscode-icons|vsc|8.8.0

(4 theme extensions excluded)

</details>

**Comment by octref** [comment] 2019-07-08 15:31
Can you give me the full file where I can repro this bug?

**Comment by tomliv** [comment] 2019-07-08 15:49
I am running just 8 extensions. If I listed them, would you know what chucked that error? Is it related to something specific?

**Comment by octref** [comment] 2019-07-08 15:58
I wouldn't. Please disable all extensions so we can figure out if it's an error caused by VS Code or extensions (you can also launch VS Code with `code --disable-extensions`)

![image](https://user-images.githubusercontent.com/4033249/60824428-6d0bd300-a15e-11e9-80f4-8bf4a0893734.png)

Also you can find more information of the error in Help -> Toggle Developer Tools when they show up.

**Comment by tomliv** [comment] 2019-07-08 15:59
Running with extensions off now. So far so good.

**Comment by FadedGradient** [comment] 2019-07-08 18:07
I'm also having this problem. Is there any fix without disabling extensions? Or maybe which extension is causing this? Thanks.

**Comment by tomliv** [comment] 2019-07-08 18:26
@FadedGradient Heck, I'm just glad it's not just me! Is there some way we can share extension lists (if here isn't the right place) and see if we can narrow it down?

**Comment by tomliv** [comment] 2019-07-08 18:33
Here's what I'm running...

<img width="364" alt="ScreenShot-extensionlist" src="https://user-images.githubusercontent.com/1153953/60833871-43b66b80-a18d-11e9-9ae7-384062bd1a4e.png">

**Comment by octref** [comment] 2019-07-08 18:49
> Is there some way we can share extension lists (if here isn't the right place) and see if we can narrow it down?

It's in your issue report. 
![image](https://user-images.githubusercontent.com/4033249/60834812-6426fb80-a176-11e9-8dc0-ee5645002742.png)

You can also run `code --list-extensions`. My guess would be `bracket-pair-colorizer`.

**Comment by tomliv** [comment] 2019-07-08 19:43
Ah, cool. Sorry, I'm a bug noob.

**Comment by octref** [comment] 2019-07-08 20:37
NP, I'll close this issue then. Was it really the bracket-pair-colorzier causing the issue?

**Closed by octref** 2019-07-08 20:37 UTC
Labels: needs more info
