### ISSUE TITLE
 Cannot read property 'strings' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#102348] opened 2020-07-13 05:56 UTC
Issue Id: <b>89766491-13cf-6610-b113-20375830a5dd</b><br /><br />*Versions* <br />- 1.47.0<br />-  e95f9e63380a139cb1cbe54bacfc6703b96e30b9<br />*Stack* <br />TypeError: Cannot read property 'strings' of null<br />[/vs/editor/common/config/commonEditorConfig.ts#373:27 (_subsetEquals)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/config/commonEditorConfig.ts#L373:27 (_subsetEquals))<br />[/vs/editor/common/config/commonEditorConfig.ts#385:15 (_subsetEquals)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/config/commonEditorConfig.ts#L385:15 (_subsetEquals))<br />[/vs/editor/common/config/commonEditorConfig.ts#402:32 (updateOptions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/config/commonEditorConfig.ts#L402:32 (updateOptions))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#363:22 (updateOptions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/browser/widget/codeEditorWidget.ts#L363:22 (updateOptions))<br />[/vs/workbench/browser/parts/editor/textEditor.ts#311:22 (updateEditorConfiguration)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/browser/parts/editor/textEditor.ts#L311:22 (updateEditorConfiguration))<br />[/vs/workbench/browser/parts/editor/textEditor.ts#150:57 (call)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/browser/parts/editor/textEditor.ts#L150:57 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#437:25 (setModel)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/browser/widget/codeEditorWidget.ts#L437:25 (setModel))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#1473:56 (call)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/browser/widget/codeEditorWidget.ts#L1473:56 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/editor/common/model/textModel.ts#385:22 (dispose)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/model/textModel.ts#L385:22 (dispose))<br />[/vs/editor/common/services/modelServiceImpl.ts#576:18 (destroyModel)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/services/modelServiceImpl.ts#L576:18 (destroyModel))<br />[/vs/workbench/common/editor/textEditorModel.ts#178:21](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/common/editor/textEditorModel.ts#L178:21)<br />    at C.dispose (out/vs<br />

**Comment by alexdima** [comment] 2020-07-21 09:43
Duplicate of #102920

**Closed by alexdima** 2020-07-21 09:43 UTC
Labels: error-telemetry
