### ISSUE TITLE
extension-specific setting for format on save

### ISSUE THREAD

**Issue by AnWeber** [Microsoft/vscode#13845] opened 2016-10-17 06:25 UTC
Feature Request for the new setting

` 
"editor.formatOnSave": true,
`

As user I want to use the new setting not only language-specific (#13547). I want also want to actively set in my workspace settings, which extension should format the content.

Example: I support 2 projects. In one project the required formatting is Javascript Standard format (chenxsan.vscode-standard-format). In my second project the format Javascript Semi Standard (homerjam.vscode-semistandard-format) is used.

**Comment by jrieken** [comment] 2016-10-17 09:18
dupe of #11609

**Closed by jrieken** 2016-10-17 09:18 UTC
