### ISSUE TITLE
[Bug] `terminalFindVisible` is true only if the find is focused

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#117159] opened 2021-02-21 03:27 UTC
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. In the integrated terminal, press `Alt + R` to enable regular expression.
2. Press `Escape` // The find widget is not hidden.
3. Click the "find input" to focus it.
4. Press `Escape` // This time, the find widget is hidden.

Does this issue occur when all extensions are disabled?: Yes

To make it work, I had to change the when expression from `terminalFindVisible && terminalFocus && terminalProcessSupported` to `terminalFocus && terminalProcessSupported`.

**Comment by Tyriar** [comment] 2021-07-15 14:34
Same root cause as https://github.com/microsoft/vscode/issues/127922, fixed in https://github.com/microsoft/vscode/pull/128144

**Closed** 2021-07-15 14:34 UTC
Labels: *duplicate, bug, terminal
