### ISSUE TITLE
Reveal in tree causes custom container to be shown

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#50274] opened 2018-05-22 11:09 UTC
I've got a tree view in a custom container in the activity bar. When my extension loads, it reveals an item in the tree. This causes the activity bar to show the container.

This actually seems sensible and normally I would expect this to happen if I interactively cause the item to be revealed, but it means that the view container is always shown at startup.

Should another parameter to added to the reveal function indicating that the view itself should be revealed?

**Comment by Gruntfuggly** [comment] 2018-05-23 13:20
Also, I've noticed that reveal causes the view to become visible when the user has previously hidden it using the context menu (both custom containers and views in standard containers).

**Comment by sandy081** [comment] 2018-05-29 13:20
Duplicate of #48198

**Closed** 2018-05-29 13:21 UTC
Labels: *duplicate, explorer-custom
