### ISSUE TITLE
Use editor.suggest.preview without quick suggestions

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#126375] opened 2021-06-15 12:33 UTC
Hello @hediet @jrieken @alexdima. I really like new setting `editor.suggest.preview`, but I'm wondering if it's possible to make these previews available even with quick suggestions disabled? It could be really powerful with `editor.tabCompletion: "on"`, because you would see suggestion as you type and you can simply hit 'Tab' to resolve it.

**Comment by svipas** [comment] 2021-06-16 10:05
@hediet What I mean is be able to see previews without quick suggestions, because if I disable them I cannot see previews. I can see them only with quick suggestions enabled. It would be very amazing, because finally in this case I could totally disable quick suggestions, especially in code-bases where I know things 🙂

**Comment by hediet** [comment] 2021-06-16 11:22
This also agrees with my vision on how tabCompletion: on should work with editor.suggest.preview!

**Comment by svipas** [comment] 2021-06-16 12:53
@hediet Amazing news!

**Comment by hediet** [comment] 2021-06-17 09:31
After having a closer look at the problem described in #125328, I think this issue really is a different feature request. I will reopen it to track it separately.

**Comment by svipas** [comment] 2021-12-07 22:54
@hediet Copilot can do this with `editor.quickSuggestions` -> `false`. I really like to turn off quick suggestions and as I type see inline suggest and simply press tab to auto-complete. I really want this feature and I believe it would be valuable to others, how I can help to push this forward?

Basically what I expect is to see inline suggest with `editor.quickSuggestions` -> `false` & `editor.inlineSuggest.enabled` -> `true`. You could look at screenshot below, this is how it looks like with Copilot, I expect the same inline suggest, but without Copilot.

<img width="424" alt="Screen Shot 2021-12-08 at 00 37 53" src="https://user-images.githubusercontent.com/10441177/145117231-f447041b-c4ed-4bde-82bd-ba6e064d1724.png">

P.S. Please tell me what should I change to at least compile VS Code by myself to have this functionality.

**Comment by hediet** [comment] 2021-12-08 09:09
> I really want this feature and I believe it would be valuable to others, how I can help to push this forward?

Unfortunately, this is not trivial at all. You need a completion session to know what items there are to suggest. `editor.suggest.preview: true` just connects to the existing completion session.
But the requested feature requires inline completions to actually create a new completion session, which is not trivial.

**Comment by svipas** [comment] 2021-12-08 12:10
@hediet Yeah I understand that and I now know the difference between `editor.suggest.preview` and inline suggestions. So basically to achieve what I want is to simply not show suggest widget, but keep the suggest model active. So we are kinda taking about even maybe new setting, because current completions do not register as inline completions. Anyways, I hope someday we could have this feature, because it's just amazing, you could simply disable quick suggest widget and while typing you could see those "inline" completions as you type. The reason why I think it's really good feature request is because it minimizes distraction and especially it's good if you know codebase. Look at Copilot, it doesn't add those completions to suggest widget, but simply uses inline completions, why not do that for all completions and maybe register 2 providers (inline & simple) so we could have this feature out-of-the box.

To go back to question @hediet do you consider this feature request reasonable? If yes, could I help to implement this? I don't know which correct way it would be, a new setting? Register completions as inline completions (in this case there would be 2 completion providers and what about Copilot since it uses inline completions)?

I know you guys have a lot of stuff going on, but I hope one day we will have this.

**Comment by hediet** [comment] 2021-12-08 12:18
> do you consider this feature request reasonable?

I would like to have it too, but I currently don't have the time to work on it.

> If yes, could I help to implement this? 

You could try, but it will be hard and would even take me a couple of days. I don't have the time to assist you here.

Long term, you could look out for [help-wanted](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+assignee%3Ahediet) issues and work on them, that would help us a lot (look at [this query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+) for more issues).
I cannot promise anything, but if we don't have to spent so much of our time on all those "easy" issues, it is much more likely that we find time to work on non-trivial issues like this.

**Comment by jrieken** [comment] 2022-02-09 15:53
Idea would be to tweak the setting like so: `editor.quickSuggestions -> true | "inline" | false `. The `true` means "_suggestions as you type, presented with the suggest widget_", and `"inline"` means "_suggestions as type, presented via inline text_"

**Comment by svipas** [comment] 2022-02-09 15:54
@jrieken Amazing idea! I really love it 👍

**Comment by jrieken** [comment] 2022-02-11 12:27
@hediet I can help with this but inline completions need to become a little more powerful, like support for snippets

**Comment by svipas** [comment] 2022-03-17 16:45
I just saw that this issue is included in current iteration plan (March 2022). This is amazing news! Thanks a lot @jrieken & @hediet!!! 🥳

**Comment by jrieken** [comment] 2022-03-18 10:54
First cut of this is in https://github.com/microsoft/vscode/pull/145386

https://user-images.githubusercontent.com/1794099/158990171-58b68109-ffaf-4575-a983-d26aba0873d8.mov

**Comment by svipas** [comment] 2022-03-18 11:08
@jrieken Looks amazing!

Is it possible to make `inline` suggestions after `.` as well? Or it should work by adding `"editor.suggestOnTriggerCharacters": false` into settings ? `console` was `inline`, but after pressing `.` you got completion widget, it would be nice to be able to use `inline` completions afterwards instead of seeing completion widget. Why? Completely use `inline` suggestions, because if you use them you probably know codebase well and if you don't know you could simply hit `ctrl + space` to see completion widget.

**Comment by jrieken** [comment] 2022-03-18 11:50
> Or it should work by adding "editor.suggestOnTriggerCharacters": false into settings

Yeah, you will need to use that config. For us quick suggest and trigger characters are separate and they shouldn't be married with this feature. Tho, I can confirm that things nice with it off.

https://user-images.githubusercontent.com/1794099/158998117-d8283329-9705-4e41-911a-59307dae603d.mov

**Comment by svipas** [comment] 2022-03-18 12:11
That is awesome! Thanks a lot! ❤️

**Comment by jrieken** [comment] 2022-03-18 14:57
merged so this can be tried in next insiders

**Closed** 2022-03-21 10:15 UTC
Labels: feature-request, suggest, inline-completions

**Comment by gjsjohnmurray** [comment] 2022-03-21 10:56
New settings give lots of flexibility but can't be handled by Settings Editor GUI, and look a bit cryptic when editing as JSON

![image](https://user-images.githubusercontent.com/6726799/159247549-bd0c265d-eb81-40af-9f3a-d27666bf9702.png)

**Comment by jrieken** [comment] 2022-03-21 11:14
Even before it couldn't be handled by the setting UI and all my attempts to simplify this setting didn't result in a working UI. @roblourens @rzhao271 this setting might be boss enemy of the UI and I am happy to accept any advice to make this better

**Comment by svipas** [comment] 2022-03-22 09:17
@jrieken Thanks a lot for implementing this feature, I did some testing and found out 2 issues, I'm not quite sure if you can call them "issues" maybe it's expected to work like this.

If you look at the gif below, you will see when I write `co` I see `cancelAnimationFrame` and it quickly changes to `confirm`, but if use suggest widget this doesn't happen. And, the last one is when I use snippet `log` it have strike like it is deprecated (same happens in Settings, so I would say for all snippets).

![Recording 2022-03-22 at 11 12 56](https://user-images.githubusercontent.com/10441177/159446803-6a4a01a2-3785-4521-a475-68a1a0622837.gif)

**Comment by jrieken** [comment] 2022-03-22 15:19
Yeah, we have a few follow-up items to make this "less nervous". The different between inline completions and "normal" completions is that the former are recomputed on each key stroke. For inline quick suggestions some caching is happening but due to UI debounce and things this isn't ideal yet. We are on it

**Comment by svipas** [comment] 2022-03-22 18:14
Very good to know, I'm really excited for this to land 🙂
