### ISSUE TITLE
when at zoom < 0, line breaks in html pages are offscreen. 

### ISSUE THREAD

**Issue by pleprince** [Microsoft/vscode#17614] opened 2016-12-20 14:58 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|xml|DotJoshJohnson|1.6.1|
|material-icon-theme|PKief|1.1.5|
|code-settings-sync|Shan|2.3.8|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|vscode-color|anseki|0.2.2|
|QML|bbenoist|1.0.0|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-instant-markdown|dbankier|0.2.1|
|line-counter|Dollyn|0.1.2|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|vscode-great-icons|emmanuelbeziat|1.1.29|
|vscode-npm|fknop|3.3.0|
|rib|glowtree|0.1.1|
|badges|idleberg|1.0.5|
|textile|idleberg|0.1.0|
|restructuredtext|lextudio|0.0.19|
|vs-color-picker|lihui|0.3.2|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.3|
|sublime-keybindings|ms-vscode|1.8.0|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|4.2.0|
|todotasks|sandy081|0.4.0|
|mel|sator-imaging|0.1.1|
|Spell|seanmcbreen|0.9.1|
|preview-vscode|searKing|1.1.1|
|perforce|slevesque|0.1.10|
|shader|slevesque|0.2.2|
|theme-monokaigraypixar|plp|0.0.1|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. split the workspace to get 2 side by side columns
2. got to Help -> Release Notes to display the release notes.
3. if zoom == 0, the lines are wrapping correctly. no off-screen words. (good)
4. set zoom to -1: some lines are cut on the right side. (bad)

![zoom_out_reformating](https://cloud.githubusercontent.com/assets/10943552/21355133/bcc5e150-c6c4-11e6-8660-83a0062e5079.jpg)

Keep up the good work, guys !

**Comment by jrieken** [comment] 2016-12-20 17:06
dupe of #5745

**Closed by jrieken** 2016-12-20 17:06 UTC
