### ISSUE TITLE
Word wrap doesn't wrap on window width for indented CJK text

### ISSUE THREAD

**Issue by dantmnf** [Microsoft/vscode#14794] opened 2016-11-01 07:50 UTC
- VSCode Version: Code - Insiders 1.7.0-insider (0706b425537d8cfe2766eac00662ecf988c7ed7f, 2016-10-28T13:10:55.168Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Input a long line of CJK text with leading spaces/tabs
2. Enable word wrap

![codewordwrap1](https://cloud.githubusercontent.com/assets/2252500/19882744/d53a0c48-a04a-11e6-86e7-860725f7420b.PNG)

![codewordwrap2](https://cloud.githubusercontent.com/assets/2252500/19882752/db0b85d4-a04a-11e6-87fc-e3ffb101e94e.PNG)

**Comment by rebornix** [comment] 2016-11-01 15:57
It might be duplicate of https://github.com/Microsoft/vscode/issues/9989 .

**Comment by alexandrudima** [comment] 2016-11-07 18:58
@dantmnf Can you please also provide the text in textual form (such that I could copy-paste it). We have some code that looks at specific code-point ranges and I'd like to make sure they cover this text.

**Comment by dantmnf** [comment] 2016-11-08 05:03
@alexandrudima Unfortunately I didn't save the original text. I copied again from Wikipedia and it triggers the same issue in the same version.
```
协和飞机（法语、英语：Concorde）是一款由法国宇航和英国飞机公司联合研制的中程超音速客机，它和苏联图波列夫设计局的图-144同为世界上少数曾投入商业使用的超音速客机。协和飞机在1969年首飞、1976年投入服务，主要用于执行从伦敦希思罗机场（英国航空）和巴黎戴高乐国际机场（法国航空）往返于纽约肯尼迪国际机场的跨大西洋定期航线。飞机能够在15000米的高空以2.02倍音速巡航，从巴黎飞到纽约只需约3小时20分钟，比普通民航客机节省超过一半时间，所以虽然票价昂贵但仍然深受商务旅客的欢迎。1996年2月7日，协和飞机从伦敦飞抵纽约仅耗时2小时52分钟59秒，创下了航班飞行的最快纪录[1]。


                 协和飞机共生产了20架，其中仅有16架投入营运。巨大的资金投入和漫长的研发过程使英法两国政府蒙受了不小的经济损失，而且两国政府还不得不拨款资助英航和法航购买协和飞机。2000年，协和飞机发生了其营运生涯的第一次、也是唯一的一次灾难性事故——法国航空4590号班机空难，旅客对其信心大减，之后的911事件又使国际民航业陷入危机。受种种因素影响，英航和法航决定协和飞机执行完2003年10月23日的最后一次商业飞行后终止服务，并于同年11月26日完成“退役”航班后结束其27年的商业飞行生涯[2]。协和飞机代表着航空技术史上的技术进步，因此即使退役后，协和飞机仍然是航空历史上的重要象征。


                 開発当時は世界各国のフラッグ・キャリアから発注があったものの、ソニックブームなどの環境問題、開発の遅滞やそれに伴う価格の高騰、また大量輸送と低コスト化の流れを受けてその多くがキャンセルとなった。特にニューヨーク便就航に際しては激しい反対運動が展開され、法廷闘争にまで至った。最終的にはエールフランスと英国海外航空を継いだブリティッシュ・エアウェイズの2社のみによる運行に留まる。
```

In addition, the following text should also trigger this issue when wrapped on Chinese part.
```
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 天地玄黃宇宙洪荒日月盈昃辰宿列張寒來暑往秋收冬藏 incididunt ut labore et dolore magna aliqua. Ut enim ad minim 閏餘成歲律呂調陽雲騰致雨露結為霜金生麗水玉出崑岡 veniam, quis nostrud exercitation ullamco laboris 劍號巨闕珠稱夜光果珍李柰菜重芥薑海鹹河淡鱗潛羽翔龍師火帝鳥官人皇始制文字乃服衣裳 nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Closed** 2016-11-08 14:20 UTC
Labels: bug, editor-core
