### ISSUE TITLE
[html] support 'import' in <script> tags

### ISSUE THREAD

**Issue by vp2177** [microsoft/vscode#29315] opened 2017-06-23 10:59 UTC
- VSCode Version: 1.13.1
- OS Version: 

Steps to Reproduce:

1. Given the files:
a.js:
```
/**
 * @param {number} param1
 * @param {string} param2
 */
export default function a(param1, param2) {}
```

index.html:
```
<script>
  import a from './a.js'

  a( )
</script>
```

2. When typing `a(`, the type information is not picked up from the definition of `a()` in `a.js`.
3. Same works from a JS file

Now that `import` is beginning to appear in browsers I think handling it would make sense

**Comment by Rich-Harris** [comment] 2017-11-23 13:39
Adding a note to say that ideally VSCode would also autocomplete import specifiers in`<script>` tags, the same way it does in .js and .ts files. Opened #35732 for this, but it was closed as a duplicate of this issue.

**Comment by vincentvictoria** [comment] 2019-05-16 05:49
Seems like this issue is vastly ignored.
I have to make a separate js file even if I want to write a short module script in html files because of this issue.
Hope it gets attention.

**Comment by bsunderhus** [comment] 2019-07-18 19:27
This feature would fit greatly with [HTML Modules proposal](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md)

**Comment by aeschli** [comment] 2019-10-09 11:00
duplicate of #26338

**Closed by aeschli** 2019-10-09 11:00 UTC
Labels: feature-request, javascript

**Comment by Rich-Harris** [comment] 2019-10-09 12:55
Is this a duplicate of #26338? They feel quite different — this issue is about being able to reuse the logic around `import` that already exists in `.js` and `.ts` files, whereas #26338 seems to be about applying intellisense to code that references legacy scripts that e.g. assign to `window`, which seems like a different (and much hairier!) problem, especially when considering `async` and `defer` attributes. Apologies if I've misunderstood.

**Comment by aeschli** [comment] 2019-10-09 20:48
@Rich-Harris Not exactly the same, I agree. Both issues are about making HTML following references and configuring the typescript service with additional files. The challenge for both is that we likely need a project understanding as to where to find the files.

**Comment by vp2177** [comment] 2019-10-10 04:34
As long as the import URL is relative (`import './a.js'`, `import 'a.js'`, `import '../a.js'` etc.), then relative to the current file.

If the import URL has a http[s] schema, then potentially fetch the file there.

Isn't the only case that's hard to handle an absolute import URL (`import '/a.js'` etc.)? In which case, I think the current behaviour is fine, just don't reference that file. It probably isn't in the project root and VSCode has no way to know where it would be served from at runtime.  
Potentially add a config option, but I think that's a separate feature request.
