### ISSUE TITLE
Deprecation warning during command line installation of VS Code extensions

### ISSUE THREAD

**Issue by ricardo-espinoza** [microsoft/vscode#133062] opened 2021-09-14 05:13 UTC
Does this issue occur when all extensions are disabled?:
Yes.

- VS Code Version: 1.59.1 (Node.js: 14.16.0)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Install an extension from its VSIX using `code --install-extension` from the command line. 
2. Observe a deprecation warning coming from Node (node:33076) on `Buffer()`.

All details on the warning and additional context can be found in the linked issue below.

This was reproduced originally using the Microsoft QDK extension [quantum-devkit-vscode-0.18.2108160999.vsix](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/quantum/vsextensions/quantum-devkit-vscode/0.18.2108160999/vspackage) from the VS Marketplace, however, this issue can be reproduced even creating a minimal new extension.

All details on how this issue was diagnosed and identified originally can be found in [this issue](https://github.com/microsoft/qsharp-compiler/issues/1130).

**Comment by isidorn** [comment] 2021-09-14 13:27
I can reproduce getting the warning
```
(node:33745) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'quantum.quantum-devkit-vscode-0.18.2108160999.vsix' was successfully installed.
```
And this seems like a duplicate of https://github.com/microsoft/vscode/issues/131472

I am not getting any errors of the sort `UnhandledPromiseRejectionWarning`.
@ricardo-espinoza can you reproduce getting this rejection with latest VS Code insiders?

**Closed** 2021-09-17 08:00 UTC
Labels: needs more info, extensions, *duplicate

**Comment by isidorn** [comment] 2021-09-17 08:27
Here's the original duplicate issue https://github.com/microsoft/vscode/issues/82524
