### ISSUE TITLE
Not returning focus to integrated terminal if Quick Open or Show Commands are cancelled

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11264] opened 2016-08-31 00:23 UTC
Testing #11137 
- VSCode Version: 1.5.0
- OS Version: OS X 10.11.6, Windows 10, Ubuntu 16.04

Steps to Reproduce:
1. Toggle integrated terminal
2. Try `Ctrl-P/Cmd-P` or `Ctrl-Shift-P/Cmd-Shift-P`, then `ESC` to exit it.
3. Focus is on the editor focused before opening the terminal, not the terminal.

**Comment by Tyriar** [comment] 2017-04-20 21:10
Closing this off as designed since all other components act like this.

**Closed by Tyriar** 2017-04-20 21:10 UTC
Labels: as-designed, integrated-terminal
