### ISSUE TITLE
JSDoc wrapping long strings not working. Possible to concatenate or have a special format for it to concatenate

### ISSUE THREAD

**Issue by lunchboxsuhi** [Microsoft/vscode#31996] opened 2017-08-03 20:10 UTC
- VSCode Version: 1.13.1
- OS Version: Windows 10 (64-bit)

Steps to Reproduce:

```
/**
 * GrafConfig is the configuration class that is to be injected into the Graf class
 *      it does not do anything special!
 * 
 * @class GrafConfig
 * @param {Point []} points the (x,y) array of positions for the current graph
 * @param {string} xDescription the title for the x axis to be displayed
 * @param {string} yDescription the title for the y axis to be displayed
 * @param {string} title the title for the graph that will be displayed at the top
 * @param { }
 */
let GrafConfig = function (points, xDescription, yDescription, title) {}

/* this line here you can press ctrl+. after new GrafConfig */
var grafConf = new GrafConfig(graphBucket, "Years old", "daily Income", "age vs income chart");
```

1. you can copy my code from above to start, simply use the function and on the definition press ctrl+. two times to get the JSDoc information
[
![vscode jsdoc bug](https://user-images.githubusercontent.com/10443153/28941234-6287852e-7865-11e7-8b88-acd88044a76c.PNG)
](url)

my question is, if you get a really really long description can we get the wrapping to work nicer? currently it will just break it off in the middle rather then expanding out and wrap in horrible places. if you view my image where the red line is, it should concat

I think I've seen similar issues open but I haven't seen this exact problem open yet.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-08-03 21:15
This is a duplicate of #11877

We currently display suggestion documentation as plaintext. #11877 tracks support for displaying markdown documentation content which would fix this issue

**Closed by mjbvz** 2017-08-03 21:15 UTC
Labels: duplicate, javascript
