### ISSUE TITLE
Emoji cause column count to be incorrect

### ISSUE THREAD

**Issue by jeremiahlee** [microsoft/vscode#34497] opened 2017-09-15 19:35 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Steps to Reproduce:
1. Add 99 red balloon emoji characters: 🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈
2. VS Code status bar reports: "Ln 1, Col 199' instead of 'Ln, Col 100'.

**Comment by ericblade** [comment] 2017-09-15 19:40
for each one added, it increases the count by 2, looks like it's a double byte character.  Probably it should count the width of a character rather than it's byte-count.  A little difficult to do in a simple fashion, but is possible.

**Comment by Paul-Dempsey** [comment] 2017-09-17 02:56
Could do like VS which shows both 'column' and character offset.

**Comment by yh1224** [comment] 2018-03-04 12:13
The 'Col' on status bar indicates visible columns and the characters marked as 'Wide' by [Unicode® Standard Annex #11 EAST ASIAN WIDTH](http://unicode.org/reports/tr11/) (including those emoji) should be treated as double visible columns. I think this behavior is reasonable.

But the problem is, VSCode is counting ALL surrogate pair character (over U+10000) as double visible columns.

ex)
𐌀𐌁𐌂𐌃𐌄𐌅𐌆

**Comment by Paul-Dempsey** [comment] 2018-03-05 16:58
When you look across Unicode, and consider that you may have multilingual text in a mix of fonts (due to font linking to display all code points), even when the primary font is monospace, there are cases where there are only debatable choices as to what "COL" means. Consider Arabic, combining characters, superscripts, and so on. Without extraordinary measures in typographic manipulation, 2-d grid addressing for characters doesn't make a lot of sense. Probably the best you can do is to define a pixel-oriented grid where the columns are the width of one En or one Em, then calculate the cell that the character falls in and call that COL. That is a lot of calculation and expensive text measurement for something that will give results that seem "wrong" in some cases - perhaps more than is justified for an indicator that was invented in a simpler time.

**Comment by sevaa** [comment] 2019-02-01 17:52
Same with Chinese characters, not even surrogate pair ones. Paste 何 on a line, place the caret after it. Col says 3, should be 2.

**Closed** 2019-10-18 15:22 UTC
Labels: bug, editor-core
