### ISSUE TITLE
Some Scroll Bars Too Small on Windows 10

### ISSUE THREAD

**Issue by bkesecker** [microsoft/vscode#88085] opened 2020-01-04 15:20 UTC
Issue Type: <b>Feature Request</b>

I guess it has been several months since it changed, but the width of scroll bars on the explorer and bottom of the reading pane are thin, and I find myself having an annoying level of difficulty getting them to appear, and then stay appeared, long enough to get ahold of them with the mouse pointer.  Would be nice to have the same size as the vertial bar on the reading pane.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment] 2020-01-06 09:04
Duplicate of https://github.com/microsoft/vscode/issues/68962

**Closed by isidorn** 2020-01-06 09:04 UTC
