### ISSUE TITLE
Electron JS icon shown instead of VSCode icon in Windows

### ISSUE THREAD

**Issue by jaywick** [Microsoft/vscode#36718] opened 2017-10-23 02:29 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (65c08338e4bece35fb53f5a1cdf56d30b7706157, 2017-10-20T15:35:45.848Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.22.0
vscode-icon-theme|jtl|1.5.0
markdown-shortcuts|mdi|0.8.1
debugger-for-chrome|msj|3.4.0
vscode-subword-navigation|ow|1.1.5
ejs-language-support|Qas|0.0.1
Encryptor|Rus|0.3.1
code-settings-sync|Sha|2.8.3
vscode-autohotkey|sle|0.2.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Have VSCode Insiders pinned to Windows taskbar

Reproduces without extensions: Yes

This is what it looks like
![image](https://user-images.githubusercontent.com/3955052/31869758-dd5cb222-b7f5-11e7-9938-b440d400e092.png)

![image](https://user-images.githubusercontent.com/3955052/31869785-03dec49e-b7f6-11e7-9abf-5d860524ec89.png)

![image](https://user-images.githubusercontent.com/3955052/31869806-1c45b1c8-b7f6-11e7-9e32-679032639fda.png)

**Comment by mjbvz** [comment] 2017-10-23 04:11
Duplicate of #36710

**Closed by mjbvz** 2017-10-23 04:11 UTC
Labels: duplicate
