### ISSUE TITLE
Setttings sync cross platform font name issues 

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#102439] opened 2020-07-13 22:52 UTC
I’m a Mac user using settings sync over Github logon to sync my 2 Macs. I just got a Windows 10 PC and turned on sync. It was convenient to get my settings and extensions instantly on a new machine. 

The only issue is fonts; they are not called the same thing across platforms. For example, a font on MacOS might be “SomeFont-Light”, but on Windows the same font is “SomeFont Light”. 

So when sync happens, font is broken on one or the other platform.

**Comment by IllusionMH** [comment] 2020-07-14 01:50
/duplicate of #89627

As mentioned in that issue you can use `sync.ignoredSettings` to avoid sync of this option. See [Configuring synced data](https://code.visualstudio.com/docs/editor/settings-sync#_configuring-synced-data)

Or come up with universal list that will have fonts from both systems and first available will be used by editor.

**Closed** 2020-07-14 01:51 UTC
Labels: *duplicate
