### ISSUE TITLE
Json parser runs on random files.

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode#108498] opened 2020-10-11 22:06 UTC
Issue Type: <b>Bug</b>

This bug is reagard externous json errors on unsaved files that have never been flagged as json. The parser seems to arbitrarily and I have not determined a definitive trigger. It frequently targets the commit message field of your built-in git source control view. That path is shown on the first line. It also randomly targets extension output. This seems to be associated  the cmake-tools in some way but I cann't lock down a pattern.

![image](https://user-images.githubusercontent.com/684470/95691193-cfc70680-0c0c-11eb-9ad3-406c3a0536e0.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 3037)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|5.68GB (0.11GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id faf32d79-1d11-4421-91bd-0059187761b3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
sdlang|Lau|0.1.2
vscode-caniuse|aka|0.5.4
cppincludeguard|aki|1.1.0
pascal|ale|9.2.0
pascal-formatter|ale|2.4.0
vscode-sqlite|ale|0.9.0
makeRunner|ale|0.1.2
gitlab-pipeline-monitor|bal|1.1.5
vscode-linux-binary-preview|bet|1.1.2
perl-html-template|bia|1.1.7
cobol|bit|6.8.5
cobol-plus-pack|bit|1.0.5
hlasm-language-support|Bro|0.11.0
ccls|ccl|0.1.29
gitignore|cod|0.6.0
yash|dao|0.2.5
git-diff-and-merge-tool|dav|1.0.4
ini-for-vscode|Dav|0.0.4
vscode-eslint|dba|2.1.10
binary-plist|dni|0.4.0
xml|Dot|2.5.1
gitlens|eam|10.2.2
git-commits|Exe|3.7.14
vs-code-http-server-and-html-preview|Fli|2.2.2
auto-close-tag|for|0.5.9
gdb|l|0.0.1
global-config|Gru|0.0.12
todo-tree|Gru|0.0.183
vscode-gitbuild|grz|1.0.1
vscode-systemd-support|han|0.1.1
CppSnippets|har|0.0.14
output-colorizer|IBM|0.1.2
innosetup|idl|1.5.0
mysql-syntax|jak|1.3.1
latex-workshop|Jam|8.13.2
svg|joc|1.3.10
vscode-valgrind|kro|0.0.1
vscode-nsis|Kry|0.0.1
restructuredtext|lex|129.0.0
vscode-clangd|llv|0.1.7
cmake-tools-helper|mad|0.2.1
autoconf|mae|0.1.0
asm-code-lens|maz|1.5.6
ninja-syntax|mel|1.0.0
git-graph|mhu|1.26.0
ecdc|mit|1.3.0
vscode-git-notify|mkl|0.4.2
hg|mrc|1.7.1
vscode-apache|mrm|1.2.0
vscode-json5|mrm|1.0.0
language-gettext|mro|0.2.0
vscode-docker|ms-|1.6.0
python|ms-|2020.9.114305
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
hexeditor|ms-|1.3.0
vscode-json-editor|nic|0.2.3
copy-json-path|nid|0.1.0
gitlab-workflow-pali-fork|Pal|2.1.2
vscode-css-peek|pra|4.0.0
quicktype|qui|12.0.46
diff|raf|0.0.1
cfold|rea|0.2.4
java|red|0.68.0
vscode-sort-json|ric|1.18.1
llvm|RRe|0.1.1
tt|sam|0.0.5
perlcritic|sfo|1.0.2
perltidy|sfo|1.3.2
vscode-zipexplorer|sle|0.3.1
python|tht|0.2.3
shellcheck|tim|0.12.0
tmlanguage|Tog|0.9.0
json2yaml|tux|0.2.0
cmake|twx|0.0.17
vscode-lldb|vad|1.5.3
vscode-todo-highlight|way|1.0.4
code-d|web|0.22.0
color-vision|wil|0.1.0
clang-format|xav|1.9.0
licenser|ymo|1.5.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-10-12 07:04
Does the problem also happen if you launch with all extensions disabled? If not, please disable selectively until you find the culprit. Then report the issue to the author.

**Comment by aeschli** [comment] 2020-10-13 10:11
This is not an error that comes from the built-in JSON extension.

It's very likely coming from the vscode-tmlanguage extension caused by the following bug: Togusa09/vscode-tmlanguage#14

marking as dup of https://github.com/microsoft/vscode/issues/57045

**Closed by aeschli** 2020-10-13 10:11 UTC
