### ISSUE TITLE
Image preview broken on file containing % in path

### ISSUE THREAD

**Issue by tillig** [microsoft/vscode#102155] opened 2020-07-10 19:01 UTC
Issue Type: <b>Bug</b>

Create a folder structure where you have a `%` in a folder name. Put an image in the folder with the `%` in the name.

```text
+- repro/
   +- path%2Dhere/
      +- image.png
```

Open VS Code in the `repro` folder and select the image. The preview will fail and say "An error occurred while loading the image. Open file using VS Code's standard text/binary editor?"

Move the image to the main `repro` folder, outside the folder where `%` is in the name.

```text
+- repro/
   +- image.png
   +- path%2Dhere/
```

Now select the image - the preview works.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

This happens when all extensions are disabled as well as when extensions are enabled.

This happens in the 1.48.0-Insiders build (e7920dce7bfd0b707ebfc0a5379c6edd2233e475  2020-07-10T11:55:11.286Z) as well.

This is the same symptoms as #96689, where the `%` was incorrectly being handled encoding-wise. PR #96935 fixed it, but it's back.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|14%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.4.0
vs-redoc-viewer|Ati|0.0.3
color-info|bie|0.5.1
prettier-toml|bod|0.1.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.6
xml|Dot|2.5.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
dotnet-test-explorer|for|0.7.3
go|gol|0.15.1
todo-tree|Gru|0.0.178
terraform|has|2.0.2
yaml-plus-json|hil|1.3.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
vscode-graphviz|joa|0.0.6
restructuredtext|lex|128.0.0
dotenv|mik|1.0.1
ecdc|mit|1.3.0
nc-gcode|ML|0.13.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
polacode|pnp|0.3.4
java|red|0.64.1
vscode-xml|red|0.13.0
vscode-yaml|red|0.8.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.12
guides|spy|0.9.3
rewrap|stk|1.12.0
msbuild-project-tools|tin|0.3.8
vscode-json-stable-stringify|Tra|1.2.0
vscode-spectral|Tra|1.2.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.9
vscode-arduino|vsc|0.3.1
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-icons|vsc|10.1.1
material-theme|zhu|3.8.3
html-css-class-completion|Zig|1.19.0

</details>

**Comment by tillig** [comment] 2020-07-10 20:14
I've spent some time trying to debug it.

[By the time the image location info gets to the webview](https://github.com/microsoft/vscode/blob/7202614406ce8477c9481ce8ed29a2709c59127e/extensions/image-preview/media/main.js#L313) it appears the URI is still fully encoded, like:

`vscode-webview-resource://68540af0-5e38-40c1-9cc4-4e9875da306e/file///path/to/the/repro/path%252Dhere/image.png?version%3D1594410714760`

However, if you run that through any sort of decode first, like if you switch

`image.src = settings.src;`

to

`image.src = decodeURIComponent(settings.src);`

then it gets recursively decoded, becoming

`vscode-webview-resource://68540af0-5e38-40c1-9cc4-4e9875da306e/file///path/to/the/repro/path-here/image.png?version%3D1594410714760`

when it _should_ be set in the image as

`vscode-webview-resource://68540af0-5e38-40c1-9cc4-4e9875da306e/file///path/to/the/repro/path%2Dhere/image.png?version%3D1594410714760`

like, just _one_ level of decoding.

I did try [skipping the encoding when getting the resource path in the extension](https://github.com/microsoft/vscode/blob/5a891b4cb3bb139cda58a585b57019e3088ad02a/extensions/image-preview/src/preview.ts#L254) by switching back to `toString(true)` on the `asWebviewUri` calls but this, too, resulted in the path being `path-here` - like saying "skip the encoding" actually results in a _decode_ operation or something.

I have a feeling it has something to do with [the way the scheme is trimmed off the URI so it can be converted to a webview URI](https://github.com/microsoft/vscode/blob/7202614406ce8477c9481ce8ed29a2709c59127e/src/vs/workbench/api/common/shared/webview.ts#L29) by doing a `toString()` and then a subsequent `URI.parse` on that. But I can't prove it; I haven't gotten that far.

**Comment by jeanp413** [comment] 2020-07-13 13:55
Just found this. I also create an issue for this #102188 and a PR to fix it.

**Comment by mjbvz** [comment] 2020-07-14 20:59
Duplicate of #102188

**Closed by mjbvz** 2020-07-14 20:59 UTC
