### ISSUE TITLE
Missing data when file is replaced

### ISSUE THREAD

**Issue by xx2342341** [Microsoft/vscode#66205] opened 2019-01-08 09:18 UTC
When I open a working file and have written a lot of content in it, because of a mistake, the file is replaced by another file with the same name, and then I return to my VSCODE interface. At this time, all the previous contents are lost and are automatically replaced with the content of the new file, this design is not considered, because I did not even receive a prompt , VSCODE will automatically update my content, like notepad plus plus will prompt whether to confirm before refreshing the content, hoping to make changes.

**Comment by RMacfarlane** [comment] 2019-01-08 18:23
Duplicate of https://github.com/Microsoft/vscode/issues/23107, let's track this there

**Closed by RMacfarlane** 2019-01-08 18:23 UTC
