### ISSUE TITLE
VS-Code Insiders - Not opening jupyter notebook in Ubuntu 20.04 after latest update of Insider version

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#123677] opened 2021-05-12 12:27 UTC
Getting below

![image](https://user-images.githubusercontent.com/12703975/117974665-73b39480-b34b-11eb-91b8-3715cb1f1dbb.png)

My VS-Code version details

![image](https://user-images.githubusercontent.com/12703975/117974459-351dda00-b34b-11eb-81bd-4f2dff122567.png)

Have tried uninstalling-and-reinstalling Python and vscode-jupyter extensions, didn't help.

### After enabling Developer-Tool getting these details when double-clicking on an .ipynb file.

```
workbench.desktop.main.js:62 [Extension Host] extension activation failed TypeError: s.notebook.onDidChangeNotebookCellExecutionState is not a function
    at new d (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:90:450992)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263462)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:261615
    at Array.map (<anonymous>)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:261587
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at Object.t.resolve (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262930)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:254027
    at e._get (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:253793)
    at e.get (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:252505)
    at a.get (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:90:505543)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:246130
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:829501
    at t.activate (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:829188)
    at async Promise.all (index 0) (at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:830020)

```

**Comment by gembancud** [comment] 2021-05-12 13:38
On W10, broken as well

**Comment by don007git** [comment] 2021-05-12 14:28
Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope ('vscode-webview://c8dd3ae1-1477-42c7-a2cc-daed406c5969/') with script ('vscode-webview://c8dd3ae1-1477-42c7-a2cc-daed406c5969/service-worker.js?platform=electron&id=c8dd3ae1-1477-42c7-a2cc-daed406c5969&vscode-resource-origin=https%3A%2F%2Fc8dd3ae1-1477-42c7-a2cc-daed406c5969.vscode-webview-test.com'): ServiceWorker cannot be started.

**Comment by GarretOConnell** [comment] 2021-05-12 14:57
On macOS Catalina 10.15.7 also

**Comment by joyceerhl** [comment] 2021-05-12 16:15
Hi all, this sounds like a duplicate of https://github.com/microsoft/vscode-jupyter/issues/5855. The solution is to restart VS Code to install any pending updates. The latest build is 37a12c9b0846167b2f68e9e1f276149d2d8b9b27. Please open an issue at https://github.com/microsoft/vscode-jupyter/issues if you encounter further problem after updating.

**Comment by rohan-paul** [comment] 2021-05-12 17:35
Resolved with the latest build released an hour back :). Thanks very much !!

**Closed** 2021-05-13 09:45 UTC
