### ISSUE TITLE
Javascript React syntax highlight is broken after arrow function with FlowType generic

### ISSUE THREAD

**Issue by zubko** [Microsoft/vscode#35478] opened 2017-10-02 07:16 UTC
- VSCode Version: 1.16.1 (1.16.1)
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. Paste this code:
```
// @flow

// without generics
const _select = (map: { [string]: T }): T => {
  if (__DEV__) {
    const supportedKeys = ['phone4', 'phone5'];
    for (const key of Object.keys(map)) {
      if (supportedKeys.indexOf(key) === -1) {
        console.error(`Device.select`);
        return 10;
      }
    }
  }
  if (isPhone4) {
    if (map.phone4 !== undefined) return map.phone4;
    if (map.phone4or5 !== undefined) return map.phone4or5;
  }
};

// with generics
const _select = <T>(map: { [string]: T }): T => {
  if (__DEV__) {
    const supportedKeys = ['phone4', 'phone5'];
    for (const key of Object.keys(map)) {
      if (supportedKeys.indexOf(key) === -1) {
        console.error(`Device.select`);
        return 10;
      }
    }
  }
  if (isPhone4) {
    if (map.phone4 !== undefined) return map.phone4;
    if (map.phone4or5 !== undefined) return map.phone4or5;
  }
};

```
 2. Choose JavaScript React syntax

Reproduces without extensions: Yes

![screen shot 2017-10-02 at 10 07 29 am](https://user-images.githubusercontent.com/16039/31067134-f9001dea-a759-11e7-8468-5fc193d1bcce.png)

**Comment by yume-chan** [comment] 2017-10-03 04:16
Duplicate of #33205

Code itself doesn't support Flow, please refer to the [official extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode).

**Comment by mjbvz** [comment] 2017-10-11 01:16
Yes, please try the flow extension. We don't ship with builtin flow support

**Closed by mjbvz** 2017-10-11 01:16 UTC
Labels: caused-by-extension, javascript
