### ISSUE TITLE
Search Widget

### ISSUE THREAD

**Issue by Ngranger** [microsoft/vscode#80908] opened 2019-09-14 05:38 UTC
Issue Type: <b>Bug</b>

Sometimes the widget partially disappears leaving maybe the top quarter of it visible and it only fully re-appears when I start typing some new characters into the find field.  This particular problem seems to manifest after I switch focus to a different open file but not when I stay within the same file for duration of the search widget's use.
![Screenshot 2019-09-14 00 28 320](https://user-images.githubusercontent.com/28519061/64903972-ea385480-d687-11e9-987e-20ae9b2254e7.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (11.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
vscode-apache|mrm|1.2.0
open-in-browser|tec|2.0.0

</details>

**Comment by alexandrudima** [comment] 2019-09-17 08:49
Duplicate of #80826

**Closed by alexandrudima** 2019-09-17 08:49 UTC
