### ISSUE TITLE
[A11y] VoiceOver doesnt not automatically focus and read the content inside Modal notification

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/vscode#82727] opened 2019-10-16 21:28 UTC
Environment Details:
Application Name: Visual Studio Code
Application Version: 1.38.1 (user setup)
Commit: b37e54
Electron: 4.2.10
Node.js: 10.11.0
OS: Windows_NT x64 10.0.18362

Repro steps:

- Open an empty workspace
- Click debug with an invalid configuration
- A modal notification pops up at the top to indicate that debug config is wrong
- Screen reader on MAC (Voice Over) doesn't focus on or reads the content of this notification

Expectation:
Screen reader reads the content of this dialog

Reality:
 Screen reader doesn't focus on or reads the content of this notification

Note that this works fine in windows with NVDA.

**Comment by isidorn** [comment] 2019-10-17 08:48
Thanks for creating an issue and for writing a nice description.
However this is a duplicate of https://github.com/microsoft/vscode/issues/55585
And at the end of the day is an upstream issue of elecetron (you can find all the details in the issue)

**Closed** 2019-10-17 08:49 UTC
Labels: *duplicate
