### ISSUE TITLE
Crash on Tab

### ISSUE THREAD

**Issue by Zawgar** [Microsoft/vscode#17674] opened 2016-12-21 13:42 UTC
Me sucedió varias veces que cuando quiero indentar una linea de código, el VSC se congela y deja de responder. Esto me sucede desde esta versión (1.8.1)

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|githistory|donjayamanne|0.1.4|
|jquerysnippets|donjayamanne|0.0.1|

---

Steps to Reproduce:

1. Paste some code (from the same file or external source)
2. Tab to indent
3. Frozen VSC

**Comment by egamma** [comment] 2016-12-21 14:11
@Zawgar I cannot reproduce the freeze given the steps you provide above. 

Questions:
- can you always reproduce this?
- can you reproduce this behaviour when all extensions are disabled (you can disable an extension in the extension viewlet)
- what kind of file did you edit (.js, html?)? 
- Can you attach the file?
- what was selected when pressed tab to indent 
- can you add an animated gif that shows the crash

**Comment by egamma** [comment] 2016-12-25 16:13
@Zawgar any update?

**Comment by egamma** [comment] 2016-12-26 15:21
@Zawgar closing the issue for now, please reopen the issue once you have added more information as requested above.

**Closed by egamma** 2016-12-26 15:21 UTC
Labels: needs more info
