### ISSUE TITLE
vscode 1.17.0 has steal so much CPU&mem,when start it,my PC's CPU was running to 100% 

### ISSUE THREAD

**Issue by nicklv** [Microsoft/vscode#35961] opened 2017-10-10 06:50 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---
![image](https://user-images.githubusercontent.com/5789960/31372731-c7aeec96-adc9-11e7-80db-bfc81f967b1a.png)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-12 09:26
@nicklv do you have this extension installed? If yes then this looks like a duplicate of #35996. Can you confirm?

**Closed** 2017-10-23 16:51 UTC
Labels: needs more info, perf
