### ISSUE TITLE
Replicate Atom's add new project capability

### ISSUE THREAD

**Issue by Oscar-21** [Microsoft/vscode#32481] opened 2017-08-14 14:48 UTC
Say I want to split screen to compare my code to code written in a directory not available in the current **explorer pane**  I don't think you can do this currently in VS Code.

If I have `~/Documents/code` open in the **explorer pane** and now I want to also have `~/Stuff/Code` open at the same time in the **explorer pane**. The way VS Code is currently configured, a new folder will open in a new window. I would like the have the new folder available in the same **explorer pane**.

**Comment by jens1o** [comment] 2017-08-14 17:33
The vscode team is heavily working on this feature. It's called multi workspaces: https://github.com/Microsoft/vscode/issues/396

If you want this feature, you might want to download the [Insiders version](https://code.visualstudio.com/).

**Comment by aeschli** [comment] 2017-08-14 20:13
duplicate of #396

**Closed by aeschli** 2017-08-14 20:13 UTC
Labels: workbench
