### ISSUE TITLE
CSS Feature recommendation

### ISSUE THREAD

**Issue by FireSniper115** [Microsoft/vscode#45021] opened 2018-03-04 17:23 UTC
I would like in css, when we clicked one the ":" key, it puts ": ;" and the cursor is in between so we can write the modifications. Thanks for your attention. Awesome App.

**Comment by aeschli** [comment] 2018-03-06 09:18
duplicate of https://github.com/Microsoft/vscode/issues/34141

**Closed by aeschli** 2018-03-06 09:18 UTC
Labels: css-less-sass
