### ISSUE TITLE
showInputBox should respect all properties - prompt, value and placeholder

### ISSUE THREAD

**Issue by agrabhi** [Microsoft/vscode#5689] opened 2016-04-23 07:32 UTC
- VSCode Version: 1
- OS Version: win 10

Steps to Reproduce:
showInputBox respects only one of three properties showInputBox should respect all three properties - prompt, value and placeholder. it should respect prompt and one  of placeholder and value property.

**Comment by jrieken** [comment] 2016-04-25 08:16
@bpasero I do [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostQuickOpen.ts#L1920). Should it be different?

**Comment by bpasero** [comment] 2016-04-25 08:51
I cannot reproduce this issue, for me prompt, value and placeholder can be used "alle 3 zusammen":

![image](https://cloud.githubusercontent.com/assets/900690/14778514/aa58c9d6-0ad3-11e6-853b-eaa834ba241a.png)

**Comment by jrieken** [comment] 2016-04-28 10:40
@agrabhi ping

**Comment by agrabhi** [comment] 2016-04-28 13:57
Hey off work currently. Well reply next week.

**Comment by jrieken** [comment] 2016-05-10 14:13
Closing since info is still missing.

**Closed by jrieken** 2016-05-10 14:13 UTC
Labels: needs more info
