### ISSUE TITLE
"DEBUG CONSOLE" tab cannot show result automaticly

### ISSUE THREAD

**Issue by wurining** [microsoft/vscode#192952] opened 2023-09-13 01:40 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

![Untitled](https://github.com/microsoft/vscode/assets/26198634/a7b236e1-8623-4df5-b3d6-fdf6a7204d1e)

When debuging a python file (I didn't test other languages) by using Remote-SSH, either click "Evaluate in Debug Console" or directly enter variables into Debug Console, all cannot automaticly display results in the output panel of Debug Console. I need to change another panel, like OUTPUT, PROBLEMS or etc., then change back, then can see the reuslt which I input just now. 

## Steps to reproduce:

1. Debug a python file with a breakpoint.
2. Pause at the breakpoint, and choose any variable to click "Evaluate in Debug Console" a couple of times.
3. Can see that only initial times results can show.
4. Change to other tab like OUTPUT, PROBLEMS or etc.
5. Change back to DEBUG CONSOLE, then can see all results.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2023-09-13 02:51:18.943 [info] DAP Server launched with command: /data/runtime/conda_envs/envs/NAME/bin/python /home/USER/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter
2023-09-13 02:51:19.126 [info] Send text to terminal:  cd /home/USER/Documents/PROJECT ; /usr/bin/env /data/runtime/conda_envs/envs/NAME/bin/python /home/USER/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 55221 -- /home/USER/Documents/PROJECT/data_modules/MultiDataloader.py 

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"

```

</p>
</details>

VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:49:22.656Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux x64 5.19.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id e70d5e06-2be3-4750-9b06-aacbc4a0c5e9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: a100_remote_wurining|
|OS|Linux x64 5.19.0-40-generic|
|CPUs|Intel(R) Xeon(R) Gold 6336Y CPU @ 2.40GHz (96 x 800)|
|Memory (System)|503.49GB (494.19GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
python|ms-|2023.16.0
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
vscode-singularity|onn|0.7.0
vscode-django|bat|1.11.0
githistory|don|0.6.20
python-environment-manager|don|1.2.2
python-extension-pack|don|1.7.0
copilot|Git|1.111.404
copilot-chat|Git|0.7.0
vscode-pull-request-github|Git|0.72.0
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
black-formatter|ms-|2023.4.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
962ge761:30835153
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-09-13 02:01
Probably a duplicate of 192653

**Closed** 2023-12-05 22:43 UTC
Labels: *duplicate
