### ISSUE TITLE
Problem with .tar.gz from version 1.31.1

### ISSUE THREAD

**Issue by rthier** [Microsoft/vscode#68979] opened 2019-02-19 12:54 UTC
The .tar.gz from version 1.31.1 is corrupted.
I can't extract the files from it.

Please check the compression.

**Comment by Tyriar** [comment] 2019-02-19 13:15
@rthier where are you located?

**Comment by Tyriar** [comment] 2019-02-19 14:26
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/68621

**Closed by Tyriar** 2019-02-19 14:26 UTC
