### ISSUE TITLE
Issue Reporter does not work

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#118459] opened 2021-03-08 16:28 UTC
Version: 1.55.0-insider
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:24:34.127Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Click "Help" > "Report Issue" in the menu bar 
2. Fill out the Issue Reporter form
3. Click "Create on GitHub"
4. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2021-03-08 16:51
Duplicate of https://github.com/microsoft/vscode/issues/117656

**Closed by RMacfarlane** 2021-03-08 16:51 UTC
