### ISSUE TITLE
workspace.onDidCloseNotebookDocument no longer getting fired when closing notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#205818] opened 2024-02-21 05:25 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1.  Add an event handler to `workspace.onDidCloseNotebookDocument`
2.  Open a Jupyter notebook document 
3. Then close it, 
4. the above event handler is never invoked.

I tried to find the cause, but have no idea where the issue is.
@rebornix @bpasero  /cc

**Comment by rebornix** [comment] 2024-02-21 22:56
It's very likely memory leak where the notebook document is ref'ed and never released.

**Comment by rebornix** [comment] 2024-02-21 23:53
Caused by https://github.com/microsoft/vscode/blob/4665ce61312f31f22607b5c72a4492b5ecaf7a98/src/vs/workbench/contrib/notebook/browser/view/cellParts/codeCell.ts#L149-L161

**Comment by rebornix** [comment] 2024-02-22 00:12
There are two `this.viewCell.resolveTextModel()` runs at the same time, so the text model is resolved twice, and `BaseCellViewModel.textModelRef`is also set twice (the later one overrides the former one). Thus we have a zombie model ref. Should be fixed via https://github.com/microsoft/vscode/pull/205921 .

cc @Yoyokrazy

**Closed** 2024-02-22 00:25 UTC
Labels: bug, freeze-slow-crash-leak, regression
