### ISSUE TITLE
JS syntax highlighting not working as expected

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#4210] opened 2016-03-14 22:17 UTC
- VSCode Version: Version 0.10.10 / 5b5f4db87c10345b9d5c8d0bed745bcad4533135
- OS Version: Mac OS X Yosemite 10.10.5 / 14F1605

## Steps to Reproduce:

1. Save a new file with a `.js` extension
2. Add some JS code

## Expected
I'll see a full range of syntax highlighting

## Actual
![highlighting sample](https://cloud.githubusercontent.com/assets/829827/13761678/952a5f68-ea10-11e5-9953-b45ccd5ccbf6.png)

I'm surprised that keywords like `var`, `let`, `const`, and `function` are not being highlighted. 

I've seen this on other people's machines as well.

I can't imagine that I'm the first one to notice this. Is this by design? Is there some JS support extension I'm supposed to install?

Maybe this issue should be going to microsoft/vscode-textmate but I'm not sure.

Thanks!

**Comment by aeschli** [comment] 2016-03-15 08:48
duplicate of #3903. It's fixed in the latest stable, released yesterday. Please update...

**Closed by aeschli** 2016-03-15 08:48 UTC

**Comment by NickHeiner** [comment] 2016-03-15 15:31
Awesome! Thanks for the fix. Sorry for the duplicate issue.
