### ISSUE TITLE
Tooltip unable to appear above workbench

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#75374] opened 2019-06-12 23:20 UTC
- VSCode Version: 1.36
- OS Version: Mac OS Mojave

Steps to Reproduce:

1. Make your workbench take up most of your screen so there won't be enough room for a tooltip
2. Hover over an error. Notice the tooltip tries to appear but quickly closes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2019-06-13 16:16
Can you take a screenshot of the problem when this happens?

**Comment by lramos15** [comment] 2019-06-13 16:33
I did a little bit more testing and it appears the error is more prone to happen towards the end of the line. I can't take a screenshot because it disappears too fast, let me know if this gif depicts the issue. 
![Issue gif](https://user-images.githubusercontent.com/4544166/59450559-50c68180-8dbe-11e9-8fad-4bdae4b73a58.gif)

**Comment by MarkKahn** [comment] 2019-06-14 20:50
#75447 was closed as a dupe, but my own issue has nothing to do with the workbench.  When the editor is scrolled even 1px to the right I see this behavior.  Scrolling all the way to the left fixes it 100% of the time

**Comment by lramos15** [comment] 2019-06-14 21:00
Both of these issues reference the same underlying problem and therefore just the older issue was left to track the problem as there is no use tracking it twice. I believe your issue is the actual way to reproduce it and I just thought it involved the workbench. The fix should fix #75447 too.

**Comment by alexandrudima** [comment] 2019-08-05 15:39
Duplicate of #51794

**Closed by alexandrudima** 2019-08-05 15:39 UTC
