### ISSUE TITLE
HTML Comments not aligned properly after uncommenting

### ISSUE THREAD

**Issue by jhildenbiddle** [Microsoft/vscode#32070] opened 2017-08-06 19:10 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.2
beautify|Hoo|1.1.1
code-settings-sync|Sha|2.8.2
quokka-vscode|Wal|1.0.46
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
vscode-html-css|ecm|0.1.7
vscode-npm-script|eg2|0.2.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
code-runner|for|0.6.32
docthis|joe|0.4.7
vue|liu|0.1.5
ecdc|mit|0.10.3
vscode-autoprefixer|mrm|2.1.1
vscode-csscomb|mrm|4.0.1
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.1.7
vetur|oct|0.9.3
rewrap|stk|1.4.2
code-spell-checker|str|1.3.4
vscode-todo-highlight|way|0.5.8
better-align|wwm|1.1.6

---

Steps to Reproduce:

1. Add HTML
   ```html
   <div>
     <p>Line 1</p>
     <p>Line 2</p>
   <div>
   ```

2. Comment a line
   ```html
   <div>
     <p>Line 1</p>
     <!-- <p>Line 2</p> -->
   <div>
   ```

3. Toggle the comment. Notice that toggled line is not properly aligned (there is an unwanted space before the opening `<p>` tag and after the closing `</p>` tag).

   ```html
   <div>
     <p>Line 1</p>
      <p>Line 2</p> 
   <div>
   ```

   To further demonstrate the issue, repeatedly toggle the line comment on/off. Below is the result of toggling the same line on/off ten times.

   ```html
   <div>
     <p>Line 1</p>
              <!-- <p>Line 2</p>          -->
   <div>
   ```

   Multi-line comments are also affected. Below is the result of toggling the entire block of HTML on/off ten times:

   ```html
            <!-- <div>
     <p>Line 1</p>
     <p>Line 2</p>
   <div>          -->   ```

I believe the expected behavior is for a toggled comment to restore the line's original alignment much like other toggled comments do. It appears that the issue is caused by space characters that are added when commenting (`<!--[SPACE]` and `[SPACE]-->`) which are not removed when uncommenting (only `<!--` and `-->` are removed).

<!-- Launch with `code --disable-extensions` to check. -->
Reproduces without extensions: Yes

Thanks!

**Comment by Septh** [comment] 2017-08-07 10:19
Also happens with JavaScript and Lua. Didn't check with other languages.

**Comment by kieferrm** [comment] 2017-08-07 20:51
Duplicate of #30804.

**Closed by kieferrm** 2017-08-07 20:51 UTC
Labels: html
