### ISSUE TITLE
increase font size for debug window

### ISSUE THREAD

**Issue by richcmwang** [microsoft/vscode#102778] opened 2020-07-17 11:35 UTC
Font for debug/outline/explore is too small for high-resolution monitor and cannot be adjusted.  It would be very helpful if users can increase the size.

**Comment by gjsjohnmurray** [comment] 2020-07-17 12:00
How about the `View: Zoom In` command? And if this makes your editor font too big, offset it by using `Editor Font Zoom Out` as well.

**Comment by ArturoDent** [comment] 2020-07-17 16:17
"Font for debug/outline/explore"  i would say this is a duplicate of https://github.com/microsoft/vscode/issues/519

**Comment by isidorn** [comment] 2020-07-27 13:56
Please use the following setting 	"debug.console.fontSize": 12,

As for the other views this is a duplicate of #519

**Closed by isidorn** 2020-07-27 13:56 UTC
Labels: debug
