### ISSUE TITLE
Language agnostic region folding

### ISSUE THREAD

**Issue by pbricout** [Microsoft/vscode#30963] opened 2017-07-18 22:02 UTC
I am using VSC to work on project written in assembly code.

The code sources are usually very long (several thousands lines of code), yes they should be probably be shorter and split into components, but that is the way it is at least now.

Indentation folding does not work in assembly, and the language aware folding does not work with assembly language.

The most practical way to do it is to use region folding tags. I haven't found any existing issue with this request so far.

Could you please consider adding support for recursive folding region tags (the standard tags #region and #endregion would be perfect). This needs to work when they are anywhere on the line, because they will be embedded inside a comment, usually a line starting with ; or * in my case.

The irony being more than twenty years, on my 16 bits machine I had an editor supporting that.

- VSCode Version: 1.14.1
- OS Version: Windows 7 64 bits

**Comment by rebornix** [comment] 2017-07-18 22:03
Dup of https://github.com/Microsoft/vscode/issues/3422 . Thank you!

**Comment by pbricout** [comment] 2017-07-18 22:06
I found this issue, but the title says language aware folding and I am requesting language agnostic folding, this is really the same issue?

**Comment by rebornix** [comment] 2017-07-18 22:07
Sorry for that, closing issues too fast :(

**Comment by pbricout** [comment] 2017-07-18 22:09
Thanks for re-opening

**Comment by redpixr** [comment] 2017-07-24 17:07
Please please make this happen, it's super useful for editing C# code

**Comment by aeschli** [comment] 2017-08-09 14:53
duplicate of #12146

**Closed by aeschli** 2017-08-09 14:53 UTC
Labels: editor, editor-folding
