### ISSUE TITLE
Why vscode jump to a .d.ts file when I command click a module

### ISSUE THREAD

**Issue by vanvanj** [Microsoft/vscode#30604] opened 2017-07-13 10:40 UTC
import { Provider } from 'react-redux';

When I command click the 'react-redux' I wanna see the source code which is a .js file, but the  vscode jump to a .d.ts file instead. How can I fix this?

**Comment by neotiango** [comment] 2017-07-13 15:24
JS is weakly typed

**Comment by vanvanj** [comment] 2017-07-14 01:20
I want the vscode jump to a .js file when I command click the module name. I think it's not about the language is strong typed or weak typed

**Comment by mjbvz** [comment] 2017-07-14 18:08
Duplicate of https://github.com/Microsoft/TypeScript/issues/14479
Duplicate of https://github.com/Microsoft/TypeScript/issues/6209

This is currently a limitation of how the TypeScript server that powers both our JS and TS intellisense works. We use `d.ts` files for module intellisense in order to provide rich suggestions without having to parse or understand the JavaScript implementation. This is done both for performance reasons and to leverage TS language features when describing JavaScript APIs

Closing as upstream

**Closed by mjbvz** 2017-07-14 18:08 UTC
Labels: duplicate, javascript, upstream

**Comment by hoegge** [comment] 2017-07-18 06:36
But why can't the intellisense find the way to the implementation in the originating .ts file instead of just the .d.ts file?
