### ISSUE TITLE
Provide a way for an extension to detect an active debug session

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#24792] opened 2017-04-14 18:03 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (9530cf6e2b804c4b986d97f105f88d40ee4d2c47, 2017-04-14T11:53:02.042Z)
- OS Version: Darwin x64 16.5.0
---

As far as I can tell there isn't a way for an extension to know if there is an active debug session. This would allow an extension to alter it behavior appropriately.

Maybe something like:
`workspace.onDidChangeDebugState` with a `state` of `started | paused | stopped`

Also in addition to to the global state it would be great to be able to detect that the active editor is currently being debugged.

Maybe like:
`window.onDidChangeTextEditorDebugState` with a `state` of `started | paused | stopped`
and/or maybe a `debugState` property on the editor

For the latter case, I can give a concrete example -- in GitLens I provide a blame decoration that is applied to the end of the selected line, which works great, but when a file is being debugged it overwrites the debug decorations (variable values) which I really don't want it to do. So I'd love a way to detect that case and turn them off (ideally only if the active editor is currently being debugged -- i.e. the debug decorations would be visible). This could probably be solved by a priority on decorations or something like that (to make sure the debug ones are higher and won't be overwritten). While that might be nice to have too, having the debug events/state feels like it could be valuable to other extensions as well.

**Comment by jrieken** [comment] 2017-04-18 08:12
closing as dupe of #10077

**Closed by jrieken** 2017-04-18 08:12 UTC
Labels: api, debug, feature-request
