### ISSUE TITLE
First startup time is incredibly slow

### ISSUE THREAD

**Issue by xxxZeus** [Microsoft/vscode#37406] opened 2017-11-01 12:59 UTC
- VSCode Version: <code>Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)</code>
- OS Version: <code>Windows_NT x64 10.0.15063</code>
- CPUs: <code>Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 x 3504)</code>
- Memory (System): <code>6.96GB (5.01GB free)</code>
- Memory (Process): <code>205.21MB working set (208.28MB peak, 191.43MB private, 41.82MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|3907|
|main|app.isReady => window.loadUrl()|1203|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|5239|
|renderer|require(workbench.main.js)|6330|
|renderer|create extension host => extensions onReady()|1950|
|renderer|restore viewlet|0|
|renderer|restore editor view state|1497|
|renderer|overall workbench load|2428|
|main + renderer|start => extensions ready|19427|
|main + renderer|start => workbench ready|19221|

---

[b1e5_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1434144/b1e5_main.cpuprofile.txt)
[b1e5_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1434145/b1e5_renderer.cpuprofile.txt)

---
# Second startup 
It is only slow when opening for the first time after the system starts. If I close VS code and reopen it again then the startup time is better than before. Here is performance profile for SECOND startup:
![second startup](https://i.gyazo.com/c4a5ea0e016309e819d22efe94608d7b.png)
CPU profile files for second startup:
[a9f7_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1434172/a9f7_main.cpuprofile.txt)
[a9f7_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1434173/a9f7_renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-11-02 08:28
Yeah, sorry for that. There is something very wrong with the electron version we are using. The upstream issue is being tracked here: https://github.com/electron/electron/issues/10506

**Comment by jrieken** [comment] 2017-11-02 16:15
closing as dupe of #22087

**Closed by jrieken** 2017-11-02 16:15 UTC
Labels: perf, perf-profile, upstream, windows
