### ISSUE TITLE
Terminal auto types random text

### ISSUE THREAD

**Issue by kizzle911** [microsoft/vscode#120352] opened 2021-04-01 15:15 UTC
Issue Type: <b>Bug</b>

I am trying to debug a powershell script in VSCode and as soon as I enter the parameter values, I get random auto entered text (see attached photos).

![Screen Shot 2021-04-01 at 11 13 30 AM](https://user-images.githubusercontent.com/18578295/113316142-03413e80-92dc-11eb-8b92-80d85e7a0dab.png)

![Screen Shot 2021-04-01 at 11 13 44 AM](https://user-images.githubusercontent.com/18578295/113315886-c1b09380-92db-11eb-9ca1-9501130ac7b1.png)

I attempted to ctrl+c but that still continues to auto enter text.

Only way to stop this is by terminating the terminal session.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.17GB free)|
|Process Argv|--crash-reporter-id bcf56f26-dca7-4c02-b3c2-69e2861263d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.1
better-comments|aar|2.1.0
aws-toolkit-vscode|ama|1.22.0
vscode-bicep|Azu|0.1.37-alpha.gf88c6d95ad
armview|ben|0.4.5
bracket-select|chu|2.0.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
terraform|has|2.9.1
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azureterraform|ms-|0.3.2
vscode-bicep|ms-|0.3.126
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
vscode-aks-tools|ms-|0.0.8
vscode-kubernetes-tools|ms-|1.3.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.0
azure-account|ms-|0.9.7
azurecli|ms-|0.5.0
powershell|ms-|2021.2.2
azurerm-vscode-tools|msa|0.15.0
vscode-yaml|red|0.17.0
markdown-preview-enhanced|shd|0.5.17
vscode-ansible|vsc|0.6.0
arm-params-generator|wil|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontbcf:30265426
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by kizzle911** [comment] 2021-04-01 18:08
Performed the following troubleshooting steps:
- Restarted app
- Restarted laptop
- Deleted powershell extension and reinstalled
- Deleted VSCode and Extensions from laptop and reinstalled along with Powershell. 

The issue only occurs when I attempt to debug a powershell script

**Comment by VanderSP** [comment] 2021-04-05 12:20
IM SUFFERING OF THIS 2 WEEKS HORRIBLE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fflaten** [comment] 2021-04-06 16:38
Been suffering for weeks myself. Not sure if this is vscode or vscode-powershell bug tbh. I've only been able to repro in Powershell integrated terminal while using my debian-based devcontainers. PowerShell integrated terminal on Windows directly hasn't shown this yet, but I guess they work fundamentally different since pasting in devcontainer terminal is **super-slow**.

Resizing vscode windows can sometimes stop it.
With "escape sequence logging" enabled, the dev tools console keeps repeating like the sample below automatically:

<details>
  <summary>Escape sequence logging sample</summary>

  > LogService.ts:66 xterm.js: parsing data [6n
> LogService.ts:66 xterm.js: sending data "[5;103R" (8) [27, 91, 53, 59, 49, 48, 51, 82]
> LogService.ts:66 xterm.js: parsing data [6n
> LogService.ts:66 xterm.js: sending data "[5;103R" (8) [27, 91, 53, 59, 49, 48, 51, 82]
> LogService.ts:66 xterm.js: parsing data [?25l[5;24H[93minvoke-pester[39;49m [37m./Samples/demoIssue1891.tests.ps1[39;49m [90m-FullNameFilter[39;49m [36m"get-emoji"[37m;[93m99R[37m;[36m" -Output Diagnostic
> LogService.ts:66 xterm.js: parsing data [39;49m[0m[5;104H[?12l[?25h
> LogService.ts:66 xterm.js: parsing data [?25l[5;24H[93minvoke-pester[39;49m [37m./Samples/demoIssue1891.tests.ps1[39;49m [90m-FullNameFilter[39;49m [36m"get-emoji"[37m;[93m99R[37m;[93m1" -Output Diagnostic[39;49m[0m
> LogService.ts:66 xterm.js: parsing data [5;105H[?12l[?25h
> LogService.ts:66 xterm.js: parsing data [?25l[5;24H[93minvoke-pester[39;49m [37m./Samples/demoIssue1891.tests.ps1[39;49m [90m-FullNameFilter[39;49m [36m"get-emoji"[37m;[93m99R[37m;[93m10" -Output Diagnostic
> LogService.ts:66 xterm.js: parsing data [39;49m[0m[5;106H[?12l[?25h
> LogService.ts:66 xterm.js: parsing data [?25l[5;24H
> LogService.ts:66 xterm.js: parsing data [93minvoke-pester[39;49m [37m./Samples/demoIssue1891.tests.ps1[39;49m [90m-FullNameFilter[39;49m [36m"get-emoji"[37m;[93m99R[37m;[93m103" -Output Diagnostic[39;49m[0m[5;107H[?12l[?25h
> LogService.ts:66 xterm.js: parsing data [?25l[5;24H
> LogService.ts:66 xterm.js: parsing data [93minvoke-pester[39;49m [37m./Samples/demoIssue1891.tests.ps1[39;49m [90m-FullNameFilter[39;49m [36m"get-emoji"[37m;[93m99R[37m;[93m103R" -Output Diagnostic[39;49m[0m[5;108H[?12l[?25h
> LogService.ts:66 xterm.js: parsing data [6n
> LogService.ts:66 xterm.js: sending data "[5;108R" (8) [27, 91, 53, 59, 49, 48, 56, 82]
> LogService.ts:66 xterm.js: parsing data [6n
> LogService.ts:66 xterm.js: sending data "[5;108R" (8) [27, 91, 53, 59, 49, 48, 56, 82]
</details>

Possible repro:
1. Use latest VSCode stable or insider with latest **ms-vscode-powershell** and **ms-vscode-remote.remote-containers**
2. Open a devcontainer using plain image `mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-3.1` and **ms-vscode.powershell** extension enabled in container.
3. Open a .ps1 file to start the PowerShell integrated console
4. Paste `invoke-pester ./Samples/demoIssue1891.tests.ps1 -FullNameFilter "get-emoji" -Output Diagnostic`
5. Add another double-quote after `get-emoji` so it becomes `...meFilter "get-emoji"" -Output....`. Problem will hopefully occur.

**Comment by VanderSP** [comment] 2021-04-07 12:25
oh i was about to say that I forget to say that im using INSIDER version... but also in stable you saying...
so it can be related to usign remote extension? i use it also for wsl2

**Comment by cicorias** [comment] 2021-04-07 14:51
I'm seeing lots of similar random string -- that look like terminal control strings -- `24;17R` --- etc. 

this occurs primarily when in a pwsh session or running a pwsh script.

**Comment by VanderSP** [comment] 2021-04-07 14:52
yeah, very annoying!

**Comment by coreylista** [comment] 2021-04-07 16:42
It only happens when using the integrated terminal for me. Tried starting in a temporary terminal, no extensions, reinstall, nothing works.

**Comment by phatmandrake** [comment] 2021-04-08 20:13
I've also been experiencing this for the last few weeks. 

Just today I was able to recently get it to stop surprisingly.

The circumstances for how it starts in the first place though are still a bit of mystery, but generally speaking it occurs, for me after a I've executed "a lot" of arbitrary commands in the Integrated Terminal. 

Then it seems to be triggered when I hit the Up Arrow or if I try to Ctl+C.

If it's the Up Arrow key only a little bit of text is output. If I ctl+c a lot of text generated.

In either case a combination of pressing the left, up and down arrow keys in no immediately discernible order or number of occurrences will cause it to stop.

When it does finally stop. I have to delete all the randomly generated characters then Clear-Host to regain control of the console.

**Comment by cicorias** [comment] 2021-04-09 16:05
just to be clear, I'm seeing this with PowerShell Core sessions only. I've also seen this on plain old macOS using pwsh core 7.x latest too.

**Comment by VanderSP** [comment] 2021-04-09 22:03
im 2 weeks getting this horrible bug... in under wsl2... 

tip: fast way to get the problem

start terminal

type

cls   enter

u get             ;1R

**Comment by andschwa** [comment] 2021-04-09 22:23
I've seen this happen in the non-integrated terminal. It was just a normal VS Code terminal running `pwsh`, with no PowerShell extension installed.

**Comment by JustinGrote** [comment] 2021-04-11 16:53
I know he's an assignee but paging @Tyriar if he's aware of any recent changes that may be related.

**Comment by Tyriar** [comment] 2021-04-12 13:35
Sorry about this, I plan to look at it soon. This might workaround the problem:

```
"terminal.integrated.localEchoLatencyThreshold": -1
```

**Comment by fflaten** [comment] 2021-04-12 15:40
> Sorry about this, I plan to look at it soon. This might workaround the problem:
> 
> ```
> "terminal.integrated.localEchoLatencyThreshold": -1
> ```

🎉🎉Thank you! That solved my reproducable scenario. I might finally be able to work again! 😄

**Comment by andschwa** [comment] 2021-04-12 18:57
Thanks @Tyriar!

**Comment by Tyriar** [comment] 2021-04-13 12:54
This is again caused by `writeSync` which was what caused the issue a couple of weeks ago, flushing the output using it is causing a double write of the cursor report response and pwsh handles an unexpected cursor report by just echoing it.

```
terminalProcessManager.js:87 on before data [6n
terminalInstance.js:851 xterm write: "\u001b[6n"
terminalProcessManager.js:399 process write: "\u001b[11;1R"
terminalProcessManager.js:399 process write: "\u001b[11;1R"
```

**Comment by Tyriar** [comment] 2021-04-13 13:12
@connor4312 I needed to disable flushing of output as it's no longer possible to do this without adding async everywhere which would be a huge change to the addon. It's not clear what the problem is getting fixed in f82ff2194fc81ed0d0ca87018fc5526dfc1946e8 and b97bb4e8b95210427d615a470161b795b894991c is but I'm pretty sure those issues won't be worth than this one which basically renders pwsh unusable.

**Comment by connor4312** [comment] 2021-04-13 22:19
I think the no-oping you did in https://github.com/microsoft/vscode/commit/14b07fe6e752926d51ae6d6c19ddcac3c6400900 is the best we can do for now. We'd really need https://github.com/microsoft/vscode/issues/115949 in order to handle this properly without writeSync.

**Closed by connor4312** 2021-04-13 22:19 UTC
Labels: bug, important, integrated-terminal, integrated-terminal-local-echo

**Comment by kizzle911** [comment] 2021-04-15 00:37
> Sorry about this, I plan to look at it soon. This might workaround the problem:
> 
> ```
> "terminal.integrated.localEchoLatencyThreshold": -1
> ```

Thank you @Tyriar.  This did the trick for now.

**Comment by VanderSP** [comment] 2021-04-15 23:45
YES THIS SOLVED for me

wsl2 pengwin... powershell 7... vscode insider... win insider

**Comment by isidorn** [comment] 2021-04-30 15:13
Author verified, adding verified label to not appear in verification query

**Comment by fflaten** [comment] 2021-05-16 16:59
I'm seeing similar issue again while still using the @Tyriar's workaround in settings. It doesn't start at random in existing consoles like the original issue, but it starts after reloading window in the same devcontainer.

1. In devcontainer with PS integrated console open
2. Reload Window
3. VsCode starts a new PS integrated consoel, but auto-focuses on "<number>: pwsh" terminal which is the original console from step 1. In this console, the control characters keep going for a while. Sometimes 2sec, sometimes more.

This was not happening after the workaround was provided. Changes in latest vscode?
Now running VSCode Stable 1.56.2 w/vscode-powershell 2021.2.2

![reload-randomchar](https://user-images.githubusercontent.com/3436158/118405509-82b28380-b678-11eb-8713-b88749114e21.gif)

**Comment by Tyriar** [comment] 2021-06-02 18:04
@fflaten should be fixed with https://github.com/microsoft/vscode/issues/123803
