### ISSUE TITLE
Settings Sync fails because device is making too many requests

### ISSUE THREAD

**Issue by srbiotik** [microsoft/vscode#101977] opened 2020-07-09 07:48 UTC
Issue Type: <b>Bug</b>

1. Installed Visual Code insiders from Ubuntu Store
2. Turn on Settings Sync
3. Select Sign in with github
4. Select any of the sync possibilities
5. Enter to confirm the start of syncing

VS Code version: Code - Insiders 1.47.0-insider (04545fa88043fd10d1f3edefd26be1b8245b516f, 2020-07-02T05:34:14.274Z)
OS version: Linux x64 5.4.0-40-generic snap
Remote OS version: Linux x64 4.15.0-101-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz (4 x 3213)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (0.49GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 10.10.10.4|
|OS|Linux x64 4.15.0-101-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz (4 x 2394)|
|Memory (System)|15.66GB (1.96GB free)|
|VM|20%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
sublime-keybindings|ms-|4.0.7
vscode-eslint|dba|2.1.6
vetur|oct|0.24.0

</details>

**Comment by sandy081** [comment] 2020-07-09 10:39
/duplicate

Seems duplicate of #101878

**Closed** 2020-07-09 10:39 UTC
Labels: *duplicate
