### ISSUE TITLE
HoverProvider text using Markdown, URL to file + Line number?

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#5084] opened 2016-04-07 17:47 UTC
I've been using HoverProvider to quickly display the origin file of a user function in Lua.
I'm using the Markdown syntax for creating a clickable link, which opens the file in the editor:

`[c:\temp\file.lua](file:c:\temp\file.lua)` -> [c:\temp\file.lua](#here)

I'm wondering if this link syntax also supports line number, and if it does, what is the syntax of it?

I believe this question is also generally related to all places where an extension can display text formatted with Markdown.

**Comment by jrieken** [comment] 2016-04-08 08:55
It's currently not possible, tho I like the idea.

**Comment by jrieken** [comment] 2016-04-14 07:03
I will handle this as a duplicate of #3676

**Closed by jrieken** 2016-04-14 07:03 UTC
Labels: feature-request

**Comment by jrieken** [comment] 2016-04-14 12:40
@Janne252 You Ok with the github style links? Like `file:///my/files/test.txtL42`?

**Comment by Janne252** [comment] 2016-04-14 12:44
@jrieken Absolutely, that's short and simple.

**Comment by jrieken** [comment] 2016-04-14 12:47
deal
