### ISSUE TITLE
Linux crash on startup in latest Insiders

### ISSUE THREAD

**Issue by intrnl** [microsoft/vscode#142574] opened 2022-02-09 00:25 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider [`2d8e93571421d69616e0ed7d7958e32abaf8d7d3`](https://github.com/microsoft/vscode/commit/2d8e93571421d69616e0ed7d7958e32abaf8d7d3) x64
- OS Version: Arch Linux 5.16.8-lqx1-1-lqx

Steps to Reproduce:

1. Open VSCode, with or without disabling extensions or GPU

```
$ code-insiders --verbose --disable-extensions
[18286:0209/072339.822046:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2022-02-09T00:23:39.853Z] [File Watcher (node.js)] Request to start watching: /home/intrnl/.config/Code - Insiders/User (excludes: <none>),/home/intrnl/.config/Code - Insiders/User/settings.json (excludes: <none>)
[main 2022-02-09T00:23:39.875Z] Starting VS Code
[main 2022-02-09T00:23:39.876Z] from: /opt/visual-studio-code-insiders/resources/app
[main 2022-02-09T00:23:39.876Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/intrnl/.config/Code - Insiders/logs/20220209T072339'
}
[main 2022-02-09T00:23:39.877Z] Resolving machine identifier...
[main 2022-02-09T00:23:39.878Z] Resolved machine identifier: 58a15d6e1e5bf15a98458ace9d5f6d012ea3ce165535cb3c7ffbf98f320c6aab
[main 2022-02-09T00:23:39.880Z] Main->SharedProcess#connect
[main 2022-02-09T00:23:39.884Z] [File Watcher (node.js)] Started watching: '/home/intrnl/.config/Code - Insiders/User'
[main 2022-02-09T00:23:39.907Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/intrnl/.config/Code - Insiders/User/settings.json'
[main 2022-02-09T00:23:39.932Z] StorageMainService: creating global storage
[main 2022-02-09T00:23:39.940Z] lifecycle (main): phase changed (value: 2)
[main 2022-02-09T00:23:39.941Z] windowsManager#open
[main 2022-02-09T00:23:39.941Z] windowsManager#open pathsToOpen [ [Object: null prototype] {} ]
[main 2022-02-09T00:23:39.942Z] windowsManager#doOpenEmpty {
  restore: false,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: false
}
[main 2022-02-09T00:23:39.944Z] IPC Object URL: Registered new channel vscode:e2743a9b-1672-470b-a911-c40bea70fa96.
[main 2022-02-09T00:23:39.944Z] window#validateWindowState: validating window state on 1 display(s) {
  width: 1024,
  height: 768,
  mode: 1,
  x: 256,
  y: 48,
  hasDefaultState: true
}
[main 2022-02-09T00:23:39.944Z] window#validateWindowState: 1 monitor working area { x: 0, y: 25, width: 1536, height: 839 }
[main 2022-02-09T00:23:39.944Z] window#ctor: using window state {
  width: 1024,
  height: 768,
  mode: 1,
  x: 256,
  y: 48,
  hasDefaultState: true
}
[main 2022-02-09T00:23:39.987Z] window#load: attempt to load window (id: 1)
[main 2022-02-09T00:23:39.999Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 0, emptyToOpen: 1)
[main 2022-02-09T00:23:40.001Z] lifecycle (main): phase changed (value: 3)
[main 2022-02-09T00:23:40.004Z] update#setState idle
[main 2022-02-09T00:23:40.005Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
```

Works fine in yesterday's build `f8c36556a2c305327f5417dc7f93220f39ed608f`

Verbose logging seems to stop here, and I'm not sure if it contains any particularly helpful information, is there any way I can get more out of it?

**Comment by atharshaikh** [comment] 2022-02-09 02:05
I am also facing the same issue! The logs look almost the same as op's.

**Comment by UnstoppableMango** [comment] 2022-02-09 04:02
I am also having issues, although my logs look slightly different. Let me know if I should create a new issue

<details>
  <summary>Logs</summary>

  ```
$ code-insiders --verbose --disable-extensions
[main 2022-02-09T03:53:34.763Z] [File Watcher (node.js)] Request to start watching: /home/erik/.config/Code - Insiders/User (excludes: <none>),/home/erik/.config/Code - Insiders/User  /settings.json (excludes: <none>)
[main 2022-02-09T03:53:34.777Z] Starting VS Code
[main 2022-02-09T03:53:34.777Z] from: /opt/visual-studio-code-insiders/resources/app
[main 2022-02-09T03:53:34.777Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '226baceb-5452-45ac-905a-a4936348d914',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/erik/.config/Code - Insiders/logs/20220208T215334'
}
[main 2022-02-09T03:53:34.778Z] Resolving machine identifier...
[main 2022-02-09T03:53:34.778Z] Resolved machine identifier: f500afe2d00242f362b4adcef3581eb6fbc2e40049258f2ce9a7612b1a2e40cb
[main 2022-02-09T03:53:34.779Z] Main->SharedProcess#connect
[main 2022-02-09T03:53:34.782Z] [File Watcher (node.js)] Started watching: '/home/erik/.config/Code - Insiders/User'
[main 2022-02-09T03:53:34.783Z] [File Watcher (node.js)] Started watching: '/home/erik/.config/Code - Insiders/User/settings.json'
[main 2022-02-09T03:53:34.785Z] StorageMainService: creating global storage
[main 2022-02-09T03:53:34.790Z] lifecycle (main): phase changed (value: 2)
[main 2022-02-09T03:53:34.791Z] windowsManager#open
[main 2022-02-09T03:53:34.791Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: '9fedb8879f983a737c94c3e9aa3f364c', uri: [h] },
    type: 2,
    exists: true
  }
]
[main 2022-02-09T03:53:34.792Z] windowsManager#doOpenFolderOrWorkspace {
  folderOrWorkspace: {
    workspace: { id: '9fedb8879f983a737c94c3e9aa3f364c', uri: [h] },
    type: 2,
    exists: true
  },
  filesToOpen: undefined
}
[main 2022-02-09T03:53:34.793Z] IPC Object URL: Registered new channel vscode:90c0293b-587b-4197-9200-ca848fc2d8c0.
[main 2022-02-09T03:53:34.793Z] window#validateWindowState: validating window state on 3 display(s) { mode: 1, x: 1989, y: 1109, width: 1686, height: 1411 }
[main 2022-02-09T03:53:34.793Z] window#validateWindowState: multi-monitor working area { x: 1920, y: 1080, width: 3440, height: 1440 }
[main 2022-02-09T03:53:34.794Z] window#ctor: using window state { mode: 1, x: 1989, y: 1109, width: 1686, height: 1411 }
[main 2022-02-09T03:53:34.819Z] window#load: attempt to load window (id: 1)
[main 2022-02-09T03:53:34.824Z] StorageMainService: creating workspace storage (9fedb8879f983a737c94c3e9aa3f364c)
[main 2022-02-09T03:53:34.824Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2022-02-09T03:53:34.824Z] lifecycle (main): phase changed (value: 3)
[main 2022-02-09T03:53:34.825Z] update#setState idle
[main 2022-02-09T03:53:34.825Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
```

</details>

**Comment by intrnl** [comment] 2022-02-09 04:18
Later today I'll try bisecting builds starting from yesterday.

**Comment by bpasero** [comment] 2022-02-09 06:39
Probably related to the Electron 16 update since insiders already has it.

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by pdanpdan** [comment] 2022-02-09 07:57
Insiders build crash on startup (ubuntu wayland)
[pending.zip](https://github.com/microsoft/vscode/files/8030601/pending.zip)

**Comment by intrnl** [comment] 2022-02-09 08:11
Here's mine.
[crash.zip](https://github.com/microsoft/vscode/files/8030705/crash.zip)

**Comment by ultraheroe** [comment] 2022-02-09 09:22
Same problem here, rolling back to 1.65.0-1644314957 version the problem dissapears.
Tried 1.65.0-1644385272 and 1.65.0-1644360343 both are broken

[dump.zip](https://github.com/microsoft/vscode/files/8031240/dump.zip)

**Comment by deepak1556** [comment] 2022-02-09 09:45
I am unable to repro the crash using the deb, archive and snap packages from https://code.visualstudio.com/insiders on Ubuntu 21.04 with both Wayland and Xorg.

Can anyone please confirm which package you are using, thanks!

**Comment by intrnl** [comment] 2022-02-09 09:59
Currently running on Arch, the [AUR package](https://aur.archlinux.org/packages/visual-studio-code-insiders-bin) uses the `.tar.gz` packages

**Comment by ultraheroe** [comment] 2022-02-09 10:03
> I am unable to repro the crash using the deb, archive and snap packages from https://code.visualstudio.com/insiders on Ubuntu 21.04 with both Wayland and Xorg.
> 
> Can anyone please confirm which package you are using, thanks!

For me, running in ubuntu 18.04 with packages from deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main

**Comment by pdanpdan** [comment] 2022-02-09 10:34
code-insiders_1.65.0-1644385272_amd64.deb

**Comment by deepak1556** [comment] 2022-02-09 10:40
@pdanpdan which version of Ubuntu are you using ?

**Comment by borgdylan** [comment] 2022-02-09 10:42
I am also experiencing this on Ubuntu 21.10, kernel version 5.16.5

**Comment by pdanpdan** [comment] 2022-02-09 10:55
lsb_release -a                                                                                                                                                         
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish

**Comment by deepak1556** [comment] 2022-02-09 11:23
Thanks for the logs and testing with insiders, I was able to confirm the bug. Will update here once the fix has been pushed.

**Comment by gotenksIN** [comment] 2022-02-09 12:50
> Insiders build crash on startup (ubuntu wayland) [pending.zip](https://github.com/microsoft/vscode/files/8030601/pending.zip)
> 
> ```
> > code-insiders --disable-extensions --verbose
> 
> /usr/share/code-insiders/code-insiders --disable-extensions --verbose --enable-crashpad: symbol lookup error: /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/vscode-encrypt/build/Release/vscode-encrypt-native.node: undefined symbol: SHA256_Init
> ```

Yep I got the exact same issue on 1.65.0-insider d09aeab62c1f93acf4a89b93e9a8a82419d6249a x64 on ubuntu

**Comment by gamcoh** [comment] 2022-02-09 13:00
Same issue

<details>
<summary>Here's are my logs:</summary>
<br>

```
(code-insiders:306244): Gtk-WARNING **: 13:57:50.094: Theme parsing error: gtk-dark.css:5822:26: '-shadow' is not a valid color name

(code-insiders:306244): Gtk-WARNING **: 13:57:50.094: Theme parsing error: gtk-dark.css:5825:14: not a number
(code-insiders:306244): Gtk-WARNING **: 13:57:50.094: Theme parsing error: gtk-dark.css:5826:13: not a number

(code-insiders:306244): Gtk-WARNING **: 13:57:50.094: Theme parsing error: gtk-dark.css:5827:11: Expected a length
Gtk-Message: 13:57:50.110: Failed to load module "appmenu-gtk-module"
[90m[main 2022-02-09T12:57:50.204Z][0m [File Watcher (node.js)] Request to start watching: /home/gamzer/.config/Code - Insiders/User (excludes: <none>),/home/gamzer/.config/Code - Insiders/User/settings.json (excludes: <none>)
[90m[main 2022-02-09T12:57:50.217Z][0m Starting VS Code
[90m[main 2022-02-09T12:57:50.217Z][0m from: /opt/visual-studio-code-insiders/resources/app
[90m[main 2022-02-09T12:57:50.217Z][0m args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/gamzer/.config/Code - Insiders/logs/20220209T135750'
}
[90m[main 2022-02-09T12:57:50.219Z][0m Resolving machine identifier...
[90m[main 2022-02-09T12:57:50.220Z][0m Resolved machine identifier: 27b5de22bc239db0380ee5713ae188290bf1dbaf9eb6d7cc6178764bd2f05d80
[90m[main 2022-02-09T12:57:50.221Z][0m Main->SharedProcess#connect
[90m[main 2022-02-09T12:57:50.223Z][0m [File Watcher (node.js)] Started watching: '/home/gamzer/.config/Code - Insiders/User'
[90m[main 2022-02-09T12:57:50.224Z][0m [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/gamzer/.config/Code - Insiders/User/settings.json'
[90m[main 2022-02-09T12:57:50.227Z][0m StorageMainService: creating global storage
[90m[main 2022-02-09T12:57:50.232Z][0m lifecycle (main): phase changed (value: 2)
[90m[main 2022-02-09T12:57:50.233Z][0m windowsManager#open
[90m[main 2022-02-09T12:57:50.234Z][0m windowsManager#open pathsToOpen [ [Object: null prototype] {} ]
[90m[main 2022-02-09T12:57:50.234Z][0m windowsManager#doOpenEmpty {
  restore: false,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: false
}
[90m[main 2022-02-09T12:57:50.235Z][0m IPC Object URL: Registered new channel vscode:e3d12312-4862-4ba7-a7d0-77ee9efa0e96.
[90m[main 2022-02-09T12:57:50.236Z][0m window#validateWindowState: validating window state on 1 display(s) {
  width: 1024,
  height: 768,
  mode: 1,
  x: 1408,
  y: 156,
  hasDefaultState: true
}
[90m[main 2022-02-09T12:57:50.236Z][0m window#validateWindowState: 1 monitor working area { x: 0, y: 30, width: 3840, height: 1050 }
[90m[main 2022-02-09T12:57:50.236Z][0m window#ctor: using window state {
  width: 1024,
  height: 768,
  mode: 1,
  x: 1408,
  y: 156,
  hasDefaultState: true
}
[90m[main 2022-02-09T12:57:50.268Z][0m window#load: attempt to load window (id: 1)
[90m[main 2022-02-09T12:57:50.280Z][0m windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 0, emptyToOpen: 1)
[90m[main 2022-02-09T12:57:50.281Z][0m lifecycle (main): phase changed (value: 3)
[90m[main 2022-02-09T12:57:50.281Z][0m update#setState idle
[90m[main 2022-02-09T12:57:50.282Z][0m resolveShellEnv(): skipped (VSCODE_CLI is set)
```

</details>

**Closed** 2022-02-09 15:26 UTC
Labels: bug, freeze-slow-crash-leak, linux, confirmed, electron-16-update

**Comment by gusbemacbe** [comment] 2022-02-09 16:39
Not just only on Insiders, it also happened on Exploration. I took a DEB of Exploration for Arch Linux. It was caused by https://github.com/microsoft/vscode/pull/137241.

**Comment by gusbemacbe** [comment] 2022-02-09 19:29
@deepak1556 and @bpasero 

I tested the latest deployed apps dated to today and they still closed:

[code-insiders_1.65.0-1644360343_amd64.deb](https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.65.0-1644360343_amd64.deb) 
[code-insiders_1.65.0-1644385272_amd64.deb](https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.65.0-1644385272_amd64.deb)

**Comment by vvtense** [comment] 2022-02-09 20:04
Where can I download a previous version (.tar.gz, linux-x64), such as 1.65.0-1644314957 mentioned by @ultraheroe ?

**Comment by gusbemacbe** [comment] 2022-02-09 20:21
> Where can I download a previous version (.tar.gz, linux-x64), such as 1.65.0-1644314957 mentioned by @ultraheroe ?

1. Go to https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/
2. Pick the wished version.
3. Open a DEB file with Ark.
4. Open` data.tar.xz`. 
5. Go to `usr/share` and extract only the folder `code-insiders`. 
6. Inside the extracted folder `code-insiders`, you click twice the `code-insiders` file.

**Comment by ZaLiTHkA** [comment] 2022-02-09 21:27
> Same problem here, rolling back to 1.65.0-1644314957 version the problem dissapears. Tried 1.65.0-1644385272 and 1.65.0-1644360343 both are broken

I'm finding the exact same thing (Pop!_OS 21.10 user over here).. just out of curiosity, why did the file size suddenly jump in `1.65.0-1644360343`?

```
...
code-insiders_1.65.0-1644314957_amd64.deb          08-Feb-2022 18:15            79946896
code-insiders_1.65.0-1644360343_amd64.deb          09-Feb-2022 00:19           109714924
code-insiders_1.65.0-1644385272_amd64.deb          09-Feb-2022 07:07           109806596
```

looks like something "big" changed there.

**Comment by gusbemacbe** [comment] 2022-02-09 21:38
> > Same problem here, rolling back to 1.65.0-1644314957 version the problem dissapears. Tried 1.65.0-1644385272 and 1.65.0-1644360343 both are broken
> 
> I'm finding the exact same thing (Pop!_OS 21.10 user over here).. just out of curiosity, why did the file size suddenly jump in `1.65.0-1644360343`?
> 
> ```
> ...
> code-insiders_1.65.0-1644314957_amd64.deb          08-Feb-2022 18:15            79946896
> code-insiders_1.65.0-1644360343_amd64.deb          09-Feb-2022 00:19           109714924
> code-insiders_1.65.0-1644385272_amd64.deb          09-Feb-2022 07:07           109806596
> ```
> 
> looks like something "big" changed there.

It seems this file `lbvk_swiftsheader` size increased:

![image](https://user-images.githubusercontent.com/2257024/153294407-e4ff991f-5b0c-49ff-832b-7c81a5278245.png)

**Comment by dqsully** [comment] 2022-02-09 21:42
That appears to be a regression in Electron: https://github.com/electron/electron/issues/32669

**Comment by intrnl** [comment] 2022-02-10 02:42
> I tested the latest deployed apps dated to today and they still closed:
> 
> [code-insiders_1.65.0-1644360343_amd64.deb](https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.65.0-1644360343_amd64.deb) [code-insiders_1.65.0-1644385272_amd64.deb](https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.65.0-1644385272_amd64.deb)

They're `2d8e93571421d69616e0ed7d7958e32abaf8d7d3` and `d09aeab62c1f93acf4a89b93e9a8a82419d6249a`, those two builds were done prior to the fix.

**Comment by intrnl** [comment] 2022-02-10 05:13
/verified :partying_face: 

![Screenshot_20220210_121302](https://user-images.githubusercontent.com/20620901/153341779-d7da6a6c-048d-47d7-b3eb-693cb84b7130.png)
