### ISSUE TITLE
Markdown automatic link updates on file rename / move not working

### ISSUE THREAD

**Issue by JoelMTaylor** [microsoft/vscode#167857] opened 2022-12-01 16:51 UTC
Type: <b>Bug</b>

I have been trying the new feature for automatic link updates (https://code.visualstudio.com/updates/v1_73#_markdown-automatic-link-updates-on-file-rename-move). However, it isn't working for me. It does do one thing, but that is contrary to what is desired.

I have tried moving and renaming one file (image from assets). The markdown file is unaffected.

I tried moving all the images to a new folder. The markdown file links do not change, but the file is itself moved to the new assests folder.

I currently have the dafult markdown.updateLinksOnFileMove.include (although I tested with just *.png files). markdown.updateLinksOnFileMove.enabled is set to 'prompt' and it never prompted anything - behaved the same as 'always'.

VS Code version: Code - Insiders 1.74.0-insider (c87fa19f7932cefa1abeac4dd85ade3983780e14, 2022-12-01T05:21:52.087Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.94GB (21.56GB free)|
|Process Argv|--crash-reporter-id ee44e8e0-455e-4929-a9e8-c4c377757877|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.24.0
vscode-msgraph-autocomplete|eli|1.2.0
vscode-msgraph-essentials|eli|0.0.5
code-runner|for|0.11.8
remotehub|Git|0.46.0
vscode-pull-request-github|Git|0.54.1
gc-excelviewer|Gra|4.2.56
path-autocomplete|ion|1.22.1
RelativePath|jak|1.5.0
powerplatform-vscode|mic|1.1.9
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
azure-account|ms-|0.11.2
powershell|ms-|2022.11.0
powershell-preview|ms-|2022.11.2
remote-repositories|ms-|0.24.0
ruby|reb|0.28.1
markdown-preview-enhanced|shd|0.6.5
code-spell-checker|str|2.11.1
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by mjbvz** [comment] 2022-12-01 17:17
Please share an example project that demonstrates the issue so I try to figure out what might be going on here

**Comment by JoelMTaylor** [comment] 2022-12-02 00:10
It is a little difficult. The project is behind MFA and I don't have permissions to change it or invite people. I'm sorry I can't be more helpful (I am also new to everything).

If there is anything else that I can try do to help, please let me know.

**Comment by mjbvz** [comment] 2022-12-02 00:18
Try creating a minimal project which demonstrates the issue. The content can all be placeholder text, we just need to see the structure of the project and how you are moving files

**Comment by JoelMTaylor** [comment] 2022-12-02 00:33
I have made a small version here: https://github.com/JoelMTaylor/Documentation.git.

I tried moving a file from assets\Authentication\multi-factorauthentication\ccm_single_sign-on.png to assets\OurSystems\UserAuthentication\Multi-FactorAuthentication. The page with the file is Our-Systems\Authentication\Single Sign On.md.

I hope that is enough. Let me know if you need more information.

**Comment by mjbvz** [comment] 2022-12-02 00:44
Thanks. In my quest testing, it looks like the path isn't updated because VS Code doesn't think you are referencing that image file:

![Screenshot 2022-12-01 at 4 37 43 PM](https://user-images.githubusercontent.com/12821956/205188434-8f5ab4bb-b9f4-431a-a6e4-7cc62c70c26e.png)

This seems like an issue with path casing.  Can you try enabling  `"markdown.validate.enabled": true` to see if VS Code understands  the path. Then try making the path case in the md file exactly match that case of the path on disk and seeing if the feature now works

I understand path casing isn't relevant on windows but want to understand if this is the root cause. Just thinking ahead, even if casing isn't relevant on the operating system, we still likely want to enforce it since path cases may matter when the markdown is rendered and hosted

**Comment by JoelMTaylor** [comment] 2022-12-02 00:53
Okay, I set the setting to true and changed the link in ```Single Sign On.md```. The link was changed successfully. 

The page was moved to the same file location as the moved image. Is this to be expected?
![image](https://user-images.githubusercontent.com/97919641/205190177-3ec9e7cd-07cd-4e6e-991f-1bba0b8233fa.png)

**Comment by mjbvz** [comment] 2022-12-02 00:59
Did you only move the image file I this case? If so,  no it should not also move the md file. It should only update the path in it

I don't see this happening but also have only tested on Linux so far

**Comment by JoelMTaylor** [comment] 2022-12-02 01:16
You raise a valid question: "did you only move the image file". It turns out that I was using ctrl + click to select the items to be moved. However, I failed to realise that the item already selected (which happened to be the md file) was included.

I apologise for my mistake.

**Comment by mjbvz** [comment] 2022-12-02 22:21
Thanks for checking. Closing this as expected then

How to handle case sensitivity in markdown files is tracked under https://github.com/microsoft/vscode-markdown-languageservice/issues/106

**Closed by mjbvz** 2022-12-02 22:21 UTC
Labels: info-needed, markdown
