### ISSUE TITLE
Terminal and output panels sometimes can not show anything

### ISSUE THREAD

**Issue by Sccotliu** [microsoft/vscode#85004] opened 2019-11-18 03:54 UTC
- VSCode Version: 1.40.1
- OS Version: windows 10 Enterpirse 1903
Terminal and output panels sometimes can not show anything.
Steps to Reproduce:

1. open one window of vscode
2. Ctrl+shift+N open another window

then new widow will keep white panel, old window will disapeared terminal and output shows. then kill the new window and reopen it, new window will opened normal but old window's termianl/output panel kept white.

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment] 2019-11-18 21:21
@Sccotliu does help when you resize the terminal? Is it a duplicate of #85010

**Comment by Sccotliu** [comment] 2019-11-19 00:53
@egamma It does not recover after resize the terminal, only way is reopen it.
Thanks for help

**Comment by egamma** [comment] 2019-11-19 07:21
@Sccotliu to make it clear that we understand the issue can you attach a screenshot how it looks when this happens the next time.

**Comment by Sccotliu** [comment] 2019-11-19 08:03
@egamma Ok, I'll watch to it , Thank you,

**Comment by Tyriar** [comment] 2019-11-20 15:12
@Sccotliu does pressing enter twice in the terminal fix the problem? Can you share your settings?

**Comment by Sccotliu** [comment] 2019-11-22 05:12
@Tyriar this is my whole settings
{
    "python.pythonPath": "venv\\Scripts\\python.exe",
    "python.linting.pylintPath": "venv\\Scripts\\pylint.exe"
}
I will try to press enter twice at next time and post my result here. thank you.

**Comment by Sccotliu** [comment] 2019-11-22 05:25
here is another issue, when I open a new window by ctrl+shift+N, then I click project name, the new window will freezed, and I catch the snap like this:
![图片](https://user-images.githubusercontent.com/12692951/69400105-8ab39080-0d2b-11ea-8549-db31436734ec.png)
Thank you

**Comment by Sccotliu** [comment] 2019-11-22 05:26
but just reopen it will be ok

**Comment by Tyriar** [comment] 2019-11-22 18:01
@deepak1556 @sbatten any ideas how we could get devtools opened when the menu bar isn't showing up after creating a new window so we can check the console? Or just any more information?

**Comment by deepak1556** [comment] 2019-11-22 19:50
If you can set the environment variable `$env:ELECTRON_ENABLE_LOGGING=1` and launch code , it should print both main and renderer process logs.

Alternatively we can also check the logs folder, should be under `AppData/Roaming/<appname>/logs` or launch code with a new `--user-data-dir` and get the fresh logs from there.

**Comment by sbatten** [comment] 2019-11-22 22:50
@Tyriar in some cases, if the dev tools keybinding is added, it will still work

**Comment by Tyriar** [comment] 2019-11-23 00:06
@Sccotliu could you follow the above logging or keybinding approach to try view logs for the broken window? You can try add this keybinding and see if that works:

```json
{ "key": "ctrl+shift+i",     "command": "workbench.action.toggleDevTools" },
```

**Closed** 2019-11-30 00:14 UTC
Labels: needs more info
