### ISSUE TITLE
Code instances lay around alive after delegating to already running instance

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4051] opened 2016-03-11 23:11 UTC
OS: Windows 10
Build: new 0.10.12-alpha
Steps:
1. Install any old VS code build.
2. Launch app to verify installation is done properly.
3. Now close all the open instances and other program (cmd prompt) which has reference of VS code.
4, Now install latest alpha build from : **https://vscode-builds.azurewebsites.net/alpha **
5. Follow the install Wizard.
6. Proceed with installation by closing all the active program which are causing problem in installation (Look at the attached img :InstallWizard.jpg).
6. The installation wizard ask for replacing files and folder of the old build under : "C:\Program Files (x86)\Microsoft VS Code Alpha".
7. Click on next to proceed with installation.
8. If installation wizard unable to override files or not able to close all the references then it is giving options like: Abort, Retry or Ignore.
9. Select ignore option and proceed with installation 
10. If you get the same pop-up again then select "Abort" to rollback changes.
11. Once rollback is done try to launch previously installed app (directly from installed location or from command prompt).

Note: Verify VS code installed directory under : C:\Program Files (x86)\Microsoft VS Code Alpha.

Actual: 
1. When trying to launch app from command prompt (>Code-alpha ) I could see that the two instances of the app has been created in the windows task manager but app UI is not launching.
2. Looks like after closing all the active window some instances are left orphan in the system which is causing the issue to upgrade build.
3. I tried closing all the orphan instances manually from task manager and then only upgrade work properly.

Expected:
1. User should be able to launch an app when new installation is rolled back successfully.
2. I am not certain but each time two instances of the app is showing up in the windows task manager whenever I am launching app. Is this expected?
![installappandinstancesintaskmanager](https://cloud.githubusercontent.com/assets/17735796/13718006/aa9f5196-e79a-11e5-8336-0c985e71a588.jpg)
![installwizard](https://cloud.githubusercontent.com/assets/17735796/13718005/aa9ac112-e79a-11e5-8563-1464682d0b7a.png)

**Comment by joaomoreno** [comment] 2016-03-14 08:37
Any idea about what you *actually* do on step 2?

**Comment by v-pavanp** [comment] 2016-03-14 08:54
So after installing the old build, I launched an app from command prompt with cmd > code-alpha. I could remember I did that 2-3 times as I was expecting it should launch multiple instances for me, but it was just highlighting the active window and keep adding the instances in background that I could see in the windows Task manager. After all this exercise I closed the active window and started installing new build and finally got the warning in installation for those active sessions which are left abandoned.
Let me know if you need more info on this.

**Comment by joaomoreno** [comment] 2016-03-14 08:57
Cool, thanks for that. We gotta find out why Code instances stay alive after delegating to an already running instance. cc @bpasero

**Comment by bpasero** [comment] 2016-03-14 09:04
@joaomoreno could it be that this is due to our launcher script? first thing to test is if this reproduces when using code.exe or by double click on the shortcut.

**Comment by joaomoreno** [comment] 2016-03-16 16:39
I can't repro this. Do you wanna give it a try, @bpasero?

**Comment by bpasero** [comment] 2016-03-16 16:55
@joaomoreno suggest to close this then and let me verify.

**Comment by bpasero** [comment] 2016-03-16 17:26
@v-pavanp we can both not reproduce, maybe you try again with our latest. when you see processes hanging, please attach the information about the process here. would be interesting which process is the one that survives.

**Closed by bpasero** 2016-03-16 17:26 UTC
Labels: bug, important, v-test

**Comment by joaomoreno** [comment] 2016-03-16 19:09
[Process Hacker](http://processhacker.sourceforge.net/) will provide many more details than the default Windows process explorer. I suggest to use that to figure out what those processes are and how they were launched.

**Comment by v-pavanp** [comment] 2016-03-17 18:34
I verified it with the latest build and not able to repro now. I will verify it again sometime later with different options and settings and will update if I am able to repro. But for now we are good as after closing the window it is cleaning up properly and I could see no active instance or background process left in the task manager.

**Comment by egamma** [comment] 2016-03-29 10:03
Flagging as verified given the comment above.
