### ISSUE TITLE
Closing developer tools sometimes causes quiting vscode

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#46031] opened 2018-03-17 17:51 UTC
Issue Type: <b>Bug</b>

1. Toggle Developer Tools
2. Click the close
![devtool](https://user-images.githubusercontent.com/24318019/37558411-9d9bd80e-2a4e-11e8-901b-8e7303a6670b.gif)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (3.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
debugger-for-chrome|msj|4.2.1
vscode-icons|rob|7.21.0

</details>
Reproduces without extensions

**Comment by mattacosta** [comment] 2018-03-18 02:11
Duplicate of #29063.

**Closed** 2018-03-18 03:48 UTC
