### ISSUE TITLE
Debugger it freezes

### ISSUE THREAD

**Issue by LI-INA** [microsoft/vscode#182025] opened 2023-05-10 08:50 UTC
Type: <b>Bug</b>

The debugger freezes after a few steps in the code.
Platform: Business Central (SAAS)
language: AL

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.35GB free)|
|Process Argv|--crash-reporter-id dbc47957-755a-48a4-93d5-01de26fa327d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|3.0.46
atlascode|atl|3.0.3
al-toolbox|Bar|2.0.28
al-language-tools|Cli|0.0.22
al-translation-center|dan|2.0.0
al-object-designer|mar|0.2.4
vscode-language-pack-hu|MS-|1.48.3
al|ms-|12.0.779795
powershell|ms-|2023.5.0
nab-al-tools|nab|1.30.0
allanguageniq|NOR|1.1.4
vscode-yaml|red|1.12.2
xliff-sync|rva|1.4.0
crs-al-language-extension|wal|1.5.25

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpath:30731978

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-05-10 09:16
/duplicate of https://github.com/microsoft/vscode/issues/181485 which is scheduled to be fixed in upcoming recovery release 1.78.2

**Closed** 2023-05-10 09:16 UTC
Labels: *duplicate
