### ISSUE TITLE
CMD+D in new unsaved file

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10075] opened 2016-08-03 11:36 UTC
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:

1. Have 1 existing file open in VSCode
2. Click File/New (CMD+N) to create new unsaved file
3. Paste 
```
abc def
abc def
abc def
```
4. Put cursor inside `abc`
5. Hit `CMD+D` multiple times
6. Problem: Nothing gets selected

**Comment by alexandrudima** [comment] 2016-08-12 09:51
@wallverb I cannot reproduce:

![cmd-d](https://cloud.githubusercontent.com/assets/5047891/17619012/13906062-6083-11e6-9d4d-6bcdc682f494.gif)

**Comment by wallverb** [comment] 2016-08-12 13:08
Ok, so here are the steps that I can always reproduce on OSX (not sure if it's also problem on WIN)

1. Have one (and only one file fully open that is from project)
2. Press `CMD+N` to open new file/tab (don't double click tab bar because this way everything works ok for some reason)
3. Type text, try to select first word with `CMD+D` - nothing happens

Here is the gif:
![yifoad4ain](https://cloud.githubusercontent.com/assets/1723815/17623077/45610fb8-606c-11e6-8953-c019941f9864.gif)

**Comment by alexandrudima** [comment] 2016-08-15 10:28
Thank you, I can reproduce with these steps! Root cause is the `editorFocus` context key, which gets set to true from a second CodeEditorWidget instance and then gets reset to false from the original CodeEditorWidget instance. Root cause is #10358.

@bpasero @jrieken Let's discuss tomorrow

**Comment by bpasero** [comment] 2016-08-15 11:51
Feel free to close as duplicate of #10358 unless there is something else we need to take care of?

**Comment by alexandrudima** [comment] 2016-08-15 12:13
I like that we finally have reproducible steps. @bpasero Let's discuss tomorrow, maybe we go back to having scoped contexts per editor instance.

**Comment by bpasero** [comment] 2016-08-15 12:31
@alexandrudima I am fine revisiting that (as I have not yet started to work on disposing the editor) but I can reproduce the other issues as well easily as soon as I bring in the settings editor.

Note that untitled files also use a different editor compared to files, so it is similar to opening settings (but likely easier to reproduce).

**Comment by bpasero** [comment] 2016-08-16 13:04
@alexandrudima @jrieken after talking briefly to Alex, Joh is trying to bring back the state of having a keybinding service per editor. That means I will not continue in https://github.com/Microsoft/vscode/issues/10358 for now.

**Closed** 2016-08-22 10:56 UTC
Labels: bug, important

**Comment by bpasero** [comment] 2016-08-22 15:11
@jrieken does this mean I can revert https://github.com/Microsoft/vscode/commit/e466584a67903e467bad1089aac1145de6a61493 ?

**Comment by jrieken** [comment] 2016-08-23 07:57
Why would you do that? I think not listening to events when you are invisible and potentially never visible again is generally a good thing

**Comment by bpasero** [comment] 2016-08-23 08:58
@jrieken 👍
