### ISSUE TITLE
Ability to reorder nodes in a treeview

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#117505] opened 2021-02-23 23:30 UTC
As a vscode extension author, I'd like to be able to specify whether vscode.TreeItems can participate in a drag-and-drop reordering inside of a custom treeview.

There is some potential complexity here as it may not be contextually appropriate for some target nodes to permit a drop operation in the case of nested nodes, so any solution here would ideally call a user-defined function along the lines of "`isAllowed(source: vscode.TreeItem, target: vscode.TreeItem) : Boolean`" before effecting a drop operation and re-ordering the tree.

Once a node has been reordered, an additional event would need to be fired on the TreeDataProvider, passing along the identifiers involved so the developer can update any underlying data structures or systems.

**Comment by alexr00** [comment] 2021-02-24 10:18
Duplicate of https://github.com/microsoft/vscode/issues/32592

**Closed** 2021-02-24 10:19 UTC
Labels: *duplicate

**Comment by gplumb** [comment] 2021-02-24 11:09
That ticket was created in 2017! Come on... clearly people want this
feature - what is it going to take to get this work into a sprint??
