### ISSUE TITLE
In 1.53.2 version , Sogou input Chinese not displayed in terminal

### ISSUE THREAD

**Issue by changeLong** [microsoft/vscode#117346] opened 2021-02-23 09:54 UTC
version: 1.53.2 (user setup)
commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17763

When I open the terminal,When using sogou Pinyin input Chinese, Chinese is not displayed in the terminal

**Comment by yume-chan** [comment] 2021-02-23 14:27
Duplicate of #115814

**Closed** 2021-02-24 20:53 UTC
Labels: *duplicate
