### ISSUE TITLE
code-insiders does not open path when given at command-line

### ISSUE THREAD

**Issue by shaunm-msft** [microsoft/vscode#137771] opened 2021-11-24 02:16 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version: 1.63.0-insider (user setup)
Commit: ed3018f4310e906daa0a9119d997e75b8a38b879
Date: 2021-11-23T05:33:39.595Z (20 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

- OS Version: win10 WSL v1

Steps to Reproduce:

1. WSL 1.0
2. code-insiders .

It should open vscode with that directory. It doesn't.
You can also give a full path and it still doesn't open the directory.

**Comment by lauritk** [comment] 2021-11-24 07:50
Perhaps duplicate of #137409 ?

**Comment by shaunm-msft** [comment] 2021-11-24 15:48
[#137409](https://github.com/microsoft/vscode/issues/137409) reports that they can open existing files or folders but cannot create new ones. 
The bug I logged here is about not being able to open existing folders in WSL. It works as expected in Windows.

**Comment by RickFrankel** [comment] 2021-11-24 22:11
I two have started getting this issue in the last 2 days using code-insiders . on WSL 2.0.

**Comment by aeschli** [comment] 2021-11-29 21:09
This got fixed by https://github.com/microsoft/vscode/commit/c1e2c6c0eb8a4d951edbca28006952c25eba9021#diff-0ed0f9517871e1a38d3995bb63296392ea63377164748c10e87cd65920b72d6b

**Closed by aeschli** 2021-11-29 21:09 UTC
Labels: bug
