### ISSUE TITLE
Keybinding UI editor should support context key suggestions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116855] opened 2021-02-17 14:53 UTC
Follow up from https://github.com/microsoft/vscode/issues/9303#issuecomment-780609343

I have added a completion item provider for context keys. For the keybindings UI this isn't working yet and what's needed is

1. use the simple editor widget as the input when authoring when-clauses
2. build a similar completion item provider (using internal API) that uses the same data source (`RawContextKey#all`)

**Comment by GF-Huang** [comment] 2022-06-30 05:48
Not work.

![image](https://user-images.githubusercontent.com/4510984/176602030-41c47ce2-f01b-4165-a7a5-77d1e6211a13.png)

![image](https://user-images.githubusercontent.com/4510984/176602046-3bff067b-385a-4fd1-9a89-218aa2565424.png)

**Comment by GF-Huang** [comment] 2022-06-30 05:49
I don't even know how to open `keybindings.json`.

**Comment by sandy081** [comment] 2022-12-30 13:36
Started using `SuggestEnabledInput` (Code Editor)  for when input and I am seeing following issues with the code editor

1. Suggest widget is showing far away from the editor.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/10746682/210075664-a72eb925-d40b-4af3-8065-a18b7488f3ea.png">

2. I listen on `Enter` key and accept the when text. This is causing problem when I am accepting an option from suggest list using Enter.  Is there a way to prevent this to happen?

@jrieken / @alexdima Your expertise would be very helpful here. 

You can find changes here - https://github.com/microsoft/vscode/pull/170291

**Comment by jrieken** [comment] 2023-01-03 08:26
> I listen on Enter key and accept the when text

Pretty sure that you need to use the keybindings service instead, e.g don't listen to keydown/up event directly


> Suggest widget is showing far away from the editor.

ops... that seems very wrong, both widgets are normal content/overlay widgets

**Comment by sandy081** [comment] 2023-01-04 18:34
Investigated the issue with overflow content widget misplacement and here is what I found:

This seems to be a bug with editor overflowing content widget `position` value set to `fixed`. According to the docs, when position value is set to fixed then the position of the element will be relative to its containing block, which is https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block

In keybindings editor, the table widget (extending list widget) has the ancestor rows element with `transform` and `contain` css property set. Hence overflowing content widgets are drawn relative to the table rows element. This can be confirmed by disabling the `transformOptimization` on the table widget that does not set above css properties.

This means, embedding a code editor widget inside any node that has these css properties set will break the position of the overflowing content widgets

CC @alexdima / @hediet for editor related.
CC @joaomoreno for table/list related.

Can you please let me know what is the right way to proceed here. Does it makes sense to disable `transformation` for keybindings table? Or this shall has to be fixed in editor?

**Comment by sandy081** [comment] 2023-01-05 11:27
It seems the trick is to use `overflowWidgetsDomNode` option in the code editor. But it seems to work only for content widgets but not for overlay widgets - like suggest element details. Using the same `overflowWidgetsDomNode` for overlay widgets fixes it.

**Comment by sandy081** [comment] 2023-01-05 15:23
For now disabled table transformations and created a separate PR to fix it in the editor - https://github.com/microsoft/vscode/pull/170632.

**Closed by sandy081** 2023-01-05 15:23 UTC
Labels: feature-request, keybindings-editor, papercut :drop_of_blood:

**Comment by sandy081** [comment] 2023-01-23 16:28
Verify that while editing when column in keyboard shortcuts editor shows the list of context key suggestions.

**Comment by jrieken** [comment] 2023-01-25 13:30
I see this is implemented but it's also mostly broken because it doesn't work real prefixes https://github.com/microsoft/vscode/issues/172385
