### ISSUE TITLE
URL underlining flickers within XMLA

### ISSUE THREAD

**Issue by Peter-Vel** [microsoft/vscode#77820] opened 2019-07-23 14:20 UTC
Issue Type: <b>Bug</b>

1. Create a new file, using the PowerShell language, Dark++ theme.
2. Create a variable containing a code block of XMLA.  For example:

$Example =    '<Create                    xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"                    xmlns:ddl2="http://schemas.microsoft.com/analysisservices/2003/engine/2"                    xmlns:ddl2_2="http://schemas.microsoft.com/analysisservices/2003/engine/2/2"                    xmlns:ddl100_100="http://schemas.microsoft.com/analysisservices/2008/engine/100/100"                   xmlns:ddl200_200="http://schemas.microsoft.com/analysisservices/2010/engine/200/200"                xmlns:ddl300_300="http://schemas.microsoft.com/analysisservices/2011/engine/300/300">
           <ObjectDefinition>
                        <Trace>
                       </Trace>
           </ObjectDefinition>
</Create>'

3. Enter enough lines in the script so you have the ability to scroll.

4. You should notice that when at the top of the script, the URL underlining will flicker.  If you scroll down at all, it will stop.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (19.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
vscode-github|Kni|0.30.2
mssql|ms-|1.6.0
python|ms-|2019.6.24221
powershell|ms-|2019.5.0

</details>

**Comment by rebornix** [comment] 2019-07-23 17:50
possible duplicate of https://github.com/microsoft/vscode/issues/48321

**Closed** 2019-07-26 22:41 UTC
Labels: *duplicate, editor-contrib
