### ISSUE TITLE
Markdown preview clipped when VS Code is zoomed in

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12921] opened 2016-09-28 18:17 UTC
- VSCode Version:1.6.0 insiders
- OS Version: Windows 7

Steps to Reproduce:

1. Open and Markdown file and zoom in several levels.
2. Open Preview

The preview is clipped.

![markdownzoomin](https://cloud.githubusercontent.com/assets/12818376/18926543/12289528-856d-11e6-964b-faa5c82b0f96.png)

**Comment by mjbvz** [comment] 2016-09-28 18:20
Duplicate of #5745 

I only know this because I opened #12824 to track the same problem and it was marked as a dup of #5745

**Closed by mjbvz** 2016-09-28 18:20 UTC
Labels: duplicate, markdown
