### ISSUE TITLE
Format on Save, makes JSON file growing more and more

### ISSUE THREAD

**Issue by ThePlenkov** [Microsoft/vscode#14667] opened 2016-10-28 14:52 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 7

Steps to Reproduce:
1. Open Settings.json
2.  Press Alt+Shift+F, some empty lines are added between parameters
3. Press again - it's starts stretching more

**Comment by aeschli** [comment] 2016-10-31 13:46
@ThePlenkov Can you paste the content of the settings.json where I can reproduce this. What are the tab and new line settings?

**Comment by aeschli** [comment] 2016-11-03 17:05
Same as #14623?

**Comment by ThePlenkov** [comment] 2016-11-07 08:00
Hi Martin!

Yes - it's exactly same problem.

**Comment by aeschli** [comment] 2016-11-08 09:48
Thanks. Marking as duplicate of #14623

**Closed by aeschli** 2016-11-08 09:48 UTC
Labels: needs more info
