### ISSUE TITLE
Bug git and terminal

### ISSUE THREAD

**Issue by nmhung1234** [microsoft/vscode#132363] opened 2021-09-05 01:46 UTC
Issue Type: <b>Bug</b>

1. terminal default change to powershell (its cmd before). 
2. show popup login github every single time open vs code (i was login before). Hope team fix early!!

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.97GB free)|
|Process Argv|C:\\Users\\Asus\\OneDrive - Hue University of Medicine and Pharmacy\\Máy tính\\BlogWS.code-workspace --crash-reporter-id 719286f2-5258-4a47-be98-24f3eea30d37|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
turbo-console-log|Cha|2.1.6
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
rest-client|hum|0.24.5
vscode-styled-components|jpo|1.6.6
cpptools|ms-|1.6.0
cocos-creator-js|nex|0.1.6
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|4.10.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.4.26
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedt:30351793
vsdyn321cf:30356811
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-05 03:31
> 1. terminal default change to powershell (its cmd before).

This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Closed** 2021-09-07 16:59 UTC
Labels: *duplicate
