### ISSUE TITLE
TS Server fatal error:  Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gbatori** [microsoft/vscode#95304] opened 2020-04-15 08:17 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (tsserver.js:19148:110)
    at Object.parseJsonText (tsserver.js:18972:26)
    at Object.parseJsonText (tsserver.js:18793:23)
    at ProjectService.loadConfiguredProject (tsserver.js:142258:33)
    at ProjectService.reloadConfiguredProject (tsserver.js:142403:22)
    at ConfiguredProject.updateGraph (tsserver.js:140650:45)
    at updateProjectIfDirty (tsserver.js:141076:45)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143114:29)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (4.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
copy-relative-path|ale|0.0.2
flutter-snippets|ale|2.0.0
vscode-add-nativescript-files|ale|1.0.1
angular-schematics|cyr|4.0.1
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
gitlens|eam|10.2.1
bloc|Fel|3.4.0
vscode-jest-runner|fir|0.4.15
pubspec-assist|jer|0.3.6
remote-wsl|ms-|0.44.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1947
awesome-flutter-snippets|Nas|2.0.3
vetur|oct|0.24.0
nativescript-extend|Pau|2.11.10
nativescript|Tel|0.11.0

</details>

**Comment by mjbvz** [comment] 2020-04-15 15:27
Duplicate of https://github.com/microsoft/TypeScript/issues/30005

**Closed by mjbvz** 2020-04-15 15:27 UTC
