### ISSUE TITLE
Unclear cell movement behaviors

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#208694] opened 2024-03-25 17:23 UTC
Testing #208267

Version: 1.88.0-insider (user setup)
Commit: b0d975fc6370f15570c380f41015b1ca2cdcb791
Date: 2024-03-25T05:49:32.344Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.25987

When moving notebook cells, I was surprised that I can only move them to the very top or bottom of the notebook. I expected to be able to move them in between other cells in the middle of the notebook too.

I also struggle to figure out how I need to focus and position my cursor to be able to move cells at all - example gif below where I'm not sure what I'm doing wrong:

![Image](https://github.com/microsoft/vscode/assets/25310137/4c80d1a9-0f29-4ad9-ab31-d8f9e791ba05)

**Comment by bamurtaugh** [comment] 2024-03-25 17:25
Upon further experimentation, it seems I can only move code cells but not markdown cells. Not sure if/why this would be expected.

**Comment by DonJayamanne** [comment] 2024-05-30 20:37
Duplicate of https://github.com/microsoft/vscode/issues/211548

**Closed by DonJayamanne** 2024-05-30 20:37 UTC
Labels: bug, notebook, notebook-dnd
