### ISSUE TITLE
Change syntax from the command palette

### ISSUE THREAD

**Issue by vicary** [Microsoft/vscode#58502] opened 2018-09-12 10:07 UTC
In Subline Text we have `set syntax: XXX` commands, useful when there are conflicting/ambiguous file extensions and we actually need both in one single project.

For example,
1. `.html`, `.tpl` family
2. `.js`, `jsx` family

**Comment by usernamehw** [comment] 2018-09-12 15:00
Duplicate of #1800

**Closed** 2018-09-13 06:58 UTC
