### ISSUE TITLE
Duplicate notifications can appear in notification center

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44607] opened 2018-02-27 15:26 UTC
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

#44319

I couldn't figure out the exact sequence of commands to trigger this, but it happened to me twice. Some combination of showing multiple commands as well as showing and hiding the notification center. There are two copied of each notification below:

![image](https://user-images.githubusercontent.com/2193314/36737247-75ed227c-1b8f-11e8-811b-fa2e79ba4a3f.png)

```ts
let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
    vscode.window.showErrorMessage('one [website](http://code.visualstudio.com?foo#bar) Non eiusmod proident labore et quis sit tempor do. Et minim excepteur fugiat consectetur magna cillum reprehenderit nulla pariatur ipsum. Minim consequat est nisi laborum duis mollit aliquip in pariatur. Voluptate fugiat adipisicing cillum ullamco minim amet in. Laborum cillum anim tempor deserunt reprehenderit sint. Laboris sint irure officia sit aliqua proident fugiat incididunt in incididunt occaecat esse voluptate.', 'a', 'b');
    vscode.window.showWarningMessage('twoConsectetur enim nostrud quis nisi aliqua qui esse aliquip consectetur aliqua. Lorem consectetur sunt nostrud laboris. Aliqua reprehenderit esse deserunt aute. Anim ut sint et eu cillum proident deserunt et anim sint labore culpa nulla. Veniam mollit sunt dolor non duis exercitation duis amet commodo id eiusmod commodo excepteur sunt. Cupidatat nisi esse reprehenderit cillum consequat excepteur excepteur id est labore. Voluptate ea sint amet quis aute et proident occaecat.');
    vscode.window.showInformationMessage('Veniam ullamco reprehenderit laboris anim labore cupidatat sunt. Aliqua aliquip laboris minim irure commodo ea nostrud amet. Eu cupidatat occaecat magna velit sit cupidatat ex eiusmod. Ex deserunt ad ut do elit nostrud pariatur est dolore anim non. Non dolore non consectetur esse.', 'e', 'f');
});
```

**Comment by bpasero** [comment] 2018-02-27 16:15
@Tyriar would be great if you could distill steps

**Comment by Tyriar** [comment] 2018-02-27 16:47
@bpasero it happened twice while creating similar issues and I spent the next 5-10 minutes trying to repro it without success. Feel free to close if nothing sticks out or if there's no obvious place to be more defensive, it's pretty hard to repro.

**Comment by bpasero** [comment] 2018-02-27 17:39
@Tyriar yeah I also could not reproduce, weird. I guess this would be a bug in the viewer layer and not the model layer where I run the de-duplication logic (which is [quite simple](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/notifications.ts#L575 based on equality of source, message and primary actions)). 

Closing until there are real steps.

**Closed by bpasero** 2018-02-27 17:39 UTC
Labels: bug, insiders, workbench-notifications
