### ISSUE TITLE
[win:terminal] Wrong default shell on startup/workspace change

### ISSUE THREAD

**Issue by AdrianSkar** [microsoft/vscode#132978] opened 2021-09-13 10:51 UTC
- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.19042

**Steps to reproduce**:

1. Close VScode (Ctrl +Q) on a workspace that has a terminal view opened.
2. Open VSCode again.

**What happened**: The terminal view changed to Powershell regardless of `"terminal.integrated.automationShell.windows"` or `Default profile` settings:
![start_up_view](https://user-images.githubusercontent.com/12052430/133070814-46080bb1-10ed-42c7-8c92-0e33aead8528.png)

**What was expected to happen**: As in previous versions, the proper terminal shell/session is restored and/or when opening the terminal view (Ctrl + `), the default profile settings are honored.
![expected_behavior](https://user-images.githubusercontent.com/12052430/133071003-4771335a-a171-4173-828e-d7a225fd2a9e.png)

**Comment by IllusionMH** [comment] 2021-09-13 10:53
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 10:53 UTC
Labels: *duplicate
