### ISSUE TITLE
Search results are showing from excluded files

### ISSUE THREAD

**Issue by sujithmathewthomas** [microsoft/vscode#115897] opened 2021-02-05 16:39 UTC
Issue Type: <b>Bug</b>

In the left hand side global search, I have given a folder path in `files to include` field (src/app/company/) and I've given a subfolder of the previous path in `files to exclude` field (src/app/company/components/company-details/). Initally it was working fine, but when I open a file from this excluded directory in editor, the results from that particular file is then being shown in global search results, even though it comes under the excluded field. If I close that file and search again,it is gone from the search results.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 4400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (4.78GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8b7a7f68-b84e-4aeb-8570-f9f8d533db39|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
vscode-docker|ms-|1.9.1
remote-containers|ms-|0.155.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-scss-formatter|sib|2.1.0
eno|Wsc|2.3.53

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by JacksonKearl** [comment] 2021-02-05 17:43
cc @roblourens

**Comment by JacksonKearl** [comment] 2021-02-05 18:50
I haven't been able to reproduce this, could you try updating to 1.53.0? We made some changes to filtering logic last iteration that might help here.

**Comment by JacksonKearl** [comment] 2021-02-05 18:51
\gifPlease

**Comment by sujithmathewthomas** [comment] 2021-02-05 19:14
@JacksonKearl I've updated VS code to 1.53.0, but the issue still persists. Im attatching a screenrecording. As you can see, I've excluded file2.txt from the search. But when I open it, it is being shown in the search. Again when I'm closing it, it is gone from the search.
![recording](https://user-images.githubusercontent.com/47884282/107078492-69e23880-6814-11eb-8c44-aae2c753c83e.gif)

**Comment by JacksonKearl** [comment] 2021-02-05 19:37
In that specific case we don't support `~` in the excludes, but removing it should work as expected. Is there a case where you have a folder open and see this behaviour for relative paths inside the folder?

**Comment by sujithmathewthomas** [comment] 2021-02-05 19:50
I've moved that to another folder and now I'm not using `~`. Still the issue persists.
![recording (1)](https://user-images.githubusercontent.com/47884282/107081975-85037700-6819-11eb-9366-86f643379b82.gif)

**Comment by JacksonKearl** [comment] 2021-02-05 20:35
Thanks, I can reproduce it. As a workaround it should mostly work without the leading `./`, but of course that would exclude matching subdirectories too.

**Comment by roblourens** [comment] 2021-02-05 20:59
Two issues here - as a general issue, an absolute path to an individual file won't work well in includes or excludes. But also, an open file will still be searched even if it's excluded: https://github.com/microsoft/vscode/issues/31819. I will close this as a dupe of that. The first is basically covered by the search API issues.

**Closed by roblourens** 2021-02-05 20:59 UTC
Labels: bug, search
