### ISSUE TITLE
Diff editor should support splitting down

### ISSUE THREAD

**Issue by felix9ia** [microsoft/vscode#66962] opened 2019-01-23 03:19 UTC
![image](https://user-images.githubusercontent.com/23549191/51580697-5c450900-1f00-11e9-9f4f-63ced41c08dc.png)

when screen erect, source control split layout just split right ,I want to  split down
![image](https://user-images.githubusercontent.com/23549191/51580713-6f57d900-1f00-11e9-9850-7df2628c2e6f.png)

**Comment by sbatten** [comment] 2019-01-23 19:22
Several commands exist for splitting the editor. Split orthogonal, down, or up should fit your use case. 
![image](https://user-images.githubusercontent.com/6561887/51631261-13418480-1f01-11e9-9d6b-f23d79ea3e87.png)

**Comment by felix9ia** [comment] 2019-01-24 01:41
Thanks, @sbatten , but I think you don't look at my issue be carefully, I mean  I want to split down the **SOURCE CONTROL** working tree , not in editors. I set it up according to your instructions,but i got this……
![image](https://user-images.githubusercontent.com/23549191/51648291-d4700500-1fba-11e9-91e3-6fbc6d7afd5a.png)

**Comment by felix9ia** [comment] 2019-01-24 02:00
And I think this kind of preview is best saved to the user settings.

**Comment by sbatten** [comment] 2019-01-24 18:18
@felix9ia ah you're right sorry i misunderstood.

**Comment by felix9ia** [comment] 2019-01-25 01:52
@sbatten It doesn't matter, I just hope to meet this requirement.

**Comment by alexandrudima** [comment] 2019-10-11 21:19
Duplicate of #26856

**Closed by alexandrudima** 2019-10-11 21:19 UTC
Labels: diff-editor, feature-request
