### ISSUE TITLE
Menubar dropdown overflows out of the window

### ISSUE THREAD

**Issue by htshah** [Microsoft/vscode#54299] opened 2018-07-14 06:49 UTC
Issue Type: <b>Bug</b>

Set the window.titleBarStyle to custom.
Then from the menubar select View(or any other dropdown which has long list of items).
The items overflows out of the window

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.94GB (1.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.2
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
prettier-vscode|esb|1.5.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vscode-javac|geo|0.1.1
vscode-auto-open-markdown-preview|hnw|0.0.4
phpcs|ika|1.0.5
vscode-phpfmt|kok|1.0.30
git-indicators|lam|2.1.1
google-fonts|lio|0.0.1
ftp-sync|luk|0.3.3
vscode-autoprefixer|mrm|2.1.2
cpptools|ms-|0.17.6
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.8.0
php-docblocker|nei|1.6.0
material-icon-theme|PKi|3.5.1
vscode-css-peek|pra|2.1.0
LiveServer|rit|5.1.1
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.0.0
markdown-preview-enhanced|shd|0.3.5
stylelint|shi|0.37.0
shell-launcher|Tyr|0.2.0
c-cpp-snippets|wlh|0.1.0
better-align|wwm|1.1.6
html-css-class-completion|Zig|1.17.1

</details>

**Comment by TomSputz** [comment] 2018-07-15 11:44
Dupe of #52533

**Closed** 2018-07-16 14:36 UTC
Labels: *duplicate, new release
