### ISSUE TITLE
Issues with regex search replace when using lookaround and `$1`

### ISSUE THREAD

**Issue by oyvindronningstad** [microsoft/vscode#192125] opened 2023-09-04 11:13 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code in a folder
2. Create a text file with the following contents
```
baz
foo bar baz
foo
bar
baz
```
3. Go to the search tab (ctrl-shift-f)
4. Turn on regex search
5. Enter into the search field: `(?<=\W)(foo|bar)`
6. Enter into the replace field: `$1`
7. Search, then Replace All
8. For me, the text file now contains (one foo has become bar, another foo and bar have become $1)
```
baz
bar bar baz
$1
$1
baz
```
9. Add a space before all lines in the text file
10. Do steps 3-7 again
11. Now, for me, the text file contains (one bar has become foo)
```
 baz
 foo foo baz
 foo
 bar
 baz
```

The expectation in both cases is that the contents of the text file don't change when doing Replace All.

I've observed issues with lookahead as well, I have not tried negative lookbehind or negative lookahead.

**Comment by andreamah** [comment] 2023-09-08 18:14
I *believe* that this is the same bug as https://github.com/microsoft/vscode/issues/128134. It seems that when it matches newline without explicitly using `\n`, then there's a bug with how it handles capture groups.

/duplicate

**Comment by oyvindronningstad** [comment] 2023-09-12 11:17
>I believe that this is the same bug as 128134. It seems that when it matches newline without explicitly using \n, then there's a bug with how it handles capture groups.

@andreamah It does look similar, but there is no matching of newlines in my example.

**Comment by oyvindronningstad** [comment] 2023-09-12 11:35
@andreamah As far as I understand, #128134 possibly covers only one of the issues I discovered, namely the replacement being a literal `$1` instead of the group contents.

But there's another issue here as well, the fact that if the regex matches twice in a line, the contents of one match is being used in the other replacement. In my example, at step 8, `foo bar` is being turned in to `bar bar`, while in step 11, it becomes `foo foo`.

**Comment by osortega** [comment] 2024-12-19 03:58
This seems to be a duplicate of https://github.com/microsoft/vscode/issues/172882
Closing this issue

/duplicate

**Closed by osortega** 2024-12-19 03:58 UTC
Labels: bug, search, confirmed
