### ISSUE TITLE
Incoming/Outgoing changes graph preview is not working properly

### ISSUE THREAD

**Issue by islamhossam1** [microsoft/vscode#221257] opened 2024-07-09 10:05 UTC
Type: <b>Bug</b>

Hello Team,

I enabled the new feature "Incoming/Outgoing changes graph preview" in VS Code June 2024 (version 1.91).

It was working smoothly until I cloned a new clean github repository, no graph tree appears and the modified files are not shown.

Regards,
Islam Hossam

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.12.0
ruff|cha|2024.30.0
python-environment-manager|don|1.2.4
gitlens|eam|15.1.0
vscode-great-icons|emm|2.1.105
vscode-proto3-tools|kal|0.1.4
rainbow-csv|mec|3.12.0
fluent-icons|mig|0.0.18
debugpy|ms-|2024.6.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

```[tasklist]
### Tasks
```

**Comment by MoetassemCh** [comment] 2024-07-09 10:20
same issue

**Comment by lszomoru** [comment] 2024-07-09 14:11
Closing as duplicate of https://github.com/microsoft/vscode/issues/220085#issuecomment-2213648879

**Closed by lszomoru** 2024-07-09 14:11 UTC
