### ISSUE TITLE
Broken Font: Colored artefacts between letters

### ISSUE THREAD

**Issue by asikstel** [Microsoft/vscode#38861] opened 2017-11-21 10:09 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.0-1-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.2.3
vscode-emacs|hir|0.1.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.2
debug|web|0.21.2

I am using a machine with 2560x1440 resolution.

![screenartefactsvscode](https://user-images.githubusercontent.com/9788864/33066668-3b93af54-ceac-11e7-89b2-e51d474ac442.png)

---

Steps to Reproduce:

1. open any file with cpp code, e.g. a standard Makefile
2. zoom in and out
3. At zoom 0 the artefacts usually do not accure, at zoom -2 they do. 

Since the screen resolution is quite high, I need to set VS Code to zoom -2. You can see the error well in the picture attached, after "E" in $MAKE and also after "M". This artefacts seem to appear  at random positions.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-11-22 08:10
Duplicate of #35675

**Closed by alexandrudima** 2017-11-22 08:10 UTC
Labels: electron, font-rendering, linux, new release, upstream
