### ISSUE TITLE
Use .gitignore to hide files in explorer

### ISSUE THREAD

**Issue by mtripp100** [microsoft/vscode#38878] opened 2017-11-21 14:15 UTC
Forking https://github.com/Microsoft/vscode/issues/23804 [on the advice of @isidorn](https://github.com/Microsoft/vscode/issues/23804#issuecomment-345280932) as it was conflating two issues - colouring and hiding gitignored files in the file explorer.

* Greying/colouring works great as of [1.18](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_18.md#git-status-in-file-explorer).
* Hiding them completely still requires an extension or manually syncing ignored patterns with the `files.exclude` setting.

I would love a separate setting which completely hides files instead of just greying them out. Thanks.

**Comment by derwaldgeist** [comment] 2018-01-08 10:22
I'd like to support this. I'm coming from Atom and used to not having my .gitignored files clutter my folder structure.

**Comment by isidorn** [comment] 2018-01-08 10:31
fyi @joaomoreno @jrieken

**Comment by tanzislam** [comment] 2018-01-27 19:36
For the moment, if people would tolerate the use of a plugin for this, the most accurate one I know of (in terms of using relevant entries from multiple `.gitignore` files, wildcard entries, etc. etc.) is [this one](https://marketplace.visualstudio.com/items?itemName=npxms.hide-gitignored).

I've tested [two](https://marketplace.visualstudio.com/items?itemName=stubailo.ignore-gitignore) [other](https://marketplace.visualstudio.com/items?itemName=sadesyllas.explorer-excluded-files) plugins, but the edge-case bugs/limitations are frankly maddening.

**Comment by HitomiTenshi** [comment] 2018-07-29 19:03
- Requested on Nov 21, 2017
- Labeled on Nov 22, 2017

Today is **July 29, 2018** and there is still no real answer or progress being made to support this feature.

I come from Atom as well and gave VS Code a chance. Working with **TypeScript** and **Sass** creates a bunch of compiled **JavaScript** and **CSS** files which all clutter the Explorer a lot. I guess I'll stay with Atom for a while longer.

**Comment by sarneeh** [comment] 2018-07-30 06:38
@HitomiTenshi Yeah, you had more than one year to contribute and all you do is complain 😛 It's open-source software, you don't pay a penny for an awesome piece of software and still demand the team to add all the features you want. It doesn't work that way buddy 😄

**Comment by HitomiTenshi** [comment] 2018-07-30 07:51
@sarneeh You're right. But you can't expect everyone to be able to code or know the project code well enough to just quickly whip up a PR with a new feature. What if I'm just a designer proficient in HTML & CSS but bad at anything else?

Maybe my wording is a bit demanding, I just wanted to point out that there is no official answer whether this feature request will be even considered. They labeled it but I don't think they gave it any thought (yet).

**Comment by sarneeh** [comment] 2018-07-30 08:06
@HitomiTenshi When you don't have the skills or time, all you can do is be patient, wait and count on the community to add this feature 😄 

I don't know if a thought from the creators/maintainers would change anything for this issue. It's just a feature request - when there's big demand on it and someone will code it - it will get reviewed and released. If not - it will hang here forever 😄

Okay! Enough of this spam here!

**Comment by HitomiTenshi** [comment] 2018-07-30 08:18
@sarneeh Well my goal was to notify the creators/maintainers that this feature is still needed by some people. The last few comments were from January this year. If no one keeps requesting this, because they are "patient, waiting and counting on the community", then no one will know that there is a big demand for this 😉

**Comment by tanzislam** [comment] 2018-07-31 08:26
@HitomiTenshi You did notice my suggestion about available plugins, right? It's not like people can't use the functionality right now, and that (i.e. a workaround exists) makes this issue lower priority than many others.

If you want to indicate support, just upvote the opening post. If you have something contributory to the feature or use-case (e.g. asking about the probable points in code that needs extending, or suggest new workarounds) then by all means ask. If you have a draft/incomplete code change that you would like a second pair of eyes to review, please open a PR and mark it "work-in-progress".

This is how open-source works. Demanding new features time and again doesn't help at all, and slowly causes mental fatigue / burnout for the small number of developers who are working on it as side projects. In this case the developers are Microsoft, but the situation is the same: they (as a company) have many other issues and money-making projects to spend their resources on.

**Comment by drorata** [comment] 2018-08-10 07:30
@tanzislam are you still happy with [`hide-gitignored`](https://marketplace.visualstudio.com/items?itemName=npxms.hide-gitignored)?

**Comment by tanzislam** [comment] 2018-08-11 11:03
Yep, works very transparently as if it were built-in functionality.

**Comment by drorata** [comment] 2018-08-13 05:56
After installing `hide-gitignored` make sure you activate it; run `Hide Gitignored: Hide files ignored by .gitignore`.

**Comment by walles** [comment] 2018-08-13 10:01
`hide-gitignored` is OK as a workaround until this has been fixed for real, but it's not super.

It basically creates a `.vscode/settings.json` file that duplicates the `.gitignore` data in a `files.exclude` section.

If it could just do its thing without creating new files in my repo that would be preferable.

**Comment by drorata** [comment] 2018-08-13 18:16
@walles I would say it is a best practice not to track `.vscode` anyways, and thus this is, albeit not optimal, a fine solution.

**Comment by McWillie** [comment] 2018-08-14 08:50
I just wanted to add that I'd very much appreciate this as a built-in feature too.

**Comment by mgabeler-lee-6rs** [comment] 2018-08-25 00:51
>  Requested on Nov 21, 2017

Correction: March 7, 2016: https://github.com/Microsoft/vscode/issues/3764

Exacerbated by the fact that that issue was closed based on the implementation of a feature that did not make any attempt to address the issue as reported.

**Comment by mediabeastnz** [comment] 2018-09-17 20:36
A small feature but so important when working. Reduces noise and helps you focus on the task at hand.

Is this likely going to be core or plugin?

**Comment by ryancole** [comment] 2018-12-19 01:42
Surprised that core vscode deems the changing of the color of ignored files to be important enough to add as a core feature but not hiding them. Majority of people seem to want hiding to be core feature and not many seem to care about the useless dimming.

**Comment by walles** [comment] 2018-12-20 08:03
@FernandoMiguel I think this might depend on what you're editing.

In Python for example, all `.py` files (that you do want to edit) are accompanied by a binary `.pyc` file (that you don't want to edit), so when using VSCode for Python editing 50% of the files shown by VSCode are uneditable binaries.

And having 50% of the explorer tree contents being noise is unhelpful, even if the noise is dimmed, here's an example from [one of my favorite projects](https://github.com/walles/px):
![noise](https://user-images.githubusercontent.com/158201/50271718-d54ecd80-0435-11e9-850a-5e0e5b9cf4a2.png)

The signal-to-noise ratio in cases like these are (IMO) what this ticket is about.

**Comment by KelSolaar** [comment] 2019-01-16 07:46
@walles: Looking at your current explorer, it is actually way over 50%, most of the directories are too!

**Comment by rakkarage** [comment] 2019-02-24 23:55
it would also solve this:

![untitled](https://user-images.githubusercontent.com/962340/53307372-c2a5aa00-3865-11e9-9f03-31e749cb7144.png)

in many cases

**Comment by KrisSiegel** [comment] 2019-04-03 22:10
Is this something the VS team would be willing to merge if someone created a PR? This is a feature I've wanted to quite some time and it's frustrating most editors support this except for vs code.

I'd be willing to spend a little bit of time to make this happen but I don't want to bother if no one from the VS Code team has weighted in regarding accepting it or not.

**Comment by swain** [comment] 2019-04-04 10:39
Add a right-click-menu-item such as 'show/hide ignored files' should be perfect.

**Comment by pferreir** [comment] 2019-05-13 07:31
I think this would be very useful.

**Comment by NiGhMa** [comment] 2019-06-09 15:54
I upvote this too.

**Comment by include4eto** [comment] 2019-06-18 09:46
Take my upvote. Working with python *and* latex produces an ungodly mess.

**Comment by kobusvdm** [comment] 2019-07-04 18:23
> Take my upvote. Working with python _and_ latex produces an ungodly mess.
> 
> > Add a right-click-menu-item such as 'show/hide ignored files' at the explorer area should be perfect.
> 
> Or even a button next to `New File`.

Upvoted. This would be very useful. 

Other, far less sophisticated editors have had this feature for ages. Even "yet another .dotfile" with settings / glob patterns for hiding files would avoid affecting vscode globally, and still allow hidden files on a per project basis.

**Comment by iansan5653** [comment] 2019-07-30 14:38
@kobusvdm 

> Even "yet another .dotfile" with settings / glob patterns for hiding files would avoid affecting vscode globally, and still allow hidden files on a per project basis. 

This is actually already possible. Create a `.vscode` subfolder in your project directory and add a `settings.json` file with the following content:
```json
{
  "files.exclude": [/* Your patterns here */]
}
```

**Comment by lackovic** [comment] 2019-10-10 11:09
> Add a right-click-menu-item such as 'show/hide ignored files' at the explorer area should be perfect.

VsCode has a cog icon in the _files to exclude_ search bar to show/hide from search results files in `files.exclude` and `.gitignore`:

![2019-10-10 13 54 50](https://user-images.githubusercontent.com/1663053/66563090-b0af1800-eb65-11e9-8885-cf6ebbed32f4.png)

Would be nice to have the same option in the Explorer, perhaps here in the folder toolbar:

![2019-10-10 14 06 44](https://user-images.githubusercontent.com/1663053/66563900-7181c680-eb67-11e9-86f5-47df06c1500c.png)

**Comment by cloudrex** [comment] 2019-10-21 22:10
Any updates on this?

**Comment by mheskol** [comment] 2019-10-25 14:50
There seems to be an extension that can hide ignored files. It can be accessed from here: https://marketplace.visualstudio.com/items?itemName=npxms.hide-gitignored

**Comment by cloudrex** [comment] 2019-10-25 16:41
> There seems to be an extension that can hide ignored files. It can be accessed from here: https://marketplace.visualstudio.com/items?itemName=npxms.hide-gitignored

@mheskol I think this should be a built-in option than having to rely on a third-party extension.

**Comment by mheskol** [comment] 2019-10-26 11:21
Agreed. It feels more basic than many existing functionality actually but I wanted to share that in the mean time as an interim solution. I wish this gets integrated soon but we don't know how long until this happens.

**Comment by singh44ashutosh** [comment] 2019-12-27 03:08
In my opinion, we don't need any third-party extension. We can just use VS Code settings.
Go to settings and search for files:exclude and define your patterns.
Ex: For C#, I have defined patterns to exclude bin and obj folder and subfolders.

![image](https://user-images.githubusercontent.com/32385467/71498858-1ae17a00-2884-11ea-93be-0076fc22c52c.png)

**Comment by tanzislam** [comment] 2019-12-27 05:27
@singh44ashutosh Yes, we don't *need* any extension and *can* (i.e. are able to) use VS Code settings. This isn't about whether it is _possible_ to do as such, but that it is **difficult** to maintain that way. (We are effectively repeating/copying the information already present in the `.gitignore` files into the VSCode Settings, and that goes against the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).)

**Comment by cloudrex** [comment] 2019-12-27 21:50
So, JetBrain's IDEs have this feature which allows you to select exactly which files you want to see. I think something similar would cover hiding `.gitignore` files and additionally other visibility contextes.

![image](https://user-images.githubusercontent.com/41349879/71533822-fb207500-28c8-11ea-9294-44af9ab2233c.png)

**Comment by rtubio** [comment] 2020-02-23 03:55
> @singh44ashutosh Yes, we don't _need_ any extension and _can_ (i.e. are able to) use VS Code settings. This isn't about whether it is _possible_ to do as such, but that it is **difficult** to maintain that way. (We are effectively repeating/copying the information already present in the `.gitignore` files into the VSCode Settings, and that goes against the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).)

I do not think this goes against DRY at all, this is actually part of automating tasks that otherwise would have to be done manually. Right now, users will have to manually update the contents of the configuration files for VS Code, anytime the .gitignore file is updated. Not implementing this feature, makes VS Code less automated with respect to other IDE environments like Atom.

**Comment by tanzislam** [comment] 2020-02-23 04:00
@rtubio Yes, the manual workflow is what is against DRY (and is possible but difficult). :slightly_smiling_face:

**Comment by inca** [comment] 2020-03-11 09:48
Whilst I appreciate the issue is valid and exists, here's a slightly different perspective to the whole story.

I have directories like `node_modules` or all sorts of `out` and `dist` which I never want to see in tree view (they are not sources after all). But also I have files like `.env` which _are_ sources — but it's [recommended](https://www.npmjs.com/package/dotenv#should-i-commit-my-env-file) to exclude them from version control. I still want to retain my `.env`s because I edit them by hand every once in a while. Same applies to some other patterns we've adopted (like decrypted plaintext secrets which we never commit, but would like to be able to edit).

For the reasons above, keeping `.vscode` under VCS and specifying what me (and my team) don't usually want to see in the tree works fine with me. Is there any disadvantage to this approach aside from partially duplicating `.gitignore`?

(Also, wanted to add that partially duplicating ignored files is not a new issue: we have `.eslintignore`, `.npmignore`, `.Dockerignore` — and all have stuff in common, but occasionally differ slightly for obvious reasons.)

**Comment by iansan5653** [comment] 2020-03-11 13:52
I really think what @cloudrex commented is the ideal solution. I'd like to see a dropdown in the title bar of the file explorer pane with checkboxes. You could have these options:

**Hide files using:**

- VSCode settings
- .gitignore

Theoretically it might be possible to allow hiding based on *any* `.*ignore` file, but I don't know how useful that would really be.

**Comment by forrestthewoods** [comment] 2020-04-28 01:07
I have a workspace with over 200 sub-projects and many dozens of gitignore files. It's absurd and highly error prone to replicate every single gitignore into the `.code-workspace` file.

Can we re-open this feature request? There is clear demand and clear value.

**Comment by Bessonov** [comment] 2020-04-28 18:40
> Can we re-open this feature request?

Short answer - no. Because it isn't even closed ;)

**Comment by forrestthewoods** [comment] 2020-04-28 23:41
> Short answer - no. Because it isn't even closed ;)

The big red "closed" box above my post confused me. I am not a clever man. :(

Anyhow, I would very much like this feature. It would be a significant improvement to my quality of life. :)

**Comment by aaronadamsCA** [comment] 2020-06-04 16:08
As soon as you've worked in a monorepo you understand how helpful this feature would be. The visual clutter throughout each package directory is a significant distraction.

I'll also (shamelessly) note #98591 which is to give dotfiles similar treatment; they only add to the clutter. In the end I'd like both things together: a handy toggle to show/hide ignored files + dotfiles, since 99% of the time I'm not touching either.

**Comment by HitomiTenshi** [comment] 2020-06-04 17:03
@aaronadamsCA Aren't those dotfiles already part of your VCS ignore file, e. g. `.gitignore`? Having all these hide options might add too much clutter in the UI.

I find the ideas of @iansan5653 and @cloudrex to be the optimal solution, with a focus on adding a "hide VCS ignored files" option first, before doing even more fancier stuff.

**Comment by aaronadamsCA** [comment] 2020-06-04 17:33
@HitomiTenshi No, these hidden files (dotfiles) are generally part of the repository.

Take [microsoft/vscode](https://github.com/microsoft/vscode) as an example. The root directory has 30 entries; 11 are hidden files/directories. Many repositories have a similar quantity of hidden files/directories in the root, and monorepos often have them in multiple package directories as well.

Given these files/directories start with a dot _so that they can be hidden_, it makes perfect sense for VSCode to offer support for its explorer to hide hidden files.

**Comment by Viech** [comment] 2020-07-12 13:15
The Hide Gitignored extension is not just hacky in that it adds a redunant list of files to ignore to a settings file but also it [does not currently work well on workspaces](https://github.com/npx/vscode-hide-gitignored/issues/4), as I understand it [due to a limitation of files.exclude](https://github.com/microsoft/vscode/issues/70438).

I'm just stating this to stress the relevance of this issue: There seems to be no satisfying workaround at the moment.

**Comment by thealjey** [comment] 2020-08-26 09:18
I for one think that it's a bad idea.
At least the option should be off by default.

**Comment by bobpaw** [comment] 2020-08-29 21:21
Not to act like they're the same, but Visual Studio Community has had this feature for ages.

**Comment by bersbersbers** [comment] 2020-09-25 10:32
> I for one think that it's a bad idea.
> At least the option should be off by default.

Seconding this with an example: in a LaTeX project, you may want to `.gitignore` the build log files, but you still need to open them from time to time to investigate build errors. The files are already hidden from "Search files by name" (which I don't like either), but also hiding them from Explorer by default would make them *very* hard to find for beginners.

**Comment by Viech** [comment] 2020-09-26 08:55
It's still a feature that a lot of people would like to the point where they actively look for plugins and suitable workarounds. Having it default to _off_ should make everyone happy. (And if you decide to use it you can still `Ctrl+O` which is a well-known key combination to open a particular file.)

**Comment by e200** [comment] 2021-02-12 13:59
We need this!

**Comment by wires** [comment] 2021-02-13 21:31
This request is more than 5 years old! 🥳 (#78)

**Comment by AbdullahSaei** [comment] 2021-02-15 02:48
+1

**Comment by Milo123459** [comment] 2021-03-29 11:45
I've started working on it. First time contributing so it's taking me a little bit of time to pick up the pace and get used to it. I'm attempting to figure out how `files.exclude` works as of now so I can use the features used under the hood in this. Wish me luck!

**Comment by Milo123459** [comment] 2021-04-11 20:15
Sadly (from my understanding) this is impossible to do as of now. There is no API to hide files so I can't do this. Very sad.

**Comment by Milo123459** [comment] 2021-04-12 09:15
^^ as soon as it comes out, I'll add it. I'm subscribed to a thread about it

**Comment by CharlesParent** [comment] 2021-04-28 10:11
+1

**Comment by themotu** [comment] 2021-06-25 05:18
https://marketplace.visualstudio.com/items?itemName=npxms.hide-gitignored

**Comment by Milo123459** [comment] 2021-06-25 08:58
On that extension, whilst it does indeed work, if you want to hide other files that aren't in the gitignore, it will override and won't work. An internal implementation would be better, as it wouldn't override the physical `.vscode/settings.json` like this extension does. I am once more looking into implementing this, but there still is no API for hiding files. I am speaking to people on the team to hopefully get an API implemented.

This will be a challenge, but, maybe it'll be out by the end of the year? 😆

**Comment by Milo123459** [comment] 2021-06-28 19:01
CC @isidorn 

Any idea on when the ability to hide files in the explorer is going to have an API?

**Comment by Milo123459** [comment] 2021-09-22 19:14
@JacksonKearl sorry for the ping, but is there any more information? I really, *really* want to implement this. It just needs something like a hide file/folder from the explorer API.

**Comment by JacksonKearl** [comment] 2021-09-23 17:58
We will likely not be exposing API for extensions to control explorer item visibility. I would consider a *small* PR to add this to core, but I am not at this point willing to take on too much extra maintenance burden to just mirror the behavior of our existing setting. 

I recently implemented [`.gitignore`-aware file walking in Core](https://github.com/microsoft/vscode/blob/2358283d76a0afdf57e60ec2fc76a57b1b0146c7/src/vs/workbench/services/search/common/ignoreFile.ts#L17), this would be helpful to look at for anyone trying to implement this.

**Comment by MrNossiom** [comment] 2021-11-14 12:05
@JacksonKearl so a pull request for this would be accepted ?

**Comment by Milo123459** [comment] 2021-11-14 12:06
> @JacksonKearl so a pull request for this would be accepted ?

It would, yes, but good luck. There is no API documentation for hiding files, nor an actual API for it. I have tried various times and, well, no luck.

**Comment by MrNossiom** [comment] 2021-11-14 12:10
Hey @Milo123459, If you did some research, do you know how the `files.exclude` property works ?

**Comment by Milo123459** [comment] 2021-11-14 12:11
Yes, I have done some research, it's rather complex. And no, I don't know where it is defined.
P.S: Why the confused reaction?

**Comment by MrNossiom** [comment] 2021-11-14 14:13
Well, I used it as a sad emoji…

**Comment by MrNossiom** [comment] 2021-11-14 16:39
@Milo123459, Did you try to register a new kind of `ITreeFilter` in the `explorerView.ts`:

https://github.com/microsoft/vscode/blob/ca58cb12bc0ddc525dea35bce886fdf6aa4c8662/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L368-L371

This snippet register the `FilesFilter` class that take care of hiding `files.exclude` defined files:
https://github.com/microsoft/vscode/blob/ca58cb12bc0ddc525dea35bce886fdf6aa4c8662/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L536-L540

**Comment by Milo123459** [comment] 2021-11-14 16:40
Ya, I did try. I gave up though. It's all yours to tackle.

**Comment by MrNossiom** [comment] 2021-11-14 16:42
Do you have a rest of some code you wrote ?

**Comment by Milo123459** [comment] 2021-11-14 16:46
No, I don't, sorry.

**Comment by MrNossiom** [comment] 2021-11-14 16:47
Thanks

**Comment by MrNossiom** [comment] 2021-11-16 18:46
So, after just a bit of research, I think there are 2 ways of implementing this:
- Implement a flag that controls `vscode-ripgrep` in the explorer directly. (Directly built-in)
- Implement a file filter that reads `gitignore ` files and filters them. `ITreeFilter` (more power cost and space if we used a lib for that)

Obviously, there is a better solution… 👀 
Tell me what you think about that.

I continue my researches for the first option.

**Comment by Milo123459** [comment] 2021-11-16 18:47
First one is just better..

Less resources used, probably faster and easier to implement. Go with the 1st one.

**Comment by MrNossiom** [comment] 2021-11-29 20:34
Research update: just using the `vscode-ripgrep` flag wouldn't be possible.
A comment before `FilesFilter` describe the problem.

https://github.com/microsoft/vscode/blob/ca58cb12bc0ddc525dea35bce886fdf6aa4c8662/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L536-L540

We want to be able to show the file in the explorer when actively opened in the editor…

Does some have an idea, or should we go with another option ?

**Comment by MrNossiom** [comment] 2021-12-21 13:07
Opinion update: use the `vscode-ripgrep` flag and let the file hidden in the explorer. Although it is cool to know where is the file you're currently looking at is located, it isn't very useful, and you should know what file you opened through CLI or filename. Also, it is an opt-in flag, so it shouldn't break non-aware users experiences.

Tell me if it could be an option...

**Comment by MrNossiom** [comment] 2021-12-23 14:31
Research update: the `disregardIgnoreFiles` property activate the `--no-ignore` `ripgrep` flag we don't want.
https://github.com/microsoft/vscode/blob/419d62aa0be0fef68ece557042c3fd5505861fe6/src/vs/workbench/services/search/node/ripgrepFileSearch.ts#L58-L63

This flag is triggered in many places (just search `disregardIgnoreFiles` in the repo).

Like there:
https://github.com/microsoft/vscode/blob/419d62aa0be0fef68ece557042c3fd5505861fe6/src/vs/workbench/api/browser/mainThreadWorkspace.ts#L146-L156
Or there:
https://github.com/microsoft/vscode/blob/419d62aa0be0fef68ece557042c3fd5505861fe6/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L498-L503

---

I don't know how to access user configuration yet, but maybe vary the value according to a certain flag.
I think this would be the right place to implement such a thing, but I'm surely wrong…

If an experimented contributor could guide me, I would be really grateful. 👍🏻

**Comment by zmaktouf** [comment] 2022-03-30 03:44
Any news on this one ?

**Comment by MrNossiom** [comment] 2022-05-08 21:15
The new file nesting feature on the new `v1.67.0` VS Code make this request less interesting. This new feature kind of replaces this request. I do still something that some people would like to see this added. And the issue is part of the iteration plan of May 2022.
My question is: do we still need this feature, I don't know if this still relevant… ❓

**Comment by flisboac** [comment] 2022-05-08 21:52
@MrNossiom How exactly does this new functionality deprecates this issue? For me, they're different things entirely (please do correct me if I'm wrong).

Personally, I still think there's a lot of value in hiding files based on gitignore configuration, as long as it's an opt-in feature. Given the ubiquity of git as a VCS, and the native support VSCode offers for it, it's only natural to have the option to hide those files in your project folder. This is especially desirable for projects usig tools that insist on littering your source folders with temporary/transient files, with no recourse for alternative behaviour (e.g. Python, any TeX-based tool, etc).

**Comment by MrNossiom** [comment] 2022-05-09 20:57
@flisboac This was actually my question. I do think that they are different features, but not entirely. Removing temporary files from the explorer view would be useful for a clearer list, but `.gitignore` files also contains things we do want to see. Also, as far as I've seen, this seems to be quite messy to implement. But maybe the core team will find out, as this is part of the iteration plan.

**Comment by flisboac** [comment] 2022-05-09 23:10
@MrNossiom I noticed how you repurposed your previous message to ask for people to thumb up or down for approval of a question that was not asked, or at least not clear, in previous versions.

It went from: "This requested feature is too similar to feature X, should we close this issue?" (I thumbed down, I don't think we should close the issue, there's more to discuss.)

To: "do we still need this requested feature, given feature X?" ( I don't know feature X enough to affirm anything, so the prudent thing should be not to interact; but my thumb down based on the previous edit remained! I rushed to remove it.)

Wouldn't it have been better to make a new message?

**Comment by flisboac** [comment] 2022-05-09 23:10
@MrNossiom 

> Removing temporary files from the explorer view would be useful for a clearer list, but .gitignore files also contains things we do want to see.

That's why I think it's important that this is implemented as an opt-in feature. Not every project is the same, so giving this option prevents a lot of work configuring not only your gitignore, but vscode settings as well. In this case, specifically, the developer knows better.

Another idea: a companion setting could also be provided to add specific exceptions, which would be applied only when gitignore is used to hide files. For example:

- `files.exclude.gitignore.enabled` (`bool`): activates auto-exclusion of files in gitignores. Respects gitignore files per folder. Default: `false`.
- `files.exclude.gitignore.exceptions` (`Array<string>`): shows any files matching the globs in this list, regardless of whether the file is also a match wrt. some gitignore file. Only applies to gitignore-based file selection. Default: `[]`.

All of that being said... Reading the issue's history again, I see that implementing any part of this feature, in any capacity, will be quite difficult. I also cannot find the time right now to study the codebase or contribute with a PR. But I hope someone can make advances on this; I really think this feature makes sense, and should be provided by vscode itself.

In any case, thank you for your contributions!

**Closed** 2022-05-20 20:24 UTC
Labels: feature-request, file-explorer

**Comment by lramos15** [comment] 2022-05-25 14:38
This is now in insiders please feel free to give a test via `files.excludeGitIgnore`. I'll lock this issue to help drive feedback and bugs to new issues as this is just tracking the feature request. Thank you everyone for your patience and I'm excited for us to finally be shipping this feature!
