### ISSUE TITLE
Allow for choosing which grammar syntax highlighting you want

### ISSUE THREAD

**Issue by eliaswood** [microsoft/vscode#205383] opened 2024-02-16 16:53 UTC
Is your feature request related to a problem? Please describe.
Upon the Jan 2024 release, the grammar syntax highlighting has changed for go, as seen [here](https://code.visualstudio.com/updates/v1_86#_languages:~:text=New%20Go%20grammar,the%20previous%20grammar). For the theme I use this ends up looking horrible and I really enjoyed the way it looked before. If there is already a way to do this please let me know.

Describe the solution you'd like
I would like to be able to choose which syntax grammar highlighting is used.

Describe alternatives you've considered
The only known work around I have found is to downgrade to the Nov 2023 version. However, this does not allow me to use copilot chat and some other features.

Additional context
This is how it looked before 
![image](https://github.com/microsoft/vscode/assets/30331021/e9ce115e-a2da-4d96-bd8f-9b3e5cc018f4)

This is how it looks now 
![image](https://github.com/microsoft/vscode/assets/30331021/1fa37073-a37a-44de-8238-399f200a1200)

**Comment by RedCMD** [comment] 2024-02-16 17:26
does installing the old extension not work? 
https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-go-syntax
it may have a `languageId` conflict
which you might be able to fix by disabling the `@builtin` go extension

**Comment by eliaswood** [comment] 2024-02-16 18:09
Oh nice! yeah that worked thank you!

**Comment by aiday-mar** [comment] 2024-02-19 08:31
Hi @eliaswood it appears the issue is resolved. Thank you @RedCMD. I will close this issue.

**Closed by aiday-mar** 2024-02-19 08:31 UTC
Labels: triage-needed
