### ISSUE TITLE
Emojis characters Problem in VS Code on Windows 7

### ISSUE THREAD

**Issue by saeedhei** [microsoft/vscode#38259] opened 2017-11-13 22:39 UTC
I Downloaded latest version of VS Code (stable + insiders), But VS code does not show emojis characters correct and in color.
![vscodeeee](https://user-images.githubusercontent.com/25050762/32753048-a74cd530-c8e0-11e7-97ef-e4c02c942e09.jpg)
Video: 🎞

**VS Code Insider version is:** 1.19
**VS Code version is:** 1.18
Windows 7

**Comment by alexandrudima** [comment] 2017-11-14 08:44
Interestingly, this is what I get on Windows 10:
![image](https://user-images.githubusercontent.com/5047891/32770552-60eee7d2-c920-11e7-8522-745b79d45d41.png)

All font rendering is done by Chromium. Does the emoji render correctly for you when opening this webpage via Chrome ?

**Comment by saeedhei** [comment] 2017-11-14 12:27
emojis is ok in my all browsers ( Chrome and firefox), but is not ok in vscode.

**Comment by alexandrudima** [comment] 2017-11-14 16:54
@saeedhei Do you have any specific customizations such as font family ?

Does the emoji get rendered when copying and pasting it somewhere else in our UI such as the Search Viewlet or the terminal?

**Comment by saeedhei** [comment] 2017-11-14 17:23
No, I removed All VS Code and then I installed 2 new versions.
after That I copy and pasted video emoji from emojipedia:
(https://emojipedia.org/film-frames/)
My output in node.js:
![aaaaa](https://user-images.githubusercontent.com/25050762/32794369-e5cd3604-c97d-11e7-852c-c2f316501106.jpg)

**Comment by jliu666** [comment] 2017-12-14 05:01
I meet this problem, too. Emojis' shape is right but they are not colorful. So ugly. :smile: :smile: :smile:

**Comment by usernamehw** [comment] 2017-12-29 01:11
I've seen somewhere a workaround to make them colorful again (not sure if it applicable to this specific issue). Add `'Segoe UI Emoji'` to the end of `editor.fontFamily`:
```json
"editor.fontFamily": "Consolas, 'Courier New', monospace, 'Segoe UI Emoji'",
```

**Comment by alexandrudima** [comment] 2019-10-09 09:54
Duplicate of #32840

**Closed by alexandrudima** 2019-10-09 09:54 UTC
Labels: font-rendering, upstream, windows
