### ISSUE TITLE
Editor stops rendering text when main window is very wide

### ISSUE THREAD

**Issue by mswf** [Microsoft/vscode#56312] opened 2018-08-14 07:36 UTC
Issue Type: <b>Bug</b>

At work I have 2 high resolution monitors (2560x1440), I usually stretch VS Code horizontally across them both. After updating (from 1.25), text stops rendering under these specific conditions:
1) Stretch my window across my 2 screens
2) Add 4 (or more columns)
The text in the main editors will stop rendering (note, in this example I did paste some placeholder text inside off all the editors):
![vs_wide](https://user-images.githubusercontent.com/9058358/44077833-2333999a-9fa5-11e8-9f09-005e1048ceb0.PNG)
3) Making any individual column larger, will make text inside of it render again:
![vs_fixed](https://user-images.githubusercontent.com/9058358/44077836-26a6ff54-9fa5-11e8-9c74-992954bf799a.PNG)

I have tried stretching VS Code vertically across my other monitors, but no similar issue appeared then.
EDIT:
I did just reproduce the same issue by stretching my window wide, opening just 2 columns and then stretching one out to over ~75% of the window. Then the smaller window also just stops rendering text.

I have reproduced this issue on a clean install of VS Insiders I just installed too:
<details><summary>1.27.0-insider log</summary>Commit: 8727085fff33bf7d8f5e27483b10f72508d4167a
Date: 2018-08-14T05:18:11.938Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
</details>

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (24.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
Lua|key|0.0.9
vscode-todo-parser|min|1.9.1
theme-monokai-pro-vscode|mon|1.1.8
cpptools|ms-|0.17.7
vscode-lua|tri|0.12.4
</details>

**Comment by bpasero** [comment] 2018-08-15 15:01
Duplicate of https://github.com/Microsoft/vscode/issues/51576

**Closed by bpasero** 2018-08-15 15:01 UTC
