### ISSUE TITLE
unable to click open files without a path on terminal

### ISSUE THREAD

**Issue by ssbarnea** [Microsoft/vscode#64511] opened 2018-12-06 11:25 UTC
- VSCode Version: 1.29.1
- OS Version: MacOS 10.14.1

Steps to Reproduce:

Run a linter in terminal in order to get an output like:
```
scripts/compare-reviews.py:64:1: H405: multi line docstring summary not separated with an empty line
testenv-client:68:80: E501 line too long (100 > 79 characters)
```

You will findout that vscode allows you to cmd-click the first link that also contains a path and edit the file at the right line and column but it will not allow you to do the same with the second line where the file happens to be on the root project directory.

I suspect this is caused by a bad regex used to identify the `file:line:column` pattern.

Seems to be related to bugs below but not a duplicate of those:
* https://github.com/Microsoft/vscode/issues/22772 
* https://github.com/Microsoft/vscode/issues/41979.

**Comment by Tyriar** [comment] 2018-12-06 19:15
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/22772 to me since testenv-client doesn't have a path separator.

**Closed by Tyriar** 2018-12-06 19:15 UTC
Labels: integrated-terminal
