### ISSUE TITLE
VSCode: Not responding overnight on Linux

### ISSUE THREAD

**Issue by ragebiswas** [Microsoft/vscode#6952] opened 2016-05-27 05:34 UTC
- VSCode Version: 1.1.1
- OS Version:RHEL 7 (kernel 3.10.0)

Steps to Reproduce:

1. Open a repository and keep a JS file open overnight
2. Next morning you'll get the "Not responding, Reopen" message

Clicking reopen doesn't help. I actually have to shut down and restart again. This is the VSCode Linux version - to be clear.

**Comment by Tyriar** [comment] 2016-05-27 05:37
Duplicate of https://github.com/Microsoft/vscode/issues/508

**Closed by Tyriar** 2016-05-27 05:37 UTC
