### ISSUE TITLE
Syntax Highlighting Error for String Literal

### ISSUE THREAD

**Issue by curtw** [Microsoft/vscode#4097] opened 2016-03-14 00:27 UTC
Code Version 0.10.10 (0.10.10)
OS X 10.10.5

In the following code, syntax highlighting for the string literal on line 5 is wrong.
```
var key = 'hello';
var val = 'world';
var arr = [];
for(var i=0; i<5; i++) {
	arr.push(key + ':' + val);
}
```
![screen shot 2016-03-13 at 5 15 25 pm](https://cloud.githubusercontent.com/assets/653448/13732429/d488b44c-e93f-11e5-8566-e9b6c308c5d5.png)

**Comment by pokakhoaitay** [comment] 2016-03-14 08:19
Did you try `Shift+Alt+F`? I don't know why but the syntax highlighting will be correct if you try reformat your code.

**Comment by aeschli** [comment] 2016-03-14 20:16
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-03-14 20:16 UTC
