### ISSUE TITLE
.ipynb cell "View as scrollable element" broken

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#190672] opened 2023-08-17 13:51 UTC
Type: <b>Bug</b>

Create a fresh .ipynb

Run something that'll generate too much output, e.g. `! pip install pytorch` (which will fail as the correct command is `pip install torch`)

You'll see the first screenshot that I'll attach.
There's a `...` in the output to indicate content has been clipped, and there's a "View as scrollable element" text underneath.

If I click that, nothing happens. It WAS working a few weeks back, but now it isn't.

If I go into settings (by clicking final hyperlink) and check "Notebook -> Output: Scrolling" (second screenshot), then reload the notebook, I get scrolling output windows.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id ffe7017d-9a68-4026-a96e-3eb92191e23c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
gitignore|cod|0.9.0
vscode-office|cwe|3.1.6
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|14.2.1
c-cpp-runner|fra|8.1.0
copilot|Git|1.103.338
vscode-pull-request-github|Git|0.70.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.3
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
swift-lang|ssw|1.4.0
cmake|twx|0.0.17
vscode-lldb|vad|1.9.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by p-i-** [comment] 2023-08-17 13:52
![Screenshot 2023-08-17 at 14 42 47](https://github.com/microsoft/vscode/assets/693495/df171e14-d224-42ed-9e89-75dde1595cdd)

**Comment by p-i-** [comment] 2023-08-17 13:52
![Screenshot 2023-08-17 at 14 43 35](https://github.com/microsoft/vscode/assets/693495/8abd4b0d-1799-4d83-a413-b5cd75cf3f27)

**Comment by jnns** [comment] 2023-08-18 09:27
Duplicate of https://github.com/microsoft/vscode/issues/189699

**Closed** 2023-08-22 19:06 UTC
