### ISSUE TITLE
"Go to Definition" to wrong file

### ISSUE THREAD

**Issue by Onfealive** [Microsoft/vscode#42592] opened 2018-01-31 03:08 UTC
- VSCode Version: 1.19.3 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
- OS Version: Windows 10 Pro 10.0.16299 N/A Build 16299

Condition:
1. 2 files with same functions, different some functions
2. Open 2 files at the same times

Steps to Reproduce:
1. Right-click and select "Go To Definition" in the 2nd file.
2. It goes to the 1st file's.
Other (following image attached)
1. Right-click and select "Go To Definition" in the 2nd file at the line "function execSearch()"
2. It goes to the 1st files's "function execSearch()"

If I switch the order of these files, then Restart, it still like above. The second's always link to the first one's.

Does this issue occur when all extensions are disabled?: Yes

![definition-problem](https://user-images.githubusercontent.com/18258131/35603071-125ef22a-066e-11e8-8949-1edbc1b05dd4.gif)

**Comment by mjbvz** [comment] 2018-02-02 19:37
Please provide a small, self contained code example or sample project

**Comment by Onfealive** [comment] 2018-02-03 10:49
I hope can you can Reproduce this bug with: [bug-folder.zip](https://github.com/Microsoft/vscode/files/1691640/bug-folder.zip)

1. Open it as the folder.
2. Open file `main1.js` (doubel-click), and scroll the end.
3. Then open file `main2.js` (double-click), and scroll the end.
4. Back to `main1.js`, at the function `second1`, right-click in `first1` and choose 'Go To Definition'
5. It will go to `first1` of `main2.js`.

**Comment by mjbvz** [comment] 2018-02-07 07:31
Thanks @Onfealive!

Looks like you are running into this issue: https://github.com/Microsoft/TypeScript/issues/14279 By default, we treat all non-module js files as part of the global scope. This makes sense for the browser world where this model is more-or-less accurate, but it can also cause unexpected behavior like this.

My proposal upstream was to create a flag that would force each js file to be treated as a separate module, however we have not seen enough reports of the issue to prioritize implementing this yet. Please leave a comment on the upstream typescript issue if you feel strongly about this issue. Possible workarounds are wrapping your code in self-executing functions (which also prevents them from leaking globals at runtime) or making your files a module by using `import` or `export` somewhere in the file

Closing as upstream

**Closed by mjbvz** 2018-02-07 07:31 UTC
Labels: javascript, needs more info
