### ISSUE TITLE
Find/Search In Open Files

### ISSUE THREAD

**Issue by zensr** [Microsoft/vscode#44028] opened 2018-02-20 10:51 UTC
Performing a search only on the files/tabs that are open in the current window.

A directory search isn't always practical when working on large projects as I open various files from various directories and frequently need to run a search query across them all. 

This is easy in Sublime Text and is incredibly helpful/time-saving, however I've moved to VSC now and, after searching the net and VSC extensions, can't find a way to do this.

**Comment by roblourens** [comment] 2018-02-28 09:14
/duplicate of https://github.com/Microsoft/vscode/issues/20530

**Closed** 2018-02-28 09:14 UTC
Labels: *duplicate, feature-request
