### ISSUE TITLE
Be able to change Enhanced Scrollbar warning and errors colors 

### ISSUE THREAD

**Issue by juanlongo** [Microsoft/vscode#31224] opened 2017-07-21 20:08 UTC
I can change the color of the warnings and errors in the editor but I can't change the colors in the Enhanced Scrollbar

Example: In this example I managed to change the green color of the warning to yellow but the scrollbar still marks the warning in green

![screen shot 2017-07-21 at 4 41 37 pm](https://user-images.githubusercontent.com/23357873/28479623-9bde2b7a-6e33-11e7-8b23-38fb6fd986c8.png)

I thought that de "editorMarkerNavigationWarning" was what I was looking for, but it doesn't work

![screen shot 2017-07-21 at 4 47 59 pm](https://user-images.githubusercontent.com/23357873/28479880-b9fcf612-6e34-11e7-8b98-6c0f2b6e99c9.png)

I read the entire color page and I found nothing to change Scrollbar warnings and errors colors. https://code.visualstudio.com/docs/getstarted/theme-color-reference#_extensions

- VSCode Version: 1.14
- OS Version: 10.12.6

**Comment by agustinlg** [comment] 2017-08-01 12:36
+1 on this one 👍

**Comment by aeschli** [comment] 2017-08-02 14:16
duplicate of #26606

**Closed by aeschli** 2017-08-02 14:16 UTC
