### ISSUE TITLE
Writing text between html tags in React JSX is suggested as emmet

### ISSUE THREAD

**Issue by Maaz0313** [microsoft/vscode#223954] opened 2024-07-26 18:53 UTC
Type: <b>Bug</b>

1. Create a React component in a JSX file.
2. Write HTML tags, and try to write some text b/w them. VS Code will suggest them as Emmet abbreviation.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.61GB free)|
|Process Argv|--crash-reporter-id 9aca98c2-b5db-464e-a26a-6665af47c183|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.6
vscode-tailwindcss|bra|0.12.5
laravel-goto-view|cod|1.3.11
composer-php-vscode|DEV|1.49.15728
phptools-vscode|DEV|1.49.15728
es7-react-js-snippets|dsz|4.4.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.92.0
laravel-create-view|gli|0.0.6
headwind|hey|1.7.0
jsx-format|Ica|0.0.2
php-namespace-resolver|Meh|1.1.9
goto-laravel-components|MrC|1.0.2
live-server|ms-|0.4.14
laravel-blade|one|1.36.1
material-icon-theme|PKi|5.8.0
vscode-blade-formatter|shu|0.24.2
cody-ai|sou|1.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31101459
ccplt:31103426
pythonrstrctxt:31103193

```

</details>

```[tasklist]
### Tasks
```

**Comment by rzhao271** [comment] 2024-07-26 20:13
Thanks for the steps! I'll consider this issue a duplicate of #51537, but it's a good test case.

**Closed by rzhao271** 2024-07-26 20:13 UTC
