### ISSUE TITLE
Completion of staging a file removes keyboard focus from the message box

### ISSUE THREAD

**Issue by grantborthwick** [microsoft/vscode#92401] opened 2020-03-10 21:21 UTC
Issue Type: <b>Bug</b>

1. Open a folder with a git repo
2. Make a change to a file
3. Click the stage button next to the item in the source control sidebar
4. While the file is being staged, click in the message box
5. Start typing a commit message
6. When the file is successfully staged, subsequent letters that you type will be shown in the search box for the source control instance.
![image](https://user-images.githubusercontent.com/2301725/76360553-7398ae80-62da-11ea-9216-8df8a8a6c50e.png)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (37.36GB free)|
|Process Argv|--file-uri file:///f%3A/src/oc/CallingSDK/CallingSDK.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
vscode-less|mrm|0.6.3
azure-pipelines|ms-|1.165.1
vscode-cosmosdb|ms-|0.12.1
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
powershell|ms-|2020.3.0
vsliveshare|ms-|1.0.1711
team|ms-|1.161.0
vscode-hexdump|sle|1.7.2
jstool|sun|1.2001.1
vscodeintellicode|Vis|1.2.6

</details>

**Comment by Agalin** [comment] 2020-03-19 07:49
#92946 is a duplicate of this one.

Extremely irritating. It moves focus not only from the message box but globally from the app (tested with typing into integrated terminal and editing an open file). It slows the version management a lot, staging files can be slow as it is, needing to wait for an async operation to finish makes it even worse.

**Comment by Dan503** [comment] 2020-03-22 23:44
Note that this is a regression of this closed issue: https://github.com/Microsoft/vscode/issues/8911

**Comment by iansan5653** [comment] 2020-03-25 13:30
Copying here from the duplicate issue: 

> 
> 
> Version: 1.44.0-insider (system setup)
> Commit: [708b019](https://github.com/microsoft/vscode/commit/708b019bb4e20f07cf89df9f1d943af3d38d7a70)
> Date: 2020-03-18T06:30:46.175Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
> 
> Steps to Reproduce:
> 
>     1. Open a Git repository in VSCode and make some changes
> 
>     2. Focus on the commit message box in the Source Control view
> 
>     3. Click on the "+" next to a file
> 
>     4. Focus is moved to the file tree, which means that typing will now start filtering the tree
> 
> 
> This is not the behavior when clicking the "+" to the right of Changes to stage all files. This may initially seem like the desired behavior, however it's very frustrating when you start typing a message, add a file, and keep typing - suddenly you aren't typing in the box you thought you were.

**Comment by arielkuzminski** [comment] 2020-03-26 15:40
![2020-03-26_16-37-53](https://user-images.githubusercontent.com/20773060/77665895-8e2c8200-6f80-11ea-9257-29d6f6a8e103.gif)
Fix it asap please.

**Closed** 2020-04-01 12:30 UTC
Labels: bug, scm
