### ISSUE TITLE
There is no possibility to copy the text from the description to the plugins.

### ISSUE THREAD

**Issue by evilpython** [Microsoft/vscode#73088] opened 2019-04-30 15:18 UTC
- VSCode Version: Update 1.33.1:
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. Into the plugin description
2. Try to copy something from there.
3. Copying does not work

In the program itself and the document body, copying works fine.

Does this issue occur when all extensions are disabled?: **No**

**Comment by gjsjohnmurray** [comment] 2019-04-30 16:08
Similar to #65310. @evilpython are you able to copy text using keyboard shortcuts (e.g. Cmd+C)?

**Comment by evilpython** [comment] 2019-04-30 16:14
> Аналогично [# 65310](https://github.com/Microsoft/vscode/issues/65310) . @evilpython вы можете копировать текст с помощью сочетаний клавиш (например, Cmd + C)?

I can copy everywhere, except the description of plug-ins.

**Comment by RMacfarlane** [comment] 2019-04-30 16:49
Hey @evilpython, this looks like a duplicate of https://github.com/Microsoft/vscode/issues/69315, let's track it there.

**Closed by RMacfarlane** 2019-04-30 16:49 UTC
Labels: extensions
