### ISSUE TITLE
Cannot access extensions search result using the keyboard

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8661] opened 2016-07-02 00:25 UTC
- VSCode Version: insiders 7/1
- OS Version: Windows

Steps to Reproduce:

1. Open Extensions
2. Press Tab key
-> Extensions search results get focus, but I can not get to the individual extensions using the arrow keys or the tab key.

**Comment by bpasero** [comment] 2016-07-02 06:30
I filed a similar bug that the list widget needs to be on par with tree widget in terms of these accessibility features.

**Comment by joaomoreno** [comment] 2016-07-04 13:41
Yes, closing as duplicate of #8621

**Closed by joaomoreno** 2016-07-04 13:41 UTC
Labels: accessibility, bug
