### ISSUE TITLE
node intellisense is broken for special folders

### ISSUE THREAD

**Issue by zhouzhonghao** [Microsoft/vscode#19907] opened 2017-02-04 07:11 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. write a local file in a sub folder called less。The path is ${root}/less/index.js.
2. require this file from another file such as ${root}/app.js.
3. now intellisense cannot suggest what less module exported.

**Comment by mjbvz** [comment] 2017-02-07 22:02
I'm unable to repo this.

@zhouzhonghao Can you please share an example project or at least the contents of the two files?

Thanks

**Comment by zhouzhonghao** [comment] 2017-02-09 05:25
[intellisense.zip](https://github.com/Microsoft/vscode/files/762658/intellisense.zip)

**Comment by zhouzhonghao** [comment] 2017-02-09 05:27
[less/index.js]
exports.f = function(a, b, c) {
    console.log('d');
}

[normal/index.js]
exports.f = function(a, b, c) {
    console.log('d');
}

[index.js]
var less = require('./less');
var normal = require('./normal');
// the intellisense is broken here.
less.f;
// the intellisense works here.
normal.f;

![image](https://cloud.githubusercontent.com/assets/5805405/22770415/49bfac66-eecb-11e6-8359-5d9e638c4a7e.png)
![image](https://cloud.githubusercontent.com/assets/5805405/22770426/5d678ff4-eecb-11e6-9c7b-98ed21203f58.png)

**Comment by mjbvz** [comment] 2017-02-24 01:21
@zhouzhonghao I'm still not able to reproduce this issue. Does it happen if you disable extensions by launching code with `--disable-extensions`?

**Comment by mjbvz** [comment] 2017-03-07 00:58
Closing as we need more info to investigate this.

@zhouzhonghao Please try upgrading to VSCode 1.10. If the issue still occurs after the upgrade with all extensions disabled, let me know and we can reopen the investigation

Thanks

**Closed by mjbvz** 2017-03-07 00:58 UTC
Labels: intellisense, javascript, needs more info

**Comment by zhouzhonghao** [comment] 2017-03-10 03:29
VSCode 1.10 is OK now.

**Comment by zhouzhonghao** [comment] 2017-03-16 02:52
Confirmed, it's broken in 1.9.0 and OK in 1.10.2.
