### ISSUE TITLE
JSON smart select results in "TypeError: e.reduceRight is not a function"

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode#76777] opened 2019-07-06 13:48 UTC
- VSCode Version: Insiders
- OS Version: Linux

Steps to Reproduce:

1. Select anything in a JSON file using smart-select
2. Notice the error popping up in devtools

Selections after this error is displayed:

```jsonc
 "problem|Matcher": [], // selects 'Matcher"'
{| // selects everything
[| // selects everything
:| // selects everything
"zenMode.cen|terLayout": false, // selects 'Mode.center'
,| // selects everything
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2019-07-18 11:02
duplicate of #77194

**Closed by aeschli** 2019-07-18 11:02 UTC
