### ISSUE TITLE
terminal.integrated.profiles.windows GitBash not working

### ISSUE THREAD

**Issue by peter31990** [microsoft/vscode#132419] opened 2021-09-06 05:20 UTC
- VS Code Version: August 2021 (version 1.60)
- OS Version: Windows 10

Settings:

```
"terminal.integrated.profiles.windows": {
        "GitBash": {
            "path": ["C:\\Programy\\Git\\bin\\bash.exe"],
            "source": "Git Bash",
            "icon": "terminal-bash",
            "args": []
        },
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "icon": "terminal-cmd"
        },
    },
    "terminal.integrated.profiles.linux": {
        "zsh (login)": {
            "path": "zsh",
            "args": ["-l"]
        }
    },
    "terminal.integrated.defaultProfile.windows": "GitBash"
```
![obraz](https://user-images.githubusercontent.com/11589305/132164468-5f595eec-7c7b-4945-ac74-b1ef5505e6d5.png)

**Comment by JiaBob** [comment] 2021-09-06 05:37
I have same issue. Even though I set the default terminal, when I click the RUN button, it still goes to PowerShell. Besides, same as peter's operation, setting the json file also not work!
![image](https://user-images.githubusercontent.com/18398440/132165713-09996811-805f-4983-a254-fd9b1d0a69a4.png)

**Comment by JiaBob** [comment] 2021-09-06 05:39
I think we should mark this issue only for new release. I solved it after I downgrade to pervious versions.

**Comment by Shawn211** [comment] 2021-09-06 06:37
remove the key "source", it maybe work
```
"terminal.integrated.profiles.windows": {
        "GitBash": {
            "path": ["C:\\Programy\\Git\\bin\\bash.exe"],
            "icon": "terminal-bash",
            "args": []
        },
        ...
}
```

**Comment by albertosantini** [comment] 2021-09-06 06:41
This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Comment by peter31990** [comment] 2021-09-06 06:47
> 
> 
> remove the key "source", it maybe works
> 
> ```
> "terminal.integrated.profiles.windows": {
>         "GitBash": {
>             "path": ["C:\\Programy\\Git\\bin\\bash.exe"],
>             "icon": "terminal-bash",
>             "args": []
>         },
>         ...
> }
> ```

 I removed "source" and it works. Thanks Shawn211 :)

**Closed** 2021-09-06 07:04 UTC
Labels: *duplicate
