### ISSUE TITLE
Force Freeze Windows 7 64 Bit

### ISSUE THREAD

**Issue by geronimo794** [Microsoft/vscode#13649] opened 2016-10-13 07:07 UTC
- VSCode Version: 1.6.0
- OS Version: Windows 7 Ultimate 64 Bit

Error :
![untitled](https://cloud.githubusercontent.com/assets/7543729/19339458/ad376620-914d-11e6-94c7-d8d77a3f8c35.png)

Step to reproduce : 
1. My extension : Php intelisense, jquery code snippet, php debug
2. Open my work folder
3. Open 3 file php
4. One document is unsaved. 2 is saved.
5. While select block of code. Its became freeze.
6. The top menu not freezing, but the text editor is freeze

**Comment by DaClan008** [comment] 2016-10-13 07:41
I have a similar issue, that might be related.  I it is either an extension issue that doesn't work well with latest update of vscode, or vscode issue.  I have logged an [issue](https://github.com/glen-84/vscode-sass-lint/issues/5) with the extension as well.

**Comment by bpasero** [comment] 2016-10-13 09:33
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by DaClan008** [comment] 2016-10-13 13:03
I have uninstalled vscode-sass-lint, which solved my problem, however now I do not have linting capabilities on my sass files.  It however is strange that sass-lint is causing it on my side,  yet geronimo794  has same issue on his php and jquery code.  It would be interesting to see if geronimo also uses sass-lint and if it is isolated to vscode-sass-lint then.  I suspect it has something to do with the lates vs code update though.

**Comment by bpasero** [comment] 2016-10-13 13:05
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed** 2016-10-13 13:11 UTC
Labels: freeze-slow-crash, needs more info

**Comment by DaClan008** [comment] 2016-10-16 08:44
Just FYI:  For me (at least) the problem has been solved with the latest vscode update (update 1.6.1).  Note it was not [I believe] an extension issue!!  I am running exactly the same vscode-sasslint extension that I was running when the problems occured.  The only environmental change was the vscode update.

Thank you, for your assistance though.  Not sure if Geronimo's (who logged the issue) problem is also resolved by updating vscode.  Please note I did not log the original error.
