### ISSUE TITLE
Extension process didn't stop after closing VS Code

### ISSUE THREAD

**Issue by pustovalov** [microsoft/vscode#175713] opened 2023-02-28 23:56 UTC
Type: <b>Bug</b>

### Reproduce
Open in vscode project like
https://github.com/blockscout/blockscout
compile this project

install extension
https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek

https://user-images.githubusercontent.com/1568885/222010377-f45f3d78-8499-4b4a-880b-df7dfa9d2a2a.mp4

### Expected behaviour

The process from extension stop after closing VS code

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 92d09ffb-b0c1-4701-929f-5b7b9365b24d|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by tamuratak** [comment] 2023-03-01 09:37
The extension has not been updated for two years. You can request the extension to be marked deprecated in the following thread if you think it should be:

- https://github.com/microsoft/vscode-discussions/discussions/1

**Comment by tamuratak** [comment] 2023-03-01 09:59
The cause would be that the extension depends on an old `vscode-languageclient` package:

```
    "vscode-languageclient": "^5.2.1"
```

- https://github.com/pranaygp/vscode-css-peek/blob/e4b0ceb3547a219e3081854f1d1e208c20cd45f8/client/package.json#L15

The old version caused similar issues:

- microsoft/vscode-languageserver-node/pull/776

**Comment by pustovalov** [comment] 2023-03-01 10:52
Would be nice if VS code make some requirements for extensions, for example VS code v1.8 requires `"vscode-languageclient": "^8.0.0"` and if an extension has a lower version then it stops working

**Comment by tamuratak** [comment] 2023-03-01 12:44
@pustovalov Seems feasible. You had better open a new issue as a feature request.

**Comment by alexdima** [comment] 2023-04-14 13:56
This is unfortunate, but the process that is leaking is not the extension host process. It is a process spawned by one of the extensions running in the extension host process. There are valid situations where extensions want to spawn processes which outlive vscode and the extension host process, so we can't attempt to kill all child processes on exit, as that would break the usecase. Given the extension appears abandoned, I would recommend raising an issue and starting the process of deprecating it.

**Comment by isidorn** [comment] 2023-06-26 08:29
Nothing to be done on the VS Code side.
Closing.

@pustalov did you file an issue on the extension? Did you ask them if we should mark them as deprecated?

**Closed by isidorn** 2023-06-26 08:29 UTC
