### ISSUE TITLE
After the last update, visual artefacts present in the IDE (`macOS`)

### ISSUE THREAD

**Issue by John15321** [microsoft/vscode#154698] opened 2022-07-10 13:40 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.69.0`
- OS Version: `macOS 12.4 arm64`

Steps to Reproduce:
I just opened my VSCode which updated automatically since my last time opening it.
For some reason now I see rectangular artifacts in a form of lighter background rectangular shapes:
![image](https://user-images.githubusercontent.com/56229312/178147341-c0c3df3f-c680-4d17-89d6-ca6310e93c49.png)

This persists with different color schemes (currently I'm using the default color scheme)

The same is also present when I use a terminal window
![image](https://user-images.githubusercontent.com/56229312/178147357-6fe5a591-d6ec-48e1-99c4-c7fac0a70b42.png)

**Comment by naveenkrdy** [comment] 2022-07-10 13:54
bump

**Comment by zero-ms** [comment] 2022-07-10 14:05
me too

**Comment by suic86** [comment] 2022-07-10 14:18
It happens only with dark themes by me.

**Comment by John15321** [comment] 2022-07-10 14:22
> It happens only with dark themes by me.

It does happen with light themes too its just harder to see:
![image](https://user-images.githubusercontent.com/56229312/178148918-ee88bc44-3cc7-47ea-843e-356d64f8b0a3.png)

**Comment by JustDenP** [comment] 2022-07-10 15:22
Same

**Comment by suic86** [comment] 2022-07-10 15:26
@John15321 I see, so this is not dark theme only. I tried 5 different light themes (see below) and it was not visible. 

![image](https://user-images.githubusercontent.com/11985251/178151251-dfc8d158-12fa-40c9-9fce-e1b521d1f411.png)

**Comment by John15321** [comment] 2022-07-10 15:28
> @John15321 I see, so this is not dark theme only. I tried 5 different light themes (see below) and it was not visible.
> 
> ![image](https://user-images.githubusercontent.com/11985251/178151251-dfc8d158-12fa-40c9-9fce-e1b521d1f411.png)

IMO
Its not really dark theme/white theme. It probably just reduces the hex number of the background by accident. It The foreground is already pure gound you cannot make it brighter. I used a light gruvbox theme as an example

**Comment by suic86** [comment] 2022-07-10 16:03
@John15321 makes sense and I agree with you, that this is not a dark/light them issue. I just wanted to clarify, where had my assumption come from.

**Comment by gjsjohnmurray** [comment] 2022-07-10 19:20
/duplicate of https://github.com/microsoft/vscode/issues/152816

**Closed** 2022-07-10 19:20 UTC
Labels: *duplicate, new release
