### ISSUE TITLE
Code Lenses stopped working with the vsls scheme

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#57078] opened 2018-08-23 10:48 UTC
- VSCode Version: 1.26.1
- OS Version: Ubuntu 18.04.1

I am trying to show Code Lenses in a file with URI `vsls:/test/one.js`, but the Code Lens doesn't show up. In fact, the `provideCodeLenses` method of my `CodeLensProvider` is never called for that file.
I've tried registering the provider with different `DocumentSelector`s, but can't get the Code Lenses to work in that file.
It used to work with version 1.25.1 and (IIRC) 1.26.0 (and it still works for local files, i.e. using the `file` scheme).

**Comment by jrieken** [comment] 2018-08-24 07:15
@hbenl For what language does that happen and how do you register your code lens provider? 

The issue is that for LiveShare a "workaround" exists which grants them exclusive registration for some language features, that means if LiveShare registers a certain provider it'll be the exclusive provider. We have done that to avoid double registration of let's say CSS completions but I can check if we still need that.

**Comment by jrieken** [comment] 2018-08-24 12:53
> Would it work if I restricted it to javascript?

Unfortunately not. When VSLS registers a provider, which for JavaScript it does, it wins. It's on our plan to remove this again, tho

**Comment by jrieken** [comment] 2018-09-10 14:41
Closing as this is the current, temporary, design

**Closed by jrieken** 2018-09-10 14:41 UTC
Labels: api, as-designed, editor-code-lens
