### ISSUE TITLE
ERR Capabilities for vscode.markdown.preview.editor already set

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99652] opened 2020-06-09 07:36 UTC
Had a markdown file open (not as preview, but source) and "Save workspace as..." which enters a workspace without reloading the window which restarts the extension host:

```
ERR Capabilities for vscode.markdown.preview.editor already set: Error: Capabilities for vscode.markdown.preview.editor already set
    at CustomEditorService.registerCustomEditorCapabilities (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/customEditor/browser/customEditors.js:193:27)
    at MainThreadWebviews.registerEditorProvider (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadWebview.js:234:59)
    at MainThreadWebviews.$registerTextEditorProvider (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadWebview.js:223:22)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:336:31)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:321:49)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:248:36)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:176:30)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:66:56
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:457:42)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:362:35)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:581:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:455:83
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:457:42)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:188:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:157:61
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:17:40)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment] 2020-06-09 19:21
Duplicate of #99053

**Closed by mjbvz** 2020-06-09 19:21 UTC
