### ISSUE TITLE
Git not working on OSX

### ISSUE THREAD

**Issue by Jeanjohnsen** [Microsoft/vscode#35751] opened 2017-10-06 16:59 UTC
Despite having found the $PATH for git etc. i sem to not be able to make git and vscode work together.
Any help would be much appreciated.

**Comment by nbeentjes** [comment] 2017-10-06 21:56
I think this is a duplicate of issue #35741. This concerns the SCM option in the Activity Bar. When you open a dir/file that _isn't_ under git control you are greeted with the message "there is no active source control providers". In my case I was presented with Mercurial because I had it installed as an additional scm. Changing it back to git (or making git the default scm) was nearly impossible and which I only managed to do by disabling the Mercurial extension (making git the only scm that is installed).

However, when you open a dir/file that _is_ under git control you get all the git options as you did in previous Code versions. The thing is...once you open a file/dir that is under git control you'll also get the git options for the ones that aren't under git control.

I expected it to work as in previous versions with the exception that when you have a list of files/dirs of which not everything is in a scm and you select one that is under git control, Code would recognise it being under git control and give you all the appropriate git functionality (instead of not giving you any because it recognised the primary dir you are in as not being a git repo). The current behaviour makes it unpredictable and illogical to use. The [official manual](https://code.visualstudio.com/Docs/editor/versioncontrol) doesn't mention the new multi SCM support at all, only the release notes do (although it doesn't mention how to actually use it) so that doesn't really help either.

**Comment by joaomoreno** [comment] 2017-10-09 07:41
> Despite having found the $PATH for git etc. i sem to not be able to make git and vscode work together.

What do you mean by _make it work_? Can you share a screenshot? What do you see?

**Comment by qoyyim** [comment] 2017-10-10 06:32
i also have same problem today
but after reopen vscode and updating git lens it seems works again

**Comment by joaomoreno** [comment] 2017-10-10 07:25
@Jeanjohnsen Please reply.

**Closed** 2017-10-17 07:51 UTC
Labels: git, needs more info
