### ISSUE TITLE
Multiple cursors and using tab completion of HTML elements not working?

### ISSUE THREAD

**Issue by andrew-serrano** [Microsoft/vscode#13090] opened 2016-09-30 16:59 UTC
- VSCode Version: Version 1.5.3 (1.5.3)
- OS Version: MacOS Sierra 10.12 (16A323)

Steps to Reproduce:
1. I created multiple cursors on a HTML Doc
2. Wrote out a element to be completed by tab completion, but for some reason it only completes the firs element.

*NOTE I am not 100% if this is a bug or hasn't been implemented yet but I just thought I should bring up a possible issue or hopefully a feature for vscode. Thank you for your time

![possible-bug](https://cloud.githubusercontent.com/assets/19215373/18999865/8df88fa4-86f4-11e6-8a27-04d0681008e4.gif)

**Comment by Mlocik97** [comment] 2016-10-01 11:13
It working when tag is without value, but with value not.

and when u click out from window vscode, and after click to window, it not work too without value.

this bug is in all versions.

(sorry for my English)

look video (from 1.4):

https://www.youtube.com/watch?v=UXgRntm2gZI&feature=youtu.be

**Comment by alexandrudima** [comment] 2017-03-02 10:02
fyi @ramya-rao-a @jrieken

**Comment by jrieken** [comment] 2017-03-02 10:08
closing as dupe of #16037

**Closed by jrieken** 2017-03-02 10:08 UTC
Labels: editor, feature-request, snippets
