### ISSUE TITLE
VSCode crashes without errors when signing in to GitHub or Microsoft

### ISSUE THREAD

**Issue by viv-eth** [microsoft/vscode#167136] opened 2022-11-24 07:56 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: CentOS 7

Steps to Reproduce:

1. Sign in to account (GitHub or Microsoft)
2. Redicrected to GitHub/Microsoft page
3. Log in
4. VSCode immediately closes without any errors or warnings

**Comment by TylerLeonhardt** [comment] 2022-12-06 00:26
Can you attach the crash dump following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

seems like a duplicate of https://github.com/microsoft/vscode/issues/167641

**Comment by viv-eth** [comment] 2022-12-07 16:07
[pending.zip](https://github.com/microsoft/vscode/files/10177769/pending.zip)
Please find attached the error dump

**Comment by viv-eth** [comment] 2022-12-08 15:59
FYI: I tried version 1.74.0 and the issue still persists.

**Comment by rzhao271** [comment] 2022-12-15 21:26
Duplicate of #164223

**Closed by rzhao271** 2022-12-15 21:26 UTC
Labels: info-needed
