### ISSUE TITLE
Is there a way to disable non attribute suggestions for Typescript React?

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/vscode#4912] opened 2016-04-04 12:55 UTC
- VSCode Version: Latest vscode-insiders release
- OS Version: Win10

Is there a way to disable appearing ctor, foreach, function and others from completion list when only inside of JSX tag? This is very annoying, 
see screenshot
![2016-04-04](https://cloud.githubusercontent.com/assets/8881674/14248454/0604cbe6-fa75-11e5-8fb6-2380625f9eca.png)

**Comment by jrieken** [comment] 2016-04-04 16:05
Agreed - it's a duplicate of #1304. Currently we lack the information to smart enough about this...

**Closed by jrieken** 2016-04-04 16:05 UTC
