### ISSUE TITLE
I want VSCode to support the collapsed code block when editing Markdown files

### ISSUE THREAD

**Issue by lijq123** [Microsoft/vscode#47720] opened 2018-04-12 07:23 UTC
Issue Type: <b>Feature Request</b>

When editing long code in markdown, for example:

```javascript
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
    var a=1;
```
There should be a fold button on the left side of this case to fold the code, just like when editing html, css, JavaScript

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment] 2018-04-12 18:55
Duplicate of #36169

**Closed by mjbvz** 2018-04-12 18:55 UTC
Labels: javascript
