### ISSUE TITLE
cannot zoom in/out

### ISSUE THREAD

**Issue by XiaodiJin** [Microsoft/vscode#69067] opened 2019-02-20 18:33 UTC
🚨 The issue tracker is not for questions 🚨

* VSCode Version: 1.31.0
* OS Version: Ubuntu18.04

Steps to Reproduce:
1.When I zoom in/out using shortcut **ctrl+=/-** or by clicking **View** -> **Appearance**-> **Zoom in/out**.
2. They do not work, and I get an error **Can not add index to parent of type array**. 
The following is information from developer Tools:

Can not add index to parent of type array
t.onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:173   ERR Can not add index to parent of type array: Error: Can not add index to parent of type array
    at Object.r [as setProperty] (file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:64:63)
    at e.getEdits (file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4503:833)
    at e.<anonymous> (file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4499:666)
    at file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:34:33)
    at file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:33:160
    at new Promise (<anonymous>)
    at i (file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:952)
    at e.writeToBuffer (file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4499:588)
    at file:///snap/vscode/77/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4499:455

**Comment by bpasero** [comment] 2019-02-21 07:11
@joaomoreno snap issue?

**Comment by joaomoreno** [comment] 2019-02-21 08:41
@bpasero No, works for me in Snap.

**Comment by bpasero** [comment] 2019-02-21 08:42
@XiaodiJin 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by XiaodiJin** [comment] 2019-02-21 12:13
@bpasero Thanks for advice. I have tried the new preview release with 1.32.0-insider. Zoom in/out works well in this version. However, I can not use this insider version for my work, because I cannot even choose "Python: select interpreter" in command palette. Is there some other choice to solve this problem?
Thank you.

**Comment by XiaodiJin** [comment] 2019-02-21 12:20
@bpasero some infos may be useful（if more infos are required, pls tell me）:
```
code --version
1.31.0
7c66f58312b48ed8ca4e387ebd9ffe9605332caa
x64
```
```
code-insiders --version
1.32.0-insider
2e4d4a6bb16a65303b460795fa4ac734f9aea43e
x64
```

**Comment by bpasero** [comment] 2019-02-21 12:49
@XiaodiJin yeah you have to install your extensions again there. Good to know that this seems fixed now.

**Closed by bpasero** 2019-02-21 12:49 UTC
Labels: needs more info
