### ISSUE TITLE
...crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by joeskeen** [microsoft/vscode#173434] opened 2023-02-04 16:26 UTC
Type: <b>Bug</b>

Not sure why it happens, but every time I open up this project it gets stuck on "Initializing JS/TS language features" and "Initializing Angular language features" and keeps showing crashing errors. Never seen this error before until the last couple days.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.34GB free)|
|Process Argv|--crash-reporter-id 53de1c83-9b6d-4f87-896a-e4db9f0f3793|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2303)|
|Memory (System)|7.61GB (5.29GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.9.1
mustache|daw|1.1.1
dotenv|mik|1.0.1
remote-containers|ms-|0.275.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.23.1
ng-template|Ang|15.1.0
vscode-emojicode|Cal|0.1.0
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
prettier-vscode|esb|9.10.4
todo-tree|Gru|0.0.223
terraform|has|2.25.2
rainbow-csv|mec|3.5.0
vscode-azurefunctions|ms-|1.10.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.4
vscode-azurestorage|ms-|0.15.0
vscode-docker|ms-|1.23.3
azure-account|ms-|0.11.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.5
powershell|ms-|2023.1.0
indent-rainbow|ode|8.3.1
pulumi-lsp-client|pul|0.2.3
code-spell-checker|str|2.16.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
89544117:30613380
pythonsymbol12:30657548
a9j8j154:30646983

```

</details>

**Comment by joeskeen** [comment] 2023-02-04 16:35
Even after disabling all extensions (except WSL) the TypeScript language features still can't get initialized:

```
[Info - 16:33:09.946] Starting TS Server
[Info - 16:33:09.946] Using tsserver from: ~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/extensions/node_modules/typescript/lib/tsserver.js
[Info - 16:33:09.947] <syntax> Forking...
[Info - 16:33:09.951] <syntax> Starting...
[Info - 16:33:09.952] <semantic> Forking...
[Info - 16:33:09.956] <semantic> Starting...
[Error - 16:33:46.972] TSServer exited. Code: null. Signal: SIGABRT
[Info - 16:33:46.975] Starting TS Server
[Info - 16:33:46.975] Using tsserver from: ~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/extensions/node_modules/typescript/lib/tsserver.js
[Info - 16:33:46.976] <syntax> Forking...
[Info - 16:33:46.979] <syntax> Starting...
[Info - 16:33:46.979] <semantic> Forking...
[Info - 16:33:46.981] <semantic> Starting...
[Error - 16:34:22.262] TSServer exited. Code: null. Signal: SIGABRT
[Info - 16:34:22.263] Starting TS Server
[Info - 16:34:22.263] Using tsserver from: ~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/extensions/node_modules/typescript/lib/tsserver.js
[Info - 16:34:22.263] <syntax> Forking...
[Info - 16:34:22.268] <syntax> Starting...
[Info - 16:34:22.268] <semantic> Forking...
[Info - 16:34:22.272] <semantic> Starting...
```

**Comment by joeskeen** [comment] 2023-02-06 15:53
I think this may belong in https://github.com/pulumi/pulumi-azure-native
After uninstalling @pulumi/azure-native, the problem stopped happening.

**Comment by mjbvz** [comment] 2023-02-06 16:24
Tentatively closing as caused by extension / TS Server plugin (angular could also be causing this)

**Closed by mjbvz** 2023-02-06 16:24 UTC
