### ISSUE TITLE
Workspace-specific color theme settings are ignored in the WSL when reopening

### ISSUE THREAD

**Issue by bitfauna** [microsoft/vscode#105493] opened 2020-08-27 13:52 UTC
Issue Type: <b>Bug</b>

1. Open a folder in the WSL.
2. Select a color theme different from the global theme in the workspace-specific settings. (Ctrl+, then edit the setting in the Workspace tab)
3. You will see the color theme change, as expected.
4. Close vscode or switch to a different workspace.
5. Reopen the first workspace.
6. Your color theme will be the global theme, instead of the workspace-specific one you just set.

This bug was introduced several builds ago, and is not new to this release.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|15.85GB (4.83GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.8
ruby|gro|0.1.0
remote-wsl|ms-|0.44.4
vscode-ruby|win|0.27.0
rainbow-brackets|2gu|0.0.6
i18n-ally|ant|2.3.6
solargraph|cas|0.21.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
ruby-linter|hoo|1.0.0
endwise|kai|1.4.2
ruby-rubocop|mis|0.8.3
vetur|oct|0.26.1
indent-rainbow|ode|7.4.0
ruby|reb|0.27.0
vscode-yaml|red|0.10.0
simple-ruby-erb|vor|0.2.1
vscode-ruby|win|0.27.0

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2020-11-04 13:35
duplicate of #101893

**Closed by aeschli** 2020-11-04 13:35 UTC
