### ISSUE TITLE
Tolerate trailing commas in jsonc format (breakage)

### ISSUE THREAD

**Issue by alexreg** [microsoft/vscode#177584] opened 2023-03-18 23:08 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.2
- OS Version: macOS 13.1

Steps to Reproduce:

1. Write a jsonc file with trailing commas.
2. Observe that VS Code complains about them.

This seems to be a breakage of [this solution](https://github.com/microsoft/vscode/issues/102061#issuecomment-657080963) which used to work – until the last VS Code update, I believe.

**Comment by aeschli** [comment] 2023-03-20 08:37
Nothing changed recently, but we have two flavours of JSON with Comment. One with just comments (a.) and one with comments and trailing commas (b.)
(a.) is the default. To get b., you also need a JSON schema associated that has `"allowTrailingCommas": true,` set as seen in https://github.com/microsoft/vscode/issues/102061#issuecomment-657080963. I verified in the latest build that this still correctly works.

If this doesn't work for you, can you give a reproducible example?

**Comment by tonyvg2013** [comment] 2023-03-20 10:51
First, & foremost accept my gratitude for your communication. Thank you for
taking your time explaining in detail. The explanation is exact.
Unfortunately on my behalf it's not currently available to put to good
practice due to the lack of adequate functional operating equipment. I have
no recorce computable operating system for implementation of your
suggestion. I realized that at this moment I'm only able to express my
gratitude and won't forget this kindness.
My ARM Samsung Galaxy  Bookgo isn't suitable to for operation due to the
incompatibility primarily and my self included. I failed to over look the
very obvious careless to say the least. I shouldn't have operated it in the
manner as I would a intel, or AMD processors I'm more antiquated perhaps.
I will spear the details, to the technical issues to resolve on a different
note. I purchased what I could afford practically months apart in
purchasing ability for my income. I have a intel now but have not opened
the box yet.
I'm currently going to put your explanation to good use once I'm able to
register the product. It's pretty certain you're closing additional extent
of formulating an example I could comprehend is well accepted on my level
it makes a very big difference to be very direct in addressing the very
nature.
Thank you once again and please accept my gratitude.

Antonio Gonzalez
***@***.***
***@***.***

**Comment by alexreg** [comment] 2023-03-21 01:53
@aeschli Thanks for the reply. I've figured out what's particular about my case: I have a workspace open with the correct JSON schemas configuration in the workspace's `settings.json`, but the JSON file in question is outside of this workspace, even though it's open in the workspace's window and matches `fileMatch` (or at least used to). So, the workspace's settings must have applied to such files before, but not any more. Is this scenario still supported in some other way?

**Comment by aeschli** [comment] 2023-03-21 09:57
Ok, yes, no I realize there have been changes there. We now apply the workspace settings only to files located in that workspace.

**Comment by alexreg** [comment] 2023-03-21 22:47
@archer884 Okay, fair enough. No "workaround" for this then? If so, feel free to close it.

**Comment by aeschli** [comment] 2023-03-23 17:28
Fixed by https://github.com/microsoft/vscode/issues/178008

**Closed by aeschli** 2023-03-23 17:28 UTC
Labels: info-needed

**Comment by alexreg** [comment] 2023-03-23 17:57
@aeschli Thanks, that's super.
