### ISSUE TITLE
Selection in submenu not aligned

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54732] opened 2018-07-20 15:10 UTC
Notice how the blue selection line is not aligned

![screen shot 2018-07-20 at 17 08 19](https://user-images.githubusercontent.com/1926584/43010063-ad7ee11e-8c3f-11e8-9438-21ea992ad01c.png)

Notice how it is nicely aligned on native mac
![screen shot 2018-07-20 at 17 09 23](https://user-images.githubusercontent.com/1926584/43010079-b2935f86-8c3f-11e8-8870-be5e7bb5b3d0.png)

**Comment by sbatten** [comment] 2018-07-20 17:01
dupe of #54527

**Closed by sbatten** 2018-07-20 17:01 UTC
Labels: bug, debt, workbench-menu
