### ISSUE TITLE
Multiline comment folding doesn't work in 1.22.1

### ISSUE THREAD

**Issue by tbranko** [Microsoft/vscode#47565] opened 2018-04-10 09:10 UTC
Issue Type: <b>Bug</b>

1. Create new .js file. 
2. Paste text bellow.

```js
/**
 * This is not folding.
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 */

let fn = () => {
    // This folds nicely
    return 1;
}
```

Comment is not offering folding option, function does. This is standard apidoc format for writing comments. Same happens with code --disable-extensions. It used to work before the latest update.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-nsp|ada|1.0.1
dakara-foldplus|dak|1.3.0
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
rainbow-csv|mec|0.2.1
vscode-exec-node|mir|0.5.0
code-spell-checker|str|1.6.6
local-history|xyz|1.6.2

</details>

**Comment by mjbvz** [comment] 2018-04-10 17:54
Duplicate of #46651 -> https://github.com/Microsoft/TypeScript/issues/22732

Set `"typescript.experimental.syntaxFolding": false` to use the old indentation based folding

**Closed** 2018-04-10 17:53 UTC
Labels: *duplicate, editor, editor-contrib

**Comment by tbranko** [comment] 2018-04-11 07:13
Thanks @mjbvz !
