### ISSUE TITLE
Focus lost in git integration panel

### ISSUE THREAD

**Issue by gliu20** [microsoft/vscode#113422] opened 2020-12-25 15:29 UTC
- VSCode Version: 1.53.0-insider
- OS Version: Github Codespaces 
- About information
  - Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
  - Date: 2020-12-21T12:32:41.893Z (3 days ago)
  - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

Steps to Reproduce:

1. Open Github Codespaces
2. Open Git integration panel
3. Edit a file
4. Quickly start typing a commit message
5. Focus will be lost on the commit message and you end up typing into the abyss
6. This appears to be because after git integration checks for updates, focus gets lost on the commit message input
![image](https://user-images.githubusercontent.com/24921711/103137568-f4713d00-4697-11eb-8b6b-96b7aa6de7b0.png)

Does this issue occur when all extensions are disabled?: Yes/[No]
This is default Github Codespace image with no changes. Only extension is a theme.
![image](https://user-images.githubusercontent.com/24921711/103137587-208cbe00-4698-11eb-9924-d1c640310295.png)

**Comment by eamodio** [comment] 2021-01-05 23:43
Duplicate of #112621

**Closed by eamodio** 2021-01-05 23:43 UTC
Labels: bug, git
