### ISSUE TITLE
Inline Chat Widget: Content is scrollable even though widget is small

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#209000] opened 2024-03-28 10:32 UTC
* use zoom level 2 `"window.zoomLevel": 2`
* make a change with inline chat
* 🧀 unwanted scroll bar

The content of the inline chat widget is always scrollable even when there is only one very short response (made changes). 

![Code_-_Insiders_SX295Maap9](https://github.com/microsoft/vscode/assets/44439583/182e5adf-e261-4cca-913f-1ca7dd33523a)

**Comment by jrieken** [comment] 2024-03-28 11:18
Does reproduce for me... @benibenj Do you have reliable steps?

**Comment by benibenj** [comment] 2024-03-28 13:03
I debugged this with different settings combinations and it turns out it is caused by using zoom level 2 in my case. 
It always happens with zoom level 2 and never with zoom level 0.

**Comment by jrieken** [comment] 2024-03-28 13:20
Thanks for drilling into this.

**Comment by jrieken** [comment] 2024-10-28 10:53
Seems to be fixed by now

**Closed** 2024-10-28 11:02 UTC
Labels: bug, inline-chat
