### ISSUE TITLE
Clone Repository always greyed out

### ISSUE THREAD

**Issue by dzsoundnirvana** [microsoft/vscode#137592] opened 2021-11-21 04:30 UTC
Issue Type: <b>Bug</b>

I've uninstalled all extensions, uninstalled VSC and reinstalled it but cannot use the Clone Repository. It works on another machine but not this one. Need a tool that completely wipes out all of VSC from a machine.
Ver  Infos:
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1607 v3 @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.92GB (28.86GB free)|
|Process Argv|--crash-reporter-id 9cf351c3-1b5f-4a58-9b25-37a8cee7d878|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-21 04:59
Have you confirmed that Git for Windows has been installed and is working?

**Comment by dzsoundnirvana** [comment] 2021-11-21 05:05
After some digging around I was able to resolve the issue (for the time being) with the following process (something in the following locations is causing an issue):
Go to: C:\Users\<UserName>\AppData\Local\Programs\Microsoft VS Code
Run: unins000.exe
Delete dir: C:\Users\<UserName>\AppData\Roaming\Code
Delete dir: C:\Users\<UserName>\.vscode
Install VSC

and the option to clone repos is available.
![image](https://user-images.githubusercontent.com/3346180/142750311-1fe3eb57-37db-42bc-8278-515e799431b7.png)

**Comment by dzsoundnirvana** [comment] 2021-11-21 15:04
> Have you confirmed that Git for Windows has been installed and is working?

Yes, it has ver. git version 2.34.0.windows.1.

**Comment by lszomoru** [comment] 2021-11-23 10:52
Closing the issue for now since it looks like reinstalling VS Code resolved the issue.

**Closed by lszomoru** 2021-11-23 10:52 UTC
