### ISSUE TITLE
Conda environment cannot activate

### ISSUE THREAD

**Issue by ribery77** [microsoft/vscode#213528] opened 2024-05-27 08:42 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows 10

Steps to Reproduce:

1. I cannot activate in git bash anaconda environment.
2. Once I open new git bash new Terminal it gives me this error:
bash: C:\Users\Philip.Manchevnaconda3: No such file or directory

If I downgrade to 1.88 it works without issue.
Simply it cannot find path to conda environment.

**Comment by meganrogge** [comment] 2024-05-30 18:36
likely /duplicate of #212508

disabling shell integration will likely fix this for you for now with `terminal.integrated.shellIntegration.enabled`

**Closed by meganrogge** 2024-05-30 18:36 UTC
