### ISSUE TITLE
EditorView crashes when trying to split with the ExtensionView

### ISSUE THREAD

**Issue by Ritorna** [microsoft/vscode#77385] opened 2019-07-15 07:55 UTC
Issue Description
=====

The EditorView crashes unexpectedly when trying to split it with the Extension view, see the following screenshots:

![image](https://user-images.githubusercontent.com/10747768/61201474-e66a6f00-a6e4-11e9-8418-2377e2fe8a7f.png)

![image](https://user-images.githubusercontent.com/10747768/61201478-ec605000-a6e4-11e9-993b-3eaf1f44a661.png)

This problem occurs in the stable 1.36.1 and also the 1.37.0-insider version, with  and without extensions enabled. I could reproduce it on other machines.

This does not apply for any extension WebView: 
![image](https://user-images.githubusercontent.com/10747768/61201902-3ac21e80-a6e6-11e9-8a7f-08297dc8f385.png)

Attached Logs
=====

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.16299 |
| VSCode | 1.36.1 + 1.37.0-insider |
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.16299.1146|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.16299.1146|
|BuildVersion|10.0.16299.1146|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.0|
|better-comments|aaron-bond|2.0.5|
|Bookmarks|alefragnani|10.4.4|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|change-case|wmaurer|1.0.0|
|code-settings-sync|Shan|3.3.1|
|code-spell-checker|streetsidesoftware|1.7.17|
|convert-css-in-js|paulmolluzzo|1.1.3|
|dark-plus-plus-theme|DryWolf|0.0.9|
|debugger-for-chrome|msjsdiag|4.11.6|
|debugger-for-edge|msjsdiag|1.0.10|
|docthis|joelday|0.7.1|
|dotenv|mikestead|1.0.1|
|dracula-theme-from-intellij|trinm1709|0.3.0|
|EditorConfig|EditorConfig|0.13.0|
|file-icons|file-icons|1.0.17|
|gc-excelviewer|GrapeCity|2.1.32|
|git-graph|mhutchie|1.11.0|
|git-project-manager|felipecaputo|1.7.1|
|github-markdown-preview|bierner|0.0.2|
|gitlens|eamodio|9.8.5|
|highlight-matching-tag|vincaslt|0.9.2|
|html-css-class-completion|Zignd|1.19.0|
|htmltagwrap|bradgashler|0.0.7|
|json-to-ts|MariusAlchimavicius|1.5.5|
|markdown-all-in-one|yzhang|2.4.0|
|markdown-checkbox|bierner|0.1.3|
|markdown-emoji|bierner|0.0.9|
|markdown-formatter|mervin|0.4.7|
|markdown-preview-github-styles|bierner|0.1.6|
|markdown-yaml-preamble|bierner|0.0.4|
|minify|HookyQR|0.4.3|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|polacode|pnp|0.3.2|
|powershell|ms-vscode|2019.5.0|
|prettier-vscode|esbenp|1.9.0|
|project-manager|alefragnani|10.5.2|
|quokka-vscode|WallabyJs|1.0.235|
|react-javascript-to-typescript-transform-vscode|mohsen1|1.10.0|
|regex|chrmarti|0.2.0|
|sass-indented|robinbentley|1.5.1|
|search-node-modules|jasonnutter|1.3.0|
|stylelint|shinnn|0.51.0|
|team|ms-vsts|1.149.2|
|theme-panda|tinkertrain|1.3.0|
|todo-tree|Gruntfuggly|0.0.138|
|tstools|iBotMedia|1.1.3|
|unique-lines|bibhasdn|1.0.0|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-filesize|mkxml|2.1.3|
|vscode-fileutils|sleistner|2.14.5|
|vscode-firefox-debug|hbenl|1.8.0|
|vscode-icon-theme|jtlowe|1.6.5|
|vscode-icons|vscode-icons-team|8.8.0|
|vscode-language-pack-de|MS-CEINTL|1.36.2|
|vscode-markdownlint|DavidAnson|0.28.0|
|vscode-npm-script|eg2|0.3.8|
|vscode-print|pdconsec|0.7.12|
|vscode-react-native|msjsdiag|0.10.1|
|vscode-scss|mrmlnc|0.6.2|
|vscode-spotify|shyykoserhiy|3.1.0|
|vscode-styled-components|jpoissonnier|0.0.26|
|vscode-svgviewer|cssho|2.0.0|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscode-versionlens|pflannery|0.24.0|
|vscode-vibrancy|eyhn|1.0.1|
|vscode-wasm|dtsvet|1.2.1|
|vscode-yaml|redhat|0.4.1|
|vscode-yarn|gamunu|1.6.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.7|
|web-debugger|Witron|0.0.1|
|web-deploy|Witron|0.0.1|
|web-markdown|Witron|0.0.1|
|web-react-typescript-snippets|Witron|0.0.2|
|web-react-typescript-tools|Witron|0.0.2|
|web-sharperDark|Witron|0.0.3|
|web-themes|Witron|0.0.1|
|web-tools|Witron|0.0.1|
|web-typescript-hero|Witron|2.3.2|
|winteriscoming|johnpapa|1.2.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by mjbvz** [comment] 2019-07-20 00:47
Seems like a duplicate of #75532 from the callstack. Please test in the latest VS Code insiders build to confirm and let me know if you still see this issue

**Closed by mjbvz** 2019-07-20 00:47 UTC
Labels: extensions

**Comment by Ritorna** [comment] 2019-07-29 12:58
> Seems like a duplicate of #75532 from the callstack. Please test in the latest VS Code insiders build to confirm and let me know if you still see this issue

Still can confirm for the latest insider version:
![image](https://user-images.githubusercontent.com/10747768/62050329-557db280-b211-11e9-8ac7-0a8bdf49b1b2.png)
