### ISSUE TITLE
misposition of cursor

### ISSUE THREAD

**Issue by funnycom** [microsoft/vscode#143086] opened 2022-02-15 07:02 UTC
Issue Type: <b>Bug</b>

Cursor does not appear between auto-typed quotation marks.
This makes some errors.
Refer below example. | means cursor position.

expected:
    <script src="| "...>

actual:
    <script src=""| ...>

![스크린샷 2022-02-15 오후 4 03 18](https://user-images.githubusercontent.com/5915404/154009878-331145b7-7a83-428f-b4fe-dd64a0d657c1.png)

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|--crash-reporter-id ca36baa1-8a9e-4c1f-8666-131a9a94c9c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-linting|doc|0.0.9
vscode-html-css|ecm|1.11.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.2.0
auto-rename-tag|for|0.1.10
copilot|Git|1.7.5003
vscode-language-pack-ko|MS-|1.64.6
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.13.0
vscode-css-peek|pra|4.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
html-to-css-autocompletion|sol|1.1.2
open-in-browser|tec|2.0.0
lorem-ipsum|Tyr|1.3.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vsrem710:30416614
vsbas813:30436447

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-02-15 12:09
Your screenshot:

![image](https://user-images.githubusercontent.com/6726799/154059165-7b269f7f-38a0-42ef-8b30-aea7a3f8c861.png)

Can you make a short recording to show where you are clicking and what you are typing?

/gifPlease

**Comment by Jadamae77** [comment] 2022-02-16 15:50
Seeing the same thing. Very very frustrating. Screen recording below. I type a quotation mark, the second one is automatically added (correct) but the cursor is moved to after both marks.

![Recording 2022-02-16 at 10 48 49](https://user-images.githubusercontent.com/63246953/154302411-88bf8581-2f69-478b-9809-7e902efe4c77.gif)

**Comment by Jadamae77** [comment] 2022-02-16 16:12
> @Jadamae77 Does configuring `"html.autoCreateQuotes": false` ameliorate things?

Yes, it does. Am I misunderstanding the configuration? When that config is false, I wouldn't expect it to create the closing quote automatically, but it still does (and correctly handles the cursor).

**Comment by alexdima** [comment] 2022-02-16 16:39
> When that config is false, I wouldn't expect it to create the closing quote automatically, but it still does (and correctly handles the cursor).

There are two features at play. `"html.autoCreateQuotes"` is an HTML specific feature where quotes are inserted automatically after accepting an attribute in Intellisense. The other one is probably `"editor.autoClosingQuotes"` which works in all languages, based on language defined rules. You can also configure `"editor.autoClosingQuotes": "never"` to disable it.

**Comment by Jadamae77** [comment] 2022-02-16 16:51
Thank you!

**Comment by aeschli** [comment] 2022-02-21 21:10
duplicate of #140698

**Closed by aeschli** 2022-02-21 21:10 UTC
Labels: needs more info

**Comment by funnycom** [comment] 2022-02-22 04:55
Thanks all.
