### ISSUE TITLE
Auto import not working

### ISSUE THREAD

**Issue by gultyaev** [microsoft/vscode#94471] opened 2020-04-05 16:06 UTC
- VSCode Version: 1.43.2
- OS Version: Windows 10 (1909)

Steps to Reproduce:

1. Create nx workspace with Angular - Nest.JS `npx create-nx-workspace@latest test`
2. Install package `npm i @nestjs/config`
3. Navigate to nest js app module
4. Try to add `ConfigModule` to imports
5. See no suggestions to import from `'@nestjs/config'`

Same happens for Angular's `FormsModule` and `ReactiveFormsModule` and to many more

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-04-06 18:37
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

After installing and restarting VS Code, does it work?

**Comment by gultyaev** [comment] 2020-04-08 15:44
Well. I've installed VSCode Insiders as it stated in comments when submitting the issue (I suppose it can be taken as reinstall). Then I've installed the provided extention in the Insiders. Afterwards, I've reopened VSCode and tried to import `FormsModule` for Angular's part of a project and no autoimport suggestions as before,

**Comment by mjbvz** [comment] 2020-04-09 22:52
IF you add `import '@nestjs/config'` anywhere in your project, do auto-imports start working (even in other TS files?)

**Comment by gultyaev** [comment] 2020-04-10 07:33
Yes it does. But it should do that from the very beginning.

**Comment by mjbvz** [comment] 2020-04-10 09:04
Duplicate of https://github.com/microsoft/TypeScript/issues/37812

**Closed by mjbvz** 2020-04-10 09:04 UTC
Labels: needs more info, typescript
