### ISSUE TITLE
Color mismatches for used and unused variables

### ISSUE THREAD

**Issue by nileshpawar-xento** [Microsoft/vscode#59541] opened 2018-09-27 11:08 UTC
Issue Type: <b>Bug</b>

Earlier there were showing used variables in the blue color but now somevariables color showing like light gray which we are using showing unused variables. Working for some variables and not for all.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
npm-intellisense|chr|1.3.0
auto-close-tag|for|0.5.6
vscode-jetbrains-keybindings|isu|0.1.6
vscode-language-babel|mgm|0.0.20
vsliveshare|ms-|0.3.735
prettier-standard-vscode|num|0.3.0
vscode-icons|rob|7.27.0

</details>

**Comment by bpasero** [comment] 2018-09-27 12:46
@nileshpawar-xento what language? And is this a duplicate of https://github.com/Microsoft/vscode/issues/59540 ?

**Closed** 2018-10-08 06:12 UTC
Labels: needs more info
