### ISSUE TITLE
docker extension install failed

### ISSUE THREAD

**Issue by liuliangsir** [Microsoft/vscode#36460] opened 2017-10-18 03:22 UTC
- VSCode Version: 3495b0b185acbe8188e821ccb3ae807274703a9c
- OS Version: macOS 10.13 (17A405)

Steps to Reproduce:

1. click the extensions icon in the activity bar
2. type docker item in the search box
3. click the install button

Reproduces without extensions: No

After clicking the install button, return error "end of central directory record signature not found".

I am sure that i am not running behind a proxy,  i also try to install another extension has no problem at all, but only for docker extension get a problem.

Here is some errors in the console, as it follows:

![image](https://user-images.githubusercontent.com/8049878/31699983-e4699d92-b3f8-11e7-97bb-b5b9655ea892.png)

**Comment by rcjsuen** [comment] 2017-10-18 03:44
See Microsoft/vscode-docker#145.
/cc @chrisdias

**Comment by mjbvz** [comment] 2017-10-18 05:43
Duplicate of https://github.com/Microsoft/vscode/issues/34730

As Microsoft/vscode-docker#145 suggests, try using install from vsix as a workaround

**Closed by mjbvz** 2017-10-18 05:43 UTC
Labels: extensions
