### ISSUE TITLE
Custom theming is broken

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137887] opened 2021-11-25 14:54 UTC
**Yesterday's insider:**
![Screenshot 2021-11-25 at 15 52 58](https://user-images.githubusercontent.com/900690/143462884-55148d75-9475-4b71-ab54-ff8178e441ea.png)

**Today's insider:**
![image](https://user-images.githubusercontent.com/900690/143462929-36174a5b-acd8-4d3f-a652-583a5df10c4a.png)

```json
"workbench.colorCustomizations": {
    "focusBorder": "#F3F3F3",
    "inputOption.activeBackground": "#007acc1f",
    "editorLineNumber.activeForeground": "#2b91af",
    "list.focusHighlightForeground": "#fff",
    "activityBar.activeBorder": "#2c2c2c",
    "sideBarSectionHeader.border": "#0000",
    "list.activeSelectionBackground": "#3399FF",
    "list.highlightForeground": "#0066BF",
    "list.activeSelectionIconForeground": "#fff"
}
```

**Comment by microhobby** [comment] 2021-11-25 20:20
@bpasero in today's insiders I see that even changing the `workbench.colorCustomizations` after a window reload or openning a new remote the default colors from the theme come back and the `workbench.colorCustomizations` is ignored. Is this issue related or should I open a new issue?

**Comment by bpasero** [comment] 2021-11-26 07:34
@microhobby good point! looks like any customization is broken.

**Comment by aeschli** [comment] 2021-11-26 09:24
duplicate of  #137867

**Closed by aeschli** 2021-11-26 09:24 UTC
Labels: bug, important, themes, quick-pick
