### ISSUE TITLE
Markdown preview does not render properly when zoomed in

### ISSUE THREAD

**Issue by KirkMunro** [Microsoft/vscode#23702] opened 2017-03-30 21:58 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 10.0.15058

Steps to Reproduce:

1. Open a markdown document in VS Code.
2. Press Ctrl+Shift+"+" to zoom in a bunch.
3. Press Ctrl+K,V to show the markdown preview. The preview shows, but the control it renders in has shrunk dramatically, making it pretty much unusable.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/3515485/24527951/6c9cd47a-1572-11e7-9079-56531365390a.png)

**Comment by gregvanl** [comment] 2017-03-31 04:30
Duplicate of https://github.com/Microsoft/vscode/issues/5745

**Closed by gregvanl** 2017-03-31 04:30 UTC
Labels: duplicate
