### ISSUE TITLE
Feature Request: A Singular Configuration Definition

### ISSUE THREAD

**Issue by geirman** [Microsoft/vscode#15780] opened 2016-11-20 17:26 UTC
I suspect I'm not unique in that I work on multiple computers. I have my windows based work computer (ug!) and my personal mac. I want to use the same editor on all and invest time tweaking the config so that it's just right. But keeping multiple computers in sync is impossible. I'll make a tweak to one, but inevitably forget to transfer that to the other. 

So, it would be SUPER SWEET if a change to one computer sync'd with all my others. A single configuration definition.

**Comment by alefragnani** [comment] 2016-11-20 17:56
There are some extensions that already do that. A very popular is this one https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync.

**Comment by geirman** [comment] 2016-11-20 19:03
Good to know! Thanks @alefragnani... that ought to do it. Sounds like a good feature for core though... maybe :-/

**Comment by seanmcbreen** [comment] 2016-12-07 00:33
Yes we will track as a feature request - thanks for sending on.  And thats the right extension for the job :)

**Comment by mjbvz** [comment] 2018-09-20 20:51
Duplicate of #2743

**Closed by mjbvz** 2018-09-20 20:51 UTC
Labels: feature-request
