### ISSUE TITLE
Show enum CSS property value first in completion 

### ISSUE THREAD

**Issue by pmpinto** [microsoft/vscode#74213] opened 2019-05-23 15:23 UTC
I have [SCSS IntelliSense](https://github.com/mrmlnc/vscode-scss) installed to be able to get a list of variables defined in other files. That's great!
But I would like VSCode to let me define which properties I would like to see listed first.

![Screen Shot 2019-05-23 at 16 13 01](https://user-images.githubusercontent.com/4265830/58264913-9a4f1e00-7d76-11e9-87cf-a7aa15f5f81e.png)

In the example above, I'm setting the `position` property. I would prefer to see on top of the suggestions list all the valid values for this property and below those, the defined variables if there are any.

You can imagine having a big list of variables will not help with this either.

**Comment by jrieken** [comment] 2019-05-23 18:45
>  I would prefer to see on top of the suggestions list all the valid values for this property and below those,

You should probably reach out to the extension author how has some control over this. Or, assuming you already know what you are looking for just, you can just start typing `p` and the best match it put atop. 

> You can imagine having a big list of variables will not help with this either.

Not if that refers to the presented list of suggestions or to the configuration that you suggest we have. How do you imagine such a list will work? Per language, per prefix? I can image that such a list quickly becomes complicated, hard to maintain

Last, there this configuration `editor.suggestSelection` which makes VS Code remember and present (not re-sort) what suggestions you have picked in the past

**Comment by pmpinto** [comment] 2019-05-28 16:02
> You should probably reach out to the extension author how has some control over this.

I was about to, but based on [this comment](https://github.com/mrmlnc/vscode-scss/issues/38#issuecomment-283615884) on a similar issue for that extension, I opted to reach out to you guys.

> Or, assuming you already know what you are looking for just, you can just start typing p and the best match it put atop.

True. And that's how I deal with it most of the time. But in some occasions I just can't remember the value I'm looking for and have to scroll a huge list of suggestions until I find the actual valid values for the property.

> How do you imagine such a list will work? Per language, per prefix?

Per language would make sense to me. Something like:
```json
{
  "editor.suggest.sort": {
    "scss": ["variables", "properties", "keywords"]
  }
}
```

Is this what you imagined?

> `editor.suggestSelection`

I currently have this set to `recentlyUsed` and it seems to work well on TypeScript files, but not on SCSS. I mean `console.` will pop a list with `log` at the top being the one I've recently used.
But `box-sizing:` triggers a list with a whole bunch of variables at the top, just like the example I posted above.

**Comment by jrieken** [comment] 2019-05-29 07:35
> Per language would make sense to me. Something like:

So, I want to group by kind? Eg. `A_var`, `B_var`, `Z_var`, `A_prop`, `B_prop`, `Z_prop`, `A_keyword`, `B_keyword`, `Z_keyword`. What happens now when you press `A`? Do you still want to see `Z_prop` before `A_keyword`?

**Comment by csalvato** [comment] 2019-06-06 22:41
I don't know if we want to group by kind across the board (since I don't know how many kinds exist).

I know in my use case for #71693, having keywords with the same string as snippits, I always want the snippet to win if there's an exact match (because the word is already written!)

The `it` snippet is an example of this.

**Comment by pmpinto** [comment] 2019-06-07 16:32
Just updated vscode to v1.35.0 which brings this:
![Screen Shot 2019-06-07 at 17 28 57](https://user-images.githubusercontent.com/4265830/59119228-20a85a00-894a-11e9-8749-65761ace4e82.png)

This is exactly what I was referring to in the first post, for SCSS files.
Not sure what's the logic behind this, but I would suggest apply a similar approach to SCSS.

Would that work?

**Comment by RUSshy** [comment] 2019-06-11 09:43
How long vscode exists guys ? and still no option to sort completion items by type instead of A-Z ? c'mon, if you want me to take this editor seriously, make it not fight against me

**Comment by RUSshy** [comment] 2019-06-12 10:02
wtf why marked as spam ? discussion is prohibited ? nice Microsoft

**Comment by RUSshy** [comment] 2019-06-12 10:03
How long vscode exists guys ? and still no option to sort completion items by type instead of A-Z ? c'mon, if you want me to take this editor seriously, make it not fight against me

**Comment by octref** [comment] 2019-10-25 22:01
Duplicate of #81669, which we'll release this month.

**Comment by octref** [comment] 2019-10-25 22:04
NVM, I misread it. This is about ranking results coming from multiple extensions.

**Comment by octref** [comment] 2019-11-12 19:50
@jrieken I'm wondering if we can do something. CSS LS now sends back the suggestions with `sortText`, but SCSS IntelliSense sends back suggestions with no `sortText`.

My proposal: If `sortText` exists on any entry, suggestions without `sortText` should be ranked below ones with `sortText`. Would that work for you?

**Comment by jrieken** [comment] 2019-11-13 08:49
> My proposal: If sortText exists on any entry, suggestions without sortText should be ranked below ones with sortText. Would that work for you?

What would break what we [state in the API](https://github.com/microsoft/vscode/blob/623bae89051768933b9a14e93a2e9b496526adfb/src/vs/vscode.d.ts#L3366-L3372) and I also don't know how it would help with the overall issue here

**Comment by octref** [comment] 2019-11-13 16:35
I see, that's a bad proposal...

Should I offer enum completions (such as `sticky`, `absolute`) with `sortText` that begins with spaces so these suggestions can precede all others?

@aeschli Also wondering what's your thought.

**Comment by octref** [comment] 2019-11-13 20:01
@aeschli is fine with this change. I'll do it for November.

**Comment by jrieken** [comment] 2019-11-14 06:08
TS is doing the same. I believe the use `String.fromCharCode(0)` as prefix

**Comment by octref** [comment] 2019-11-14 18:48
I updated title to reflect what this asks for.

![image](https://user-images.githubusercontent.com/4033249/68886332-df239400-06cb-11ea-955a-252f32d6f36d.png)

Verifier: Verify that with https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss installed, you still get enum CSS property value completion first. For example `position`, `float` etc. Verify for other properties such as `color`, the `$` variables provided by SCSS IntelliSense comes first (since there's no enum for it).

**Closed** 2019-11-14 18:48 UTC
Labels: css-less-scss, feature-request, verification-needed
