### ISSUE TITLE
After Vscode is updated, use the Vue development program interface to highlight exceptions！！！

### ISSUE THREAD

**Issue by litchi-iconfont** [microsoft/vscode#185542] opened 2023-06-19 08:39 UTC
Guys, have you ever encountered the problem of abnormal program highlighting after updating vscode? Before the update, it was used normally, but after the update, the display was abnormal. The draw crashed every 3 minutes, the code prompt disappeared, random error was reported, and the style did not prompt; engineering It uses Vue3+ts+Element-plus+vite+pinia technology stack.
![微信图片_20230619163820](https://github.com/microsoft/vscode/assets/76797435/c0071607-5c80-421e-8c02-a498221cafa1)

**Comment by roblourens** [comment] 2023-06-19 17:59
Does it help to restart vscode? If not please give some more details like what error you saw

**Comment by litchi-iconfont** [comment] 2023-06-20 02:11
> 重新启动 vscode 有帮助吗？如果不是，请提供更多详细信息，例如您看到的错误

Restarting vscode can temporarily solve it, but it will happen again in a short time, even after the editor is reinstalled.

**Comment by johnsoncodehk** [comment] 2023-06-20 17:19
Duplicate of #185479

**Closed** 2023-06-30 17:31 UTC
Labels: info-needed
