### ISSUE TITLE
Unclickable extra custom editor tab

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#99292] opened 2020-06-03 15:39 UTC
Testing https://github.com/microsoft/vscode/issues/99003

I made some scratches and left my editor unsaved. 
Then I reloaded.
As expected, the file showed up as dirt and restored my unsaved scratches.
Unexpectedly, there is a second tab for that editor that I didn't open. And when I click on it, it just opens the first tab. The extra tab just sits there.

![image](https://user-images.githubusercontent.com/38270282/83657322-fde26d00-a5c0-11ea-94a7-7e57cf7e48db.png)

**Comment by mjbvz** [comment] 2021-02-27 00:43
I believe this is a duplicate of #111474

Please let me know if you still see

**Closed by mjbvz** 2021-02-27 00:43 UTC
Labels: bug, custom-editors
