### ISSUE TITLE
Must type the same letter twice when one letter is selected

### ISSUE THREAD

**Issue by acls** [Microsoft/vscode#25901] opened 2017-05-04 15:33 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T15:02:36.792Z)
- OS Version: Linux x64 4.4.0-75-generic
- Extensions: none
---

Steps to Reproduce:

1. select a letter
2. type the selected letter (nothing happens)
3. type the selected letter again (the letter will finally be typed)

Real example - rename `i` to `idx`

1. select all three `i` variables
2. type `idx` (only `dx` will appear)
2. type `iidx` (first `i` won't appear)
```
for (var i = 0; i < length; i++) {
}
```

**Comment by kieferrm** [comment] 2017-05-04 17:14
This works for me on Ubuntu.

**Comment by Tyriar** [comment] 2017-05-04 17:24
@acls some questions:

- What's in your settings.json?
- What's your OS locale set to?
- What Linux distro are you on?
- What keyboard layout are you using?

**Comment by acls** [comment] 2017-05-04 18:06
- What's in your settings.json?
```
{
    "window.zoomLevel": 1
}
```
- What's your OS locale set to?
  - en_US
- What Linux distro are you on?
  - Ubuntu 16.04
- What keyboard layout are you using?
  - English (US)

I just booted up an old windows box and installed vscode. Issue still happens there.

**Comment by Tyriar** [comment] 2017-05-04 18:08
It's happening on another Windows machine as well? Are you sharing the physical keyboard by chance?

Moving to editor owners.

**Comment by acls** [comment] 2017-05-04 18:20
Yeah, the windows box was just an old laptop, so different keyboards.

**Comment by alexandrudima** [comment] 2017-05-05 12:25
Duplicate of #16520 . 

The fix should come out starting with today's or yesterday's insiders (i.e. anything that has 242cb936f0b703a92547c8884dc0c5609eab01e9 ). This might explain the difficulty in reproducing.

**Closed by alexandrudima** 2017-05-05 12:25 UTC
Labels: bug, needs more info

**Comment by acls** [comment] 2017-05-05 15:02
Talk about bad timing. The fix was made less than a day before I posted, so the latest insider's build didn't have it.

And sorry about the duplicate posting. I hadn't run into the issue until after I got the latest build an hour earlier. I had searched for doops, but not 6 months back.
