### ISSUE TITLE
Filename filter for Explorer

### ISSUE THREAD

**Issue by jrcsdev** [Microsoft/vscode#72376] opened 2019-04-15 23:00 UTC
File Explorer needs Filter by Name, like Visual Studio.

This is very useful when we want to open related files, and they have the same name in common,

Thanks for all!

PD: See VS screenshot
![vs-explorer](https://user-images.githubusercontent.com/765950/56170644-df2dab00-5fa7-11e9-9e25-b27ffebc5a29.png)

**Comment by usernamehw** [comment] 2019-04-15 23:18
Possible duplicate of #66971 or #70646

**Comment by isidorn** [comment] 2019-04-16 07:30
Click on the explorer and start typing

**Closed** 2019-04-16 07:30 UTC
Labels: *duplicate
