### ISSUE TITLE
Slowing down when running simple code

### ISSUE THREAD

**Issue by christopherdparker** [microsoft/vscode#205301] opened 2024-02-15 16:54 UTC
Type: <b>Performance Issue</b>

I'm reopening https://github.com/microsoft/vscode/issues/191303 vscode.ipynb is running very slow. When I look at running extensions I see Unresponsive and Performance Issue notifications. Things like df.columns pause for 5-10 seconds before executing.

VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin x64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|128.00GB (35.86GB free)|
|Process Argv|--crash-reporter-id ffe1e2c8-0195-4e46-b241-0060dda23ec6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   393	 43270	code main
    0	   131	 43273	   gpu-process
    0	     0	 43274	   utility-network-service
    0	  1049	 43275	window [1] (PROFILE.cpuprofile.txt)
    0	   131	 43280	shared-process
    0	     0	 43476	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 43281	fileWatcher [1]
    0	   655	 43286	extensionHost [1]
    0	     0	 43295	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=43286
    0	     0	 43297	     /usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python /Users/chris/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/run-jedi-language-server.py
    0	     0	 43298	     /usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python /Users/chris/.vscode/extensions/ms-python.isort-2023.10.1/bundled/tool/lsp_server.py
    0	 14287	 43358	     electron-nodejs (XrHhZwGwsEEV.js )
    0	     0	 43412	       electron-nodejs (min.js MathJax.js )
    0	     0	 43413	         electron-nodejs (min.js MathJax.js )
    0	   131	 43417	           electron-nodejs (min.js MathJax.js )
    0	     0	 43418	             gpu-process
    0	     0	 43419	             utility-network-service
    0	   131	 43420	             window
    0	  1049	 43293	   window
    0	   131	 43474	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
stata-enhanced|kyl|1.6.1
debugpy|ms-|2024.1.10441007
isort|ms-|2023.10.1
python|ms-|2024.0.1
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30962250
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
b5d27386:30958190
fegfb526:30961430
3ef8e399:30964150
bg6jg535:30958357
ccp1r6:30958156

```

</details>

**Comment by christopherdparker** [comment] 2024-02-15 16:54
[CPU-20240215T164859.809Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/14299758/CPU-20240215T164859.809Z.cpuprofile.txt)

Here is a profile of the running extensions

**Comment by rebornix** [comment] 2024-03-13 05:03
@christopherdparker thanks for the cpu profile, will take a look!

**Comment by DonJayamanne** [comment] 2024-12-10 00:31
Duplicate of https://github.com/microsoft/vscode/issues/230187

**Closed by DonJayamanne** 2024-12-10 00:31 UTC
Labels: freeze-slow-crash-leak, notebook-execution
