### ISSUE TITLE
How to set the account prompt to be hidden

### ISSUE THREAD

**Issue by 82318179** [microsoft/vscode#118396] opened 2021-03-08 04:18 UTC
- VS Code Version:1.54.1
After login my account, the account will always prompt for synchronous change,how to  turn off the prompt, let it update itself directly, instead of prompting me often and letting me update manually。Or the user can set no prompt
![QQ图片20210308121511](https://user-images.githubusercontent.com/25976728/110273702-1bd57600-8008-11eb-9cee-abb18a1067c2.png)

**Comment by RMacfarlane** [comment] 2021-05-13 16:36
Closing as a duplicate of https://github.com/microsoft/vscode/issues/118668

**Closed by RMacfarlane** 2021-05-13 16:36 UTC
Labels: feature-request
