### ISSUE TITLE
"Find All References" throws error

### ISSUE THREAD

**Issue by stephensong** [Microsoft/vscode#26774] opened 2017-05-16 21:29 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10.

Steps to Reproduce:

1. Hover over a function name (optionally select / highlight function name).
2. Right-click and select "Find All References"

produces error included below.  Happens most times, but not _every_ time, and I've not been able to figure out any pattern.  When it does happen, the interface incorrectly reports no matches - which is not ideal.

[Error - 7:22:22 am] 'references' request failed with error.
Error processing request. Debug Failure. False expression: 
Error: Debug Failure. False expression: 
    at Object.assert (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2898:23)
    at importerFromModuleSpecifier (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:62027:22)
    at forEachImport (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:61985:28)
    at getDirectImportsMap (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:61962:17)
    at Object.createImportTracker (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:61736:36)
    at Object.getImportSearches (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:62476:59)
    at searchForImportsOfExport (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:62512:32)
    at getImportOrExportReferences (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:62793:21)
    at getReferencesAtLocation (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:62731:17)
    at getReferencesInContainer (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:62693:21)

**Comment by mjbvz** [comment] 2017-05-17 01:10
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/15814

To test this, try installing typescript@next and using this new TS version in your workspace: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

Closing as upstream duplicate

**Closed by mjbvz** 2017-05-17 01:10 UTC
Labels: bug, duplicate, javascript, upstream

**Comment by stephensong** [comment] 2017-05-17 02:09
Hmm...  hardly seems to qualify as a "duplicate" imho, but anyway ...

I tried installing typescript@next to test if your theory was correct, but I got the following in response:

    `-- typescript@2.4.0-dev.20170516  invalid

so I am unable to confirm or deny whether or not this had indeed been "fixed". 

I must say closing this on the basis of a vague hunch seems a tad ...  eager.

**Comment by mjbvz** [comment] 2017-05-17 02:19
@stephensong Invalid usually just means there's a conflict with the typescript dependency listed in your package.json. It still should have installed the updated version

This issue is upstream with TypeScript though. I suspect 15814 because `implementation` and `references` share much of the same code. If after updating to typescript@next you don't see the issue resolved, please open a new issue against TypeScript:  https://github.com/Microsoft/TypeScript/issues/new

**Comment by stephensong** [comment] 2017-05-17 02:32
ok, thanks.  I can confirm that it is fixed under typescript 2.4.0-dev.20170516.

**Comment by stephensong** [comment] 2017-05-17 03:27
Alas, the 2.4.0-dev version introduces it's own issues.  I guess I'll just have to wait for 2.4 to be released.  Or might the 15814 fix appear before that perhaps (2.3.3)?
