### ISSUE TITLE
Allow to disable textual completion prosals for an position or language

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2496] opened 2016-01-28 15:06 UTC
At the moment when none of the contributed completion processors returns any proposals, the textual completion processor starts adding proposals.
That's fine for languages where we have no sophisticated completion processor, but looks bad for languages that pretend to have a 'smart' completion processor.

**Comment by jrieken** [comment] 2016-01-28 15:27
> That's fine for languages where we have no sophisticated completion processor, but looks bad for languages that pretend to have a 'smart' completion processor.

Well, I love it in TypeScript even tho it's smart. Textual completion proposes variable names, completes in comments and in strings, etc. Such a flag should only be used when having great confidence, like in member completion. 

One option will be to add a `isComplete` flag to the `CompletionList` tho that's a big hammer. I can image some smart extension wanting to add quick fixes as completion proposals - like _add method_ when doing unsuccessful member completion. We have to make sure we don't disable such scenarios with such a hammer.

**Comment by jrieken** [comment] 2016-03-08 15:46
closing as duplicate of #1657

**Closed by jrieken** 2016-03-08 15:46 UTC
Labels: api, feature-request
