### ISSUE TITLE
Multiple shells in integrated terminal

### ISSUE THREAD

**Issue by bckelley** [microsoft/vscode#113924] opened 2021-01-06 16:49 UTC
I know it's been said before but I'm going to say it again! It's 2021, the fact that we can't open multiple shell windows in the integrated terminal is crap especially since microsoft knows how to do it i.e Windows Terminal, the fact we don't have it is pure laziness, update your code!

**Comment by meganrogge** [comment] 2021-01-06 22:19
Duplicate of #10546

**Closed by meganrogge** 2021-01-06 22:19 UTC
