### ISSUE TITLE
visual studio code crash and running slow

### ISSUE THREAD

**Issue by bshaw2424** [microsoft/vscode#80132] opened 2019-08-30 20:36 UTC
visual studio code keeps crashing when I try and start it up. It just alerts a message that is has crashed and to try and reopen it. After a few tries when I do get it up and running, it is really slow.
Has been like that for a few days now. Tried to even disable my extensions and reinstall visual studio code but that did not work either. Any information would be appreciated.

**Comment by bshaw2424** [comment] 2019-09-03 01:54
**Visual Studio Code version:** 1.37.1

**System information:**
CPUs Intel(R) Pentium(R) CPU N3520 @ 2.16GHz (4 x 2167)
GPU Status 2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_deferred_display_list: disabled_off
skia_renderer: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	3.89GB (1.36GB free)
Process Argv	
Screen Reader	no
VM	0%

**Extensions installed:**
bracket-pair-colorizer | Coe | 1.0.61
prettier-vscode | esb | 2.2.2
beautify | Hoo | 1.5.0
dotenv | mik | 1.0.1
debugger-for-chrome | msj | 4.11.7
material-icon-theme | PKi | 3.9.0
LiveServer | rit | 5.6.1

Sometimes my editor wont even work. it will just says window crashed and give me the option to reopen or close. It takes several attempts to reopen before my visual studio code editor works. 
When it does finally not crash it is very slow and lagging. 
This has been happening for about two weeks now.

**Comment by rensa** [comment] 2019-09-03 04:43
I'm not getting performance problems (ie. slowness), but I _am_ getting frequent crashes (perhaps every 10–20 mins when doing a variety of tasks, so I'm having trouble pinning reproducibility down) that started a couple of weeks ago.

The window first stops responding to input and eventually pops up a dialog labelled "Stopped responding" with a button to "Reopen the window". I've confirmed that this occurs even with all extensions disabled.

**Version:** 1.37.1 (user setup)
**Commit:** f06011ac164ae4dc8e753a3fe7f9549844d15e35
**Date:** 2019-08-15T16:17:55.855Z
**Electron:** 4.2.7
**Chrome:** 69.0.3497.128
**Node.js:** 10.11.0
**V8:** 6.9.427.31-electron.0
**OS:** Windows_NT x64 10.0.18362

**System information:**

CPUs | Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.93GB (2.96GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by bpasero** [comment] 2019-09-03 12:23
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rensa** [comment] 2019-09-04 23:43
@bpasero I've been running Insider (commit 3db7e09f3b61f915d03bbfa58e258d6eee843f35) for about 24 hours and haven't had any problems!

**Comment by rensa** [comment] 2019-09-05 03:26
For me, this problem doesn't occur (even in the non-Insiders build) if I don't open any integrated terminals. Will update if I narrow reproduction down any further!

**Comment by bpasero** [comment] 2019-09-05 04:50
@Tyriar 

> This problem doesn't occur (even in the non-Insiders build) if I don't open any integrated terminals.

**Comment by Tyriar** [comment] 2019-09-05 23:29
Looks like a duplicate of https://github.com/microsoft/vscode/issues/71966

Currently working through the problem with the Windows console team.

/duplicate https://github.com/microsoft/vscode/issues/71966

**Closed by Tyriar** 2019-09-05 23:29 UTC
Labels: freeze-slow-crash, needs more info
