### ISSUE TITLE
RFE: Further bracket match styling customizations

### ISSUE THREAD

**Issue by photex** [Microsoft/vscode#40073] opened 2017-12-12 07:46 UTC
Howdy awesome vscode folks,

It would be nice to have some more options to how matching brackets are highlighted. For me personally I don't want the outline or background, I'd just like to change the foreground color (perhaps make the font bold).

Cheers!

**Comment by sbatten** [comment] 2018-09-20 22:33
duplicate of #19534

**Closed by sbatten** 2018-09-20 22:33 UTC
Labels: editor-brackets, feature-request
