### ISSUE TITLE
Incorrect jsdoc IntelliSense @type from d.ts interface

### ISSUE THREAD

**Issue by jt000** [Microsoft/vscode#44777] opened 2018-02-28 22:23 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10 v1709

Steps to Reproduce:

1. Create npm project that includes "inquirer" (`npm init && npm install --save inquirer`)
2. Add JS file with the following

```javascript
const inquirer = require('inquirer')

const goodIntellisense = inquirer.createPromptModule();

/** @type {inquirer.PromptModule} */
const badIntellisense = null;
```

3.  typing `goodIntellisense.` shows methods in inquirer.PromptModule
4. typing `badIntellisense.` shows same options inquirer.Inquirer (i.e. createPromptModule(), etc)
**Expected:** badIntellisense should show the same intellisense as goodIntellisense

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-03-01 02:49
Same root cause as https://github.com/Microsoft/TypeScript/issues/21551

Will be looking into this next iteration. Closing as upstream

**Closed by mjbvz** 2018-03-01 02:49 UTC
Labels: javascript, upstream
