### ISSUE TITLE
Allow to Undock Editor Panel

### ISSUE THREAD

**Issue by mkeuschn** [Microsoft/vscode#17064] opened 2016-12-12 09:07 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10

In Visual Studio it is possible to drag a window out of the main application to drop it on the second screen. In Visual Code I have to open a second instance and than I can drop it (but in the first window the file stays open). 

It would be nice, if the behaviour is the same as in Visual Studio.

**Comment by mlewand** [comment] 2017-03-14 14:13
@bpasero @mkeuschn isn't it a duplicate of #10121?

**Closed** 2017-03-14 14:27 UTC
Labels: feature-request, workbench
