### ISSUE TITLE
Dialog not showing up when uninstall Vetur package.

### ISSUE THREAD

**Issue by howilliams** [Microsoft/vscode#40368] opened 2017-12-17 07:02 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
html-css-class-completion|Zig|1.14.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.4.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
docthis|joe|0.6.0
Angular2|joh|2.11.2
typings-autoinstaller|jvi|1.2.0
vue|liu|0.1.5
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.0.0
vuejs-extension-pack|mub|0.3.0
vetur|oct|0.11.5
java|red|0.16.0
sass-indented|rob|1.4.5
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
vscode-react-native|vsm|0.5.7
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment] 2017-12-17 07:56
Try deleting it from `~/.vscode/extensions`

**Comment by marswong** [comment] 2017-12-19 02:10
same problem, I even cannot uninstall any extension, any...

**Comment by sandy081** [comment] 2017-12-19 08:59
@howilliams @marswong Can you please explain in detail about the issue. 

Are you getting any errors in
- Dev tools. Open by running command `Toggle Developer Tools`
- Shared process. Open by running command `Toggle Shared Process`

**Comment by marswong** [comment] 2017-12-19 11:03
@sandy081 Sorry, I cannot reproduce it now. When I try to reinstall and reuninstall extensions, it works without errors in `Developer Tools` and `Shared Process`. Are there any changes of the Extension Interface from `code 1.17.0` to `code 1.19.0`? Cause my extensions had been installed since `1.17.0`, and I never try to uninstall them until today (`1.19.0`). Thank you :)

**Comment by sean-mcmanus** [comment] 2017-12-19 21:08
I'm also unable to uninstall extensions. Seems like it could be a 1.19 regression. It gets stuck saying "Uninstalling" with no errors in the developer tools.

**Comment by 105th** [comment] 2017-12-20 08:48
@ramya-rao-a 
> Try deleting it from ~/.vscode/extensions
This way helped with 'rm -rf' command, thanks a lot!

**Comment by sandy081** [comment] 2017-12-20 09:17
I see multiple users complaining about this, which we also reported internally - https://github.com/Microsoft/vscode/issues/39612

As @sean-mcmanus says, the dialog is not being shown and uninstall gets stuck in that state.

@bpasero @joaomoreno FYI

**Comment by sandy081** [comment] 2017-12-20 09:27
Since this is not reproducible consistently and also could be a timing issue, I would put some logs today in this flow and retry

**Comment by bpasero** [comment] 2017-12-20 09:34
I will also add some logs to the dialog usage in renderer and main side.

**Comment by sandy081** [comment] 2017-12-20 17:36
Also added some logs for the uninstall lifecycle.

Please use the insiders tomorrow and check if you see this issue again. If it is, please provide us all logs.

Thans

**Comment by ramya-rao-a** [comment] 2017-12-21 04:36
One way I could repro this earlier is to have the extension code folder ($HOME/.vscode/extensions/extension-to-be-uninstalled) opened and then try to uninstall the extension. Since the files to be deleted are opened in vscode, uninstalling fails but doesn't tell the user that.

**Comment by sandy081** [comment] 2017-12-21 09:51
@ramya-rao-a Were you getting the dialog to uninstall in the scenario you mentioned?

![image](https://user-images.githubusercontent.com/10746682/34250337-d987e854-e63c-11e7-938b-e1ba95e34502.png)

I suspect from what users complain, it is that the above dialog itself does not appear.

**Comment by ramya-rao-a** [comment] 2017-12-26 05:27
@sandy081 From what I can recall, the dialog wouldn't appear. But I cannot repro this any more in stable or insiders

**Comment by bartoszdurda** [comment] 2017-12-28 08:06
I have the same problem, dialog doesn't appear, uninstalling label is disabled and after vscode restart extension is still installed. I observed this bug occurs in current version when i'm trying to uninstall extension immediately after vscode restart. If i wait some time after vscode was launched, it works and the dialog appears properly. This scenario happens on 3 PC which i have tried. For me insiders version works good.

**Comment by bpasero** [comment] 2017-12-28 08:32
@bartoszdurda thanks for the missing hint here how to reproduce! I can reproduce as well in stable when pressing the uninstall button quickly enough after starting up and I would guess the underlying issue is again the delayed startup of the shared process (which @alexandrudima reverted in insiders via https://github.com/Microsoft/vscode/issues/40425).

**Comment by sandy081** [comment] 2018-01-08 10:56
@bartoszdurda Thanks for the hint.

@bpasero So #40425 is the root cause of this.reverted, this is no longer happening in insiders? 

Since #40425 reverted and this is no longer happening in insiders, closing this issue. I also associated this to the issue #40505 that is to revisit delaying startup of shared process.

**Closed by sandy081** 2018-01-08 10:56 UTC
Labels: extensions
