### ISSUE TITLE
Blurred when losing focus

### ISSUE THREAD

**Issue by orphanBB** [microsoft/vscode#115189] opened 2021-01-27 06:12 UTC
- VSCode Version:1.52.1(user steup)
- OS Version:Windows 10 Professional Insider Preview 2004      21296.1010

Steps to Reproduce:

1.Open VScode and make the window maximum
2.Open another software and make it‘s window smaller than VS code
3.Make the mouse’s focus on the second software，than the VScode will be fuzzy，if move the second software，it will be more fuzzy.

Move the VScode when it is not the maximum,it still exists.

![1.png](https://orphanbb-picgo.oss-cn-shenzhen.aliyuncs.com/other/VScode_issue/1.png)
![2.png](https://orphanbb-picgo.oss-cn-shenzhen.aliyuncs.com/other/VScode_issue/2.png)

[video1](https://orphanbb-picgo.oss-cn-shenzhen.aliyuncs.com/other/VScode_issue/record-14.02.05%5B27.01.2021%5D.mp4)
[video2](https://orphanbb-picgo.oss-cn-shenzhen.aliyuncs.com/other/VScode_issue/record-14.04.08%5B27.01.2021%5D.mp4)

Does this issue occur when all extensions are disabled?: Yes/No
Yes
I have uninstall all extensions and re-install the vscode，it still exists.

**Comment by yume-chan** [comment] 2021-01-27 07:28
Duplicate of #93356

At this point workaround is either pass --disable-gpu on application start e.g. code --disable-gpu or use steps in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

@deepak1556 #93356 doesn't contain a definitive resolution, has it really been fixed or only workarounded?

**Comment by IllusionMH** [comment] 2021-01-27 10:35
Same as recent #114552 which is duplicate of #93356

Could you please check if it is reproducible for you in Insiders builds? https://code.visualstudio.com/insiders/

**Comment by orphanBB** [comment] 2021-01-27 12:02
Thank you.
This reminded me to change the graphics card settings。
After  I changed the global Nvidia high performance to automatic switching in the graphics control panel,it was solved.

**Closed** 2021-01-27 12:03 UTC
