### ISSUE TITLE
Problem with unreadable texts in tabs due to low contrast, brightness

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#18947] opened 2017-01-20 21:20 UTC
Most themes (and I think it's not their fault) use in effect very unreadable colors with low brightness/contrast ratios for inactive tabs, since they are faded using opacity. This is very inconvenient - not being able to clearly see what files are open and finding easily the ones I want. Especially if you are working at night with decreased screen brightness or in bright light (in the morning).

Currently:
![image](https://cloud.githubusercontent.com/assets/821272/22165447/1ee1347a-df5c-11e6-8096-e2d825a38cf1.png)

Illutration how the issue could be improved:
![image](https://cloud.githubusercontent.com/assets/821272/22165607/0f8b09b4-df5d-11e6-8fbf-74f14ff87329.png)

I am not proposing a solution, as I feel it may come from multiple directions e.g..:
- allow themes to customize tabs styling
- do not use opacity to fade inactive tab, highlight active tab by other means
- allows custom user styling of tabs...

**Comment by steph643** [comment] 2017-03-17 08:59
+1
This is, in my opinion, the most annoying issue in vscode.

**Comment by bpasero** [comment] 2017-05-29 10:08
In 1.13 this will be under full control either by the theme picked or user settings. Closing as duplicate of https://github.com/Microsoft/vscode/issues/27067

**Closed by bpasero** 2017-05-29 10:08 UTC
Labels: ux, workbench, workbench-tabs
