### ISSUE TITLE
Find widget needs better responsive design

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11390] opened 2016-09-01 13:14 UTC
IMO the last thing to leave the view should be the `X` action to close the widget. The first thing to leave should be the find counter.

Also, notice how the overflow goes into the next line and it still visible through some cheese.

![bug](https://cloud.githubusercontent.com/assets/22350/18168558/a72715d6-7056-11e6-87b4-fb500480a257.gif)

**Comment by alexandrudima** [comment] 2016-09-01 13:16
I agree. Duplicate of #2338

**Closed by alexandrudima** 2016-09-01 13:16 UTC
