### ISSUE TITLE
GIT: modification to staged file not detected

### ISSUE THREAD

**Issue by xrfang** [Microsoft/vscode#35606] opened 2017-10-05 03:53 UTC
VSCode Version: 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d)
OS Version: Kubuntu 17.04 (Linux x86_64 4.10.0)

Steps to Reproduce:

1. under a local git repo, create a new file in vscode, stage it (but not commit) 
2. make changes to the staged file, you can see the change via git under command line, but in vscode, the changes are not detected. 
3. If I shutdown vscode, then re-open it, the change is detected.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment] 2017-10-05 07:47
Are the changes detected without staging the file beforehand?

**Comment by kumarharsh** [comment] 2017-10-06 08:34
Happens with me too in latest build.

I also observed two related issues while in the SCM view:

1. when clicking on *some* files in the sidebar, the changes don't get displayed in the diff pane. The clicks don't even register in the *Git Output Panel*, meaning, I don't get a line like this for some files:

```
git show HEAD:ui/src/.../app.js
git show HEAD:ui/src/screens/.../test.js
```

2. I renamed some files, and while staging, clicking the **+** button on one file failed to put it into the staged changes list, no matter how many times I tried. I had to go to the terminal and manually do a `git add`. VSCode was showing some error related to `invalid URI...` or something like that.

Just reloading the vscode window fixed both these errors. Seems like the git commands fail for some reason, and vscode caches the result and doesn't even try to execute them again, or something like that...

**Comment by joaomoreno** [comment] 2017-10-06 09:28
Very interesting.

@bpasero Could this be your issue too?

**Comment by bpasero** [comment] 2017-10-06 09:33
Yeah sounds a bit, though in my case it was never a new file as far as I remember.

**Comment by kumarharsh** [comment] 2017-10-06 10:30
@joaomoreno OS is Windows 10 CU.

VSCode details:
![image](https://user-images.githubusercontent.com/760112/31274154-6333065c-aaaf-11e7-8639-f0832b675faf.png)

**Comment by gulshan** [comment] 2017-10-07 10:22
Experiencing this issue. Diff is shown between current file and committed file, not staged file. Restarting vscode fixes it. Version-
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0

**Comment by joaomoreno** [comment] 2017-10-10 08:33
Duplicate of #35559

Releasing a fix in the September candidate release.

**Closed by joaomoreno** 2017-10-10 08:33 UTC
Labels: git, needs more info
