### ISSUE TITLE
"You'll need a new app to open this devtools link"

### ISSUE THREAD

**Issue by WilliamVenner** [microsoft/vscode#114871] opened 2021-01-25 01:52 UTC
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro 64-bit 10.0.18363

Steps to Reproduce:

1. Press Help > Toggle Developer Tools

![image](https://user-images.githubusercontent.com/14863743/105651697-7929c380-5eaf-11eb-8ab5-15b9da8a9211.png)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/14863743/105651861-e3426880-5eaf-11eb-9080-d9705d35deb2.png)

**Comment by yume-chan** [comment] 2021-01-25 06:12
Duplicate of #72621

**Closed** 2021-01-25 06:13 UTC
