### ISSUE TITLE
VSCode user account feature

### ISSUE THREAD

**Issue by noririco** [microsoft/vscode#97247] opened 2020-05-08 11:26 UTC
Can you please explain why there is no simple way to connect with VSCode as a VSCode user ? why it is so complicated ?

If I want to sync my settings in my day job (which work with git but not github), and at my home (i work with github), I cant do so....

**Comment by usernamehw** [comment] 2020-05-08 12:01
The syncing feature is in the preview state (only available in Insiders release for now): https://code.visualstudio.com/updates/v1_45#_settings-sync

/duplicate of #2743

**Closed** 2020-05-08 12:02 UTC
Labels: *duplicate
