### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by AlekseiMakhov** [microsoft/vscode#174202] opened 2023-02-12 22:00 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230210

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33923:11)
    at parseSimpleUnaryExpression (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33552:16)
    at parseUnaryExpressionOrHigher (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33520:35)
    at parseBinaryExpressionOrHigher (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33438:25)
    at parseAssignmentExpressionOrHigher (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33111:18)
    at parseExpression (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33077:16)
    at doOutsideOfContext (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30772:12)
    at allowInAnd (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30793:12)
    at parseExpressionOrLabeledStatement (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:34593:24)
    at parseStatement (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:34825:12)
    at parseListElement (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:31544:12)
    at parseList (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:31529:19)
    at parseSourceFileWorker (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30588:24)
    at Object.parseSourceFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30421:20)
    at createSourceFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30282:21)
    at createLanguageServiceSourceFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:134900:22)
    at acquireOrUpdateDocument (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:131822:26)
    at Object.acquireDocumentWithKey (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:131747:12)
    at getOrCreateSourceFileByPath (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135225:31)
    at Object.getOrCreateSourceFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135205:14)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135137:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:116904:24)
    at findSourceFileWorker (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119236:23)
    at findSourceFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119156:20)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119105:22
    at getSourceFileFromReferenceWorker (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119074:26)
    at processSourceFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119103:5)
    at processRootFile (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:118899:5)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:117684:41
    at forEach (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:2308:22)
    at createProgram (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:117684:5)
    at synchronizeHostData (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135161:15)
    at Object.getProgram (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135233:5)
    at ConfiguredProject2.updateGraphWorker (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:171784:41)
    at ConfiguredProject2.updateGraph (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:171721:32)
    at ConfiguredProject2.updateGraph (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:172903:24)
    at updateProjectIfDirty (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:173356:35)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175613:15
    at callback (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:173305:21)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:173284:57
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:173319:20
    at forEach (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:2308:22)
    at forEachResolvedProjectReferenceProjectWorker (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:173310:10)
    at forEachResolvedProjectReferenceProject (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:173281:22)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175609:11)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175881:64
    at flatMap (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175881:24)
    at updateOpen (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:177026:29)
    at /Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179593:69
    at IpcIOSession.executeWithRequestId (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179585:14)
    at IpcIOSession.executeCommand (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179593:29)
    at IpcIOSession.onMessage (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179635:51)
    at process.<anonymous> (/Users/chosen-one/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:181203:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.76.0-insider (Universal) (25514d899f4bd877803defb213719f8af3d997d3, 2023-02-07T05:23:26.688Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 9, 9|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 94f3c6a6-ed3e-43e0-8830-439c017803c5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
project-manager|ale|12.7.0
vscode-tailwindcss|bra|0.9.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
postcss|css|1.0.9
vscode-eslint|dba|2.4.0
githistory|don|0.6.19
gitlens|eam|13.2.0
vscode-archiver|ecm|0.0.27
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
vue-format|feb|0.1.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.58.1
vue-snippets|hol|1.0.4
tailwindcss-intellisense-twin|lig|3.0.0
git-graph|mhu|1.30.0
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|1.1.6
vscode-docker|ms-|1.23.3
vscode-typescript-next|ms-|5.0.202302100
material-icon-theme|PKi|4.24.0
tsimporter|pmn|2.0.1
vscode-yaml|red|1.11.0
vue-vscode-snippets|sdr|3.1.1
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.10.0
autoimport|ste|1.5.4
vscode-stylelint|sty|1.2.3
sort-lines|Tyr|1.9.1
vue-ls-snippets|van|0.0.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
volar|Vue|1.0.24
vscode-typescript-vue-plugin|Vue|1.0.25
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
tailwind-snippets|Zar|1.0.1
vue-component|zhu|1.1.0
vue|znc|0.13.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192:30661256

```

</details>

**Comment by mjbvz** [comment] 2023-02-21 02:30
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-21 02:30 UTC
