### ISSUE TITLE
Hot Exit: Very difficult to get out of a bad search/replace

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16827] opened 2016-12-07 15:01 UTC
Testing #16544

* create a file `generator.js`
```js
var fs = require('fs');

for (var i = 0; i < 200; i++) {
	fs.writeFileSync('consumer_'+i+'.ts', `
import {x} from './provider';

console.log(x);
`)
}

fs.writeFileSync('provider.ts', `
export var x = 'Hello world';
`)
```
* run `node generator.js`
* open the folder where you have generated these files
* do a search for `x` whole words, case sensitive, `*.ts` files only
* replace everything with `y`
* run the replace
* close VS Code
* open VS Code
* the files are restored and **slowly** dots are appearing next to the file names. (why slowly?)
* try to close all the files (via right click close all, or via the close all editors action in the explorer)
> You get prompted for each and every one. This is a regression IMHO since in the stable version there is a single dialog that prompts me for all 200+ files:

![image](https://cloud.githubusercontent.com/assets/5047891/20972759/3b5fb326-bc96-11e6-89be-6708900f94f1.png)

**Comment by bpasero** [comment] 2016-12-07 15:49
This is a duplicate of https://github.com/Microsoft/vscode/issues/8009 which is now becoming more important with the advent of hot exit being on by default.

**Comment by Tyriar** [comment] 2016-12-07 17:21
The slow dirty indicator is being discussed in #16584, let's close this off as a duplicate of that and #8009.

**Closed by Tyriar** 2016-12-07 17:21 UTC
