### ISSUE TITLE
Saving and CPU Usage Issues

### ISSUE THREAD

**Issue by shadeed** [Microsoft/vscode#13976] opened 2016-10-19 06:09 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: ms-vscode.Theme-MarkdownKit-0.1.1, ms-vscode.csharp-1.4.1, swyphcosmo.spellchecker-1.1.6

Steps to Reproduce:
It happens randomly. 

Yesterday I noticed the following issues:
- Emmet-like functionality is not working. For example when I add `li` and hit `tab` key, it doesn't convert that to `<li></li>`. Instead, I got `libs` word.
- CPU usage was over 100%, my Macbook Pro fan went really loud.
- When I hit save, it doesn't save anything. I need to restart the editor a couple of times.

Any help please?

Thanks,

**Comment by aeschli** [comment] 2016-10-19 07:12
That's when editing HTML? Or PHP?

**Comment by shadeed** [comment] 2016-10-19 07:22
@aeschli .html files

**Comment by aeschli** [comment] 2016-10-26 15:17
I was able to reproduce the 'libs' with
```html
<!-- libs -->
li
```
Typing li will bring up the suggestion widget proposing 'libs'. Pressing Enter will select the proposal.
If you want Emmet, make sure no suggestion window is open (press escape).

On the slowness/deadlock, can you run vscode without extensions and see if the slowness is caused by an extension?

**Comment by aeschli** [comment] 2017-02-01 15:04
closing. Need more information.

**Closed by aeschli** 2017-02-01 15:04 UTC
Labels: freeze-slow-crash, needs more info
