### ISSUE TITLE
Comments are very wide which makes text harder to read

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#170098] opened 2022-12-27 11:22 UTC
Current has a very wide container so it's harder than normal to read the text

![image](https://user-images.githubusercontent.com/2193314/209659150-2dc68363-0c2c-4b3e-bd79-3986fb9d7669.png)

Proposal (keeping the image wider would be ideal):

![image](https://user-images.githubusercontent.com/2193314/209659506-19d3b7e8-ca82-4767-8c76-bafc794060ee.png)

**Comment by alexr00** [comment] 2022-12-27 14:16
Duplicate of https://github.com/microsoft/vscode/issues/150824

**Closed by alexr00** 2022-12-27 14:16 UTC
