### ISSUE TITLE
Markdown list item word-wrap hanging indent

### ISSUE THREAD

**Issue by Kroc** [microsoft/vscode#167314] opened 2022-11-26 21:13 UTC
When word-wrapping is enabled, Markdown documents already automatically indent the wrapped lines to match scope *except* for lines that contain bullet/numbered points.

For example, the following:

![image](https://user-images.githubusercontent.com/142650/204108921-b7ff7689-9345-42b6-9119-899b925d3433.png)

Should really render as:  
(without the hard line-breaks)

![image](https://user-images.githubusercontent.com/142650/204109043-840fbcb0-2603-4c2f-9386-49d345be336f.png)

This improves visual fidelity and matches the HTML output closer.

**Comment by mjbvz** [comment] 2022-11-28 23:56
Duplicate of #164267

**Closed by mjbvz** 2022-11-28 23:56 UTC
