### ISSUE TITLE
Multiple commas in header throws compile time error

### ISSUE THREAD

**Issue by tonymanuel** [microsoft/vscode#107564] opened 2020-09-28 06:24 UTC
Issue Type: <b>Bug</b>

Type a React component name that you want to import. While typing vs code intellisense shows the auto import options. Once you click on auto import, the component get imported and if it a named import from a file, there will be multiple commas appended in the imported header and throws compile time error. Eg: import {TextField,,Radio} from "somePackage". This issue started occuring from my last update

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1814)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|11.62GB (1.49GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id e3aec01a-1e7e-46e4-816c-9c96f8476ab2|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
php-xdebug|kak|0.0.7
debugger-for-chrome|msj|4.12.11
vscode-php-getters-setters|php|1.2.3

</details>

**Comment by mjbvz** [comment] 2020-09-28 17:19
Duplicate of #105214 and #106735

**Closed by mjbvz** 2020-09-28 17:19 UTC
Labels: new release
