### ISSUE TITLE
Issue with using Tab or Enter when performing short hand code (not for sure if short hand is the way to put it but it works)

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#11719] opened 2016-09-08 21:35 UTC
- VSCode Version: Code 1.5.0 (4fc690be310dd02e0ab6529c0b9bf348a8b26a19, 2016-09-08T09:09:27.395Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Type Table and hit tab
2. Type tr and hit tab

What used to happen is the cursor would be placed in between the tr tags `<tr>cursor would be here</tr>` after hitting the tab key on a tr or td tag.  Since the last update, it now goes to the end of the line which isn't too aggravating if you have just the tr and nothing else.  It become aggravating when you have something like this:

`<td><input type="text" name="something" id="something" value="something"></td>`

Let's say you forgot to change or want to add some styles to the td tag.  

Steps to Reproduce:

1. Go into the td tag and hit space just after the 'd' in 'td'
2. Type 'style' and hit tab

Instead of placing the cursor inside the style tag `style="cursor goes here"`, you end up with:

`<td style=""><input type="text" name="something" id="something" value="something"></td>CURSOR IS WAY OVER HERE`

**Comment by pzmosquito** [comment] 2016-09-08 21:53
I have the same issue, with Code 1.5.0 on OS X 10.11.6
cursor goes to the end of the line when auto completes HTML attribute

**Comment by ramya-rao-a** [comment] 2016-09-08 22:37
@BrandonRice I can see cursor going to end of line when auto completing the HTML attribute but not the tag.
i.e 
Type `table` and hit `TAB` -> cursor is in between the starting and closing tag (as expected)
Type an attribute like your `style` example and hit `TAB` -> cursor is goes to end of line instead of staying inside the quotes so that user can provide value for the attribute

Can you confirm?

**Comment by ramya-rao-a** [comment] 2016-09-08 22:39
@egamma @mrmlnc This is related to emmet?

**Comment by mrmlnc** [comment] 2016-09-09 06:31
@ramya-rao-a, nope, it's not Emmet. This is related to `snippetController.ts` after a6d74abc42c843d87e096c67cd5c63c5e938c540 by @jrieken.

Works fine before 3e87aced31c90e9e0227d600d3571af6d33c839d and broken after 5fbe501da2f32576c25ad3f0a161a9c95a8539df.

**Comment by jrieken** [comment] 2016-09-09 07:27
@aeschli will know. @mrmlnc Is this with multiple cursors?

**Comment by mrmlnc** [comment] 2016-09-09 07:35
@jrieken, no, just one.

![2016-09-09_10-34-23](https://cloud.githubusercontent.com/assets/7034281/18379036/04e8f8a6-7679-11e6-8ece-3bfb1e318d1f.gif)

**Comment by ITSecMedia** [comment] 2016-09-09 07:53
Definitely a new issue with shortcode cursor positioning. 
The cursor position is wrong on every use.
Happens here  since the last update to V1.5 and 1.5.1

**Comment by mrmlnc** [comment] 2016-09-09 08:33
@jrieken, I think here should be `snippet`.

```ts
private _runForAllSelections(...): void {
   // ...
  for (let i = 0; i < selections.length; i++) {
    // ...
    if (i === 0 && snippet.isSingleTabstopOnly) {
      const finalCursorPos = SnippetController._getSnippetCursorOnly(adaptedSnippet);
      // ----------------------------------------------------------------- ^
    }
  }
}

**Comment by jrieken** [comment] 2016-09-09 10:09
Ack - the is a regression. Closing this as a duplicate of #11742 because it contains already more info

**Closed by jrieken** 2016-09-09 10:09 UTC
Labels: html
