### ISSUE TITLE
`statusBar.fontSize` seems to be sadly absent in configurability

### ISSUE THREAD

**Issue by ozra** [Microsoft/vscode#43299] opened 2018-02-09 09:16 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-livescript-preview|ehe|1.0.2
livescript|pse|0.1.1

Feature request.

The fontsize in the statusbar is microscopic on my machine, all other features of the asides are fine. I can use ctrl-+, but that makes the other parts (sidebars etc.) clumsily big. It's just all disproportionate — at least to my standards and tastes.

If `statusBar.fontSize` is to tricky in order to maintain layout integrity, could perhaps `statusBar.zoomLevel` — taking precendence over `window.zoomLevel` — be an alternative?

I'm otherwise extremely surprised and happy to have found a Microsoft product I actually enjoy XD Keep up the good work!

[pardon any language-misuse, I'm Swedish]

[edit:]
I have only used the editor for two days, and haven't looked in to extension writing yet. Is it possible to manipulate the statusBar from script, to change the formatting of row/col and preferably also it's fontsize? That's the most sticking point. I'd like a clear and large "47:13" instead of a tiny "Ln 47, Col 13" (weird presentation!?)

**Comment by bpasero** [comment] 2018-02-09 10:08
Duplicate of https://github.com/Microsoft/vscode/issues/519

**Closed by bpasero** 2018-02-09 10:08 UTC

**Comment by ozra** [comment] 2018-02-09 14:20
Alright, sorry, I did my best searching the issues, there where quite a few ;-)
