### ISSUE TITLE
Regression: keyboard shortcut to switch to Explorer (Ctrl+Shift+E) fails

### ISSUE THREAD

**Issue by AviVahl** [Microsoft/vscode#56819] opened 2018-08-20 13:35 UTC
This got broken in 1.26.0, I believe. Will reinstall 1.25 and report back.
EDIT: 1.25.1 works as expected. Insiders (code-insiders-1.27.0-1534754880.el7.x86_64.rpm) still broken.

- VSCode Version: 1.26.1
- OS Version: Fedora 28

Keyboard shortcut to switch to Explorer (Ctrl+Shift+E) fails

Steps to Reproduce:

1. Focus on code editor, somewhere in the text.
2. Press Ctrl+Shift+E.

Temporary `e` is written inline code, with different color. If you press it several times (~10-11), it adds capital `E`s, so the following is inlined: `eEEEEEEEEEE`. After several key presses, the text disappears.

If caps lock is turned on, shortcut works.

Also, if I try pointing another command to ctrl+shift+e (using keybindings settings in vscode), it says `ctrl+shift+unknown` when I use `e`. Very weird.

Does this issue occur when all extensions are disabled?: **Yes**

My `keybindings.json` and `settings.json`:
[keybindings-and-settings.zip](https://github.com/Microsoft/vscode/files/2302544/keybindings-and-settings.zip)

**Comment by sandy081** [comment] 2018-08-20 14:21
Duplicate of https://github.com/Microsoft/vscode/issues/48480

**Closed** 2018-08-20 14:21 UTC
Labels: *duplicate, new release
