### ISSUE TITLE
"Fold All Regions" is not working on markdown

### ISSUE THREAD

**Issue by kenng** [Microsoft/vscode#48077] opened 2018-04-17 21:11 UTC
markdown collapse "Fold All Regions" is not working.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. define the region and endregion in a markdown file
```
## [ topic ] My Topic
<!-- #region -->
my content
<!-- #endregion -->

## [ topic ] My Second Topic
<!-- #region -->
my content 2
<!-- #endregion -->
```
2. run command >Fold All Regions. 
Result:
Region is not collapsing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kenng** [comment] 2018-04-17 21:13
Could be a duplicate issue of 
Collapse/expand regions does not work (#47308)

**Comment by mjbvz** [comment] 2018-04-17 22:18
Duplicate of #45118 

You should be able to fold document areas by heading level. Folding regions in markdown were sort of an ugly hack we added before we supported proper syntax-aware folding

**Closed by mjbvz** 2018-04-17 22:18 UTC
Labels: editor-folding, markdown
