### ISSUE TITLE
Problem on Maximize Window

### ISSUE THREAD

**Issue by didiokener** [microsoft/vscode#84176] opened 2019-11-08 00:22 UTC
Issue Type: <b>Bug</b>

The Window Chrome should maximize normally but, the bug seems to be like a electron`s bug that happens when the frame window is false and you make your own customizable frame (Electron Frameless), i already tried fix this issue in my own application i have developed but i had no success.
It would be great if you guys can fix this electron`s problem. 
Thanks for listening

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
npm-intellisense|chr|1.3.0
angular-schematics|cyr|2.2.0
vscode-ionic-snippets|fiv|1.7.1
html-slim-scss-css-class-completion|gen|1.5.21
vscode-pull-request-github|Git|0.12.0
html-tag-wrapper|hwe|0.2.3
ionic-preview|ion|0.0.18
path-autocomplete|ion|1.13.3
Angular-BeastCode|Mik|8.0.10
vsliveshare|ms-|1.0.1123
cordova-tools|msj|1.9.0
debugger-for-chrome|msj|4.12.1
angular-console|nrw|8.1.2
material-icon-theme|PKi|3.9.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2019-11-08 13:00
@didiokener as a workaround you can configure `"window.titleBarStyle": "native"`. Does that "fix" it?

**Comment by didiokener** [comment] 2019-11-08 13:52
@bpasero  Yes, it did. Thanks for helping. One last question, why does it happen? Is it a compatibility problem with electron and windows 10 1903? Thanks a lot again

**Comment by sbatten** [comment] 2019-11-08 19:12
@didiokener sorry, I did not quite follow the bug description. Are you saying the maximize button is just not working?

**Comment by wongjn** [comment] 2019-11-08 19:22
I think I have the same problem (with dual screens):

1. Press the maximize button with window in screen 2 (right)
2. Screen “maximizes” to screen 1 (left)
  - Maximize button is still there instead of what should be the restore button
  - I can still drag the window around at this new size; as though it is not maximized but simply resized the the screen size.
3. Using Window's aero snap (dragging the window to the top of the screen) on screen 2 maximizes it, but it renders over the task bar (I have the taskbar at the bottom with autohide)

Native solves these problems, but I like the look of custom so much better!

**Comment by sbatten** [comment] 2019-11-08 19:38
@wongjn If this is the same issue, then this is a duplicate of https://github.com/microsoft/vscode/issues/81102

I will close as duplicate but if @didiokener feels these are different, we can re-open

**Closed by sbatten** 2019-11-08 19:39 UTC
Labels: needs more info, new release

**Comment by didiokener** [comment] 2019-11-08 19:40
@wongjn That`s it, @wongjn described better than me, but in my case it does the same problem with one screen
