### ISSUE TITLE
[JavaScript/Node.js] Support for "Go to definition" of code located in "node_modules"

### ISSUE THREAD

**Issue by drywolf** [Microsoft/vscode#2550] opened 2016-01-29 15:54 UTC
I am using "npm link ../../lib/my-lib" to symlink a local module that is shared across several apps into the "node_modules" directory of each of the apps. This is nice for developing the shared lib in combination with all the apps.

    // a standard npm module, can't navigate to its definition
    var shortid = require('shortid');
    // some functions from a symlink-ed local module inside node_modules, can't navigate to it either
    var ModelMountUtils = require('@ipp/loopback-lib').ModelMountUtils;
    var RemoteMethodUtils = require('@ipp/loopback-lib').RemoteMethodUtils;

VS-Code does not allow me to navigate to this shared libraries' code by pressing F12 or "Go to definition". The same applies for all other npm modules inside the node_modules directory.

Is this restricted functionality intentional ? or should it be working and I am running to a JS parsing bug that prevents the "Go to definition" to do its work ?
If the "Go to definition" feature is not supposed to work for all things "node_modules" ... could we integrate an exception for symlink directories inside node_modules ?

Thanks

**Comment by jrieken** [comment] 2016-01-29 18:06
That's a bug. We will soon ship with a revamped JS language support and such things should be fixed then

**Comment by drywolf** [comment] 2016-01-31 19:05
Nice, I'm looking forward to the next release :smile:

**Comment by girvo** [comment] 2016-08-17 04:25
Just checking, this still seems to be broken in the latest Insider build. Is that expected behaviour? It's a React Native Javascript project, if that matters :)

**Comment by zjaml** [comment] 2016-09-09 07:01
Subscribed to this too. The feature could be very useful.

**Comment by jrieken** [comment] 2016-09-09 08:16
@waderyan This is an issue with the typescript brain

**Comment by waderyan** [comment] 2016-09-09 13:08
@jrieken just to make sure I understand, when you say "typescript brain" you mean the TypeScript language service, correct?

**Comment by jrieken** [comment] 2016-09-09 15:27
yes

**Comment by waderyan** [comment] 2016-09-09 15:32
This issue was moved to Microsoft/TypeScript#10808

**Closed by waderyan** 2016-09-09 15:32 UTC
Labels: bug, js

**Comment by ramya-rao-a** [comment] 2016-09-28 22:36
Moving to next milestone, as this cannot be verified at the moment

**Comment by nguyennb9** [comment] 2017-09-07 01:41
Related to https://github.com/Microsoft/vscode/issues/26633 and I think it still not resolves yet.

**Comment by tucq88** [comment] 2017-09-21 10:45
@nguyennb9 Me too. Got the same issue with fresh install of Vscode. E.g I'm using Angular 4 and Bulma. Can go to definition of Angular but but it can't go to others. Kind of strange.
