### ISSUE TITLE
Extension debugger cannot connect when WiFi is Disabled

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#798] opened 2015-11-29 16:57 UTC
Debugging an extension does not work if the WiFi adapter is disabled on my laptop. (i.e in airplane mode). I get the message "Cannot connect to runtime process (reason: [object Object])", while the debug window said it could not connect to the debugger.

Additionally it would be nice for the debugging window to give  a better message than [object Object], and for it to log the message in the debug console.

![vscode_wifi_debug_issue](https://cloud.githubusercontent.com/assets/817264/11458555/31e39e50-96ba-11e5-8e26-6c3fe695b0b9.PNG)

**Comment by weinand** [comment] 2015-11-29 21:13
This is a duplicate of #619.

**Closed by weinand** 2015-11-29 21:13 UTC

**Comment by weinand** [comment] 2015-12-24 00:06
fixed by https://github.com/Microsoft/vscode-node-debug/pull/31
