### ISSUE TITLE
Port forwarding: unable to change port protocol to HTTPS

### ISSUE THREAD

**Issue by icleolion** [microsoft/vscode#201371] opened 2023-12-21 15:58 UTC
Type: <b>Bug</b>

Forward a port
Right click on forwarded port -> Change Port Protocol -> Select HTTPS.
Right click on forwarded port -> Change Port Protocol -> HTTP is still selected.
Nothing appears in the Output panel for "Port Forwarding" when attempting to change the port protocol, almost as if nothing is listening for a click event!

![image](https://github.com/microsoft/vscode/assets/47498402/0c656053-31d5-4a7c-90af-ff4588e63ab9)

My application listens on port 5000 for HTTP and 5001 for HTTPS.  Forwarding port 5000 is working fine.  5001 isn't working, which I'm assuming is due to the inability to change the port protocol.  All I eventually end up with is a 504.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (16 x 2195)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.99GB (6.80GB free)|
|Process Argv|--crash-reporter-id d268f487-8a1d-4815-bfed-99d8e80ca353|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
EditorConfig|Edi|0.16.4
auto-rename-tag|for|0.1.10
i18n-ally|lok|2.12.0
csharp|ms-|2.14.8
vscode-dotnet-runtime|ms-|2.0.0
vscode-versionlens|pfl|1.9.2
vscode-thunder-client|ran|2.16.3
vscode-stylelint|sty|1.3.0
vscode-icons|vsc|12.6.0
volar|Vue|1.8.25

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t:30925682

```

</details>

**Comment by alexr00** [comment] 2024-01-08 17:09
Marking as duplicate of #201465 since there's more discussion there.

**Closed by alexr00** 2024-01-08 17:09 UTC
