### ISSUE TITLE
error max limit

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#52736] opened 2018-06-23 22:34 UTC
existe a way to show more than 200 error list?
Or can you add a feature for user can set limit ?

 **"editor.error.maxLimit": 450,**

![image](https://user-images.githubusercontent.com/24865815/41814181-e9368be4-7713-11e8-8ad9-e422a2bc7819.png)
thank guys
i know this can give maybe a performance issue, but it only for debugging and i have a huge memory pc.

**Comment by TomSputz** [comment] 2018-06-23 22:37
That looks like it is probably an error thrown by the linter you are using rather than VSCode, maybe try using ESLint instead and seeing the output?

Also, *Why have you left so many errors*, surely you should be fixing them?

**Comment by djmisterjon** [comment] 2018-06-23 22:44
@TomSputz 
it not me lol , it from the pixi engine 
https://github.com/pixijs/pixi.js/releases

i need check if it bad error, or only not used variable for keep compatibility with older version.
thank i take a look in ESLint , not find way to change limit error.

**Comment by sandy081** [comment] 2018-06-25 12:47
@djmisterjon I am not sure what you are asking for by looking at the screenshot. May I know what is the message in the screenshot?

**Comment by djmisterjon** [comment] 2018-06-25 17:41
@sandy081 yep sorry.
By default, if an error has been found, vscode displays a list, but if the list is too large, it is sencured and I can not navigate the list of errors.
I would like the opportunity to see all list error references, even though it exceeds 241.

The message from vscode in translated in english say:
> 242 additional errors and warnings are not displayed

also am not sure if is the same request here ? but 
https://github.com/Microsoft/vscode/issues/9826

**Comment by sandy081** [comment] 2018-06-26 08:14
Yeah it is related to that

**Comment by jrieken** [comment] 2018-06-26 08:43
/duplicate of https://github.com//Microsoft/vscode/issues/49687.

**Comment by jrieken** [comment] 2018-06-26 08:43
the limit is now 1000 errors per file

**Closed by jrieken** 2018-06-26 08:43 UTC
Labels: *duplicate

**Comment by djmisterjon** [comment] 2018-06-26 09:58
@jriedken
hi thank for your answer, how i can set it , because as you can see, my limit are 200 ?
is will available in a next update ?
