### ISSUE TITLE
Webviews can't use the builtin icons

### ISSUE THREAD

**Issue by misode** [microsoft/vscode#116242] opened 2021-02-10 00:40 UTC
I am trying to implement find-replace functionality in my custom editor webview. However I can't seem to use the builting vscode icons. I've tries using the class `.codicon-widget-close` and using `content: '\ea76';`.

It seems like the `.../resources/app/extensions/theme-seti/icons/seti.woff` font-face isn't loaded. There should be a way to include some of these resources in webviews.

**Comment by mjbvz** [comment] 2021-02-10 00:55
Duplicate of #95199

**Closed by mjbvz** 2021-02-10 00:55 UTC
