### ISSUE TITLE
External Change to file Detection Has changed and is acting weird

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#36266] opened 2017-10-14 09:02 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.2.18
code-runner|for|0.7.2
vscode-autohotkey|sle|0.2.1

I was using the feature that I could change a file from say notepad++ which was also opened in code... the old behavior before last update was that Code would reload the file. Now either it does nothing or on rare occasions it pops up a "file on disk is newer" warning, asking me to resolved the issue (in a confusing way which actually made me chose the wrong changes. 

Frankly I was quite happy with Studio Code reloading the file no questions asked, I was in fact relying on the behavior as one editor has options that I can use quickly to make changes

---

Steps to Reproduce:

1. Open a js file in code
2. Open Same file in notepad++
3. Make a change in notepad++ and save
4. Go back to Code, the file is the old content, not reloaded. Or it asks to resolve the issue (happened once)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-10-17 08:26
@icuurd12b42 can you share your settings? I just briefly tried and cannot reproduce.

**Comment by icuurd12b42** [comment] 2017-10-17 11:42
I would not know how to share my settings... I have all default settings aside some changes in the color scheme and I have Autosave ON

The problem seems to be with .js files. this video shows it works as expected with a .ini file

[https://www.youtube.com/watch?v=YH6yAFpMwic](url)

**Comment by brizo001** [comment] 2017-12-01 17:02
I'm having similar issues on version 1.18 for MAC OS.   I used gnu sed to make changes to a file and the changes do not show in the file inside VSCode. Even closing and opening the file does not show it. However, when I open it with another editor i can see the changes.  The only way I get the see the changes is if i restart VSCode

**Comment by ian-perkins** [comment] 2018-01-16 17:16
Same effect in 1.19.2 on Mac. For example, open package.json in a Node project, run `npm install -s` from the VS Code terminal on any random package and package.json doesn't refresh. Has to be closed and re-opened 

Run a gulp script to copy files between folders, delete files etc and the sidebar doesn't update unless the refresh icon is clicked.

**Comment by bpasero** [comment] 2018-09-05 16:48
Closing as fixed, the original steps to not reproduce for me:

Steps to Reproduce:

Open a js file in code
Open Same file in notepad++
Make a change in notepad++ and save
Go back to Code, the file is the old content, not reloaded. Or it asks to resolve the issue (happened once)

**Closed by bpasero** 2018-09-05 16:48 UTC
Labels: file-watcher, needs more info
