### ISSUE TITLE
scm is not showing changed file badge anymore

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#202330] opened 2024-01-12 10:07 UTC
Type: <b>Bug</b>

scm is not showing changed file badge anymore

VS Code version: Code - Insiders 1.86.0-insider (29bef5673ebb1fc3a59b90c9d8bfd2bc61c3f011, 2024-01-12T05:37:28.770Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.0.3
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|14.6.1
prettier-vscode|esb|10.1.0
vscode-pull-request-github|Git|0.78.1
output-colorizer|IBM|0.1.2
git-graph|mhu|1.30.0
mongodb-vscode|mon|1.4.0
vscode-scss|mrm|0.10.0
vscode-dotnet-runtime|ms-|2.0.0
vscode-edge-devtools|ms-|2.1.3
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.25.0
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vscode-typescript-next|ms-|5.4.20240111
angular-console|nrw|18.12.0
vscode-yaml|red|1.14.0
sonarlint-vscode|Son|4.2.2
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.3.0
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22

</details>

**Comment by gjsjohnmurray** [comment] 2024-01-12 10:49
Has your `scm.countBadge` setting been changed?

**Comment by sanket-bhalerao** [comment] 2024-01-12 11:09
no, its set to `all`

**Comment by gjsjohnmurray** [comment] 2024-01-12 11:56
Please use the Start Extension Bisect command to check whether any of your extensions are causing the issue.

**Comment by sanket-bhalerao** [comment] 2024-01-12 12:06
i started seeing this after the insiders update yesterday.
i will try the extension bisect

**Comment by sanket-bhalerao** [comment] 2024-01-16 07:26
i disabled all the extensions and the issue is still there.
i found the cause

`
"workbench.colorCustomizations": {
"activityBarBadge.foreground": "#ff9100",
}
`

this color setting is not taking effect in the SCM badge.
for all other badges, the text is visible with the color customization. only in the case of the SCM badge is the text not visible even after removing the customization and disabling the extensions

![image](https://github.com/microsoft/vscode/assets/9264813/77d10abe-1362-41d9-b5e9-2cba480b36df)

**Comment by gjsjohnmurray** [comment] 2024-01-16 07:48
Are you sure it's not because of how big the number is?

**Comment by sanket-bhalerao** [comment] 2024-01-16 08:06
ohh, that never crossed my mind.
the current number is 143, is that too much? should there be an ellipsis kind of indicator in that case?

**Comment by gjsjohnmurray** [comment] 2024-01-16 08:30
The blank dot is as designed. I think of it as like the blank dot that appears on the notifications bell to tell me I have unread notifications.

**Comment by lszomoru** [comment] 2024-01-16 13:47
This is by design. Duplicate of https://github.com/microsoft/vscode/issues/199392.

**Closed by lszomoru** 2024-01-16 13:47 UTC
