### ISSUE TITLE
Typing ) when there is already a ')' should not eat the character. 

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#43042] opened 2018-02-06 15:36 UTC
Steps to Reproduce:

1. Type `helloWorld(((('hello'))))`
2. Put cursor after apostrophe Type `helloWorld(((('hello'|))))`
3. Type ')', vscode will eat the character. 
4. Vscode will eat the next 4 characters.  You can add '(' but ')' gets eaten if there is a already a ')'.

It's very weird. When I type something, I want vscode to show it on the editor. 

Stop the hungry hippo behaviour please :)

**Comment by svitlana-galianova** [comment] 2018-02-06 19:24
Hello, I would love to help out here. I tried to find folder/file/function where this issue should be fixed, but unfortunately I could not find it. I would appreciate if you would guide me in the right direction.

**Comment by usernamehw** [comment] 2018-02-06 21:04
Duplicate of https://github.com/Microsoft/vscode/issues/34606 ? 
There is an option `"editor.autoClosingBrackets": false` that disables this behavior but it also disables auto creating brackets. 
Splitting it into 2 options would be nice: one to disable auto creation, another - to disable jumping.

**Comment by octref** [comment] 2018-02-07 01:03
#37315

**Closed by octref** 2018-02-07 01:03 UTC
Labels: *duplicate
