### ISSUE TITLE
Node debug doesn't terminate using WSL

### ISSUE THREAD

**Issue by thecodingdude** [Microsoft/vscode#40366] opened 2017-12-16 23:38 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
php-intellisense|fel|2.1.0
beautify|Hoo|1.1.1
vscode-icons|rob|7.19.0
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Debug a node JS script
2. using htop or similar, observe a [similar](https://i.imgur.com/hfmagjB.png) output.

These processes live forever, so when I restart debugging and make a POST request, it uses an old process.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "name",
            "program": "${workspaceFolder}\\models\\script.js",
            "useWSL": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "WWW",
            "program": "${workspaceFolder}\\bin\\www",
            "useWSL": true
        }
    ]
}
```

**Comment by thecodingdude** [comment] 2017-12-16 23:44
This is similar to #38424 - I'd consider this a pretty fundamental breakage and essentially renders debugging via WSL useless, hopefully can make it into a recovery build asap =).

**Comment by weinand** [comment] 2017-12-18 09:18
duplicate of 38424

**Closed by weinand** 2017-12-18 09:18 UTC
Labels: debug
