### ISSUE TITLE
Local Markdown images not loaded in preview

### ISSUE THREAD

**Issue by kt215** [Microsoft/vscode#45718] opened 2018-03-14 00:44 UTC
- VSCode Version: 1.21.0
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Create a new folder
2. Create and save a new Test.md (markdown) document with content: `![](test.png)`
3. Add `test.png` to the same folder.
4. Open document in PREVIEW mode
5. Image does not appear and a "broken image" shown instead.

Does this issue occur when all extensions are disabled?: Yes

Note: This bug did not exist in versions prior to 1.21.0

**Comment by mjbvz** [comment] 2018-03-14 16:08
Duplicate of #45155

**Closed by mjbvz** 2018-03-14 16:08 UTC
Labels: markdown
