### ISSUE TITLE
Select Default Profile do not actually open gitbash. After relaunch, on startup, it just keeps open PowerShell

### ISSUE THREAD

**Issue by sysroad** [microsoft/vscode#132957] opened 2021-09-13 01:37 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10 build ver 19042.1165

Steps to Reproduce:

1. Set default terminal to gitbash.
2. Close VSCode
2. Re-Launch VSCode
3. Powershell's opened...  why?? it's not default terminal.
4. kill terminal & open terminal then gitbash launched normally.

https://github.com/microsoft/vscode/issues/123684 
this issue not resolved.
why closed ??

**Comment by IllusionMH** [comment] 2021-09-13 09:37
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 09:37 UTC
Labels: *duplicate
