### ISSUE TITLE
Update badge is not removed while vscode did updated

### ISSUE THREAD

**Issue by ckybonist** [microsoft/vscode#94866] opened 2020-04-10 05:42 UTC
Issue Type: <b>Bug</b>

I've clicked udpate button and restart the vscode, but update badge still hang on the settings icon. "There are currently no updates available." is shown by clicking [Check for Updates].

![image](https://user-images.githubusercontent.com/3832925/78965950-2013bd80-7b31-11ea-82ad-2b5c3a589f01.png)

VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:26:30.083Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-node-readme|ben|3.0.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
language-postcss|cpy|1.1.0
vscode-eslint|dba|2.1.2
xml|Dot|2.5.0
css-flexbox-cheatsheet|dzh|2.0.1
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
gc-excelviewer|Gra|2.1.34
better-dockerfile-syntax|jef|1.0.2
svg|joc|1.1.7
vscode-styled-components|jpo|0.0.29
json-to-ts|Mar|1.7.4
python|ms-|2020.3.71659
Go|ms-|0.13.1
js-debug-companion|ms-|0.0.4
color-highlight|nau|2.3.0
github-actions-vscode|Oma|2.7.0
ruby|reb|0.27.0
vscode-yaml|red|0.7.2
json-to-js-object|sal|0.0.4
vscode-stylelint|sty|0.84.0
highlight-matching-tag|vin|0.9.6
vscode-icons|vsc|10.0.0
vim|vsc|1.13.1
vscode-ruby|win|0.27.0
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.2.5

(3 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2020-04-10 05:56
See #94822

**Comment by RMacfarlane** [comment] 2020-04-10 15:21
Closing as a duplicate of #94822

**Closed by RMacfarlane** 2020-04-10 15:21 UTC
