### ISSUE TITLE
Source Control display problem

### ISSUE THREAD

**Issue by daix6** [microsoft/vscode#102470] opened 2020-07-14 08:06 UTC
Issue Type: <b>Bug</b>

1. Workspace with two git project
2. Submit a commit and then undo the last commit
3. Then the display will become wrong

![image](https://user-images.githubusercontent.com/8535971/87400903-03819880-c5ec-11ea-9d9e-0b3db1b0a232.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment] 2020-07-14 13:22
Can you reliably reproduce? Can you show me with a [screen recording](https://gifcap.dev/)?

**Comment by poshcodebear** [comment] 2020-07-16 17:23
I just had this happen to me twice, while submitting commits to multiple repos.  I don't know how to reliably reproduce it, unfortunately, but until this is resolved, I have no choice but to revert to 1.46; having to relaunch VSCode and wait for it to reparse all of my repos every five or ten minutes isn't exactly a good workflow.

**Comment by joaomoreno** [comment] 2020-07-17 08:26
@poshcodebear What exactly happened to you? What did you do and what did you observe? Can you share a screenshot?

**Comment by poshcodebear** [comment] 2020-07-17 18:07
> 
> 
> @poshcodebear What exactly happened to you? What did you do and what did you observe? Can you share a screenshot?

I was just making a lot of changes and commits, and after several, the display in Source Control turned blank, like the screenshot above.  After the second time it happened, I reverted.

I tried to replicate the issue on another system that's still got 1.47.1 on it so I could give a step-by-step, but I wasn't able to.  I see that 1.47.2 is released, though, and it looks like it lists #102358 as resolved which sounds very similar to this one (the one thing I didn't try on my other system was pushing, which I did do when it was breaking on my main system, to a Bitbucket repo).

I'm going to go ahead and reinstall 1.47.2 and see if it happens again.  If it does, I'll try to see if I can replicate the steps and narrow it down for you.

I have to say, though, I'm with most of the community on this one: I'm not a fan of the new single-view SCM panel, it's way too chaotic when you have a lot of repos loaded.

**Comment by joaomoreno** [comment] 2020-07-21 10:28
> I'm going to go ahead and reinstall 1.47.2 and see if it happens again. If it does, I'll try to see if I can replicate the steps and narrow it down for you.

Thanks! Will close this for now.

> I have to say, though, I'm with most of the community on this one: I'm not a fan of the new single-view SCM panel, it's way too chaotic when you have a lot of repos loaded.

Yes, we're taking feedback and the UX is not set in stone, we'll be iterating on it as time goes by.

**Closed by joaomoreno** 2020-07-21 10:28 UTC
Labels: needs more info
