### ISSUE TITLE
Cursor goes crazy after clicking Add Function Breakpoint twice

### ISSUE THREAD

**Issue by zmajeed** [microsoft/vscode#116663] opened 2021-02-15 00:04 UTC
Issue Type: <b>Bug</b>

Click plus icon for Add Function Breakpoint in Breakpoints tab of Run side panel
Click plus icon again
Cursor begins to flicker and alternate between the two text boxes for the  new function breakpoints with high frequency

![vscode_breakpoints_cursor_14feb21](https://user-images.githubusercontent.com/6625550/107892974-78a4ab80-6ef6-11eb-9c4c-9f5b4a0e60f9.png)

CPU use jumps to over 50% from 12%

![vscode_breakpoints_cursor_high_cpu_14feb21](https://user-images.githubusercontent.com/6625550/107893112-53fd0380-6ef7-11eb-8a45-d120d687a6bd.png)

Switching focus to different application window interrupts the cursor activity CPU goes back down to 12%
Switching back to vscode makes the cursor go crazy again
Deleting all breakpoints stops the cursor activity and brings CPU down

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         660  @ 3.33GHz (4 x 3325)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.88GB free)|
|Process Argv|--crash-reporter-id e86d712e-1df7-440f-91ae-1043a236a317|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment] 2021-02-16 08:11
Thanks for reporting this. I have pushed a fix, you can try it out in latest vscode insiders from tomorrow to let us know if the issue is now good for you. Thanks

**Closed** 2021-02-16 08:11 UTC
Labels: bug, debug
