### ISSUE TITLE
Feature Request: $TM_FILENAME variable without file extension in snippets

### ISSUE THREAD

**Issue by HosseinAgha** [Microsoft/vscode#29582] opened 2017-06-27 11:59 UTC
- VSCode Version: 1.13.1
- OS Version: OSX Sierra

I want to use only file name without file extension in my snippet.   
For sublime the solution was like this:  
`${TM_FILENAME/(.+)\..+|.*/$1/:name}`

**Comment by jrieken** [comment] 2017-07-10 07:42
dupe of #6920

**Closed by jrieken** 2017-07-10 07:42 UTC
Labels: duplicate, snippets
