### ISSUE TITLE
Broken vscode.ProcessExecution in Tasks API in v1.37

### ISSUE THREAD

**Issue by ivankravets** [microsoft/vscode#78898] opened 2019-08-11 11:43 UTC
- VSCode Version: 1.37
- OS Version: macOS, Linux

# Steps to Reproduce:

See:

- https://github.com/platformio/platformio-vscode-ide/issues/957
- https://github.com/platformio/platformio-vscode-ide/blob/develop/src/tasks.js#L68

**Comment by alexr00** [comment] 2019-08-12 09:19
Shell launch configs look very similar.
From Insiders where issue exists:
<img width="833" alt="insidersLaunchConfigs" src="https://user-images.githubusercontent.com/38270282/62855643-16f8f500-bcf3-11e9-9b42-b8ccf95f2f80.png">

From 1.35.1 stable, where issue does not exist:
<img width="848" alt="oldStableLaunchConfigs" src="https://user-images.githubusercontent.com/38270282/62855654-1a8c7c00-bcf3-11e9-8866-063ad6abf783.png">

**Comment by alexr00** [comment] 2019-08-12 09:24
Looking at the env from the shell launch config, they both have the same path and platform io related env vars.

**Comment by alexr00** [comment] 2019-08-12 09:33
@Tyriar could this be related tot he executable verification now done in the constructor of TerminalProcess?

**Comment by alexr00** [comment] 2019-08-12 09:43
@Tyriar, TerminalProcess doesn't do any path resolution on the executable. So if something that is visible on the the Path is passed as the executable, then the TerminalProcess constructor will fail because "platformio" isn't a path or symlink unless you look at the env.

**Comment by Tyriar** [comment] 2019-08-12 13:27
@ivankravets where is `platformio` exactly? It looks like you're passing in `process.env` as the `env` which is meant to do nothing since https://github.com/platformio/platformio-vscode-ide/blob/develop/src/tasks.js#L68 is running on the ext host.

**Comment by ivankravets** [comment] 2019-08-12 13:32
It depends on the extension configuration. It could be in the global system env `PATH` or in the isolated Python virtual environment which we dynamically add to system env `PATH`. This is why we add "patched" `env` to `ProcessExecution`.

**Comment by Tyriar** [comment] 2019-08-12 13:42
@ivankravets maybe there's an issue but env's default value is meant to be process.env

**Comment by ivankravets** [comment] 2019-08-12 13:46
See https://github.com/platformio/platformio-node-helpers/blob/master/src/misc.js#L25

This is actually a workaround when we can't update global `env`.

**Comment by Tyriar** [comment] 2019-08-12 13:55
I think the issue is that we're not validating against the provided `env`. What I said is true only for remote windows, it would be checking against the renderer env which is why it's happening.

**Comment by Tyriar** [comment] 2019-08-12 16:52
Closing as it's fixed in master and release/1.37

**Closed by Tyriar** 2019-08-12 16:52 UTC
Labels: bug, candidate, important, new release

**Comment by ivankravets** [comment] 2019-08-12 16:55
Thanks!
