### ISSUE TITLE
When I use a snippet the suggestions / autocompletes do not work

### ISSUE THREAD

**Issue by ivanlegranbizarro** [microsoft/vscode#105972] opened 2020-09-02 19:43 UTC
- VSCode Version: 1.48.42 (but it happens in all the older versions I have tried)
- OS Version: Any version of Windows, Linux or Mac I have tried

Steps to Reproduce:

1. log+tab for execute the snippet of console.log from Javascript
2. When I run the snippet, I don't get suggestions for created variables or functions

Does this issue occur when all extensions are disabled?: No

**Comment by ivanlegranbizarro** [comment] 2020-09-02 19:58
I have solved the mystery myself, I explain it here in case the same thing happens to someone: When using the 'log' snippet to do a console.log (); variable or function suggestions stop appearing because the semi-colon that is automatically added means that you have finished the declaration and that you don't need suggestions. It is best to use the StandardJS extension, which allows you to use the cl snipet to do console.log (), without a semicolon.

Regards

**Comment by IllusionMH** [comment] 2020-09-03 01:07
Actually looks like duplicate of #89997

`"editor.suggest.snippetsPreventQuickSuggestions": false` should allow suggestions

**Closed** 2020-09-03 04:26 UTC
Labels: *question
