### ISSUE TITLE
C++ custom class name is not highlighted

### ISSUE THREAD

**Issue by Miigon** [Microsoft/vscode#68099] opened 2019-02-07 13:05 UTC
Custom class names is not highlighted.
<img width="322" alt="2019-02-07 9 00 33" src="https://user-images.githubusercontent.com/16161991/52413056-6deef900-2b1b-11e9-891c-8c192d6b2d8e.png">
Notice `FoobarView` on the beginning. It's not highlighted.

I know this is a duplicate. But this problem remains unfixed.

According to:
https://github.com/atom/language-c/issues/266
https://github.com/atom/language-c/issues/207

Atom has fixed this problem by switching to tree-sitter parser system. Is it possible that VSCode also  switch to the new parser system?
Or maybe add such feature in the C/C++ extension?

**Comment by alexr00** [comment] 2019-02-08 08:41
Duplicate of the atom issues and #216

**Closed** 2019-02-08 08:42 UTC
Labels: *duplicate
