### ISSUE TITLE
The terminal uses the PowerShell and cursor have offset

### ISSUE THREAD

**Issue by lyric-index** [Microsoft/vscode#23936] opened 2017-04-05 13:26 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|EditorConfig|EditorConfig|0.6.2|
|vscode-npm-script|eg2|0.1.8|
|vscode-great-icons|emmanuelbeziat|1.1.47|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.1|
|vue|liuji-jim|0.1.5|
|PowerShell|ms-vscode|0.12.1|
|vuehelper|oysun|0.1.0|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

it's happen when I open the terminal, but it's disappear when I change font size.

**Comment by chrmarti** [comment] 2017-04-05 14:54
Could you attach a screenshot of the problem?

**Comment by coreylendo** [comment] 2017-04-05 15:08
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I went there couldn't attach a screenshot 


Sent from Yahoo Mail for iPhone


On Wednesday, April 5, 2017, 11:55, chrmarti <notifications@github.com> wrote:


Could you attach a screenshot of the problem?

**Comment by coreylendo** [comment] 2017-04-05 15:14
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Can't attach anything taking screenshots but then there not here and it won't load google drive either


Sent from Yahoo Mail for iPhone


On Wednesday, April 5, 2017, 11:55, chrmarti <notifications@github.com> wrote:


Could you attach a screenshot of the problem?

**Comment by Tyriar** [comment] 2017-04-05 18:10
Likely a duplicate of https://github.com/Microsoft/vscode/issues/19665

**Closed by Tyriar** 2017-04-05 18:10 UTC

**Comment by lyric-index** [comment] 2017-04-06 12:54
my problem is blow:
![image](https://cloud.githubusercontent.com/assets/23474941/24754972/02bdf84c-1b0b-11e7-8dd1-167d6598ff90.png)
