### ISSUE TITLE
Strange HTML auto close issue.

### ISSUE THREAD

**Issue by djandiek** [microsoft/vscode#229465] opened 2024-09-24 01:18 UTC
Type: <b>Bug</b>

Until recently the auto close feature with HTML tags was working as expected. I would type <p> and it would auto close with a </p>. Suddenly it is also auto closing copy/pasted blocks strangely. Here is an example.

If I copy/paste this I get

```
<div>
1
2
3
</div>

<div></div> <-- weird extra closing tag
1
2
3
</div>
```

I have posted about this on reddit and quite a few people have reported it happening to them as well.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-9044-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 4075)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|15.32GB (10.68GB free)|
|Process Argv|--crash-reporter-id beda1039-08fb-429c-99d5-3dca32c03960|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
arepl|alm|2.0.5
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
regex|chr|0.5.0
bracket-select|chu|2.0.2
vscode-eslint|dba|3.0.10
vscode-quick-select|dba|0.2.9
vscode-html-css|ecm|2.0.10
git-commits|Exe|4.2.0
shell-format|fox|7.2.5
perl-outline|hit|0.0.7
beautify|Hoo|1.5.0
rest-client|hum|0.25.1
vscode-edit-csv|jan|0.10.0
search-node-modules|jas|1.3.0
ssmacro|joe|0.6.0
vscode-phpfmt|kok|1.2.16
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
ssh-config-syntax-highlighter|mou|0.0.5
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
live-server|ms-|0.4.15
remote-explorer|ms-|0.4.3
sftp|Nat|1.16.3
indent-rainbow|ode|8.3.1
vscode-print|pdc|0.12.16
vscode-css-peek|pra|4.4.1
vscode-thunder-client|ran|2.25.7
LiveServer|rit|5.7.9
multi-command|ryu|1.6.0
rewrap|stk|1.16.3
lorem-ipsum|Tyr|1.3.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
cf971741:31144450
ei213698:31121563
iacca1:31144502

```

</details>

**Comment by aeschli** [comment] 2024-09-24 07:45
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-24 07:45 UTC

**Comment by ichibidouble2** [comment] 2024-09-25 05:40
I have the same problem, is there any way to fix it?

**Comment by aeschli** [comment] 2024-09-26 08:52
The fix will be in the next release.

 If the bug is too much of a hassle, turn off the auto close feature: "html.autoClosingTags": false
