### ISSUE TITLE
Hide .* folder in "Open Folder" panel

### ISSUE THREAD

**Issue by mrcaidev** [microsoft/vscode#148358] opened 2022-04-28 06:50 UTC
The current "Open Folder" panel is showing many .* folders (as shown below), which are supposed to be hidden under Linux, so we often have to scroll down to see our real projects.

Can we hide these hidden folders in this panel, and offer a new button to toggle view when we want these folders to show up?

![image](https://user-images.githubusercontent.com/78269445/165693004-dcc0ce6e-2e22-48d8-9e58-8c1596afd246.png)

**Comment by alexr00** [comment] 2022-04-28 15:52
duplicate of https://github.com/microsoft/vscode/issues/136307

**Closed by alexr00** 2022-04-28 15:52 UTC
