### ISSUE TITLE
JS parser does not handle some cases properly

### ISSUE THREAD

**Issue by ZEDCWT** [Microsoft/vscode#34878] opened 2017-09-23 13:06 UTC
- VSCode Version: 1.16.1
- OS Version: Win 7, x86

Steps to Reproduce:

1. Open any js files
2. Input the following code.
```js
console.log(() =>
(
	console.log,
	() => false
))
```
3. It says there are errors in the code, thought the code is valid.
![x](https://user-images.githubusercontent.com/7867810/30773403-7765b910-a0a2-11e7-9084-c34905adbbb9.png)

4. But these errors disappear if the code is slightly changed
```js
console.log(() =>
(
	console.log,() => false
))
```
![y](https://user-images.githubusercontent.com/7867810/30773415-bc68be5e-a0a2-11e7-94c6-2c3112fcdb40.png)

Reproduces without extensions: Yes

**Comment by yume-chan** [comment] 2017-09-24 13:04
I can reproduce this with TypeScript `2.5.2` but not `2.5.3-insiders.2.17.19`.

Although I cannot find a corresponding issue in the TypeScript repository, seems that it has already been fixed.

**Comment by mjbvz** [comment] 2017-09-25 20:44
Yes, looks like this is a duplicate of https://github.com/Microsoft/TypeScript/issues/18406

Closing as upstream. Please let me know if you see this again in VSCode insiders builds that use this TS version

**Closed by mjbvz** 2017-09-25 20:44 UTC
Labels: javascript, new release, upstream
