### ISSUE TITLE
[folding] JSX cant collapse blog of code in 1.25.1

### ISSUE THREAD

**Issue by bossnarathip** [Microsoft/vscode#54223] opened 2018-07-13 03:11 UTC
blog of code in JSX can collapse before v 1.24 but in the present can't, give it back to our

<img width="677" alt="screen shot 2561-07-13 at 10 07 25" src="https://user-images.githubusercontent.com/18586257/42670425-fb87aef6-8684-11e8-9cc9-f34c6c8ee9c3.png">

**Comment by mjbvz** [comment] 2018-07-13 04:53
Duplicate of #53939

**Closed by mjbvz** 2018-07-13 04:53 UTC
Labels: editor, editor-folding
