### ISSUE TITLE
Space appears when searching for words

### ISSUE THREAD

**Issue by animanoir** [Microsoft/vscode#41361] opened 2018-01-09 17:47 UTC
- VSCode Version: 1.19.1
- OS Version: W10

Steps to Reproduce:

1. CTRL+F on the top.

Does this issue occur when all extensions are disabled?: Yes.

![captura](https://user-images.githubusercontent.com/5607826/34734842-df64f780-f532-11e7-95e2-0b8d300cde83.PNG)

**Comment by usernamehw** [comment] 2018-01-09 19:36
Duplicate of https://github.com/Microsoft/vscode/issues/28390

**Closed** 2018-01-10 06:48 UTC
Labels: *duplicate

**Comment by animanoir** [comment] 2018-01-10 06:50
Thanks Mr. Bot! Such a warm comment <3 not like those simply writing coldly 'duplicate' >:^o
