### ISSUE TITLE
TS intellisense is not putting exact match at top

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85958] opened 2019-12-02 19:54 UTC
When writing a test using `chai` and `chai-http`

![image](https://user-images.githubusercontent.com/2193314/69990208-1c748800-14fa-11ea-83ba-b4074a3ab3bc.png)
![image](https://user-images.githubusercontent.com/2193314/69990303-4037ce00-14fa-11ea-8a35-bc46f1c8990b.png)
![image](https://user-images.githubusercontent.com/2193314/69990319-46c64580-14fa-11ea-98bd-62297252ebd2.png)

Accepting setEncoding replaces with 

![image](https://user-images.githubusercontent.com/2193314/69990375-66f60480-14fa-11ea-901b-f151b34f9b92.png)

**Comment by mjbvz** [comment] 2019-12-03 03:09
Text: 

```js
import * as chai from 'chai';

describe('stuff', () => {
    it('should', async () => {
        await chai.request('url').post('/').send
    });
});
```

**Comment by mjbvz** [comment] 2019-12-03 03:20
@jrieken As you noted, the reason this happens is that we auto insert `await` when you select `setEncoding`. The way TS returns the result to us is that we replace the entire expression `chai.request('url').post('/').send`

Even if I disable the filterText, I can't seem to get `send` to ever have a higher priority than `setEncoding`

**Comment by mjbvz** [comment] 2019-12-03 19:02
I guess in this case we could expand the replacement range for all suggestions to cover the entire expression. Either that or get TS to return additional text edits instead of replacing the entire expression

Not a priority since this case—a mix of completions that need to insert async and ones that don't—isn't typical

**Comment by Tyriar** [comment] 2019-12-03 19:26
I don't really understand why the `setEncoding` score is so high, I would think that nothing should be able to beat an exact match like `send`.

**Comment by jrieken** [comment] 2019-12-04 08:50
Yeah, the problem is that the range selects much text - using only `setEncoding` as filter text then won't match. I think the only available fix would be to make the edit only insert `setEncoding` with the corresponding text and to have the `await` keyword inserted via an additional text edit

**Comment by mjbvz** [comment] 2020-10-03 01:19
Closing this given that it's a non-trivial fix and I'm concerned about causing other regressions

**Closed by mjbvz** 2020-10-03 01:19 UTC
Labels: bug, javascript, suggest, typescript
