### ISSUE TITLE
Feature Request: Adaptive Suggestions

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#28712] opened 2017-06-14 11:23 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
---

It would be nice if the suggestions for a file or language would come up with a sorted list where the most used partial match would end up at the top of the list.
Simple example, when you type `req` in a js file, eventually `requestAnimationFrame` will be at the top, most likely you want `require` there if you work in nodejs.

**Comment by jrieken** [comment] 2017-06-15 07:24
dupe of #22839

**Closed by jrieken** 2017-06-15 07:24 UTC
