### ISSUE TITLE
Emoji picker in Windows 10 does not open in correct position

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode#54289] opened 2018-07-13 23:59 UTC
Issue Type: <b>Bug</b>

When opening the Windows 10 emoji picker window (Win+.) with focus in the integrated terminal, the window position opens on the side of the desktop (no where close to the insertion point in the terminal window).

![image](https://user-images.githubusercontent.com/1532486/42718468-076924f0-86be-11e8-98a7-b267afa0e383.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (20.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
xml|Dot|2.3.1
vscode-guid|hea|1.3.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.4.0
vscode-cosmosdb|ms-|0.8.0
python|ms-|2018.6.0
azure-account|ms-|0.4.1
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.8.1
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.0
vscode-docker|Pet|0.0.27

</details>

**Comment by heaths** [comment] 2018-07-14 00:14
I did find and review #35266 and this is a different issue. I, too, see the overlapping glyph issues but this is a case where the emoji picker isn't popping up at the right spot. On larger monitors it can easily be missed.

**Comment by Tyriar** [comment] 2018-07-16 14:40
I didn't think the emoji picker worked at all, regardless closing this as a duplicate of https://github.com/Microsoft/vscode/issues/35266 and https://github.com/xtermjs/xterm.js/issues/469 which are about supporting the emoji IME.

**Closed by Tyriar** 2018-07-16 14:40 UTC
Labels: new release
