### ISSUE TITLE
"notebook.scrolling.revealCellBehavior": "fullCell" reveals the end of the output

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#194164] opened 2023-09-26 15:24 UTC
Version: 1.83.0-insider
Commit: 8ecf5453e8e8f98cca0f9a661d3a6457d8a0e703
Date: 2023-09-26T05:34:22.077Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.14.0-1048-oem

Also tested on Mac

Testing #194069

- have two cells with long outputs
```
import time
for i in range(20):
    time.sleep(.5)
    print(i)
```
and
```
for i in range(20):
    print(i)
```
- run them both
- set `"notebook.scrolling.revealCellBehavior": "fullCell"`
- focus the first, run with `Shift + Enter`. Second cell is revealed ( ✅ ). 
- But it's at the end of the output. I'd expect it to see as much of it, starting from the input cell, at the top of the viewport.
- (not sure if my example is a good one)

![Image](https://github.com/microsoft/vscode/assets/6461412/ab1d7115-cd0a-43c6-8c97-2682fd945b69)

**Comment by amunger** [comment] 2023-09-26 21:27
dupe of https://github.com/microsoft/vscode/issues/189735. Revealing with minimal scrolling also means pinning to the bottom at the moment unfortunately.

**Closed by amunger** 2023-09-26 21:27 UTC
