### ISSUE TITLE
Square Icons on Windows 11, requires changing to fix

### ISSUE THREAD

**Issue by nidnogg** [microsoft/vscode#179599] opened 2023-04-10 13:01 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1 (user setup)
- OS Version: Windows_NT x64 10.0.22621 (Windows 11)

Steps to Reproduce:

1. Open VS Code
2. File icons will all look like colored squares, see screencap.
3. If the file icon set is changed, they revert back to normal. 
4. If VSCode is restarted again, the issue comes back.

This is the exact same issue as https://github.com/microsoft/vscode/issues/77030 that has been closed for some reason. The hotfix from [dmxt](https://github.com/dmxt) is the same as the one mentioned here.

![Code_ap9UPnsONA](https://user-images.githubusercontent.com/17261185/230905936-b345dbeb-c05a-485b-a427-2bced6e41630.png)

**Comment by aeschli** [comment] 2023-04-17 07:20
You are using the Seti-UI theme?
Are you familiar with the Chrome Dev tools? If yes, can you run `Toggle Developer Tools`, open the Network tab, press Ctrl+R (reload) and see if the seti.woff is correctly loaded?

**Comment by aeschli** [comment] 2023-04-19 07:39
@nidnogg Thanks a lot. It looks like the font is correctly loaded.
Can you inspect one of the icons?
- click on the inspect tool in the uper left corner of the inspect tool
![image](https://user-images.githubusercontent.com/6461412/233003384-b78a852d-de24-4431-9055-8c53d65919b4.png)
- then click on one of the icon that is invalid
- it should look like that:
![image](https://user-images.githubusercontent.com/6461412/233003169-8aa4c616-ca77-40da-a5e4-7af673ed0266.png)

**Comment by nidnogg** [comment] 2023-04-25 05:19
Sorry for the delay with this one!
Here's the view when I inspect one of the icons in the dev console.
![firefox_UPYf7Y0pPQ](https://user-images.githubusercontent.com/17261185/234180983-b20e7a18-2fdf-493d-9090-593cdc7a9707.png)

**Comment by aeschli** [comment] 2023-05-10 07:57
I don't know what we can do here...

**Comment by aeschli** [comment] 2023-12-20 17:18
Closing. I'm not able to reproduce and I'm out of ideas how this can happen.

**Closed by aeschli** 2023-12-20 17:18 UTC
Labels: themes
