### ISSUE TITLE
wsl terminal not opening folder path

### ISSUE THREAD

**Issue by mishrasatyam** [microsoft/vscode#102788] opened 2020-07-17 13:38 UTC
Issue Type: <b>Bug</b>

I am using wsl2 ubuntu . When I do "code . " inside a folder in wsl2 terminal, it opens the correct folder. But when I open terminal in vs code. It does not open in folder path. It always open in /home/user

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.17GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/satyam/coldboxchain-frontend --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|6.08GB (4.57GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-vscode|Jam|0.9.3
remote-wsl|ms-|0.44.4

</details>

**Comment by Tyriar** [comment] 2020-08-04 13:31
Can you put together a [gif](https://gifcap.dev/) showing the terminal launch with the explorer visible and also do a [trace log](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging) when launching?

**Comment by mishrasatyam** [comment] 2020-08-06 09:10
I have attached log trace output and gif showing folder path not opening in terminal.
![vscode_terminal_not opening_path](https://user-images.githubusercontent.com/31180325/89513627-6c76bd80-d7f2-11ea-8c4f-67b54467c57d.gif)

[log-trace-output.txt](https://github.com/microsoft/vscode/files/5033829/log-trace-output.txt)

**Comment by Tyriar** [comment] 2020-08-10 16:50
I cannot reproduce this and see that the logs are launching with cwd set to `/home/satyam/website`. The only thing I can think of that this could be is that you are setting the directory with a `cd` call or something in one of your terminal launch scripts. Closing as I don't think this is actionable on our end.

**Closed by Tyriar** 2020-08-10 16:50 UTC
Labels: needs more info
