### ISSUE TITLE
Merge conflict text decorations not getting properly cleared

### ISSUE THREAD

**Issue by benjaminRomano** [Microsoft/vscode#897] opened 2015-12-02 02:24 UTC
Steps to reproduce:

1. Find a merge conflict
![image](https://cloud.githubusercontent.com/assets/9221137/11520395/a68862c2-9868-11e5-9296-026e4070ee08.png)

2. Press backspace twice on the line containing ``` ====== ```
3. Undo the changes
4. Repeat 2-3 a couple times

The text decorations will stack as shown below.
![image](https://cloud.githubusercontent.com/assets/9221137/11520447/26f7fd14-9869-11e5-9eae-705852c134af.png)

Also once the text decorations are stacked you can spread the text decoration to multiple lines like so.
![image](https://cloud.githubusercontent.com/assets/9221137/11520481/760ec14e-9869-11e5-9c42-971803fae09d.png)

**Comment by joaomoreno** [comment] 2015-12-02 08:47
Duplicate of #66

**Closed by joaomoreno** 2015-12-02 08:47 UTC
