### ISSUE TITLE
Watching task keeps on spinning if isBackground is not specified

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23406] opened 2017-03-28 12:30 UTC
Refs #23277

1. Generate a new vscode extension using yo generator
2. Open `tasks.json` and add a `"isBackground": false` to the `npm` task
3. Run task npm -> it the status bar always shows the spinner and it never completes

I would expect a more gracefull way of handling watching tasks.
This is particularly noticable if this task is a preLaunchTask so debugging does not start since the task is never finished

**Comment by dbaeumer** [comment] 2017-03-28 12:33
This is by design. If a task specifies that isBackground: false I suspect that task to end before I signal it is done. So the debugging framework waits correctly for it.

@isidorn what would you expect me to do instead?

**Comment by isidorn** [comment] 2017-03-28 12:40
Agree that there is not much you can do here.
What is your default valeu for the `isBackground` - if it is not set

**Comment by dbaeumer** [comment] 2017-03-28 13:53
Default is false.

**Comment by dbaeumer** [comment] 2017-04-26 14:18
All I can think of is stopping the spinning after a certain amount of time assuming that a long running task is a watching task. But might have bad consequences as well.

@isidorn since I don't know how to address this other than providing the flag `isBackground` I will close the issue. Please reopen if you have ideas how to address.

**Closed by dbaeumer** 2017-04-26 14:18 UTC
Labels: tasks
