### ISSUE TITLE
[C#] #region  can't  fold  when the code inside within same level

### ISSUE THREAD

**Issue by ChongWangUBI** [Microsoft/vscode#5266] opened 2016-04-14 17:51 UTC
- VSCode Version:  1.0.0
- OS Version: osx   10.11.1

Steps to Reproduce:
1 write #region & #endregion 
2 inside code write in same level
3 #region can't  fold
<img width="467" alt="10d5c9e2-aa57-4e15-b831-ecca9cc5b24e" src="https://cloud.githubusercontent.com/assets/16005289/14538139/d2320f8c-02ac-11e6-83e6-7568fa75d020.png">

**Comment by Tyriar** [comment] 2016-04-14 18:14
Duplicate of https://github.com/Microsoft/vscode/issues/3422

**Closed by Tyriar** 2016-04-14 18:14 UTC
