### ISSUE TITLE
VSCode Insiders has different task bar icons when open and closed

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#33190] opened 2017-08-26 12:05 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (e5ed356edb364d102c061fc3ef6634de0dd58e0d, 2017-08-25T09:24:13.877Z)
- OS Version: Windows_NT x64 10.0.15063

---

It seems that the [new icon](https://github.com/Microsoft/vscode/issues/6607#issuecomment-324456824) has a lower-detail version that is used at smaller sizes (which makes a lot of sense, at 16x16 you can't make out details like the L-shape not being fully filled-in very well).

With small task bar icons, it looks like this:

![](http://i.imgur.com/E6Co3UJ.png)

The problem is that _starting_ VSCode Insiders leads to another icon being shown, so you have different icons for VSCode in the opened and closed state. This seems like a weird inconsistency and doesn't feel polished.

![](http://i.imgur.com/4l48kLA.png)

This inconsistency doesn't exist when using regular-sized taskbar icons.

**Comment by Tyriar** [comment] 2017-08-26 16:11
@bpasero there must be a borderless icon somewhere 😕

**Comment by tsabolov** [comment] 2017-08-28 08:08
The icon has changed on Linux too.
I guess that the icons are somehow broken. This orange icon seems to be some visual artifact.

VSCode Version: code-insiders-1.16.0-1503897702.el7.x86_64.rpm
OS Version: Fedora 26 with GNOME on X.org

**Comment by bpasero** [comment] 2017-08-28 08:25
I cannot reproduce: 
![image](https://user-images.githubusercontent.com/900690/29765375-35e4ad42-8bdb-11e7-9c2d-736a9633b3bf.png)

@Gama11 steps?

**Comment by Gama11** [comment] 2017-08-28 08:41
Hm, that's interesting...

![](http://i.imgur.com/1cpKQhy.png)

I also have "Combine taskbar buttons" set to "Never", but that doesn't seem to make a difference. I can reproduce this on another PC, also Windows 10.

Do you see the simplified version of the icon anywhere? For instance, the icon for `Code - Insiders.exe` changes for me depending on the detail level of the explorer:

![](http://i.imgur.com/YMo7S5B.gif)

Could this be related to the monitor's DPI or resolution? I've tested this on 1920x1080 / 24" and 1920x1080 / 17".

**Comment by Gama11** [comment] 2017-08-28 08:49
It seems the unopened task bar icon changes to the detailed version when I change the "Scale and layout" settings from 100% to 125%.

**Comment by bpasero** [comment] 2017-08-28 08:51
Just to make it clear, none of the resources we ship is the icon without the shaped border to the side (I just verified that), so this must be windows doing something with the icon.

**Comment by Gama11** [comment] 2017-08-28 08:53
Very interesting. I actually prefer Windows' version. ;)

**Comment by bpasero** [comment] 2017-08-28 08:56
I will follow up with the icon designers, maybe the icon pack on windows indeed includes a version for small resolutions where this border is dropped.

**Comment by bpasero** [comment] 2017-08-29 09:50
Closing as designed. There is still the issue of not being able to distinguish insiders from stable which we will follow up.

**Closed by bpasero** 2017-08-29 09:50 UTC
Labels: insiders, workbench
