### ISSUE TITLE
can not debug cluster.fork code

### ISSUE THREAD

**Issue by songguangyu** [Microsoft/vscode#30904] opened 2017-07-18 07:09 UTC
can not debug cluster.fork code

- VSCode Version: 1.14.1 (
- OS Version: 10.11.2 (

```js
var cluster = require('cluster');  
var http = require('http');  
var numCPUs = require('os').cpus().length;  
process.execArgv[1] = process.execArgv[1].replace('-brk', '');
if (cluster.isMaster) {  
  console.log("master start...");  
  for (var i = 0; i < numCPUs; i++) {
    cluster.fork();
  }  

  cluster.on('listening',function(worker,address){  
      console.log('listening: worker ' + worker.process.pid +', Address: '+address.address+":"+address.port);  
  });  

  cluster.on('exit', function(worker, code, signal) {  
      console.log('worker ' + worker.process.pid + ' died');  
  });  
} else {
  http.createServer(function(req, res) {
    console.log(11);
      res.writeHead(200);  
      res.end("hello world\n");  
  }).listen(8878);  
} 
 ```

**Comment by weinand** [comment] 2017-07-18 08:12
duplicate of #3201

**Closed by weinand** 2017-07-18 08:12 UTC
Labels: debug
