### ISSUE TITLE
JS intellisense not working for socket.io client

### ISSUE THREAD

**Issue by OSG-Proj** [microsoft/vscode#95824] opened 2020-04-22 05:07 UTC
- VSCode Version: Newest
- OS Version: Win10

Steps to Reproduce:

1. Make JS intellisense work for client side libraries such as socket.io when imported to html
2.

Does this issue occur when all extensions are disabled?: same thing happens even if I do

**Comment by mjbvz** [comment] 2020-04-22 07:05
Please share a code example that demonstrates the issue

**Comment by OSG-Proj** [comment] 2020-04-23 07:06
var socket = io(); no intellisense at io()
When using client side socketio library in JS

**Comment by mjbvz** [comment] 2020-04-23 20:41
Are you importing `io` somehow?

**Comment by OSG-Proj** [comment] 2020-04-24 05:34
No, and import works only with the aliased path which then gives a problem when I try to use it with an html file

**Comment by mjbvz** [comment] 2020-04-27 22:39
So you're writing this JavaScript in an html file?

**Comment by OSG-Proj** [comment] 2020-04-28 02:52
Embedding it

**Comment by mjbvz** [comment] 2020-04-28 04:00
Duplicate of #26338

**Closed by mjbvz** 2020-04-28 04:00 UTC
Labels: needs more info
