### ISSUE TITLE
 EH debugging does not work on first try

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#65472] opened 2018-12-20 09:43 UTC
Insiders d315b31c6b5cdca082b0a6e193306e4001586509 (and later):

- start VS Code Insiders (or out of source) and open simple "hello world" extension
- press F5

Observe: debug sessions starts but no window appears

- stop session
- press F5

Observe: debug sessions starts with window

- Now comment out the "preLaunchTask" in the "Extension" launch config
- restart VS Code
- press F5

Observe: debug sessions starts with window on first try

This indicates that the issue is probably task related.

**Comment by weinand** [comment] 2018-12-20 09:52
Seems to be fixed in 2803a8655cf5e05066a4ee47cce303eefca6408c

**Comment by weinand** [comment] 2018-12-20 09:59
Still seeing it.

**Comment by isidorn** [comment] 2018-12-20 10:35
The issue is that there seems to be a regression in Tasks framework with regards to `isBackground` property.
Note that the extension starter sample sets the `isBackground` however the tasks seem to ignore this.
Basically this check [here](https://github.com/Microsoft/vscode/blob/7e995286dd61521002e99daaa21038b00749c4a2/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L727) fails even though the task has `isBackground` nicely set in `tasks.json`

I see @alexr00 doing strict null checking in tasks land which would be my N#1 suspect for this breakage. Please check the isBackground property and if this somehow broke
fyi @dbaeumer

**Comment by alexr00** [comment] 2018-12-20 10:39
Almost certainly related to strict null checking. Looking now.

**Comment by alexr00** [comment] 2018-12-20 12:02
Fixed the missing isBackground issue, thanks for narrowing it down to that. However, this scenario still won't work because the terminal isn't sending any online data events until the terminal exits. I'll follow up with @Tyriar on this.

**Comment by alexr00** [comment] 2018-12-20 12:13
New issue for terminal bug: #65485

**Comment by weinand** [comment] 2018-12-27 09:45
@please close this issue as soon as EH debugging works again in Insiders.

**Comment by isidorn** [comment] 2019-01-03 14:20
Works for me in latest insiders. Closing

**Closed by isidorn** 2019-01-03 14:20 UTC
Labels: bug, debug, important, tasks
