### ISSUE TITLE
Markdown links that are broken across lines aren't highlighted correctly

### ISSUE THREAD

**Issue by ianloic** [Microsoft/vscode#11224] opened 2016-08-30 15:37 UTC
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6 (15G31)

In a Markdown file if a link label is broken across multiple lines (common if you wrap text) it isn't highlighted. For example in:

```
[This is
an example](https://example.com/)
[another example](https://example.com)
```

the first link label is not highlighted while the second is.

**Comment by mjbvz** [comment] 2018-02-09 22:55
This is a surprisingly difficult problem to fix using text mate grammars since we tokenize line by line.

Given that this problem hasn't attracted much attention since it was opened, I'm going to close this as out of scope as the effort required to fixed it does not seem worth the limited payoff and the high risk of regressions

**Closed by mjbvz** 2018-02-09 22:55 UTC
Labels: bug, help wanted, languages basic, markdown
