### ISSUE TITLE
Poor performance of History Graph kills the source control usability 

### ISSUE THREAD

**Issue by JasonWHowell** [microsoft/vscode#225153] opened 2024-08-08 17:41 UTC
Testing #223106

The performance is too slow. The source control spins for 1 hour on big repos.  Hangs for about 1 hour on large repo like https://github.com/MicrosoftDocs/azure-docs

The graph rendering blocks me from using the list of files in the source control. It should not block the user from doing their work in my opinion. Separate the rendering.

Workaround is to turn off the new feature. `scm.showHistoryGraph` false

After the graph rendered, then it crashed VS Code with an out of memory error.

**Comment by JasonWHowell** [comment] 2024-08-08 17:58
Thanks for looking!

When it's busy it just sits in this pending state for long times. Wish I could see the file list without the graph.
![image](https://github.com/user-attachments/assets/d6b59a87-6c80-476a-a482-35f4d86857f1)

**Comment by SeBsZ** [comment] 2024-08-12 12:17
I received the update to 1.92.1 this morning which seems to have come with the new history graph. Immediately I started getting continuous 'The window is not responding' messages when doing anything Git related (merging, switching branches, etc.).
Disabling the graph using `scm.showHistoryGraph` fixed it for me too. My other devs are running into the same issue. This should not be released like this.

![image](https://github.com/user-attachments/assets/406b611b-88be-4b61-99e5-6156bb73d402)

Let me know if I can help by sharing more information.

**Comment by archon810** [comment] 2024-08-12 12:52
Same issue here.

**Comment by maciejmackowiak** [comment] 2024-08-12 17:07
Same here.
Any ETA on a fix?

**Comment by mazer1310** [comment] 2024-08-12 21:46
See also #224646

**Comment by JasonWHowell** [comment] 2024-08-13 00:24
Related issues:
https://github.com/microsoft/vscode/issues/225153
https://github.com/microsoft/vscode/issues/225210
https://github.com/microsoft/vscode/issues/225088
https://github.com/microsoft/vscode/issues/225006
https://github.com/microsoft/vscode/issues/224916
https://github.com/microsoft/vscode/issues/224646

**Comment by lszomoru** [comment] 2024-08-26 07:55
Closing as duplicate of https://github.com/microsoft/vscode/issues/224646

**Closed by lszomoru** 2024-08-26 07:55 UTC
Labels: perf, scm
