### ISSUE TITLE
Undoing a deletion in an html tag creates a corresponding closing tag,

### ISSUE THREAD

**Issue by KshitijKythe** [microsoft/vscode#109270] opened 2020-10-23 23:08 UTC
- VSCode Version: 1.16.1
- OS Version: Windows 10 Enterprise 10.0.17763 Build 17763

Steps to Reproduce:

1. Deletion a portion of any opening html tag. For e.g. deleting `<html>` to `<htm`
2. Undo the deletion using ctrl+Z, that'll create a corresponding closing tag. For e.g. `<htm` to `<html></html>`

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2020-10-25 19:35
duplicate of https://github.com/microsoft/vscode/issues/52777

**Closed by aeschli** 2020-10-25 19:35 UTC
