### ISSUE TITLE
Default settings contains warnings for Integrated terminal configuration options

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#7307] opened 2016-06-07 08:32 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open User settings 
2. Open the problems view
3. Warnings are generated for integrated terminal configuration options

Expected: There should not be any warnings generated from the settings file

![warnings from user settings](https://cloud.githubusercontent.com/assets/10746682/15897556/44c2d12c-2d95-11e6-9c39-9a402e0dfa6e.png)

As a result on clicking these warnings an error is shown
![error](https://cloud.githubusercontent.com/assets/10746682/15850971/22f3239e-2c9b-11e6-8927-32ecb4722854.PNG)

First of all no warnings/errors are expected from default settings file.

Second, If there are, its correct that Problems view is showing them

Third, I am not sure if it is expected to show the above error on opening the above file, especially if these default settings files are generated and not-editable - @bpasero your input would be helpful here

**Comment by bpasero** [comment] 2016-06-08 14:38
@sandy081 I would not expect the problems view to show me problems for anything but markers for file:// and untitled:// resources.

Please debug this and see where the "then" failure happens (I do not get this warning and cannot reproduce).

**Comment by sandy081** [comment] 2016-06-08 15:21
@bpasero Problems view and Status bar is completely relying on the underlying markers model to show errors/warnings. This would cause inconsistencies in the views. 

Showing them in the view helps because for eg, in this case these problems have to be fixed in the files we generated.

I think the right solution would be either to allow opening these files or show a nice message that user cannot open these files.

**Comment by bpasero** [comment] 2016-06-08 15:23
@sandy081 I am fine pushing this knowledge into the markers layer, but I am never interested in errors or warnings from files I cannot edit :)

**Comment by bpasero** [comment] 2016-06-09 07:10
@sandy081 seeing the warnings now and I think I was able to fix the NPE when clicking on the error.

The editor does not show the warning btw so I think we already do some filtering of warnings that are from non file editors:

![image](https://cloud.githubusercontent.com/assets/900690/15921467/fd03a874-2e21-11e6-8447-f431ce549143.png)

**Comment by Tyriar** [comment] 2016-06-09 07:20
Closing in favor of https://github.com/Microsoft/vscode/issues/7420

**Closed by Tyriar** 2016-06-09 07:20 UTC
Labels: bug, integrated-terminal
