### ISSUE TITLE
Crash when searching in markdown preview

### ISSUE THREAD

**Issue by zjopy** [microsoft/vscode#92725] opened 2020-03-15 16:40 UTC
- VSCode Version: 1.43.0
- OS Version: macOS 10.15.3 (19D76)

VSCode crashes regularly when opening the search in a markdown preview. It doesn't crash on me in other parts of the application, so I don't think it's a duplicate of #92420 since it is not "random". I can pretty much reproduce it consistenly by opening a new workspace with some markdown files and invoking search in the markdown preview. It doesn't crash each time, but after a handful of tries it always does.

Steps to Reproduce:

1. Create a markdown file
2. Open markdown preview
3. Open search in the markdown preview

Does this issue occur when all extensions are disabled?: Yes!

This is a trimmed down GIF of the crashing part after a handful of tries.

![vscrashgif](https://user-images.githubusercontent.com/33468089/76711378-cf669b80-670f-11ea-8d6c-5f426c7db8dc.gif)

For a full screencast of 1:30 min see [here](https://streamable.com/5icsj). I should note that this time it took me longer to get it to crash, normally it does so after a handful of tries.

My console shows nothing like described in [the wiki](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues) but after some digging I found the following line:

> com.apple.xpc.launchd[1] (com.microsoft.VSCode.18464[49341]): Service exited due to SIGSEGV | sent by exc

But setting logging to `trace` I could obtain the following logs from within `/Users/<username>/Library/Application Support/Code/logs` (username redacted)

[vscrashlog.zip](https://github.com/microsoft/vscode/files/4335185/vscrashlog.zip)

**Comment by rebornix** [comment] 2020-03-15 20:59
/duplicate of https://github.com/microsoft/vscode/issues/92420

**Comment by zjopy** [comment] 2020-03-15 21:12
@rebornix It is not random like in the issue you mention... It happens only when searching in markdown preview. I adjusted my post to reflect that more clearly.

**Comment by deepak1556** [comment] 2020-03-16 07:18
Thanks @zjopy for the steps and detailed info, but unfortunately its the same issue as https://github.com/microsoft/vscode/issues/92420 , markdown preview uses webview, I have edited the issue title to clarify it.

You can try the workaround mentioned in https://github.com/microsoft/vscode/issues/92420#issuecomment-598907473 for now. Please follow that issue for updates.

**Closed** 2020-03-16 07:19 UTC
Labels: *duplicate
