### ISSUE TITLE
Interpolated multiline strings syntax coloring gets messed despite compiling fine

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#69162] opened 2019-02-21 18:39 UTC
Issue Type: <b>Bug</b>

This has been an issue for a while and has been a minor annoyance and I guess I was too lazy to report it, sorry about that.

Basically in a C# code file if you create a multiline interpolated string, and use `{}` for substitution at the very beginning of a line the coloring gets screwy, but it still compiles fine.

Specifically:
```
public void Main(){
    int foo = 0;
    string test = $@"
 {foo} (there is a space at the beginning of this line!)
    ";
}
```
Works fine! Compiles correctly and is colored correctly:
![image](https://user-images.githubusercontent.com/8572438/53192978-c7f0c380-35dd-11e9-9451-d26855d36d18.png)

However if you remove the space before `{foo}` it gets screwy:
![image](https://user-images.githubusercontent.com/8572438/53193062-09816e80-35de-11e9-8cc8-dc969ca0574c.png)

On it's own it's not a big deal, but if you start doing function calls within the substitution area the context get's all sorts of messed.

Please let me know if there are any other details you need.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.70GB free)|
|Process Argv|C:\_bunker\4klick\CM|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
vscode-css-formatter|aes|1.0.1
Ionide-fsharp|Ion|3.33.0
docomment|k--|0.1.3
code-beautifier|mic|2.1.0
mssql|ms-|1.4.0
csharp|ms-|1.17.1
unity-debug|Uni|2.6.6

</details>

**Comment by alexr00** [comment] 2019-02-26 10:37
Reopening since it happens with all extensions disabled.

**Comment by alexr00** [comment] 2019-02-27 15:40
Duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/131

**Closed** 2019-02-27 15:40 UTC
Labels: *duplicate, grammar

**Comment by klick-barakgall** [comment] 2019-02-27 19:35
Ugh. Apologies apparently I posted the original issue as well. Guess I forgot about it.
