### ISSUE TITLE
Sign in to sync settings fails with GitHubTokenExchangeError

### ISSUE THREAD

**Issue by jozefizso** [microsoft/vscode#188154] opened 2023-07-18 12:17 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.80.1
- OS Version: macOS 13.4.1 (c)

Steps to Reproduce:

1. Click account icon
2. Choose Sign in to Sync Settings
3. Authenticate to GitHub in a browser
4. VSCode window will active
5. Notification "Having trouble logging in? Would you like to try a different way? (local server)" will popup

### GitHub Authentication logs

```
2023-07-18 14:14:38.842 [info] Logging in for the following scopes: user:email
2023-07-18 14:14:38.843 [info] Trying without local server... (user:email)
2023-07-18 14:14:43.279 [info] Exchanging code for token...
2023-07-18 14:14:43.618 [error] GitHubTokenExchangeError: <!DOCTYPE html>
... HTML content ...

    at t.GitHubServer.u (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:599972)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:594927
```

The HTML content contains this message:

```
<h1>Whoa there!</h1>
<p>You have exceeded a secondary rate limit.<br><br>
  Please wait a few minutes before you try again;<br>
  in some cases this may take up to an hour.
</p>
```

### VSCode Info
```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:58.115Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by TylerLeonhardt** [comment] 2023-07-19 21:48
This is a duplicate of https://github.com/microsoft/vscode/issues/179372 and will be fixed in the next release of VS Code. You're welcome to use https://code.visualstudio.com/insiders which has the fix already until then, or wait for the next version which should be in a couple weeks.

**Closed by TylerLeonhardt** 2023-07-19 21:48 UTC
