### ISSUE TITLE
Debugging mocha breakpoints not working right and value inspector not showing right info.

### ISSUE THREAD

**Issue by caperavensoftware** [Microsoft/vscode#5762] opened 2016-04-25 14:42 UTC
- VSCode Version: 1.0.0
- OS Version: 10.11.4

Using mocha, es6 and chai with vs code does not debug properly.
1. Breakpoints in tests do not work properly, they may fire but in wrong place.
2. Value inspector does not show local variables defined using let
3. Debugging ES6 files, local variables do not show nor can you view values of function parameters.

Steps to Reproduce:

See attached file.

set breakpoint in calc.js.
when breakpoint hits and you hover over it shows nothing.
typing "value1" in the console states undefined.

set breakpoint in test that will call the calc function, a breakpoint hits but not on breakpoint position.
also can not see local values.
[test.zip](https://github.com/Microsoft/vscode/files/234769/test.zip)

**Comment by bill-mybiz** [comment] 2016-04-25 16:09
I also have been having this problem. I have it both with VS code 1.0.0 and 1.0.1-insider. My project is not ES6, but rather a TypeScript project that compiles to ES5. The repo is an umbrella repo called [thingGib on GitHub](https://github.com/ibgib/thingGib), and the particular project I'm working on is in the [alexa](https://github.com/ibgib/thingGib/tree/master/alexa) folder. It's a pretty simple project so far, so cloning probably wouldn't be an issue if you wanted to also use it for reproducing the issue.

**Comment by weinand** [comment] 2016-04-27 11:07
@caperavensoftware dynamically generated source maps (e.g. through 'babel-register') are not yet supported.

This is a duplicate of https://github.com/Microsoft/vscode/issues/5728

**Closed by weinand** 2016-04-27 11:07 UTC
Labels: bug, debug
